# Developed-Markets External Validation

This notebook evaluates the frozen US research specifications separately in four pre-specified developed markets: the United Kingdom, Australia, Germany, and France. Country selection is based on institutional comparability, complete 2000--2024 coverage, cross-sectional breadth, characteristic availability, and approximately complete next-month-return coverage; no country is selected using model performance.

Each country uses its stable JKP `id` as the security identifier, excludes nano stocks, rank-normalizes characteristics within its own monthly eligible universe, and applies the unchanged 15-year training, 4-year validation, 1-year test schedule. The resulting OOS period is January 2019--December 2024 (72 months).

The chosen model, `HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50`, is evaluated as the primary specification. Its fixed US-selected construction is preserved by averaging the aligned OOS predictions of `LGBM_40` and `DEEPSET_40_DYNAMIC` with equal weights in every country; foreign-market data are not used to reselect or reweight it. The two component models are reported as benchmarks, while the validation-weighted `HYBRID_LGBM40_DEEPSET40_DYNAMIC` is retained only as a robustness comparator. Every completed country is reported.

## 1. Runtime and project setup

In [1]:
import gc
import importlib
import os
import sys
from pathlib import Path

LOCAL_PROJECT_DIR = Path(r'C:\Users\sandh\OneDrive\Documents\Coding\FDS Project')
LOCAL_DATA_DIR = Path(r'C:\Users\sandh\FDS Research Project\jkp_developed_153_parquet_2000_2024')
DRIVE_PROJECT_DIR = Path('/content/drive/MyDrive/Colab Notebooks/FDS Project')
DRIVE_DATA_DIR = DRIVE_PROJECT_DIR / 'jkp_developed_153_parquet_2000_2024'

try:
    from google.colab import drive
except ImportError:
    RUNNING_IN_COLAB = False
    PROJECT_DIR, DATA_DIR = LOCAL_PROJECT_DIR, LOCAL_DATA_DIR
else:
    RUNNING_IN_COLAB = True
    drive.mount('/content/drive', force_remount=False)
    PROJECT_DIR, DATA_DIR = DRIVE_PROJECT_DIR, DRIVE_DATA_DIR

for required in (PROJECT_DIR, PROJECT_DIR / 'src', DATA_DIR):
    if not required.is_dir():
        raise FileNotFoundError(f'Required directory not found: {required}')
os.chdir(PROJECT_DIR)
project_path = str(PROJECT_DIR)
sys.path = [path for path in sys.path if path != project_path]
sys.path.insert(0, project_path)
for module_name in tuple(sys.modules):
    if module_name == 'src' or module_name.startswith('src.'):
        del sys.modules[module_name]
importlib.invalidate_caches()
import src
if PROJECT_DIR.resolve() not in Path(src.__file__).resolve().parents:
    raise RuntimeError(f'Imported src from the wrong location: {src.__file__}')
print('Project directory:', PROJECT_DIR)
print('Country data directory:', DATA_DIR)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Project directory: /content/drive/MyDrive/Colab Notebooks/FDS Project
Country data directory: /content/drive/MyDrive/Colab Notebooks/FDS Project/jkp_developed_153_parquet_2000_2024

## 2. Frozen country and model configuration

The external validation preserves the model choice made using the US sample. The component models and validation-weighted hybrid must be estimated within each country; the chosen 50/50 model is then constructed mechanically from the component OOS predictions.

In [2]:
from src.config import ExperimentConfig, UniverseConfig
from src.developed_markets import (
    CHOSEN_MODEL_ID, COMPONENT_BENCHMARK_IDS, COUNTRY_NAMES,
    EXTERNAL_MODEL_IDS, REPORT_MODEL_IDS,
)

COUNTRIES = ('GBR', 'AUS', 'DEU', 'FRA')
OUTPUT_DIR = PROJECT_DIR / 'model_runs' / 'developed_markets'
SUMMARY_DIR = OUTPUT_DIR / 'summary'

CONFIGS = {
    country: ExperimentConfig(
        experiment_id=f'external_validation_{country}_v1',
        project_dir=PROJECT_DIR,
        data_path=DATA_DIR / f'jkp_{country}_153_2000_2024.parquet',
        output_dir=OUTPUT_DIR,
        selected_models=EXTERNAL_MODEL_IDS,
        seed=42,
        use_gpu=True,
        universe=UniverseConfig(
            country=country, start_year=2000, end_year=2024,
            security_id_col='id',
        ),
    )
    for country in COUNTRIES
}
for config in CONFIGS.values():
    config.validate()
print({country: str(config.data_path) for country, config in CONFIGS.items()})

{'GBR': '/content/drive/MyDrive/Colab Notebooks/FDS Project/jkp_developed_153_parquet_2000_2024/jkp_GBR_153_2000_2024.parquet', 'AUS': '/content/drive/MyDrive/Colab Notebooks/FDS Project/jkp_developed_153_parquet_2000_2024/jkp_AUS_153_2000_2024.parquet', 'DEU': '/content/drive/MyDrive/Colab Notebooks/FDS Project/jkp_developed_153_parquet_2000_2024/jkp_DEU_153_2000_2024.parquet', 'FRA': '/content/drive/MyDrive/Colab Notebooks/FDS Project/jkp_developed_153_parquet_2000_2024/jkp_FRA_153_2000_2024.parquet'}

## 3. Preflight validation

In [3]:
import pyarrow.parquet as pq
import torch
from src.config import FEATURES_40
from src.models import MODEL_REGISTRY

required_columns = {
    'id', 'eom', 'excntry', 'size_grp', 'me', 'ret_exc_lead1m', *FEATURES_40
}
for country, config in CONFIGS.items():
    if not config.data_path.is_file():
        raise FileNotFoundError(config.data_path)
    columns = set(pq.read_schema(config.data_path).names)
    missing = sorted(required_columns - columns)
    if missing:
        raise ValueError(f'{country} is missing required columns: {missing}')
    if 'permno' in columns:
        print(f'{country}: PERMNO is present but is not used; JKP id is the security key.')
if set(EXTERNAL_MODEL_IDS) - set(MODEL_REGISTRY):
    raise RuntimeError('An external-validation model is not registered.')
if not torch.cuda.is_available():
    raise RuntimeError('Select a GPU runtime before model estimation.')
print('GPU:', torch.cuda.get_device_name(0))
print('Country files and model registry: PASS')

GBR: PERMNO is present but is not used; JKP id is the security key.
AUS: PERMNO is present but is not used; JKP id is the security key.
DEU: PERMNO is present but is not used; JKP id is the security key.
FRA: PERMNO is present but is not used; JKP id is the security key.
GPU: NVIDIA A100-SXM4-40GB
Country files and model registry: PASS

## 4. Run or resume required country-level estimations

Each country and estimated specification has an independent experiment directory and signature. Completed annual refits load from disk; incomplete refits resume without altering completed artifacts. The chosen model itself requires no additional fitting because its equal weights are fixed in advance.

In [4]:
from dataclasses import replace
from src.runner import ExperimentRunner

for country, country_config in CONFIGS.items():
    print(f'\n######## {country}: {COUNTRY_NAMES[country]} ########')
    for model_id in EXTERNAL_MODEL_IDS:
        print(f'\n=== {country} | {model_id} ===')
        model_config = replace(country_config, selected_models=(model_id,))
        ExperimentRunner(model_config).run()
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

######## GBR: United Kingdom ########

=== GBR | LGBM_40 ===
Device: cuda

LGBM_40 [ae0f20ba802df85f]
  refit 01/06 | test_year=2019 | status=training | train_n=193,944 | validation_n=45,059 | test_n=11,514

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 01/06 | test_year=2019 | status=saved | n_predictions=11,514
  refit 02/06 | test_year=2020 | status=training | train_n=187,209 | validation_n=44,984 | test_n=11,578

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 02/06 | test_year=2020 | status=saved | n_predictions=11,578
  refit 03/06 | test_year=2021 | status=training | train_n=180,407 | validation_n=45,247 | test_n=10,049

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 03/06 | test_year=2021 | status=saved | n_predictions=10,049
  refit 04/06 | test_year=2022 | status=training | train_n=177,767 | validation_n=44,108 | test_n=10,156

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 04/06 | test_year=2022 | status=saved | n_predictions=10,156
  refit 05/06 | test_year=2023 | status=training | train_n=177,500 | validation_n=43,060 | test_n=10,464

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 05/06 | test_year=2023 | status=saved | n_predictions=10,464
  refit 06/06 | test_year=2024 | status=training | train_n=178,098 | validation_n=42,020 | test_n=9,416

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 06/06 | test_year=2024 | status=saved | n_predictions=9,416

=== GBR | DEEPSET_40_DYNAMIC ===
Device: cuda

DEEPSET_40_DYNAMIC [11e1aa6b2db4e879]
  refit 01/06 | test_year=2019 | status=training | train_n=193,944 | validation_n=45,059 | test_n=11,514
    epoch 001/100 | train_mse=0.02206353 | val_mse=0.01437280 | best_val_mse=0.01437280 | early_stop=00/10 | 1.5s
    epoch 002/100 | train_mse=0.02158102 | val_mse=0.01426883 | best_val_mse=0.01426883 | early_stop=00/10 | 1.2s
    epoch 003/100 | train_mse=0.02147662 | val_mse=0.01423826 | best_val_mse=0.01423826 | early_stop=00/10 | 1.0s
    epoch 004/100 | train_mse=0.02141534 | val_mse=0.01426566 | best_val_mse=0.01423826 | early_stop=01/10 | 1.0s
    epoch 005/100 | train_mse=0.02134531 | val_mse=0.01423397 | best_val_mse=0.01423397 | early_stop=00/10 | 1.0s
    epoch 006/100 | train_mse=0.02126992 | val_mse=0.01421948 | best_val_mse=0.01421948 | early_stop=00/10 | 1.0s
    epoch 007/100 | train_mse=0.02123735 | val_mse=0.01422640 | best_val_mse=0.01421948 | early_stop=01/10 | 1.0s
    epoch 008/100 | train_mse=0.02128493 | val_mse=0.01421542 | best_val_mse=0.01421542 | early_stop=00/10 | 1.0s
    epoch 009/100 | train_mse=0.02114836 | val_mse=0.01429469 | best_val_mse=0.01421542 | early_stop=01/10 | 1.0s
    epoch 010/100 | train_mse=0.02126805 | val_mse=0.01423766 | best_val_mse=0.01421542 | early_stop=02/10 | 1.0s
    epoch 011/100 | train_mse=0.02116818 | val_mse=0.01427228 | best_val_mse=0.01421542 | early_stop=03/10 | 0.9s
    epoch 012/100 | train_mse=0.02112700 | val_mse=0.01421767 | best_val_mse=0.01421542 | early_stop=04/10 | 1.0s
    epoch 013/100 | train_mse=0.02107514 | val_mse=0.01424648 | best_val_mse=0.01421542 | early_stop=05/10 | 1.1s
    epoch 014/100 | train_mse=0.02110787 | val_mse=0.01452696 | best_val_mse=0.01421542 | early_stop=06/10 | 1.0s
    epoch 015/100 | train_mse=0.02101328 | val_mse=0.01423070 | best_val_mse=0.01421542 | early_stop=07/10 | 1.0s
    epoch 016/100 | train_mse=0.02086092 | val_mse=0.01435943 | best_val_mse=0.01421542 | early_stop=08/10 | 1.0s
    epoch 017/100 | train_mse=0.02082826 | val_mse=0.01436210 | best_val_mse=0.01421542 | early_stop=09/10 | 1.0s
    epoch 018/100 | train_mse=0.02080484 | val_mse=0.01432658 | best_val_mse=0.01421542 | early_stop=10/10 | 1.0s
  refit 01/06 | test_year=2019 | status=saved | n_predictions=11,514
  refit 02/06 | test_year=2020 | status=training | train_n=187,209 | validation_n=44,984 | test_n=11,578
    epoch 001/100 | train_mse=0.02141560 | val_mse=0.01539387 | best_val_mse=0.01539387 | early_stop=00/10 | 1.0s
    epoch 002/100 | train_mse=0.02056706 | val_mse=0.01557264 | best_val_mse=0.01539387 | early_stop=01/10 | 1.0s
    epoch 003/100 | train_mse=0.02053474 | val_mse=0.01572990 | best_val_mse=0.01539387 | early_stop=02/10 | 1.0s
    epoch 004/100 | train_mse=0.02051640 | val_mse=0.01533830 | best_val_mse=0.01533830 | early_stop=00/10 | 1.0s
    epoch 005/100 | train_mse=0.02029477 | val_mse=0.01527116 | best_val_mse=0.01527116 | early_stop=00/10 | 0.9s
    epoch 006/100 | train_mse=0.02028471 | val_mse=0.01531508 | best_val_mse=0.01527116 | early_stop=01/10 | 0.9s
    epoch 007/100 | train_mse=0.02030077 | val_mse=0.01525736 | best_val_mse=0.01525736 | early_stop=00/10 | 1.1s
    epoch 008/100 | train_mse=0.02025489 | val_mse=0.01527496 | best_val_mse=0.01525736 | early_stop=01/10 | 0.9s
    epoch 009/100 | train_mse=0.02012837 | val_mse=0.01548602 | best_val_mse=0.01525736 | early_stop=02/10 | 0.9s
    epoch 010/100 | train_mse=0.02018839 | val_mse=0.01526826 | best_val_mse=0.01525736 | early_stop=03/10 | 0.9s
    epoch 011/100 | train_mse=0.02014380 | val_mse=0.01529200 | best_val_mse=0.01525736 | early_stop=04/10 | 0.9s
    epoch 012/100 | train_mse=0.02010467 | val_mse=0.01530557 | best_val_mse=0.01525736 | early_stop=05/10 | 1.0s
    epoch 013/100 | train_mse=0.02013253 | val_mse=0.01528691 | best_val_mse=0.01525736 | early_stop=06/10 | 1.0s
    epoch 014/100 | train_mse=0.02003454 | val_mse=0.01531756 | best_val_mse=0.01525736 | early_stop=07/10 | 1.0s
    epoch 015/100 | train_mse=0.02008913 | val_mse=0.01530168 | best_val_mse=0.01525736 | early_stop=08/10 | 1.0s
    epoch 016/100 | train_mse=0.01992512 | val_mse=0.01532020 | best_val_mse=0.01525736 | early_stop=09/10 | 0.9s
    epoch 017/100 | train_mse=0.01985357 | val_mse=0.01533068 | best_val_mse=0.01525736 | early_stop=10/10 | 1.0s
  refit 02/06 | test_year=2020 | status=saved | n_predictions=11,578
  refit 03/06 | test_year=2021 | status=training | train_n=180,407 | validation_n=45,247 | test_n=10,049
    epoch 001/100 | train_mse=0.02013470 | val_mse=0.02303782 | best_val_mse=0.02303782 | early_stop=00/10 | 1.0s
    epoch 002/100 | train_mse=0.01949239 | val_mse=0.02314765 | best_val_mse=0.02303782 | early_stop=01/10 | 1.0s
    epoch 003/100 | train_mse=0.01938201 | val_mse=0.02301146 | best_val_mse=0.02301146 | early_stop=00/10 | 1.0s
    epoch 004/100 | train_mse=0.01923028 | val_mse=0.02304613 | best_val_mse=0.02301146 | early_stop=01/10 | 0.9s
    epoch 005/100 | train_mse=0.01922115 | val_mse=0.02297457 | best_val_mse=0.02297457 | early_stop=00/10 | 1.0s
    epoch 006/100 | train_mse=0.01918097 | val_mse=0.02296430 | best_val_mse=0.02296430 | early_stop=00/10 | 1.0s
    epoch 007/100 | train_mse=0.01917139 | val_mse=0.02295979 | best_val_mse=0.02295979 | early_stop=00/10 | 1.0s
    epoch 008/100 | train_mse=0.01924437 | val_mse=0.02298765 | best_val_mse=0.02295979 | early_stop=01/10 | 0.9s
    epoch 009/100 | train_mse=0.01910127 | val_mse=0.02297564 | best_val_mse=0.02295979 | early_stop=02/10 | 0.9s
    epoch 010/100 | train_mse=0.01915782 | val_mse=0.02296860 | best_val_mse=0.02295979 | early_stop=03/10 | 1.0s
    epoch 011/100 | train_mse=0.01900848 | val_mse=0.02297395 | best_val_mse=0.02295979 | early_stop=04/10 | 1.0s
    epoch 012/100 | train_mse=0.01906057 | val_mse=0.02300190 | best_val_mse=0.02295979 | early_stop=05/10 | 0.9s
    epoch 013/100 | train_mse=0.01897448 | val_mse=0.02309781 | best_val_mse=0.02295979 | early_stop=06/10 | 0.9s
    epoch 014/100 | train_mse=0.01907962 | val_mse=0.02299419 | best_val_mse=0.02295979 | early_stop=07/10 | 0.9s
    epoch 015/100 | train_mse=0.01904661 | val_mse=0.02296762 | best_val_mse=0.02295979 | early_stop=08/10 | 0.9s
    epoch 016/100 | train_mse=0.01893786 | val_mse=0.02296526 | best_val_mse=0.02295979 | early_stop=09/10 | 0.9s
    epoch 017/100 | train_mse=0.01882802 | val_mse=0.02319377 | best_val_mse=0.02295979 | early_stop=10/10 | 0.9s
  refit 03/06 | test_year=2021 | status=saved | n_predictions=10,049
  refit 04/06 | test_year=2022 | status=training | train_n=177,767 | validation_n=44,108 | test_n=10,156
    epoch 001/100 | train_mse=0.01934565 | val_mse=0.02395013 | best_val_mse=0.02395013 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.01882929 | val_mse=0.02399503 | best_val_mse=0.02395013 | early_stop=01/10 | 0.9s
    epoch 003/100 | train_mse=0.01869689 | val_mse=0.02424209 | best_val_mse=0.02395013 | early_stop=02/10 | 0.9s
    epoch 004/100 | train_mse=0.01875520 | val_mse=0.02390173 | best_val_mse=0.02390173 | early_stop=00/10 | 0.9s
    epoch 005/100 | train_mse=0.01863988 | val_mse=0.02385333 | best_val_mse=0.02385333 | early_stop=00/10 | 1.4s
    epoch 006/100 | train_mse=0.01862666 | val_mse=0.02390430 | best_val_mse=0.02385333 | early_stop=01/10 | 1.6s
    epoch 007/100 | train_mse=0.01848203 | val_mse=0.02382873 | best_val_mse=0.02382873 | early_stop=00/10 | 1.4s
    epoch 008/100 | train_mse=0.01849402 | val_mse=0.02387496 | best_val_mse=0.02382873 | early_stop=01/10 | 1.3s
    epoch 009/100 | train_mse=0.01841202 | val_mse=0.02383005 | best_val_mse=0.02382873 | early_stop=02/10 | 1.7s
    epoch 010/100 | train_mse=0.01838238 | val_mse=0.02382950 | best_val_mse=0.02382873 | early_stop=03/10 | 1.4s
    epoch 011/100 | train_mse=0.01837721 | val_mse=0.02383040 | best_val_mse=0.02382873 | early_stop=04/10 | 1.6s
    epoch 012/100 | train_mse=0.01832206 | val_mse=0.02383676 | best_val_mse=0.02382873 | early_stop=05/10 | 1.2s
    epoch 013/100 | train_mse=0.01828469 | val_mse=0.02383578 | best_val_mse=0.02382873 | early_stop=06/10 | 1.1s
    epoch 014/100 | train_mse=0.01826760 | val_mse=0.02385580 | best_val_mse=0.02382873 | early_stop=07/10 | 1.2s
    epoch 015/100 | train_mse=0.01822898 | val_mse=0.02381752 | best_val_mse=0.02381752 | early_stop=00/10 | 1.2s
    epoch 016/100 | train_mse=0.01816105 | val_mse=0.02381027 | best_val_mse=0.02381027 | early_stop=00/10 | 1.0s
    epoch 017/100 | train_mse=0.01806252 | val_mse=0.02389442 | best_val_mse=0.02381027 | early_stop=01/10 | 0.9s
    epoch 018/100 | train_mse=0.01802742 | val_mse=0.02381951 | best_val_mse=0.02381027 | early_stop=02/10 | 1.3s
    epoch 019/100 | train_mse=0.01800028 | val_mse=0.02385459 | best_val_mse=0.02381027 | early_stop=03/10 | 1.8s
    epoch 020/100 | train_mse=0.01797378 | val_mse=0.02398963 | best_val_mse=0.02381027 | early_stop=04/10 | 1.7s
    epoch 021/100 | train_mse=0.01810948 | val_mse=0.02384130 | best_val_mse=0.02381027 | early_stop=05/10 | 1.3s
    epoch 022/100 | train_mse=0.01784576 | val_mse=0.02398405 | best_val_mse=0.02381027 | early_stop=06/10 | 1.1s
    epoch 023/100 | train_mse=0.01767491 | val_mse=0.02390847 | best_val_mse=0.02381027 | early_stop=07/10 | 1.1s
    epoch 024/100 | train_mse=0.01769489 | val_mse=0.02390395 | best_val_mse=0.02381027 | early_stop=08/10 | 1.2s
    epoch 025/100 | train_mse=0.01753313 | val_mse=0.02425120 | best_val_mse=0.02381027 | early_stop=09/10 | 1.4s
    epoch 026/100 | train_mse=0.01771475 | val_mse=0.02427844 | best_val_mse=0.02381027 | early_stop=10/10 | 1.7s
  refit 04/06 | test_year=2022 | status=saved | n_predictions=10,156
  refit 05/06 | test_year=2023 | status=training | train_n=177,500 | validation_n=43,060 | test_n=10,464
    epoch 001/100 | train_mse=0.01925635 | val_mse=0.02557003 | best_val_mse=0.02557003 | early_stop=00/10 | 1.6s
    epoch 002/100 | train_mse=0.01851586 | val_mse=0.02545004 | best_val_mse=0.02545004 | early_stop=00/10 | 2.0s
    epoch 003/100 | train_mse=0.01836134 | val_mse=0.02549076 | best_val_mse=0.02545004 | early_stop=01/10 | 1.2s
    epoch 004/100 | train_mse=0.01847035 | val_mse=0.02563197 | best_val_mse=0.02545004 | early_stop=02/10 | 1.2s
    epoch 005/100 | train_mse=0.01834296 | val_mse=0.02542377 | best_val_mse=0.02542377 | early_stop=00/10 | 1.4s
    epoch 006/100 | train_mse=0.01828130 | val_mse=0.02537446 | best_val_mse=0.02537446 | early_stop=00/10 | 2.1s
    epoch 007/100 | train_mse=0.01825987 | val_mse=0.02539207 | best_val_mse=0.02537446 | early_stop=01/10 | 1.2s
    epoch 008/100 | train_mse=0.01823091 | val_mse=0.02548392 | best_val_mse=0.02537446 | early_stop=02/10 | 0.9s
    epoch 009/100 | train_mse=0.01817808 | val_mse=0.02539673 | best_val_mse=0.02537446 | early_stop=03/10 | 1.3s
    epoch 010/100 | train_mse=0.01820127 | val_mse=0.02539384 | best_val_mse=0.02537446 | early_stop=04/10 | 1.8s
    epoch 011/100 | train_mse=0.01812173 | val_mse=0.02543470 | best_val_mse=0.02537446 | early_stop=05/10 | 1.5s
    epoch 012/100 | train_mse=0.01822479 | val_mse=0.02537178 | best_val_mse=0.02537178 | early_stop=00/10 | 1.7s
    epoch 013/100 | train_mse=0.01810106 | val_mse=0.02541337 | best_val_mse=0.02537178 | early_stop=01/10 | 1.3s
    epoch 014/100 | train_mse=0.01809723 | val_mse=0.02541884 | best_val_mse=0.02537178 | early_stop=02/10 | 1.2s
    epoch 015/100 | train_mse=0.01809877 | val_mse=0.02538598 | best_val_mse=0.02537178 | early_stop=03/10 | 1.5s
    epoch 016/100 | train_mse=0.01804836 | val_mse=0.02536631 | best_val_mse=0.02536631 | early_stop=00/10 | 1.4s
    epoch 017/100 | train_mse=0.01800491 | val_mse=0.02538959 | best_val_mse=0.02536631 | early_stop=01/10 | 1.6s
    epoch 018/100 | train_mse=0.01796553 | val_mse=0.02539531 | best_val_mse=0.02536631 | early_stop=02/10 | 1.5s
    epoch 019/100 | train_mse=0.01795825 | val_mse=0.02536652 | best_val_mse=0.02536631 | early_stop=03/10 | 1.6s
    epoch 020/100 | train_mse=0.01787134 | val_mse=0.02535571 | best_val_mse=0.02535571 | early_stop=00/10 | 1.0s
    epoch 021/100 | train_mse=0.01789682 | val_mse=0.02550740 | best_val_mse=0.02535571 | early_stop=01/10 | 1.3s
    epoch 022/100 | train_mse=0.01778608 | val_mse=0.02551667 | best_val_mse=0.02535571 | early_stop=02/10 | 1.3s
    epoch 023/100 | train_mse=0.01771041 | val_mse=0.02541709 | best_val_mse=0.02535571 | early_stop=03/10 | 2.4s
    epoch 024/100 | train_mse=0.01768820 | val_mse=0.02548578 | best_val_mse=0.02535571 | early_stop=04/10 | 2.2s
    epoch 025/100 | train_mse=0.01777751 | val_mse=0.02564847 | best_val_mse=0.02535571 | early_stop=05/10 | 1.3s
    epoch 026/100 | train_mse=0.01757872 | val_mse=0.02604887 | best_val_mse=0.02535571 | early_stop=06/10 | 1.2s
    epoch 027/100 | train_mse=0.01748167 | val_mse=0.02550965 | best_val_mse=0.02535571 | early_stop=07/10 | 1.7s
    epoch 028/100 | train_mse=0.01740607 | val_mse=0.02570879 | best_val_mse=0.02535571 | early_stop=08/10 | 1.5s
    epoch 029/100 | train_mse=0.01721519 | val_mse=0.02584752 | best_val_mse=0.02535571 | early_stop=09/10 | 1.2s
    epoch 030/100 | train_mse=0.01718856 | val_mse=0.02592990 | best_val_mse=0.02535571 | early_stop=10/10 | 1.2s
  refit 05/06 | test_year=2023 | status=saved | n_predictions=10,464
  refit 06/06 | test_year=2024 | status=training | train_n=178,098 | validation_n=42,020 | test_n=9,416
    epoch 001/100 | train_mse=0.01916664 | val_mse=0.02660731 | best_val_mse=0.02660731 | early_stop=00/10 | 1.0s
    epoch 002/100 | train_mse=0.01893440 | val_mse=0.02601141 | best_val_mse=0.02601141 | early_stop=00/10 | 1.2s
    epoch 003/100 | train_mse=0.01883594 | val_mse=0.02615501 | best_val_mse=0.02601141 | early_stop=01/10 | 1.2s
    epoch 004/100 | train_mse=0.01873544 | val_mse=0.02597075 | best_val_mse=0.02597075 | early_stop=00/10 | 1.4s
    epoch 005/100 | train_mse=0.01868035 | val_mse=0.02609935 | best_val_mse=0.02597075 | early_stop=01/10 | 1.5s
    epoch 006/100 | train_mse=0.01867766 | val_mse=0.02594997 | best_val_mse=0.02594997 | early_stop=00/10 | 1.2s
    epoch 007/100 | train_mse=0.01861392 | val_mse=0.02595877 | best_val_mse=0.02594997 | early_stop=01/10 | 1.3s
    epoch 008/100 | train_mse=0.01861451 | val_mse=0.02612892 | best_val_mse=0.02594997 | early_stop=02/10 | 1.3s
    epoch 009/100 | train_mse=0.01858149 | val_mse=0.02595487 | best_val_mse=0.02594997 | early_stop=03/10 | 1.4s
    epoch 010/100 | train_mse=0.01856806 | val_mse=0.02595125 | best_val_mse=0.02594997 | early_stop=04/10 | 1.9s
    epoch 011/100 | train_mse=0.01852032 | val_mse=0.02607047 | best_val_mse=0.02594997 | early_stop=05/10 | 1.8s
    epoch 012/100 | train_mse=0.01847994 | val_mse=0.02599127 | best_val_mse=0.02594997 | early_stop=06/10 | 1.2s
    epoch 013/100 | train_mse=0.01844961 | val_mse=0.02595911 | best_val_mse=0.02594997 | early_stop=07/10 | 1.3s
    epoch 014/100 | train_mse=0.01840558 | val_mse=0.02600447 | best_val_mse=0.02594997 | early_stop=08/10 | 1.2s
    epoch 015/100 | train_mse=0.01852434 | val_mse=0.02603473 | best_val_mse=0.02594997 | early_stop=09/10 | 1.2s
    epoch 016/100 | train_mse=0.01842520 | val_mse=0.02599342 | best_val_mse=0.02594997 | early_stop=10/10 | 1.3s
  refit 06/06 | test_year=2024 | status=saved | n_predictions=9,416

=== GBR | HYBRID_LGBM40_DEEPSET40_DYNAMIC ===
Device: cuda

HYBRID_LGBM40_DEEPSET40_DYNAMIC [472b1bcfb72a7712]
  refit 01/06 | test_year=2019 | status=training | train_n=193,944 | validation_n=45,059 | test_n=11,514

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02206353 | val_mse=0.01393496 | best_val_mse=0.01393496 | early_stop=00/10 | 1.0s
    epoch 002/100 | train_mse=0.02158102 | val_mse=0.01390766 | best_val_mse=0.01390766 | early_stop=00/10 | 1.8s
    epoch 003/100 | train_mse=0.02147662 | val_mse=0.01387321 | best_val_mse=0.01387321 | early_stop=00/10 | 1.3s
    epoch 004/100 | train_mse=0.02141534 | val_mse=0.01398383 | best_val_mse=0.01387321 | early_stop=01/10 | 1.8s
    epoch 005/100 | train_mse=0.02134531 | val_mse=0.01392455 | best_val_mse=0.01387321 | early_stop=02/10 | 1.4s
    epoch 006/100 | train_mse=0.02126992 | val_mse=0.01390432 | best_val_mse=0.01387321 | early_stop=03/10 | 1.4s
    epoch 007/100 | train_mse=0.02123735 | val_mse=0.01392994 | best_val_mse=0.01387321 | early_stop=04/10 | 1.3s
    epoch 008/100 | train_mse=0.02128493 | val_mse=0.01391383 | best_val_mse=0.01387321 | early_stop=05/10 | 0.9s
    epoch 009/100 | train_mse=0.02114836 | val_mse=0.01403318 | best_val_mse=0.01387321 | early_stop=06/10 | 1.0s
    epoch 010/100 | train_mse=0.02126805 | val_mse=0.01392380 | best_val_mse=0.01387321 | early_stop=07/10 | 1.4s
    epoch 011/100 | train_mse=0.02116818 | val_mse=0.01399695 | best_val_mse=0.01387321 | early_stop=08/10 | 1.5s
    epoch 012/100 | train_mse=0.02112700 | val_mse=0.01386826 | best_val_mse=0.01386826 | early_stop=00/10 | 1.8s
    epoch 013/100 | train_mse=0.02107514 | val_mse=0.01383552 | best_val_mse=0.01383552 | early_stop=00/10 | 1.3s
    epoch 014/100 | train_mse=0.02110787 | val_mse=0.01434316 | best_val_mse=0.01383552 | early_stop=01/10 | 1.2s
    epoch 015/100 | train_mse=0.02101328 | val_mse=0.01382282 | best_val_mse=0.01382282 | early_stop=00/10 | 1.3s
    epoch 016/100 | train_mse=0.02086092 | val_mse=0.01406667 | best_val_mse=0.01382282 | early_stop=01/10 | 0.9s
    epoch 017/100 | train_mse=0.02082826 | val_mse=0.01407491 | best_val_mse=0.01382282 | early_stop=02/10 | 1.4s
    epoch 018/100 | train_mse=0.02080484 | val_mse=0.01387085 | best_val_mse=0.01382282 | early_stop=03/10 | 1.3s
    epoch 019/100 | train_mse=0.02080450 | val_mse=0.01391183 | best_val_mse=0.01382282 | early_stop=04/10 | 1.0s
    epoch 020/100 | train_mse=0.02063786 | val_mse=0.01386859 | best_val_mse=0.01382282 | early_stop=05/10 | 0.9s
    epoch 021/100 | train_mse=0.02060694 | val_mse=0.01411150 | best_val_mse=0.01382282 | early_stop=06/10 | 1.3s
    epoch 022/100 | train_mse=0.02059098 | val_mse=0.01388983 | best_val_mse=0.01382282 | early_stop=07/10 | 1.2s
    epoch 023/100 | train_mse=0.02048708 | val_mse=0.01414899 | best_val_mse=0.01382282 | early_stop=08/10 | 1.0s
    epoch 024/100 | train_mse=0.02066363 | val_mse=0.01386145 | best_val_mse=0.01382282 | early_stop=09/10 | 0.9s
    epoch 025/100 | train_mse=0.02047052 | val_mse=0.01389477 | best_val_mse=0.01382282 | early_stop=10/10 | 1.1s
  refit 01/06 | test_year=2019 | status=saved | n_predictions=11,514
  refit 02/06 | test_year=2020 | status=training | train_n=187,209 | validation_n=44,984 | test_n=11,578

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02141560 | val_mse=0.01470234 | best_val_mse=0.01470234 | early_stop=00/10 | 1.2s
    epoch 002/100 | train_mse=0.02056706 | val_mse=0.01485173 | best_val_mse=0.01470234 | early_stop=01/10 | 1.1s
    epoch 003/100 | train_mse=0.02053474 | val_mse=0.01500368 | best_val_mse=0.01470234 | early_stop=02/10 | 0.9s
    epoch 004/100 | train_mse=0.02051640 | val_mse=0.01462418 | best_val_mse=0.01462418 | early_stop=00/10 | 1.3s
    epoch 005/100 | train_mse=0.02029477 | val_mse=0.01456378 | best_val_mse=0.01456378 | early_stop=00/10 | 1.4s
    epoch 006/100 | train_mse=0.02028471 | val_mse=0.01462288 | best_val_mse=0.01456378 | early_stop=01/10 | 0.9s
    epoch 007/100 | train_mse=0.02030077 | val_mse=0.01456042 | best_val_mse=0.01456042 | early_stop=00/10 | 0.9s
    epoch 008/100 | train_mse=0.02025489 | val_mse=0.01457702 | best_val_mse=0.01456042 | early_stop=01/10 | 1.3s
    epoch 009/100 | train_mse=0.02012837 | val_mse=0.01477469 | best_val_mse=0.01456042 | early_stop=02/10 | 1.6s
    epoch 010/100 | train_mse=0.02018839 | val_mse=0.01456806 | best_val_mse=0.01456042 | early_stop=03/10 | 1.1s
    epoch 011/100 | train_mse=0.02014380 | val_mse=0.01458068 | best_val_mse=0.01456042 | early_stop=04/10 | 0.9s
    epoch 012/100 | train_mse=0.02010467 | val_mse=0.01460644 | best_val_mse=0.01456042 | early_stop=05/10 | 1.1s
    epoch 013/100 | train_mse=0.02013253 | val_mse=0.01458359 | best_val_mse=0.01456042 | early_stop=06/10 | 0.9s
    epoch 014/100 | train_mse=0.02003454 | val_mse=0.01463697 | best_val_mse=0.01456042 | early_stop=07/10 | 1.1s
    epoch 015/100 | train_mse=0.02008913 | val_mse=0.01461361 | best_val_mse=0.01456042 | early_stop=08/10 | 1.8s
    epoch 016/100 | train_mse=0.01992512 | val_mse=0.01462553 | best_val_mse=0.01456042 | early_stop=09/10 | 1.2s
    epoch 017/100 | train_mse=0.01985357 | val_mse=0.01463913 | best_val_mse=0.01456042 | early_stop=10/10 | 0.9s
  refit 02/06 | test_year=2020 | status=saved | n_predictions=11,578
  refit 03/06 | test_year=2021 | status=training | train_n=180,407 | validation_n=45,247 | test_n=10,049

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02013470 | val_mse=0.01490938 | best_val_mse=0.01490938 | early_stop=00/10 | 1.3s
    epoch 002/100 | train_mse=0.01949239 | val_mse=0.01510112 | best_val_mse=0.01490938 | early_stop=01/10 | 1.6s
    epoch 003/100 | train_mse=0.01938201 | val_mse=0.01482993 | best_val_mse=0.01482993 | early_stop=00/10 | 0.9s
    epoch 004/100 | train_mse=0.01923028 | val_mse=0.01481730 | best_val_mse=0.01481730 | early_stop=00/10 | 1.1s
    epoch 005/100 | train_mse=0.01922115 | val_mse=0.01480689 | best_val_mse=0.01480689 | early_stop=00/10 | 1.3s
    epoch 006/100 | train_mse=0.01918097 | val_mse=0.01480679 | best_val_mse=0.01480679 | early_stop=00/10 | 1.3s
    epoch 007/100 | train_mse=0.01917139 | val_mse=0.01479994 | best_val_mse=0.01479994 | early_stop=00/10 | 0.9s
    epoch 008/100 | train_mse=0.01924437 | val_mse=0.01490001 | best_val_mse=0.01479994 | early_stop=01/10 | 1.4s
    epoch 009/100 | train_mse=0.01910127 | val_mse=0.01478325 | best_val_mse=0.01478325 | early_stop=00/10 | 1.5s
    epoch 010/100 | train_mse=0.01915782 | val_mse=0.01480344 | best_val_mse=0.01478325 | early_stop=01/10 | 0.9s
    epoch 011/100 | train_mse=0.01900848 | val_mse=0.01482227 | best_val_mse=0.01478325 | early_stop=02/10 | 1.3s
    epoch 012/100 | train_mse=0.01906057 | val_mse=0.01478898 | best_val_mse=0.01478325 | early_stop=03/10 | 1.0s
    epoch 013/100 | train_mse=0.01897448 | val_mse=0.01508023 | best_val_mse=0.01478325 | early_stop=04/10 | 0.9s
    epoch 014/100 | train_mse=0.01907962 | val_mse=0.01480414 | best_val_mse=0.01478325 | early_stop=05/10 | 1.3s
    epoch 015/100 | train_mse=0.01904661 | val_mse=0.01488715 | best_val_mse=0.01478325 | early_stop=06/10 | 0.9s
    epoch 016/100 | train_mse=0.01893786 | val_mse=0.01486088 | best_val_mse=0.01478325 | early_stop=07/10 | 1.0s
    epoch 017/100 | train_mse=0.01882802 | val_mse=0.01491392 | best_val_mse=0.01478325 | early_stop=08/10 | 1.1s
    epoch 018/100 | train_mse=0.01899914 | val_mse=0.01492596 | best_val_mse=0.01478325 | early_stop=09/10 | 1.3s
    epoch 019/100 | train_mse=0.01880571 | val_mse=0.01488982 | best_val_mse=0.01478325 | early_stop=10/10 | 0.9s
  refit 03/06 | test_year=2021 | status=saved | n_predictions=10,049
  refit 04/06 | test_year=2022 | status=training | train_n=177,767 | validation_n=44,108 | test_n=10,156

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.01934565 | val_mse=0.02674201 | best_val_mse=0.02674201 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.01882929 | val_mse=0.02680881 | best_val_mse=0.02674201 | early_stop=01/10 | 1.4s
    epoch 003/100 | train_mse=0.01869689 | val_mse=0.02708314 | best_val_mse=0.02674201 | early_stop=02/10 | 1.6s
    epoch 004/100 | train_mse=0.01875520 | val_mse=0.02671502 | best_val_mse=0.02671502 | early_stop=00/10 | 1.5s
    epoch 005/100 | train_mse=0.01863988 | val_mse=0.02666322 | best_val_mse=0.02666322 | early_stop=00/10 | 1.4s
    epoch 006/100 | train_mse=0.01862666 | val_mse=0.02672150 | best_val_mse=0.02666322 | early_stop=01/10 | 1.4s
    epoch 007/100 | train_mse=0.01848203 | val_mse=0.02664359 | best_val_mse=0.02664359 | early_stop=00/10 | 1.3s
    epoch 008/100 | train_mse=0.01849402 | val_mse=0.02667274 | best_val_mse=0.02664359 | early_stop=01/10 | 0.9s
    epoch 009/100 | train_mse=0.01841202 | val_mse=0.02664182 | best_val_mse=0.02664182 | early_stop=00/10 | 1.1s
    epoch 010/100 | train_mse=0.01838238 | val_mse=0.02665714 | best_val_mse=0.02664182 | early_stop=01/10 | 1.2s
    epoch 011/100 | train_mse=0.01837721 | val_mse=0.02665065 | best_val_mse=0.02664182 | early_stop=02/10 | 1.2s
    epoch 012/100 | train_mse=0.01832206 | val_mse=0.02666067 | best_val_mse=0.02664182 | early_stop=03/10 | 1.3s
    epoch 013/100 | train_mse=0.01828469 | val_mse=0.02667767 | best_val_mse=0.02664182 | early_stop=04/10 | 1.3s
    epoch 014/100 | train_mse=0.01826760 | val_mse=0.02668192 | best_val_mse=0.02664182 | early_stop=05/10 | 0.9s
    epoch 015/100 | train_mse=0.01822898 | val_mse=0.02665977 | best_val_mse=0.02664182 | early_stop=06/10 | 0.9s
    epoch 016/100 | train_mse=0.01816105 | val_mse=0.02663541 | best_val_mse=0.02663541 | early_stop=00/10 | 1.1s
    epoch 017/100 | train_mse=0.01806252 | val_mse=0.02673053 | best_val_mse=0.02663541 | early_stop=01/10 | 0.9s
    epoch 018/100 | train_mse=0.01802742 | val_mse=0.02665521 | best_val_mse=0.02663541 | early_stop=02/10 | 0.9s
    epoch 019/100 | train_mse=0.01800028 | val_mse=0.02671412 | best_val_mse=0.02663541 | early_stop=03/10 | 1.0s
    epoch 020/100 | train_mse=0.01797378 | val_mse=0.02687152 | best_val_mse=0.02663541 | early_stop=04/10 | 1.0s
    epoch 021/100 | train_mse=0.01810948 | val_mse=0.02670821 | best_val_mse=0.02663541 | early_stop=05/10 | 0.9s
    epoch 022/100 | train_mse=0.01784576 | val_mse=0.02682703 | best_val_mse=0.02663541 | early_stop=06/10 | 0.9s
    epoch 023/100 | train_mse=0.01767491 | val_mse=0.02676404 | best_val_mse=0.02663541 | early_stop=07/10 | 0.9s
    epoch 024/100 | train_mse=0.01769489 | val_mse=0.02676036 | best_val_mse=0.02663541 | early_stop=08/10 | 0.9s
    epoch 025/100 | train_mse=0.01753313 | val_mse=0.02704548 | best_val_mse=0.02663541 | early_stop=09/10 | 0.9s
    epoch 026/100 | train_mse=0.01771475 | val_mse=0.02707231 | best_val_mse=0.02663541 | early_stop=10/10 | 0.9s
  refit 04/06 | test_year=2022 | status=saved | n_predictions=10,156
  refit 05/06 | test_year=2023 | status=training | train_n=177,500 | validation_n=43,060 | test_n=10,464

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.01925635 | val_mse=0.02697911 | best_val_mse=0.02697911 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.01851586 | val_mse=0.02685552 | best_val_mse=0.02685552 | early_stop=00/10 | 1.0s
    epoch 003/100 | train_mse=0.01836134 | val_mse=0.02668096 | best_val_mse=0.02668096 | early_stop=00/10 | 1.0s
    epoch 004/100 | train_mse=0.01847035 | val_mse=0.02716567 | best_val_mse=0.02668096 | early_stop=01/10 | 1.0s
    epoch 005/100 | train_mse=0.01834296 | val_mse=0.02666065 | best_val_mse=0.02666065 | early_stop=00/10 | 1.0s
    epoch 006/100 | train_mse=0.01828130 | val_mse=0.02674447 | best_val_mse=0.02666065 | early_stop=01/10 | 0.9s
    epoch 007/100 | train_mse=0.01825987 | val_mse=0.02664623 | best_val_mse=0.02664623 | early_stop=00/10 | 0.9s
    epoch 008/100 | train_mse=0.01823091 | val_mse=0.02695416 | best_val_mse=0.02664623 | early_stop=01/10 | 0.9s
    epoch 009/100 | train_mse=0.01817808 | val_mse=0.02678836 | best_val_mse=0.02664623 | early_stop=02/10 | 0.9s
    epoch 010/100 | train_mse=0.01820127 | val_mse=0.02679729 | best_val_mse=0.02664623 | early_stop=03/10 | 0.9s
    epoch 011/100 | train_mse=0.01812173 | val_mse=0.02684966 | best_val_mse=0.02664623 | early_stop=04/10 | 0.9s
    epoch 012/100 | train_mse=0.01822479 | val_mse=0.02664105 | best_val_mse=0.02664105 | early_stop=00/10 | 1.0s
    epoch 013/100 | train_mse=0.01810106 | val_mse=0.02680240 | best_val_mse=0.02664105 | early_stop=01/10 | 0.9s
    epoch 014/100 | train_mse=0.01809723 | val_mse=0.02682417 | best_val_mse=0.02664105 | early_stop=02/10 | 0.9s
    epoch 015/100 | train_mse=0.01809877 | val_mse=0.02675667 | best_val_mse=0.02664105 | early_stop=03/10 | 0.9s
    epoch 016/100 | train_mse=0.01804836 | val_mse=0.02662847 | best_val_mse=0.02662847 | early_stop=00/10 | 1.0s
    epoch 017/100 | train_mse=0.01800491 | val_mse=0.02659294 | best_val_mse=0.02659294 | early_stop=00/10 | 1.0s
    epoch 018/100 | train_mse=0.01796553 | val_mse=0.02660966 | best_val_mse=0.02659294 | early_stop=01/10 | 1.0s
    epoch 019/100 | train_mse=0.01795825 | val_mse=0.02664203 | best_val_mse=0.02659294 | early_stop=02/10 | 0.9s
    epoch 020/100 | train_mse=0.01787134 | val_mse=0.02663200 | best_val_mse=0.02659294 | early_stop=03/10 | 0.9s
    epoch 021/100 | train_mse=0.01789682 | val_mse=0.02690555 | best_val_mse=0.02659294 | early_stop=04/10 | 0.9s
    epoch 022/100 | train_mse=0.01778608 | val_mse=0.02688510 | best_val_mse=0.02659294 | early_stop=05/10 | 0.9s
    epoch 023/100 | train_mse=0.01771041 | val_mse=0.02668141 | best_val_mse=0.02659294 | early_stop=06/10 | 0.9s
    epoch 024/100 | train_mse=0.01768820 | val_mse=0.02681989 | best_val_mse=0.02659294 | early_stop=07/10 | 0.9s
    epoch 025/100 | train_mse=0.01777751 | val_mse=0.02705908 | best_val_mse=0.02659294 | early_stop=08/10 | 0.9s
    epoch 026/100 | train_mse=0.01757872 | val_mse=0.02702719 | best_val_mse=0.02659294 | early_stop=09/10 | 0.9s
    epoch 027/100 | train_mse=0.01748167 | val_mse=0.02677742 | best_val_mse=0.02659294 | early_stop=10/10 | 0.9s
  refit 05/06 | test_year=2023 | status=saved | n_predictions=10,464
  refit 06/06 | test_year=2024 | status=training | train_n=178,098 | validation_n=42,020 | test_n=9,416

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.01916664 | val_mse=0.02907195 | best_val_mse=0.02907195 | early_stop=00/10 | 1.2s
    epoch 002/100 | train_mse=0.01893440 | val_mse=0.02838212 | best_val_mse=0.02838212 | early_stop=00/10 | 1.1s
    epoch 003/100 | train_mse=0.01883594 | val_mse=0.02844910 | best_val_mse=0.02838212 | early_stop=01/10 | 1.0s
    epoch 004/100 | train_mse=0.01873544 | val_mse=0.02833284 | best_val_mse=0.02833284 | early_stop=00/10 | 1.1s
    epoch 005/100 | train_mse=0.01868035 | val_mse=0.02839485 | best_val_mse=0.02833284 | early_stop=01/10 | 1.0s
    epoch 006/100 | train_mse=0.01867766 | val_mse=0.02829365 | best_val_mse=0.02829365 | early_stop=00/10 | 1.1s
    epoch 007/100 | train_mse=0.01861392 | val_mse=0.02831186 | best_val_mse=0.02829365 | early_stop=01/10 | 1.0s
    epoch 008/100 | train_mse=0.01861451 | val_mse=0.02841124 | best_val_mse=0.02829365 | early_stop=02/10 | 1.0s
    epoch 009/100 | train_mse=0.01858149 | val_mse=0.02829720 | best_val_mse=0.02829365 | early_stop=03/10 | 1.0s
    epoch 010/100 | train_mse=0.01856806 | val_mse=0.02830006 | best_val_mse=0.02829365 | early_stop=04/10 | 1.0s
    epoch 011/100 | train_mse=0.01852032 | val_mse=0.02846589 | best_val_mse=0.02829365 | early_stop=05/10 | 1.0s
    epoch 012/100 | train_mse=0.01847994 | val_mse=0.02833012 | best_val_mse=0.02829365 | early_stop=06/10 | 1.0s
    epoch 013/100 | train_mse=0.01844961 | val_mse=0.02829125 | best_val_mse=0.02829125 | early_stop=00/10 | 1.0s
    epoch 014/100 | train_mse=0.01840558 | val_mse=0.02831651 | best_val_mse=0.02829125 | early_stop=01/10 | 1.0s
    epoch 015/100 | train_mse=0.01852434 | val_mse=0.02838212 | best_val_mse=0.02829125 | early_stop=02/10 | 1.0s
    epoch 016/100 | train_mse=0.01842520 | val_mse=0.02831305 | best_val_mse=0.02829125 | early_stop=03/10 | 1.0s
    epoch 017/100 | train_mse=0.01834189 | val_mse=0.02854006 | best_val_mse=0.02829125 | early_stop=04/10 | 1.1s
    epoch 018/100 | train_mse=0.01829477 | val_mse=0.02834141 | best_val_mse=0.02829125 | early_stop=05/10 | 1.1s
    epoch 019/100 | train_mse=0.01839660 | val_mse=0.02835497 | best_val_mse=0.02829125 | early_stop=06/10 | 1.1s
    epoch 020/100 | train_mse=0.01830590 | val_mse=0.02836827 | best_val_mse=0.02829125 | early_stop=07/10 | 1.0s
    epoch 021/100 | train_mse=0.01820672 | val_mse=0.02838479 | best_val_mse=0.02829125 | early_stop=08/10 | 1.0s
    epoch 022/100 | train_mse=0.01808313 | val_mse=0.02853089 | best_val_mse=0.02829125 | early_stop=09/10 | 1.0s
    epoch 023/100 | train_mse=0.01823902 | val_mse=0.02842941 | best_val_mse=0.02829125 | early_stop=10/10 | 1.0s
  refit 06/06 | test_year=2024 | status=saved | n_predictions=9,416

######## AUS: Australia ########

=== AUS | LGBM_40 ===
Device: cuda

LGBM_40 [26a77b3f5953b7c2]
  refit 01/06 | test_year=2019 | status=training | train_n=100,261 | validation_n=30,193 | test_n=8,478

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 01/06 | test_year=2019 | status=saved | n_predictions=8,478
  refit 02/06 | test_year=2020 | status=training | train_n=102,610 | validation_n=31,795 | test_n=9,940

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 02/06 | test_year=2020 | status=saved | n_predictions=9,940
  refit 03/06 | test_year=2021 | status=training | train_n=104,555 | validation_n=34,089 | test_n=8,112

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 03/06 | test_year=2021 | status=saved | n_predictions=8,112
  refit 04/06 | test_year=2022 | status=training | train_n=107,321 | validation_n=34,334 | test_n=8,881

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 04/06 | test_year=2022 | status=saved | n_predictions=8,881
  refit 05/06 | test_year=2023 | status=training | train_n=110,241 | validation_n=35,199 | test_n=9,821

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 05/06 | test_year=2023 | status=saved | n_predictions=9,821
  refit 06/06 | test_year=2024 | status=training | train_n=113,637 | validation_n=36,534 | test_n=8,732

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 06/06 | test_year=2024 | status=saved | n_predictions=8,732

=== AUS | DEEPSET_40_DYNAMIC ===
Device: cuda

DEEPSET_40_DYNAMIC [e6917ff0b09bbb56]
  refit 01/06 | test_year=2019 | status=training | train_n=100,261 | validation_n=30,193 | test_n=8,478
    epoch 001/100 | train_mse=0.02746351 | val_mse=0.02154673 | best_val_mse=0.02154673 | early_stop=00/10 | 1.0s
    epoch 002/100 | train_mse=0.02688710 | val_mse=0.02135061 | best_val_mse=0.02135061 | early_stop=00/10 | 0.9s
    epoch 003/100 | train_mse=0.02688513 | val_mse=0.02111378 | best_val_mse=0.02111378 | early_stop=00/10 | 0.9s
    epoch 004/100 | train_mse=0.02673926 | val_mse=0.02113963 | best_val_mse=0.02111378 | early_stop=01/10 | 0.9s
    epoch 005/100 | train_mse=0.02658840 | val_mse=0.02109330 | best_val_mse=0.02109330 | early_stop=00/10 | 0.9s
    epoch 006/100 | train_mse=0.02646838 | val_mse=0.02108742 | best_val_mse=0.02108742 | early_stop=00/10 | 0.9s
    epoch 007/100 | train_mse=0.02644258 | val_mse=0.02117207 | best_val_mse=0.02108742 | early_stop=01/10 | 0.9s
    epoch 008/100 | train_mse=0.02656774 | val_mse=0.02112377 | best_val_mse=0.02108742 | early_stop=02/10 | 0.9s
    epoch 009/100 | train_mse=0.02631459 | val_mse=0.02118412 | best_val_mse=0.02108742 | early_stop=03/10 | 0.9s
    epoch 010/100 | train_mse=0.02636827 | val_mse=0.02112063 | best_val_mse=0.02108742 | early_stop=04/10 | 0.9s
    epoch 011/100 | train_mse=0.02634269 | val_mse=0.02111406 | best_val_mse=0.02108742 | early_stop=05/10 | 0.9s
    epoch 012/100 | train_mse=0.02634946 | val_mse=0.02113669 | best_val_mse=0.02108742 | early_stop=06/10 | 0.9s
    epoch 013/100 | train_mse=0.02630080 | val_mse=0.02125022 | best_val_mse=0.02108742 | early_stop=07/10 | 0.9s
    epoch 014/100 | train_mse=0.02628116 | val_mse=0.02113528 | best_val_mse=0.02108742 | early_stop=08/10 | 0.9s
    epoch 015/100 | train_mse=0.02618232 | val_mse=0.02120688 | best_val_mse=0.02108742 | early_stop=09/10 | 0.9s
    epoch 016/100 | train_mse=0.02614096 | val_mse=0.02124921 | best_val_mse=0.02108742 | early_stop=10/10 | 0.9s
  refit 01/06 | test_year=2019 | status=saved | n_predictions=8,478
  refit 02/06 | test_year=2020 | status=training | train_n=102,610 | validation_n=31,795 | test_n=9,940
    epoch 001/100 | train_mse=0.02731399 | val_mse=0.02327503 | best_val_mse=0.02327503 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.02644914 | val_mse=0.02343247 | best_val_mse=0.02327503 | early_stop=01/10 | 0.9s
    epoch 003/100 | train_mse=0.02627874 | val_mse=0.02329310 | best_val_mse=0.02327503 | early_stop=02/10 | 0.9s
    epoch 004/100 | train_mse=0.02622471 | val_mse=0.02373251 | best_val_mse=0.02327503 | early_stop=03/10 | 0.9s
    epoch 005/100 | train_mse=0.02623857 | val_mse=0.02319748 | best_val_mse=0.02319748 | early_stop=00/10 | 0.9s
    epoch 006/100 | train_mse=0.02598556 | val_mse=0.02322757 | best_val_mse=0.02319748 | early_stop=01/10 | 0.9s
    epoch 007/100 | train_mse=0.02598047 | val_mse=0.02318189 | best_val_mse=0.02318189 | early_stop=00/10 | 0.9s
    epoch 008/100 | train_mse=0.02608237 | val_mse=0.02323604 | best_val_mse=0.02318189 | early_stop=01/10 | 0.9s
    epoch 009/100 | train_mse=0.02598075 | val_mse=0.02346255 | best_val_mse=0.02318189 | early_stop=02/10 | 0.9s
    epoch 010/100 | train_mse=0.02595680 | val_mse=0.02328729 | best_val_mse=0.02318189 | early_stop=03/10 | 0.9s
    epoch 011/100 | train_mse=0.02587137 | val_mse=0.02318323 | best_val_mse=0.02318189 | early_stop=04/10 | 0.9s
    epoch 012/100 | train_mse=0.02586924 | val_mse=0.02317067 | best_val_mse=0.02317067 | early_stop=00/10 | 0.9s
    epoch 013/100 | train_mse=0.02583008 | val_mse=0.02331632 | best_val_mse=0.02317067 | early_stop=01/10 | 0.9s
    epoch 014/100 | train_mse=0.02585226 | val_mse=0.02331493 | best_val_mse=0.02317067 | early_stop=02/10 | 0.9s
    epoch 015/100 | train_mse=0.02583947 | val_mse=0.02326014 | best_val_mse=0.02317067 | early_stop=03/10 | 0.9s
    epoch 016/100 | train_mse=0.02577608 | val_mse=0.02326466 | best_val_mse=0.02317067 | early_stop=04/10 | 0.9s
    epoch 017/100 | train_mse=0.02566775 | val_mse=0.02323312 | best_val_mse=0.02317067 | early_stop=05/10 | 0.9s
    epoch 018/100 | train_mse=0.02561643 | val_mse=0.02322423 | best_val_mse=0.02317067 | early_stop=06/10 | 0.9s
    epoch 019/100 | train_mse=0.02559434 | val_mse=0.02324661 | best_val_mse=0.02317067 | early_stop=07/10 | 0.9s
    epoch 020/100 | train_mse=0.02568852 | val_mse=0.02322426 | best_val_mse=0.02317067 | early_stop=08/10 | 0.9s
    epoch 021/100 | train_mse=0.02560676 | val_mse=0.02349634 | best_val_mse=0.02317067 | early_stop=09/10 | 0.9s
    epoch 022/100 | train_mse=0.02560706 | val_mse=0.02331065 | best_val_mse=0.02317067 | early_stop=10/10 | 0.9s
  refit 02/06 | test_year=2020 | status=saved | n_predictions=9,940
  refit 03/06 | test_year=2021 | status=training | train_n=104,555 | validation_n=34,089 | test_n=8,112
    epoch 001/100 | train_mse=0.02725384 | val_mse=0.03385253 | best_val_mse=0.03385253 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.02614111 | val_mse=0.03420631 | best_val_mse=0.03385253 | early_stop=01/10 | 0.9s
    epoch 003/100 | train_mse=0.02612905 | val_mse=0.03387409 | best_val_mse=0.03385253 | early_stop=02/10 | 0.9s
    epoch 004/100 | train_mse=0.02585804 | val_mse=0.03393602 | best_val_mse=0.03385253 | early_stop=03/10 | 0.9s
    epoch 005/100 | train_mse=0.02583163 | val_mse=0.03379252 | best_val_mse=0.03379252 | early_stop=00/10 | 0.9s
    epoch 006/100 | train_mse=0.02578848 | val_mse=0.03382726 | best_val_mse=0.03379252 | early_stop=01/10 | 0.9s
    epoch 007/100 | train_mse=0.02566989 | val_mse=0.03422551 | best_val_mse=0.03379252 | early_stop=02/10 | 0.9s
    epoch 008/100 | train_mse=0.02576606 | val_mse=0.03381772 | best_val_mse=0.03379252 | early_stop=03/10 | 0.9s
    epoch 009/100 | train_mse=0.02569211 | val_mse=0.03381038 | best_val_mse=0.03379252 | early_stop=04/10 | 0.9s
    epoch 010/100 | train_mse=0.02570466 | val_mse=0.03380603 | best_val_mse=0.03379252 | early_stop=05/10 | 0.9s
    epoch 011/100 | train_mse=0.02561651 | val_mse=0.03380206 | best_val_mse=0.03379252 | early_stop=06/10 | 0.9s
    epoch 012/100 | train_mse=0.02570039 | val_mse=0.03382207 | best_val_mse=0.03379252 | early_stop=07/10 | 0.9s
    epoch 013/100 | train_mse=0.02560734 | val_mse=0.03396582 | best_val_mse=0.03379252 | early_stop=08/10 | 0.9s
    epoch 014/100 | train_mse=0.02585362 | val_mse=0.03392047 | best_val_mse=0.03379252 | early_stop=09/10 | 0.9s
    epoch 015/100 | train_mse=0.02556568 | val_mse=0.03395172 | best_val_mse=0.03379252 | early_stop=10/10 | 0.9s
  refit 03/06 | test_year=2021 | status=saved | n_predictions=8,112
  refit 04/06 | test_year=2022 | status=training | train_n=107,321 | validation_n=34,334 | test_n=8,881
    epoch 001/100 | train_mse=0.02586064 | val_mse=0.03614380 | best_val_mse=0.03614380 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.02511481 | val_mse=0.03607673 | best_val_mse=0.03607673 | early_stop=00/10 | 0.9s
    epoch 003/100 | train_mse=0.02512932 | val_mse=0.03639075 | best_val_mse=0.03607673 | early_stop=01/10 | 0.9s
    epoch 004/100 | train_mse=0.02538011 | val_mse=0.03613438 | best_val_mse=0.03607673 | early_stop=02/10 | 0.9s
    epoch 005/100 | train_mse=0.02503462 | val_mse=0.03591666 | best_val_mse=0.03591666 | early_stop=00/10 | 0.9s
    epoch 006/100 | train_mse=0.02498007 | val_mse=0.03595584 | best_val_mse=0.03591666 | early_stop=01/10 | 0.9s
    epoch 007/100 | train_mse=0.02482709 | val_mse=0.03591091 | best_val_mse=0.03591091 | early_stop=00/10 | 0.9s
    epoch 008/100 | train_mse=0.02482003 | val_mse=0.03596841 | best_val_mse=0.03591091 | early_stop=01/10 | 0.9s
    epoch 009/100 | train_mse=0.02473321 | val_mse=0.03596596 | best_val_mse=0.03591091 | early_stop=02/10 | 0.9s
    epoch 010/100 | train_mse=0.02474217 | val_mse=0.03592524 | best_val_mse=0.03591091 | early_stop=03/10 | 0.9s
    epoch 011/100 | train_mse=0.02472256 | val_mse=0.03602289 | best_val_mse=0.03591091 | early_stop=04/10 | 0.9s
    epoch 012/100 | train_mse=0.02468260 | val_mse=0.03595858 | best_val_mse=0.03591091 | early_stop=05/10 | 0.9s
    epoch 013/100 | train_mse=0.02460185 | val_mse=0.03600921 | best_val_mse=0.03591091 | early_stop=06/10 | 0.9s
    epoch 014/100 | train_mse=0.02456874 | val_mse=0.03608004 | best_val_mse=0.03591091 | early_stop=07/10 | 0.9s
    epoch 015/100 | train_mse=0.02460389 | val_mse=0.03602957 | best_val_mse=0.03591091 | early_stop=08/10 | 0.9s
    epoch 016/100 | train_mse=0.02458519 | val_mse=0.03600883 | best_val_mse=0.03591091 | early_stop=09/10 | 0.9s
    epoch 017/100 | train_mse=0.02454469 | val_mse=0.03598203 | best_val_mse=0.03591091 | early_stop=10/10 | 0.9s
  refit 04/06 | test_year=2022 | status=saved | n_predictions=8,881
  refit 05/06 | test_year=2023 | status=training | train_n=110,241 | validation_n=35,199 | test_n=9,821
    epoch 001/100 | train_mse=0.02637501 | val_mse=0.03674653 | best_val_mse=0.03674653 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.02555874 | val_mse=0.03696715 | best_val_mse=0.03674653 | early_stop=01/10 | 0.9s
    epoch 003/100 | train_mse=0.02541768 | val_mse=0.03663470 | best_val_mse=0.03663470 | early_stop=00/10 | 1.0s
    epoch 004/100 | train_mse=0.02562107 | val_mse=0.03675181 | best_val_mse=0.03663470 | early_stop=01/10 | 0.9s
    epoch 005/100 | train_mse=0.02536040 | val_mse=0.03674854 | best_val_mse=0.03663470 | early_stop=02/10 | 0.9s
    epoch 006/100 | train_mse=0.02541556 | val_mse=0.03708687 | best_val_mse=0.03663470 | early_stop=03/10 | 0.9s
    epoch 007/100 | train_mse=0.02528395 | val_mse=0.03662569 | best_val_mse=0.03662569 | early_stop=00/10 | 0.9s
    epoch 008/100 | train_mse=0.02528830 | val_mse=0.03692961 | best_val_mse=0.03662569 | early_stop=01/10 | 0.9s
    epoch 009/100 | train_mse=0.02516854 | val_mse=0.03687663 | best_val_mse=0.03662569 | early_stop=02/10 | 0.9s
    epoch 010/100 | train_mse=0.02512212 | val_mse=0.03680975 | best_val_mse=0.03662569 | early_stop=03/10 | 0.9s
    epoch 011/100 | train_mse=0.02506145 | val_mse=0.03664158 | best_val_mse=0.03662569 | early_stop=04/10 | 0.9s
    epoch 012/100 | train_mse=0.02509350 | val_mse=0.03662929 | best_val_mse=0.03662569 | early_stop=05/10 | 0.9s
    epoch 013/100 | train_mse=0.02505621 | val_mse=0.03704267 | best_val_mse=0.03662569 | early_stop=06/10 | 0.9s
    epoch 014/100 | train_mse=0.02503200 | val_mse=0.03724440 | best_val_mse=0.03662569 | early_stop=07/10 | 0.9s
    epoch 015/100 | train_mse=0.02513106 | val_mse=0.03668367 | best_val_mse=0.03662569 | early_stop=08/10 | 0.9s
    epoch 016/100 | train_mse=0.02499292 | val_mse=0.03664536 | best_val_mse=0.03662569 | early_stop=09/10 | 0.9s
    epoch 017/100 | train_mse=0.02492719 | val_mse=0.03670707 | best_val_mse=0.03662569 | early_stop=10/10 | 0.9s
  refit 05/06 | test_year=2023 | status=saved | n_predictions=9,821
  refit 06/06 | test_year=2024 | status=training | train_n=113,637 | validation_n=36,534 | test_n=8,732
    epoch 001/100 | train_mse=0.02662840 | val_mse=0.03607178 | best_val_mse=0.03607178 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.02641332 | val_mse=0.03559060 | best_val_mse=0.03559060 | early_stop=00/10 | 0.9s
    epoch 003/100 | train_mse=0.02649120 | val_mse=0.03573227 | best_val_mse=0.03559060 | early_stop=01/10 | 0.9s
    epoch 004/100 | train_mse=0.02623930 | val_mse=0.03553781 | best_val_mse=0.03553781 | early_stop=00/10 | 0.9s
    epoch 005/100 | train_mse=0.02610662 | val_mse=0.03553649 | best_val_mse=0.03553649 | early_stop=00/10 | 0.9s
    epoch 006/100 | train_mse=0.02604254 | val_mse=0.03561999 | best_val_mse=0.03553649 | early_stop=01/10 | 0.9s
    epoch 007/100 | train_mse=0.02595687 | val_mse=0.03571767 | best_val_mse=0.03553649 | early_stop=02/10 | 0.9s
    epoch 008/100 | train_mse=0.02598875 | val_mse=0.03578595 | best_val_mse=0.03553649 | early_stop=03/10 | 0.9s
    epoch 009/100 | train_mse=0.02603700 | val_mse=0.03557093 | best_val_mse=0.03553649 | early_stop=04/10 | 0.9s
    epoch 010/100 | train_mse=0.02594605 | val_mse=0.03579385 | best_val_mse=0.03553649 | early_stop=05/10 | 0.9s
    epoch 011/100 | train_mse=0.02593137 | val_mse=0.03580664 | best_val_mse=0.03553649 | early_stop=06/10 | 0.9s
    epoch 012/100 | train_mse=0.02586837 | val_mse=0.03561166 | best_val_mse=0.03553649 | early_stop=07/10 | 0.9s
    epoch 013/100 | train_mse=0.02580388 | val_mse=0.03563797 | best_val_mse=0.03553649 | early_stop=08/10 | 0.9s
    epoch 014/100 | train_mse=0.02578295 | val_mse=0.03566215 | best_val_mse=0.03553649 | early_stop=09/10 | 0.9s
    epoch 015/100 | train_mse=0.02586651 | val_mse=0.03566528 | best_val_mse=0.03553649 | early_stop=10/10 | 0.9s
  refit 06/06 | test_year=2024 | status=saved | n_predictions=8,732

=== AUS | HYBRID_LGBM40_DEEPSET40_DYNAMIC ===
Device: cuda

HYBRID_LGBM40_DEEPSET40_DYNAMIC [c5be9ed74028e96b]
  refit 01/06 | test_year=2019 | status=training | train_n=100,261 | validation_n=30,193 | test_n=8,478

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02746351 | val_mse=0.01994466 | best_val_mse=0.01994466 | early_stop=00/10 | 0.8s
    epoch 002/100 | train_mse=0.02688710 | val_mse=0.01981493 | best_val_mse=0.01981493 | early_stop=00/10 | 0.8s
    epoch 003/100 | train_mse=0.02688513 | val_mse=0.01974437 | best_val_mse=0.01974437 | early_stop=00/10 | 0.9s
    epoch 004/100 | train_mse=0.02673926 | val_mse=0.02000871 | best_val_mse=0.01974437 | early_stop=01/10 | 0.8s
    epoch 005/100 | train_mse=0.02658840 | val_mse=0.01974015 | best_val_mse=0.01974015 | early_stop=00/10 | 0.9s
    epoch 006/100 | train_mse=0.02646838 | val_mse=0.01975149 | best_val_mse=0.01974015 | early_stop=01/10 | 0.8s
    epoch 007/100 | train_mse=0.02644258 | val_mse=0.02003283 | best_val_mse=0.01974015 | early_stop=02/10 | 0.8s
    epoch 008/100 | train_mse=0.02656774 | val_mse=0.01971353 | best_val_mse=0.01971353 | early_stop=00/10 | 0.9s
    epoch 009/100 | train_mse=0.02631459 | val_mse=0.02004449 | best_val_mse=0.01971353 | early_stop=01/10 | 0.8s
    epoch 010/100 | train_mse=0.02636827 | val_mse=0.01986790 | best_val_mse=0.01971353 | early_stop=02/10 | 0.8s
    epoch 011/100 | train_mse=0.02634269 | val_mse=0.01973276 | best_val_mse=0.01971353 | early_stop=03/10 | 0.8s
    epoch 012/100 | train_mse=0.02634946 | val_mse=0.01983754 | best_val_mse=0.01971353 | early_stop=04/10 | 0.8s
    epoch 013/100 | train_mse=0.02630080 | val_mse=0.01975015 | best_val_mse=0.01971353 | early_stop=05/10 | 0.9s
    epoch 014/100 | train_mse=0.02628116 | val_mse=0.01981332 | best_val_mse=0.01971353 | early_stop=06/10 | 0.8s
    epoch 015/100 | train_mse=0.02618232 | val_mse=0.01976399 | best_val_mse=0.01971353 | early_stop=07/10 | 0.8s
    epoch 016/100 | train_mse=0.02614096 | val_mse=0.02008139 | best_val_mse=0.01971353 | early_stop=08/10 | 0.8s
    epoch 017/100 | train_mse=0.02631917 | val_mse=0.01988197 | best_val_mse=0.01971353 | early_stop=09/10 | 0.9s
    epoch 018/100 | train_mse=0.02618709 | val_mse=0.01991593 | best_val_mse=0.01971353 | early_stop=10/10 | 0.9s
  refit 01/06 | test_year=2019 | status=saved | n_predictions=8,478
  refit 02/06 | test_year=2020 | status=training | train_n=102,610 | validation_n=31,795 | test_n=9,940

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02731399 | val_mse=0.02166461 | best_val_mse=0.02166461 | early_stop=00/10 | 0.8s
    epoch 002/100 | train_mse=0.02644914 | val_mse=0.02183005 | best_val_mse=0.02166461 | early_stop=01/10 | 0.8s
    epoch 003/100 | train_mse=0.02627874 | val_mse=0.02169440 | best_val_mse=0.02166461 | early_stop=02/10 | 0.9s
    epoch 004/100 | train_mse=0.02622471 | val_mse=0.02213011 | best_val_mse=0.02166461 | early_stop=03/10 | 0.9s
    epoch 005/100 | train_mse=0.02623857 | val_mse=0.02157984 | best_val_mse=0.02157984 | early_stop=00/10 | 0.9s
    epoch 006/100 | train_mse=0.02598556 | val_mse=0.02160773 | best_val_mse=0.02157984 | early_stop=01/10 | 0.8s
    epoch 007/100 | train_mse=0.02598047 | val_mse=0.02158226 | best_val_mse=0.02157984 | early_stop=02/10 | 0.9s
    epoch 008/100 | train_mse=0.02608237 | val_mse=0.02161862 | best_val_mse=0.02157984 | early_stop=03/10 | 0.9s
    epoch 009/100 | train_mse=0.02598075 | val_mse=0.02187980 | best_val_mse=0.02157984 | early_stop=04/10 | 1.0s
    epoch 010/100 | train_mse=0.02595680 | val_mse=0.02166997 | best_val_mse=0.02157984 | early_stop=05/10 | 1.0s
    epoch 011/100 | train_mse=0.02587137 | val_mse=0.02157937 | best_val_mse=0.02157937 | early_stop=00/10 | 1.0s
    epoch 012/100 | train_mse=0.02586924 | val_mse=0.02157218 | best_val_mse=0.02157218 | early_stop=00/10 | 1.0s
    epoch 013/100 | train_mse=0.02583008 | val_mse=0.02172697 | best_val_mse=0.02157218 | early_stop=01/10 | 1.0s
    epoch 014/100 | train_mse=0.02585226 | val_mse=0.02169590 | best_val_mse=0.02157218 | early_stop=02/10 | 1.0s
    epoch 015/100 | train_mse=0.02583947 | val_mse=0.02166638 | best_val_mse=0.02157218 | early_stop=03/10 | 1.0s
    epoch 016/100 | train_mse=0.02577608 | val_mse=0.02167412 | best_val_mse=0.02157218 | early_stop=04/10 | 0.8s
    epoch 017/100 | train_mse=0.02566775 | val_mse=0.02161975 | best_val_mse=0.02157218 | early_stop=05/10 | 0.8s
    epoch 018/100 | train_mse=0.02561643 | val_mse=0.02161859 | best_val_mse=0.02157218 | early_stop=06/10 | 0.8s
    epoch 019/100 | train_mse=0.02559434 | val_mse=0.02164297 | best_val_mse=0.02157218 | early_stop=07/10 | 0.8s
    epoch 020/100 | train_mse=0.02568852 | val_mse=0.02161623 | best_val_mse=0.02157218 | early_stop=08/10 | 0.9s
    epoch 021/100 | train_mse=0.02560676 | val_mse=0.02192761 | best_val_mse=0.02157218 | early_stop=09/10 | 0.9s
    epoch 022/100 | train_mse=0.02560706 | val_mse=0.02172383 | best_val_mse=0.02157218 | early_stop=10/10 | 0.9s
  refit 02/06 | test_year=2020 | status=saved | n_predictions=9,940
  refit 03/06 | test_year=2021 | status=training | train_n=104,555 | validation_n=34,089 | test_n=8,112

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02725384 | val_mse=0.02343014 | best_val_mse=0.02343014 | early_stop=00/10 | 0.8s
    epoch 002/100 | train_mse=0.02614111 | val_mse=0.02410879 | best_val_mse=0.02343014 | early_stop=01/10 | 0.8s
    epoch 003/100 | train_mse=0.02612905 | val_mse=0.02327253 | best_val_mse=0.02327253 | early_stop=00/10 | 0.9s
    epoch 004/100 | train_mse=0.02585804 | val_mse=0.02322117 | best_val_mse=0.02322117 | early_stop=00/10 | 0.9s
    epoch 005/100 | train_mse=0.02583163 | val_mse=0.02327899 | best_val_mse=0.02322117 | early_stop=01/10 | 0.8s
    epoch 006/100 | train_mse=0.02578848 | val_mse=0.02329576 | best_val_mse=0.02322117 | early_stop=02/10 | 0.8s
    epoch 007/100 | train_mse=0.02566989 | val_mse=0.02330869 | best_val_mse=0.02322117 | early_stop=03/10 | 0.8s
    epoch 008/100 | train_mse=0.02576606 | val_mse=0.02342547 | best_val_mse=0.02322117 | early_stop=04/10 | 0.8s
    epoch 009/100 | train_mse=0.02569211 | val_mse=0.02329978 | best_val_mse=0.02322117 | early_stop=05/10 | 0.8s
    epoch 010/100 | train_mse=0.02570466 | val_mse=0.02330514 | best_val_mse=0.02322117 | early_stop=06/10 | 0.8s
    epoch 011/100 | train_mse=0.02561651 | val_mse=0.02342856 | best_val_mse=0.02322117 | early_stop=07/10 | 0.8s
    epoch 012/100 | train_mse=0.02570039 | val_mse=0.02326951 | best_val_mse=0.02322117 | early_stop=08/10 | 0.8s
    epoch 013/100 | train_mse=0.02560734 | val_mse=0.02374864 | best_val_mse=0.02322117 | early_stop=09/10 | 0.8s
    epoch 014/100 | train_mse=0.02585362 | val_mse=0.02320206 | best_val_mse=0.02320206 | early_stop=00/10 | 0.8s
    epoch 015/100 | train_mse=0.02556568 | val_mse=0.02377711 | best_val_mse=0.02320206 | early_stop=01/10 | 0.8s
    epoch 016/100 | train_mse=0.02570876 | val_mse=0.02330024 | best_val_mse=0.02320206 | early_stop=02/10 | 0.8s
    epoch 017/100 | train_mse=0.02543618 | val_mse=0.02328007 | best_val_mse=0.02320206 | early_stop=03/10 | 0.9s
    epoch 018/100 | train_mse=0.02566357 | val_mse=0.02327937 | best_val_mse=0.02320206 | early_stop=04/10 | 0.9s
    epoch 019/100 | train_mse=0.02547033 | val_mse=0.02323974 | best_val_mse=0.02320206 | early_stop=05/10 | 0.9s
    epoch 020/100 | train_mse=0.02538397 | val_mse=0.02342982 | best_val_mse=0.02320206 | early_stop=06/10 | 0.9s
    epoch 021/100 | train_mse=0.02552768 | val_mse=0.02326549 | best_val_mse=0.02320206 | early_stop=07/10 | 0.8s
    epoch 022/100 | train_mse=0.02552111 | val_mse=0.02324611 | best_val_mse=0.02320206 | early_stop=08/10 | 0.8s
    epoch 023/100 | train_mse=0.02523377 | val_mse=0.02326713 | best_val_mse=0.02320206 | early_stop=09/10 | 0.8s
    epoch 024/100 | train_mse=0.02518927 | val_mse=0.02331194 | best_val_mse=0.02320206 | early_stop=10/10 | 0.8s
  refit 03/06 | test_year=2021 | status=saved | n_predictions=8,112
  refit 04/06 | test_year=2022 | status=training | train_n=107,321 | validation_n=34,334 | test_n=8,881

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02586064 | val_mse=0.03913443 | best_val_mse=0.03913443 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.02511481 | val_mse=0.03896148 | best_val_mse=0.03896148 | early_stop=00/10 | 0.9s
    epoch 003/100 | train_mse=0.02512932 | val_mse=0.03922957 | best_val_mse=0.03896148 | early_stop=01/10 | 0.8s
    epoch 004/100 | train_mse=0.02538011 | val_mse=0.03900349 | best_val_mse=0.03896148 | early_stop=02/10 | 0.8s
    epoch 005/100 | train_mse=0.02503462 | val_mse=0.03887572 | best_val_mse=0.03887572 | early_stop=00/10 | 0.9s
    epoch 006/100 | train_mse=0.02498007 | val_mse=0.03886900 | best_val_mse=0.03886900 | early_stop=00/10 | 0.9s
    epoch 007/100 | train_mse=0.02482709 | val_mse=0.03885120 | best_val_mse=0.03885120 | early_stop=00/10 | 0.9s
    epoch 008/100 | train_mse=0.02482003 | val_mse=0.03893474 | best_val_mse=0.03885120 | early_stop=01/10 | 0.8s
    epoch 009/100 | train_mse=0.02473321 | val_mse=0.03892690 | best_val_mse=0.03885120 | early_stop=02/10 | 0.8s
    epoch 010/100 | train_mse=0.02474217 | val_mse=0.03886011 | best_val_mse=0.03885120 | early_stop=03/10 | 0.8s
    epoch 011/100 | train_mse=0.02472256 | val_mse=0.03900012 | best_val_mse=0.03885120 | early_stop=04/10 | 0.8s
    epoch 012/100 | train_mse=0.02468260 | val_mse=0.03887869 | best_val_mse=0.03885120 | early_stop=05/10 | 0.8s
    epoch 013/100 | train_mse=0.02460185 | val_mse=0.03897210 | best_val_mse=0.03885120 | early_stop=06/10 | 0.8s
    epoch 014/100 | train_mse=0.02456874 | val_mse=0.03905189 | best_val_mse=0.03885120 | early_stop=07/10 | 0.8s
    epoch 015/100 | train_mse=0.02460389 | val_mse=0.03899177 | best_val_mse=0.03885120 | early_stop=08/10 | 0.8s
    epoch 016/100 | train_mse=0.02458519 | val_mse=0.03895629 | best_val_mse=0.03885120 | early_stop=09/10 | 0.8s
    epoch 017/100 | train_mse=0.02454469 | val_mse=0.03890525 | best_val_mse=0.03885120 | early_stop=10/10 | 0.8s
  refit 04/06 | test_year=2022 | status=saved | n_predictions=8,881
  refit 05/06 | test_year=2023 | status=training | train_n=110,241 | validation_n=35,199 | test_n=9,821

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02637501 | val_mse=0.03932785 | best_val_mse=0.03932785 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.02555874 | val_mse=0.03969267 | best_val_mse=0.03932785 | early_stop=01/10 | 0.9s
    epoch 003/100 | train_mse=0.02541768 | val_mse=0.03910410 | best_val_mse=0.03910410 | early_stop=00/10 | 0.9s
    epoch 004/100 | train_mse=0.02562107 | val_mse=0.03943153 | best_val_mse=0.03910410 | early_stop=01/10 | 0.9s
    epoch 005/100 | train_mse=0.02536040 | val_mse=0.03942909 | best_val_mse=0.03910410 | early_stop=02/10 | 0.8s
    epoch 006/100 | train_mse=0.02541556 | val_mse=0.03987845 | best_val_mse=0.03910410 | early_stop=03/10 | 0.8s
    epoch 007/100 | train_mse=0.02528395 | val_mse=0.03922172 | best_val_mse=0.03910410 | early_stop=04/10 | 0.8s
    epoch 008/100 | train_mse=0.02528830 | val_mse=0.03968031 | best_val_mse=0.03910410 | early_stop=05/10 | 0.8s
    epoch 009/100 | train_mse=0.02516854 | val_mse=0.03959844 | best_val_mse=0.03910410 | early_stop=06/10 | 0.8s
    epoch 010/100 | train_mse=0.02512212 | val_mse=0.03950946 | best_val_mse=0.03910410 | early_stop=07/10 | 0.8s
    epoch 011/100 | train_mse=0.02506145 | val_mse=0.03923915 | best_val_mse=0.03910410 | early_stop=08/10 | 0.8s
    epoch 012/100 | train_mse=0.02509350 | val_mse=0.03919080 | best_val_mse=0.03910410 | early_stop=09/10 | 0.8s
    epoch 013/100 | train_mse=0.02505621 | val_mse=0.03979389 | best_val_mse=0.03910410 | early_stop=10/10 | 0.8s
  refit 05/06 | test_year=2023 | status=saved | n_predictions=9,821
  refit 06/06 | test_year=2024 | status=training | train_n=113,637 | validation_n=36,534 | test_n=8,732

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02662840 | val_mse=0.04039415 | best_val_mse=0.04039415 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.02641332 | val_mse=0.03959710 | best_val_mse=0.03959710 | early_stop=00/10 | 0.9s
    epoch 003/100 | train_mse=0.02649120 | val_mse=0.03943897 | best_val_mse=0.03943897 | early_stop=00/10 | 0.9s
    epoch 004/100 | train_mse=0.02623930 | val_mse=0.03950330 | best_val_mse=0.03943897 | early_stop=01/10 | 0.9s
    epoch 005/100 | train_mse=0.02610662 | val_mse=0.03950062 | best_val_mse=0.03943897 | early_stop=02/10 | 0.9s
    epoch 006/100 | train_mse=0.02604254 | val_mse=0.03973565 | best_val_mse=0.03943897 | early_stop=03/10 | 0.9s
    epoch 007/100 | train_mse=0.02595687 | val_mse=0.03988967 | best_val_mse=0.03943897 | early_stop=04/10 | 0.8s
    epoch 008/100 | train_mse=0.02598875 | val_mse=0.03945668 | best_val_mse=0.03943897 | early_stop=05/10 | 0.9s
    epoch 009/100 | train_mse=0.02603700 | val_mse=0.03955743 | best_val_mse=0.03943897 | early_stop=06/10 | 0.9s
    epoch 010/100 | train_mse=0.02594605 | val_mse=0.03998709 | best_val_mse=0.03943897 | early_stop=07/10 | 0.9s
    epoch 011/100 | train_mse=0.02593137 | val_mse=0.04000463 | best_val_mse=0.03943897 | early_stop=08/10 | 0.9s
    epoch 012/100 | train_mse=0.02586837 | val_mse=0.03960527 | best_val_mse=0.03943897 | early_stop=09/10 | 0.8s
    epoch 013/100 | train_mse=0.02580388 | val_mse=0.03964950 | best_val_mse=0.03943897 | early_stop=10/10 | 0.8s
  refit 06/06 | test_year=2024 | status=saved | n_predictions=8,732

######## DEU: Germany ########

=== DEU | LGBM_40 ===
Device: cuda

LGBM_40 [61670d27807e6b8b]
  refit 01/06 | test_year=2019 | status=training | train_n=87,240 | validation_n=20,814 | test_n=5,624

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 01/06 | test_year=2019 | status=saved | n_predictions=5,624
  refit 02/06 | test_year=2020 | status=training | train_n=84,598 | validation_n=21,434 | test_n=5,905

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 02/06 | test_year=2020 | status=saved | n_predictions=5,905
  refit 03/06 | test_year=2021 | status=training | train_n=81,306 | validation_n=22,234 | test_n=5,099

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 03/06 | test_year=2021 | status=saved | n_predictions=5,099
  refit 04/06 | test_year=2022 | status=training | train_n=80,407 | validation_n=22,007 | test_n=5,334

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 04/06 | test_year=2022 | status=saved | n_predictions=5,334
  refit 05/06 | test_year=2023 | status=training | train_n=81,016 | validation_n=21,897 | test_n=5,834

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 05/06 | test_year=2023 | status=saved | n_predictions=5,834
  refit 06/06 | test_year=2024 | status=training | train_n=82,421 | validation_n=22,104 | test_n=5,480

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 06/06 | test_year=2024 | status=saved | n_predictions=5,480

=== DEU | DEEPSET_40_DYNAMIC ===
Device: cuda

DEEPSET_40_DYNAMIC [5e00a14b3c8919c2]
  refit 01/06 | test_year=2019 | status=training | train_n=87,240 | validation_n=20,814 | test_n=5,624
    epoch 001/100 | train_mse=0.02238419 | val_mse=0.01120623 | best_val_mse=0.01120623 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.02170873 | val_mse=0.01126405 | best_val_mse=0.01120623 | early_stop=01/10 | 0.9s
    epoch 003/100 | train_mse=0.02160333 | val_mse=0.01113554 | best_val_mse=0.01113554 | early_stop=00/10 | 0.9s
    epoch 004/100 | train_mse=0.02146290 | val_mse=0.01129842 | best_val_mse=0.01113554 | early_stop=01/10 | 0.8s
    epoch 005/100 | train_mse=0.02138910 | val_mse=0.01112681 | best_val_mse=0.01112681 | early_stop=00/10 | 0.9s
    epoch 006/100 | train_mse=0.02127998 | val_mse=0.01123810 | best_val_mse=0.01112681 | early_stop=01/10 | 0.9s
    epoch 007/100 | train_mse=0.02125594 | val_mse=0.01129292 | best_val_mse=0.01112681 | early_stop=02/10 | 0.9s
    epoch 008/100 | train_mse=0.02128420 | val_mse=0.01116104 | best_val_mse=0.01112681 | early_stop=03/10 | 0.9s
    epoch 009/100 | train_mse=0.02110082 | val_mse=0.01188723 | best_val_mse=0.01112681 | early_stop=04/10 | 0.8s
    epoch 010/100 | train_mse=0.02116611 | val_mse=0.01109957 | best_val_mse=0.01109957 | early_stop=00/10 | 0.9s
    epoch 011/100 | train_mse=0.02106083 | val_mse=0.01113404 | best_val_mse=0.01109957 | early_stop=01/10 | 0.9s
    epoch 012/100 | train_mse=0.02104424 | val_mse=0.01116248 | best_val_mse=0.01109957 | early_stop=02/10 | 0.9s
    epoch 013/100 | train_mse=0.02109811 | val_mse=0.01109554 | best_val_mse=0.01109554 | early_stop=00/10 | 0.9s
    epoch 014/100 | train_mse=0.02082462 | val_mse=0.01142291 | best_val_mse=0.01109554 | early_stop=01/10 | 0.9s
    epoch 015/100 | train_mse=0.02078280 | val_mse=0.01107807 | best_val_mse=0.01107807 | early_stop=00/10 | 0.9s
    epoch 016/100 | train_mse=0.02087381 | val_mse=0.01178401 | best_val_mse=0.01107807 | early_stop=01/10 | 0.9s
    epoch 017/100 | train_mse=0.02069680 | val_mse=0.01131596 | best_val_mse=0.01107807 | early_stop=02/10 | 0.8s
    epoch 018/100 | train_mse=0.02071535 | val_mse=0.01115865 | best_val_mse=0.01107807 | early_stop=03/10 | 0.9s
    epoch 019/100 | train_mse=0.02077432 | val_mse=0.01107956 | best_val_mse=0.01107807 | early_stop=04/10 | 0.8s
    epoch 020/100 | train_mse=0.02054817 | val_mse=0.01117088 | best_val_mse=0.01107807 | early_stop=05/10 | 0.9s
    epoch 021/100 | train_mse=0.02060584 | val_mse=0.01110934 | best_val_mse=0.01107807 | early_stop=06/10 | 0.8s
    epoch 022/100 | train_mse=0.02047792 | val_mse=0.01120626 | best_val_mse=0.01107807 | early_stop=07/10 | 0.8s
    epoch 023/100 | train_mse=0.02072293 | val_mse=0.01110998 | best_val_mse=0.01107807 | early_stop=08/10 | 0.8s
    epoch 024/100 | train_mse=0.02064207 | val_mse=0.01120478 | best_val_mse=0.01107807 | early_stop=09/10 | 0.8s
    epoch 025/100 | train_mse=0.02053052 | val_mse=0.01106052 | best_val_mse=0.01106052 | early_stop=00/10 | 0.9s
    epoch 026/100 | train_mse=0.02049165 | val_mse=0.01107129 | best_val_mse=0.01106052 | early_stop=01/10 | 0.9s
    epoch 027/100 | train_mse=0.02035760 | val_mse=0.01129263 | best_val_mse=0.01106052 | early_stop=02/10 | 0.9s
    epoch 028/100 | train_mse=0.02054314 | val_mse=0.01109841 | best_val_mse=0.01106052 | early_stop=03/10 | 0.9s
    epoch 029/100 | train_mse=0.02032590 | val_mse=0.01117742 | best_val_mse=0.01106052 | early_stop=04/10 | 0.9s
    epoch 030/100 | train_mse=0.02025421 | val_mse=0.01119867 | best_val_mse=0.01106052 | early_stop=05/10 | 0.8s
    epoch 031/100 | train_mse=0.02008640 | val_mse=0.01116134 | best_val_mse=0.01106052 | early_stop=06/10 | 0.8s
    epoch 032/100 | train_mse=0.02023433 | val_mse=0.01118738 | best_val_mse=0.01106052 | early_stop=07/10 | 0.8s
    epoch 033/100 | train_mse=0.02000246 | val_mse=0.01111032 | best_val_mse=0.01106052 | early_stop=08/10 | 0.9s
    epoch 034/100 | train_mse=0.01993656 | val_mse=0.01140542 | best_val_mse=0.01106052 | early_stop=09/10 | 0.8s
    epoch 035/100 | train_mse=0.01992942 | val_mse=0.01116209 | best_val_mse=0.01106052 | early_stop=10/10 | 0.8s
  refit 01/06 | test_year=2019 | status=saved | n_predictions=5,624
  refit 02/06 | test_year=2020 | status=training | train_n=84,598 | validation_n=21,434 | test_n=5,905
    epoch 001/100 | train_mse=0.02039055 | val_mse=0.01106227 | best_val_mse=0.01106227 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.01952865 | val_mse=0.01104071 | best_val_mse=0.01104071 | early_stop=00/10 | 0.9s
    epoch 003/100 | train_mse=0.01936528 | val_mse=0.01126379 | best_val_mse=0.01104071 | early_stop=01/10 | 0.9s
    epoch 004/100 | train_mse=0.01941112 | val_mse=0.01139546 | best_val_mse=0.01104071 | early_stop=02/10 | 0.9s
    epoch 005/100 | train_mse=0.01926717 | val_mse=0.01087461 | best_val_mse=0.01087461 | early_stop=00/10 | 0.9s
    epoch 006/100 | train_mse=0.01913786 | val_mse=0.01090980 | best_val_mse=0.01087461 | early_stop=01/10 | 0.8s
    epoch 007/100 | train_mse=0.01919942 | val_mse=0.01088739 | best_val_mse=0.01087461 | early_stop=02/10 | 0.9s
    epoch 008/100 | train_mse=0.01913189 | val_mse=0.01087350 | best_val_mse=0.01087350 | early_stop=00/10 | 0.9s
    epoch 009/100 | train_mse=0.01909378 | val_mse=0.01101630 | best_val_mse=0.01087350 | early_stop=01/10 | 0.8s
    epoch 010/100 | train_mse=0.01899936 | val_mse=0.01085440 | best_val_mse=0.01085440 | early_stop=00/10 | 0.8s
    epoch 011/100 | train_mse=0.01899018 | val_mse=0.01089869 | best_val_mse=0.01085440 | early_stop=01/10 | 0.8s
    epoch 012/100 | train_mse=0.01888181 | val_mse=0.01130447 | best_val_mse=0.01085440 | early_stop=02/10 | 0.8s
    epoch 013/100 | train_mse=0.01921009 | val_mse=0.01102887 | best_val_mse=0.01085440 | early_stop=03/10 | 0.8s
    epoch 014/100 | train_mse=0.01891563 | val_mse=0.01084183 | best_val_mse=0.01084183 | early_stop=00/10 | 0.9s
    epoch 015/100 | train_mse=0.01901007 | val_mse=0.01110731 | best_val_mse=0.01084183 | early_stop=01/10 | 0.8s
    epoch 016/100 | train_mse=0.01877372 | val_mse=0.01083173 | best_val_mse=0.01083173 | early_stop=00/10 | 0.9s
    epoch 017/100 | train_mse=0.01878927 | val_mse=0.01086100 | best_val_mse=0.01083173 | early_stop=01/10 | 0.9s
    epoch 018/100 | train_mse=0.01869574 | val_mse=0.01104494 | best_val_mse=0.01083173 | early_stop=02/10 | 0.9s
    epoch 019/100 | train_mse=0.01851110 | val_mse=0.01091670 | best_val_mse=0.01083173 | early_stop=03/10 | 0.9s
    epoch 020/100 | train_mse=0.01872681 | val_mse=0.01087851 | best_val_mse=0.01083173 | early_stop=04/10 | 0.9s
    epoch 021/100 | train_mse=0.01866817 | val_mse=0.01101484 | best_val_mse=0.01083173 | early_stop=05/10 | 0.9s
    epoch 022/100 | train_mse=0.01865740 | val_mse=0.01090085 | best_val_mse=0.01083173 | early_stop=06/10 | 0.9s
    epoch 023/100 | train_mse=0.01837725 | val_mse=0.01095151 | best_val_mse=0.01083173 | early_stop=07/10 | 0.9s
    epoch 024/100 | train_mse=0.01834462 | val_mse=0.01099448 | best_val_mse=0.01083173 | early_stop=08/10 | 0.8s
    epoch 025/100 | train_mse=0.01827427 | val_mse=0.01105824 | best_val_mse=0.01083173 | early_stop=09/10 | 0.8s
    epoch 026/100 | train_mse=0.01845044 | val_mse=0.01100420 | best_val_mse=0.01083173 | early_stop=10/10 | 0.9s
  refit 02/06 | test_year=2020 | status=saved | n_predictions=5,905
  refit 03/06 | test_year=2021 | status=training | train_n=81,306 | validation_n=22,234 | test_n=5,099
    epoch 001/100 | train_mse=0.01809222 | val_mse=0.01571281 | best_val_mse=0.01571281 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.01731867 | val_mse=0.01597917 | best_val_mse=0.01571281 | early_stop=01/10 | 0.9s
    epoch 003/100 | train_mse=0.01731184 | val_mse=0.01566630 | best_val_mse=0.01566630 | early_stop=00/10 | 0.9s
    epoch 004/100 | train_mse=0.01700508 | val_mse=0.01576187 | best_val_mse=0.01566630 | early_stop=01/10 | 0.9s
    epoch 005/100 | train_mse=0.01707014 | val_mse=0.01572611 | best_val_mse=0.01566630 | early_stop=02/10 | 0.9s
    epoch 006/100 | train_mse=0.01694790 | val_mse=0.01568224 | best_val_mse=0.01566630 | early_stop=03/10 | 0.9s
    epoch 007/100 | train_mse=0.01687637 | val_mse=0.01570964 | best_val_mse=0.01566630 | early_stop=04/10 | 0.9s
    epoch 008/100 | train_mse=0.01692599 | val_mse=0.01565066 | best_val_mse=0.01565066 | early_stop=00/10 | 0.9s
    epoch 009/100 | train_mse=0.01685610 | val_mse=0.01569302 | best_val_mse=0.01565066 | early_stop=01/10 | 0.9s
    epoch 010/100 | train_mse=0.01686090 | val_mse=0.01569051 | best_val_mse=0.01565066 | early_stop=02/10 | 0.9s
    epoch 011/100 | train_mse=0.01676413 | val_mse=0.01565393 | best_val_mse=0.01565066 | early_stop=03/10 | 0.9s
    epoch 012/100 | train_mse=0.01678853 | val_mse=0.01565763 | best_val_mse=0.01565066 | early_stop=04/10 | 0.9s
    epoch 013/100 | train_mse=0.01685253 | val_mse=0.01566091 | best_val_mse=0.01565066 | early_stop=05/10 | 0.9s
    epoch 014/100 | train_mse=0.01673775 | val_mse=0.01569850 | best_val_mse=0.01565066 | early_stop=06/10 | 0.9s
    epoch 015/100 | train_mse=0.01678744 | val_mse=0.01567077 | best_val_mse=0.01565066 | early_stop=07/10 | 0.9s
    epoch 016/100 | train_mse=0.01673114 | val_mse=0.01565053 | best_val_mse=0.01565053 | early_stop=00/10 | 0.9s
    epoch 017/100 | train_mse=0.01663170 | val_mse=0.01626417 | best_val_mse=0.01565053 | early_stop=01/10 | 0.8s
    epoch 018/100 | train_mse=0.01682146 | val_mse=0.01598319 | best_val_mse=0.01565053 | early_stop=02/10 | 0.9s
    epoch 019/100 | train_mse=0.01664698 | val_mse=0.01575524 | best_val_mse=0.01565053 | early_stop=03/10 | 0.9s
    epoch 020/100 | train_mse=0.01657802 | val_mse=0.01579407 | best_val_mse=0.01565053 | early_stop=04/10 | 0.9s
    epoch 021/100 | train_mse=0.01668561 | val_mse=0.01597772 | best_val_mse=0.01565053 | early_stop=05/10 | 0.9s
    epoch 022/100 | train_mse=0.01660115 | val_mse=0.01584075 | best_val_mse=0.01565053 | early_stop=06/10 | 0.9s
    epoch 023/100 | train_mse=0.01649676 | val_mse=0.01582195 | best_val_mse=0.01565053 | early_stop=07/10 | 0.9s
    epoch 024/100 | train_mse=0.01650547 | val_mse=0.01583860 | best_val_mse=0.01565053 | early_stop=08/10 | 0.9s
    epoch 025/100 | train_mse=0.01663808 | val_mse=0.01565219 | best_val_mse=0.01565053 | early_stop=09/10 | 0.9s
    epoch 026/100 | train_mse=0.01639588 | val_mse=0.01593396 | best_val_mse=0.01565053 | early_stop=10/10 | 0.8s
  refit 03/06 | test_year=2021 | status=saved | n_predictions=5,099
  refit 04/06 | test_year=2022 | status=training | train_n=80,407 | validation_n=22,007 | test_n=5,334
    epoch 001/100 | train_mse=0.01681413 | val_mse=0.01594420 | best_val_mse=0.01594420 | early_stop=00/10 | 0.8s
    epoch 002/100 | train_mse=0.01604911 | val_mse=0.01607407 | best_val_mse=0.01594420 | early_stop=01/10 | 0.8s
    epoch 003/100 | train_mse=0.01601043 | val_mse=0.01635021 | best_val_mse=0.01594420 | early_stop=02/10 | 0.8s
    epoch 004/100 | train_mse=0.01617984 | val_mse=0.01622925 | best_val_mse=0.01594420 | early_stop=03/10 | 0.9s
    epoch 005/100 | train_mse=0.01590668 | val_mse=0.01582916 | best_val_mse=0.01582916 | early_stop=00/10 | 0.9s
    epoch 006/100 | train_mse=0.01584907 | val_mse=0.01584482 | best_val_mse=0.01582916 | early_stop=01/10 | 0.9s
    epoch 007/100 | train_mse=0.01580918 | val_mse=0.01587484 | best_val_mse=0.01582916 | early_stop=02/10 | 0.9s
    epoch 008/100 | train_mse=0.01578377 | val_mse=0.01580862 | best_val_mse=0.01580862 | early_stop=00/10 | 0.9s
    epoch 009/100 | train_mse=0.01569979 | val_mse=0.01586622 | best_val_mse=0.01580862 | early_stop=01/10 | 0.9s
    epoch 010/100 | train_mse=0.01565163 | val_mse=0.01585407 | best_val_mse=0.01580862 | early_stop=02/10 | 0.9s
    epoch 011/100 | train_mse=0.01572516 | val_mse=0.01582938 | best_val_mse=0.01580862 | early_stop=03/10 | 0.9s
    epoch 012/100 | train_mse=0.01567793 | val_mse=0.01586747 | best_val_mse=0.01580862 | early_stop=04/10 | 0.9s
    epoch 013/100 | train_mse=0.01558243 | val_mse=0.01584535 | best_val_mse=0.01580862 | early_stop=05/10 | 0.9s
    epoch 014/100 | train_mse=0.01556326 | val_mse=0.01589683 | best_val_mse=0.01580862 | early_stop=06/10 | 0.8s
    epoch 015/100 | train_mse=0.01569126 | val_mse=0.01590748 | best_val_mse=0.01580862 | early_stop=07/10 | 0.9s
    epoch 016/100 | train_mse=0.01555668 | val_mse=0.01589893 | best_val_mse=0.01580862 | early_stop=08/10 | 0.8s
    epoch 017/100 | train_mse=0.01549580 | val_mse=0.01605651 | best_val_mse=0.01580862 | early_stop=09/10 | 0.9s
    epoch 018/100 | train_mse=0.01558276 | val_mse=0.01592472 | best_val_mse=0.01580862 | early_stop=10/10 | 0.8s
  refit 04/06 | test_year=2022 | status=saved | n_predictions=5,334
  refit 05/06 | test_year=2023 | status=training | train_n=81,016 | validation_n=21,897 | test_n=5,834
    epoch 001/100 | train_mse=0.01610307 | val_mse=0.01802072 | best_val_mse=0.01802072 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.01533005 | val_mse=0.01799631 | best_val_mse=0.01799631 | early_stop=00/10 | 0.9s
    epoch 003/100 | train_mse=0.01527165 | val_mse=0.01782167 | best_val_mse=0.01782167 | early_stop=00/10 | 0.8s
    epoch 004/100 | train_mse=0.01540834 | val_mse=0.01790885 | best_val_mse=0.01782167 | early_stop=01/10 | 0.8s
    epoch 005/100 | train_mse=0.01524390 | val_mse=0.01780135 | best_val_mse=0.01780135 | early_stop=00/10 | 0.9s
    epoch 006/100 | train_mse=0.01515559 | val_mse=0.01799600 | best_val_mse=0.01780135 | early_stop=01/10 | 0.9s
    epoch 007/100 | train_mse=0.01512266 | val_mse=0.01787653 | best_val_mse=0.01780135 | early_stop=02/10 | 0.9s
    epoch 008/100 | train_mse=0.01505148 | val_mse=0.01781805 | best_val_mse=0.01780135 | early_stop=03/10 | 0.9s
    epoch 009/100 | train_mse=0.01501664 | val_mse=0.01784881 | best_val_mse=0.01780135 | early_stop=04/10 | 0.9s
    epoch 010/100 | train_mse=0.01500174 | val_mse=0.01807618 | best_val_mse=0.01780135 | early_stop=05/10 | 0.9s
    epoch 011/100 | train_mse=0.01497544 | val_mse=0.01786556 | best_val_mse=0.01780135 | early_stop=06/10 | 0.9s
    epoch 012/100 | train_mse=0.01499139 | val_mse=0.01784921 | best_val_mse=0.01780135 | early_stop=07/10 | 0.9s
    epoch 013/100 | train_mse=0.01493923 | val_mse=0.01785284 | best_val_mse=0.01780135 | early_stop=08/10 | 0.9s
    epoch 014/100 | train_mse=0.01486572 | val_mse=0.01806140 | best_val_mse=0.01780135 | early_stop=09/10 | 0.9s
    epoch 015/100 | train_mse=0.01506190 | val_mse=0.01791929 | best_val_mse=0.01780135 | early_stop=10/10 | 0.9s
  refit 05/06 | test_year=2023 | status=saved | n_predictions=5,834
  refit 06/06 | test_year=2024 | status=training | train_n=82,421 | validation_n=22,104 | test_n=5,480
    epoch 001/100 | train_mse=0.01559070 | val_mse=0.02298922 | best_val_mse=0.02298922 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.01552128 | val_mse=0.02236721 | best_val_mse=0.02236721 | early_stop=00/10 | 0.9s
    epoch 003/100 | train_mse=0.01531759 | val_mse=0.02239512 | best_val_mse=0.02236721 | early_stop=01/10 | 0.9s
    epoch 004/100 | train_mse=0.01516497 | val_mse=0.02230260 | best_val_mse=0.02230260 | early_stop=00/10 | 0.9s
    epoch 005/100 | train_mse=0.01516294 | val_mse=0.02232316 | best_val_mse=0.02230260 | early_stop=01/10 | 0.9s
    epoch 006/100 | train_mse=0.01506857 | val_mse=0.02229638 | best_val_mse=0.02229638 | early_stop=00/10 | 0.9s
    epoch 007/100 | train_mse=0.01502263 | val_mse=0.02230463 | best_val_mse=0.02229638 | early_stop=01/10 | 0.9s
    epoch 008/100 | train_mse=0.01503294 | val_mse=0.02253171 | best_val_mse=0.02229638 | early_stop=02/10 | 0.9s
    epoch 009/100 | train_mse=0.01503931 | val_mse=0.02233641 | best_val_mse=0.02229638 | early_stop=03/10 | 0.8s
    epoch 010/100 | train_mse=0.01501909 | val_mse=0.02233541 | best_val_mse=0.02229638 | early_stop=04/10 | 0.8s
    epoch 011/100 | train_mse=0.01497562 | val_mse=0.02245200 | best_val_mse=0.02229638 | early_stop=05/10 | 0.8s
    epoch 012/100 | train_mse=0.01492161 | val_mse=0.02237243 | best_val_mse=0.02229638 | early_stop=06/10 | 0.8s
    epoch 013/100 | train_mse=0.01490244 | val_mse=0.02235635 | best_val_mse=0.02229638 | early_stop=07/10 | 0.9s
    epoch 014/100 | train_mse=0.01485332 | val_mse=0.02245918 | best_val_mse=0.02229638 | early_stop=08/10 | 0.9s
    epoch 015/100 | train_mse=0.01491735 | val_mse=0.02241026 | best_val_mse=0.02229638 | early_stop=09/10 | 0.9s
    epoch 016/100 | train_mse=0.01484309 | val_mse=0.02238576 | best_val_mse=0.02229638 | early_stop=10/10 | 0.9s
  refit 06/06 | test_year=2024 | status=saved | n_predictions=5,480

=== DEU | HYBRID_LGBM40_DEEPSET40_DYNAMIC ===
Device: cuda

HYBRID_LGBM40_DEEPSET40_DYNAMIC [216adab744557374]
  refit 01/06 | test_year=2019 | status=training | train_n=87,240 | validation_n=20,814 | test_n=5,624

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02238419 | val_mse=0.01130715 | best_val_mse=0.01130715 | early_stop=00/10 | 0.8s
    epoch 002/100 | train_mse=0.02170873 | val_mse=0.01143633 | best_val_mse=0.01130715 | early_stop=01/10 | 0.8s
    epoch 003/100 | train_mse=0.02160333 | val_mse=0.01129381 | best_val_mse=0.01129381 | early_stop=00/10 | 0.8s
    epoch 004/100 | train_mse=0.02146290 | val_mse=0.01161013 | best_val_mse=0.01129381 | early_stop=01/10 | 0.8s
    epoch 005/100 | train_mse=0.02138910 | val_mse=0.01126483 | best_val_mse=0.01126483 | early_stop=00/10 | 0.9s
    epoch 006/100 | train_mse=0.02127998 | val_mse=0.01145361 | best_val_mse=0.01126483 | early_stop=01/10 | 0.8s
    epoch 007/100 | train_mse=0.02125594 | val_mse=0.01160605 | best_val_mse=0.01126483 | early_stop=02/10 | 0.8s
    epoch 008/100 | train_mse=0.02128420 | val_mse=0.01132583 | best_val_mse=0.01126483 | early_stop=03/10 | 0.8s
    epoch 009/100 | train_mse=0.02110082 | val_mse=0.01244449 | best_val_mse=0.01126483 | early_stop=04/10 | 0.8s
    epoch 010/100 | train_mse=0.02116611 | val_mse=0.01118360 | best_val_mse=0.01118360 | early_stop=00/10 | 0.9s
    epoch 011/100 | train_mse=0.02106083 | val_mse=0.01118092 | best_val_mse=0.01118092 | early_stop=00/10 | 0.8s
    epoch 012/100 | train_mse=0.02104424 | val_mse=0.01124996 | best_val_mse=0.01118092 | early_stop=01/10 | 0.8s
    epoch 013/100 | train_mse=0.02109811 | val_mse=0.01116762 | best_val_mse=0.01116762 | early_stop=00/10 | 0.8s
    epoch 014/100 | train_mse=0.02082462 | val_mse=0.01176042 | best_val_mse=0.01116762 | early_stop=01/10 | 0.8s
    epoch 015/100 | train_mse=0.02078280 | val_mse=0.01109186 | best_val_mse=0.01109186 | early_stop=00/10 | 0.8s
    epoch 016/100 | train_mse=0.02087381 | val_mse=0.01217723 | best_val_mse=0.01109186 | early_stop=01/10 | 0.8s
    epoch 017/100 | train_mse=0.02069680 | val_mse=0.01158778 | best_val_mse=0.01109186 | early_stop=02/10 | 0.8s
    epoch 018/100 | train_mse=0.02071535 | val_mse=0.01104232 | best_val_mse=0.01104232 | early_stop=00/10 | 0.8s
    epoch 019/100 | train_mse=0.02077432 | val_mse=0.01120005 | best_val_mse=0.01104232 | early_stop=01/10 | 0.8s
    epoch 020/100 | train_mse=0.02054817 | val_mse=0.01111408 | best_val_mse=0.01104232 | early_stop=02/10 | 0.8s
    epoch 021/100 | train_mse=0.02060584 | val_mse=0.01110391 | best_val_mse=0.01104232 | early_stop=03/10 | 0.8s
    epoch 022/100 | train_mse=0.02047792 | val_mse=0.01138829 | best_val_mse=0.01104232 | early_stop=04/10 | 0.8s
    epoch 023/100 | train_mse=0.02072293 | val_mse=0.01120143 | best_val_mse=0.01104232 | early_stop=05/10 | 0.8s
    epoch 024/100 | train_mse=0.02064207 | val_mse=0.01146968 | best_val_mse=0.01104232 | early_stop=06/10 | 0.8s
    epoch 025/100 | train_mse=0.02053052 | val_mse=0.01118499 | best_val_mse=0.01104232 | early_stop=07/10 | 0.8s
    epoch 026/100 | train_mse=0.02049165 | val_mse=0.01114809 | best_val_mse=0.01104232 | early_stop=08/10 | 0.8s
    epoch 027/100 | train_mse=0.02035760 | val_mse=0.01116846 | best_val_mse=0.01104232 | early_stop=09/10 | 0.8s
    epoch 028/100 | train_mse=0.02054314 | val_mse=0.01130388 | best_val_mse=0.01104232 | early_stop=10/10 | 0.8s
  refit 01/06 | test_year=2019 | status=saved | n_predictions=5,624
  refit 02/06 | test_year=2020 | status=training | train_n=84,598 | validation_n=21,434 | test_n=5,905

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02039055 | val_mse=0.01111603 | best_val_mse=0.01111603 | early_stop=00/10 | 0.8s
    epoch 002/100 | train_mse=0.01952865 | val_mse=0.01109961 | best_val_mse=0.01109961 | early_stop=00/10 | 0.8s
    epoch 003/100 | train_mse=0.01936528 | val_mse=0.01132847 | best_val_mse=0.01109961 | early_stop=01/10 | 0.8s
    epoch 004/100 | train_mse=0.01941112 | val_mse=0.01145931 | best_val_mse=0.01109961 | early_stop=02/10 | 0.8s
    epoch 005/100 | train_mse=0.01926717 | val_mse=0.01092135 | best_val_mse=0.01092135 | early_stop=00/10 | 0.8s
    epoch 006/100 | train_mse=0.01913786 | val_mse=0.01094073 | best_val_mse=0.01092135 | early_stop=01/10 | 0.8s
    epoch 007/100 | train_mse=0.01919942 | val_mse=0.01092067 | best_val_mse=0.01092067 | early_stop=00/10 | 0.8s
    epoch 008/100 | train_mse=0.01913189 | val_mse=0.01091389 | best_val_mse=0.01091389 | early_stop=00/10 | 0.9s
    epoch 009/100 | train_mse=0.01909378 | val_mse=0.01106620 | best_val_mse=0.01091389 | early_stop=01/10 | 0.8s
    epoch 010/100 | train_mse=0.01899936 | val_mse=0.01089006 | best_val_mse=0.01089006 | early_stop=00/10 | 0.9s
    epoch 011/100 | train_mse=0.01899018 | val_mse=0.01094360 | best_val_mse=0.01089006 | early_stop=01/10 | 0.9s
    epoch 012/100 | train_mse=0.01888181 | val_mse=0.01130984 | best_val_mse=0.01089006 | early_stop=02/10 | 0.8s
    epoch 013/100 | train_mse=0.01921009 | val_mse=0.01104999 | best_val_mse=0.01089006 | early_stop=03/10 | 0.8s
    epoch 014/100 | train_mse=0.01891563 | val_mse=0.01086499 | best_val_mse=0.01086499 | early_stop=00/10 | 0.8s
    epoch 015/100 | train_mse=0.01901007 | val_mse=0.01111861 | best_val_mse=0.01086499 | early_stop=01/10 | 0.8s
    epoch 016/100 | train_mse=0.01877372 | val_mse=0.01086338 | best_val_mse=0.01086338 | early_stop=00/10 | 0.8s
    epoch 017/100 | train_mse=0.01878927 | val_mse=0.01087300 | best_val_mse=0.01086338 | early_stop=01/10 | 0.8s
    epoch 018/100 | train_mse=0.01869574 | val_mse=0.01104481 | best_val_mse=0.01086338 | early_stop=02/10 | 0.8s
    epoch 019/100 | train_mse=0.01851110 | val_mse=0.01090776 | best_val_mse=0.01086338 | early_stop=03/10 | 0.8s
    epoch 020/100 | train_mse=0.01872681 | val_mse=0.01091501 | best_val_mse=0.01086338 | early_stop=04/10 | 0.8s
    epoch 021/100 | train_mse=0.01866817 | val_mse=0.01099532 | best_val_mse=0.01086338 | early_stop=05/10 | 0.8s
    epoch 022/100 | train_mse=0.01865740 | val_mse=0.01090756 | best_val_mse=0.01086338 | early_stop=06/10 | 0.8s
    epoch 023/100 | train_mse=0.01837725 | val_mse=0.01092977 | best_val_mse=0.01086338 | early_stop=07/10 | 0.8s
    epoch 024/100 | train_mse=0.01834462 | val_mse=0.01096839 | best_val_mse=0.01086338 | early_stop=08/10 | 0.8s
    epoch 025/100 | train_mse=0.01827427 | val_mse=0.01101335 | best_val_mse=0.01086338 | early_stop=09/10 | 0.9s
    epoch 026/100 | train_mse=0.01845044 | val_mse=0.01099789 | best_val_mse=0.01086338 | early_stop=10/10 | 0.8s
  refit 02/06 | test_year=2020 | status=saved | n_predictions=5,905
  refit 03/06 | test_year=2021 | status=training | train_n=81,306 | validation_n=22,234 | test_n=5,099

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.01809222 | val_mse=0.01077768 | best_val_mse=0.01077768 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.01731867 | val_mse=0.01120189 | best_val_mse=0.01077768 | early_stop=01/10 | 0.8s
    epoch 003/100 | train_mse=0.01731184 | val_mse=0.01078190 | best_val_mse=0.01077768 | early_stop=02/10 | 0.8s
    epoch 004/100 | train_mse=0.01700508 | val_mse=0.01068171 | best_val_mse=0.01068171 | early_stop=00/10 | 0.9s
    epoch 005/100 | train_mse=0.01707014 | val_mse=0.01069106 | best_val_mse=0.01068171 | early_stop=01/10 | 0.8s
    epoch 006/100 | train_mse=0.01694790 | val_mse=0.01065915 | best_val_mse=0.01065915 | early_stop=00/10 | 0.9s
    epoch 007/100 | train_mse=0.01687637 | val_mse=0.01067926 | best_val_mse=0.01065915 | early_stop=01/10 | 0.8s
    epoch 008/100 | train_mse=0.01692599 | val_mse=0.01070215 | best_val_mse=0.01065915 | early_stop=02/10 | 0.8s
    epoch 009/100 | train_mse=0.01685610 | val_mse=0.01066473 | best_val_mse=0.01065915 | early_stop=03/10 | 0.8s
    epoch 010/100 | train_mse=0.01686090 | val_mse=0.01067301 | best_val_mse=0.01065915 | early_stop=04/10 | 0.8s
    epoch 011/100 | train_mse=0.01676413 | val_mse=0.01073105 | best_val_mse=0.01065915 | early_stop=05/10 | 0.8s
    epoch 012/100 | train_mse=0.01678853 | val_mse=0.01068112 | best_val_mse=0.01065915 | early_stop=06/10 | 0.8s
    epoch 013/100 | train_mse=0.01685253 | val_mse=0.01079915 | best_val_mse=0.01065915 | early_stop=07/10 | 0.8s
    epoch 014/100 | train_mse=0.01673775 | val_mse=0.01066653 | best_val_mse=0.01065915 | early_stop=08/10 | 0.8s
    epoch 015/100 | train_mse=0.01678744 | val_mse=0.01078351 | best_val_mse=0.01065915 | early_stop=09/10 | 0.9s
    epoch 016/100 | train_mse=0.01673114 | val_mse=0.01071389 | best_val_mse=0.01065915 | early_stop=10/10 | 0.8s
  refit 03/06 | test_year=2021 | status=saved | n_predictions=5,099
  refit 04/06 | test_year=2022 | status=training | train_n=80,407 | validation_n=22,007 | test_n=5,334

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.01681413 | val_mse=0.01741583 | best_val_mse=0.01741583 | early_stop=00/10 | 0.8s
    epoch 002/100 | train_mse=0.01604911 | val_mse=0.01752957 | best_val_mse=0.01741583 | early_stop=01/10 | 0.8s
    epoch 003/100 | train_mse=0.01601043 | val_mse=0.01777822 | best_val_mse=0.01741583 | early_stop=02/10 | 0.8s
    epoch 004/100 | train_mse=0.01617984 | val_mse=0.01765419 | best_val_mse=0.01741583 | early_stop=03/10 | 0.8s
    epoch 005/100 | train_mse=0.01590668 | val_mse=0.01728441 | best_val_mse=0.01728441 | early_stop=00/10 | 0.8s
    epoch 006/100 | train_mse=0.01584907 | val_mse=0.01729962 | best_val_mse=0.01728441 | early_stop=01/10 | 0.8s
    epoch 007/100 | train_mse=0.01580918 | val_mse=0.01731742 | best_val_mse=0.01728441 | early_stop=02/10 | 0.8s
    epoch 008/100 | train_mse=0.01578377 | val_mse=0.01728445 | best_val_mse=0.01728441 | early_stop=03/10 | 0.8s
    epoch 009/100 | train_mse=0.01569979 | val_mse=0.01731417 | best_val_mse=0.01728441 | early_stop=04/10 | 0.8s
    epoch 010/100 | train_mse=0.01565163 | val_mse=0.01731247 | best_val_mse=0.01728441 | early_stop=05/10 | 0.8s
    epoch 011/100 | train_mse=0.01572516 | val_mse=0.01729103 | best_val_mse=0.01728441 | early_stop=06/10 | 0.8s
    epoch 012/100 | train_mse=0.01567793 | val_mse=0.01732608 | best_val_mse=0.01728441 | early_stop=07/10 | 0.8s
    epoch 013/100 | train_mse=0.01558243 | val_mse=0.01732018 | best_val_mse=0.01728441 | early_stop=08/10 | 0.8s
    epoch 014/100 | train_mse=0.01556326 | val_mse=0.01739556 | best_val_mse=0.01728441 | early_stop=09/10 | 0.8s
    epoch 015/100 | train_mse=0.01569126 | val_mse=0.01740838 | best_val_mse=0.01728441 | early_stop=10/10 | 0.8s
  refit 04/06 | test_year=2022 | status=saved | n_predictions=5,334
  refit 05/06 | test_year=2023 | status=training | train_n=81,016 | validation_n=21,897 | test_n=5,834

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.01610307 | val_mse=0.01756071 | best_val_mse=0.01756071 | early_stop=00/10 | 0.8s
    epoch 002/100 | train_mse=0.01533005 | val_mse=0.01777734 | best_val_mse=0.01756071 | early_stop=01/10 | 0.8s
    epoch 003/100 | train_mse=0.01527165 | val_mse=0.01749352 | best_val_mse=0.01749352 | early_stop=00/10 | 0.8s
    epoch 004/100 | train_mse=0.01540834 | val_mse=0.01765847 | best_val_mse=0.01749352 | early_stop=01/10 | 0.8s
    epoch 005/100 | train_mse=0.01524390 | val_mse=0.01745651 | best_val_mse=0.01745651 | early_stop=00/10 | 0.8s
    epoch 006/100 | train_mse=0.01515559 | val_mse=0.01779474 | best_val_mse=0.01745651 | early_stop=01/10 | 0.8s
    epoch 007/100 | train_mse=0.01512266 | val_mse=0.01743371 | best_val_mse=0.01743371 | early_stop=00/10 | 0.8s
    epoch 008/100 | train_mse=0.01505148 | val_mse=0.01750886 | best_val_mse=0.01743371 | early_stop=01/10 | 0.8s
    epoch 009/100 | train_mse=0.01501664 | val_mse=0.01755023 | best_val_mse=0.01743371 | early_stop=02/10 | 0.8s
    epoch 010/100 | train_mse=0.01500174 | val_mse=0.01790213 | best_val_mse=0.01743371 | early_stop=03/10 | 0.8s
    epoch 011/100 | train_mse=0.01497544 | val_mse=0.01757240 | best_val_mse=0.01743371 | early_stop=04/10 | 0.8s
    epoch 012/100 | train_mse=0.01499139 | val_mse=0.01755648 | best_val_mse=0.01743371 | early_stop=05/10 | 0.8s
    epoch 013/100 | train_mse=0.01493923 | val_mse=0.01754299 | best_val_mse=0.01743371 | early_stop=06/10 | 0.8s
    epoch 014/100 | train_mse=0.01486572 | val_mse=0.01788033 | best_val_mse=0.01743371 | early_stop=07/10 | 0.8s
    epoch 015/100 | train_mse=0.01506190 | val_mse=0.01766421 | best_val_mse=0.01743371 | early_stop=08/10 | 0.8s
    epoch 016/100 | train_mse=0.01493104 | val_mse=0.01748045 | best_val_mse=0.01743371 | early_stop=09/10 | 0.8s
    epoch 017/100 | train_mse=0.01484248 | val_mse=0.01747635 | best_val_mse=0.01743371 | early_stop=10/10 | 0.8s
  refit 05/06 | test_year=2023 | status=saved | n_predictions=5,834
  refit 06/06 | test_year=2024 | status=training | train_n=82,421 | validation_n=22,104 | test_n=5,480

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.01559070 | val_mse=0.02115893 | best_val_mse=0.02115893 | early_stop=00/10 | 0.8s
    epoch 002/100 | train_mse=0.01552128 | val_mse=0.02038625 | best_val_mse=0.02038625 | early_stop=00/10 | 0.9s
    epoch 003/100 | train_mse=0.01531759 | val_mse=0.02028261 | best_val_mse=0.02028261 | early_stop=00/10 | 0.8s
    epoch 004/100 | train_mse=0.01516497 | val_mse=0.02026319 | best_val_mse=0.02026319 | early_stop=00/10 | 0.8s
    epoch 005/100 | train_mse=0.01516294 | val_mse=0.02027833 | best_val_mse=0.02026319 | early_stop=01/10 | 0.8s
    epoch 006/100 | train_mse=0.01506857 | val_mse=0.02026532 | best_val_mse=0.02026319 | early_stop=02/10 | 0.8s
    epoch 007/100 | train_mse=0.01502263 | val_mse=0.02027840 | best_val_mse=0.02026319 | early_stop=03/10 | 0.8s
    epoch 008/100 | train_mse=0.01503294 | val_mse=0.02038722 | best_val_mse=0.02026319 | early_stop=04/10 | 0.8s
    epoch 009/100 | train_mse=0.01503931 | val_mse=0.02027471 | best_val_mse=0.02026319 | early_stop=05/10 | 0.8s
    epoch 010/100 | train_mse=0.01501909 | val_mse=0.02034896 | best_val_mse=0.02026319 | early_stop=06/10 | 0.8s
    epoch 011/100 | train_mse=0.01497562 | val_mse=0.02053057 | best_val_mse=0.02026319 | early_stop=07/10 | 0.8s
    epoch 012/100 | train_mse=0.01492161 | val_mse=0.02031630 | best_val_mse=0.02026319 | early_stop=08/10 | 0.8s
    epoch 013/100 | train_mse=0.01490244 | val_mse=0.02035438 | best_val_mse=0.02026319 | early_stop=09/10 | 0.8s
    epoch 014/100 | train_mse=0.01485332 | val_mse=0.02034605 | best_val_mse=0.02026319 | early_stop=10/10 | 0.8s
  refit 06/06 | test_year=2024 | status=saved | n_predictions=5,480

######## FRA: France ########

=== FRA | LGBM_40 ===
Device: cuda

LGBM_40 [ded9e54eda05e69f]
  refit 01/06 | test_year=2019 | status=training | train_n=88,438 | validation_n=21,822 | test_n=5,445

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 01/06 | test_year=2019 | status=saved | n_predictions=5,445
  refit 02/06 | test_year=2020 | status=training | train_n=86,776 | validation_n=21,758 | test_n=5,803

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 02/06 | test_year=2020 | status=saved | n_predictions=5,803
  refit 03/06 | test_year=2021 | status=training | train_n=84,361 | validation_n=22,015 | test_n=4,701

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 03/06 | test_year=2021 | status=saved | n_predictions=4,701
  refit 04/06 | test_year=2022 | status=training | train_n=83,544 | validation_n=21,180 | test_n=4,916

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 04/06 | test_year=2022 | status=saved | n_predictions=4,916
  refit 05/06 | test_year=2023 | status=training | train_n=83,543 | validation_n=20,648 | test_n=5,506

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 05/06 | test_year=2023 | status=saved | n_predictions=5,506
  refit 06/06 | test_year=2024 | status=training | train_n=84,114 | validation_n=20,734 | test_n=5,220

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

  refit 06/06 | test_year=2024 | status=saved | n_predictions=5,220

=== FRA | DEEPSET_40_DYNAMIC ===
Device: cuda

DEEPSET_40_DYNAMIC [957deee44ac91bf8]
  refit 01/06 | test_year=2019 | status=training | train_n=88,438 | validation_n=21,822 | test_n=5,445
    epoch 001/100 | train_mse=0.02011548 | val_mse=0.01042077 | best_val_mse=0.01042077 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.01956056 | val_mse=0.01036630 | best_val_mse=0.01036630 | early_stop=00/10 | 0.9s
    epoch 003/100 | train_mse=0.01940035 | val_mse=0.01043240 | best_val_mse=0.01036630 | early_stop=01/10 | 0.9s
    epoch 004/100 | train_mse=0.01933076 | val_mse=0.01035824 | best_val_mse=0.01035824 | early_stop=00/10 | 0.9s
    epoch 005/100 | train_mse=0.01920781 | val_mse=0.01032114 | best_val_mse=0.01032114 | early_stop=00/10 | 0.9s
    epoch 006/100 | train_mse=0.01913498 | val_mse=0.01032986 | best_val_mse=0.01032114 | early_stop=01/10 | 0.9s
    epoch 007/100 | train_mse=0.01915424 | val_mse=0.01035009 | best_val_mse=0.01032114 | early_stop=02/10 | 0.9s
    epoch 008/100 | train_mse=0.01918493 | val_mse=0.01031235 | best_val_mse=0.01031235 | early_stop=00/10 | 0.9s
    epoch 009/100 | train_mse=0.01899293 | val_mse=0.01045267 | best_val_mse=0.01031235 | early_stop=01/10 | 1.0s
    epoch 010/100 | train_mse=0.01909546 | val_mse=0.01030504 | best_val_mse=0.01030504 | early_stop=00/10 | 1.0s
    epoch 011/100 | train_mse=0.01896402 | val_mse=0.01031340 | best_val_mse=0.01030504 | early_stop=01/10 | 1.0s
    epoch 012/100 | train_mse=0.01893653 | val_mse=0.01043383 | best_val_mse=0.01030504 | early_stop=02/10 | 0.9s
    epoch 013/100 | train_mse=0.01891286 | val_mse=0.01032823 | best_val_mse=0.01030504 | early_stop=03/10 | 0.8s
    epoch 014/100 | train_mse=0.01888412 | val_mse=0.01035857 | best_val_mse=0.01030504 | early_stop=04/10 | 0.8s
    epoch 015/100 | train_mse=0.01878952 | val_mse=0.01032240 | best_val_mse=0.01030504 | early_stop=05/10 | 0.9s
    epoch 016/100 | train_mse=0.01877438 | val_mse=0.01051664 | best_val_mse=0.01030504 | early_stop=06/10 | 0.9s
    epoch 017/100 | train_mse=0.01882934 | val_mse=0.01035459 | best_val_mse=0.01030504 | early_stop=07/10 | 0.9s
    epoch 018/100 | train_mse=0.01870620 | val_mse=0.01039584 | best_val_mse=0.01030504 | early_stop=08/10 | 0.9s
    epoch 019/100 | train_mse=0.01862972 | val_mse=0.01042467 | best_val_mse=0.01030504 | early_stop=09/10 | 0.9s
    epoch 020/100 | train_mse=0.01864337 | val_mse=0.01053952 | best_val_mse=0.01030504 | early_stop=10/10 | 0.8s
  refit 01/06 | test_year=2019 | status=saved | n_predictions=5,445
  refit 02/06 | test_year=2020 | status=training | train_n=86,776 | validation_n=21,758 | test_n=5,803
    epoch 001/100 | train_mse=0.01849219 | val_mse=0.01025710 | best_val_mse=0.01025710 | early_stop=00/10 | 0.8s
    epoch 002/100 | train_mse=0.01762678 | val_mse=0.01027641 | best_val_mse=0.01025710 | early_stop=01/10 | 0.9s
    epoch 003/100 | train_mse=0.01756944 | val_mse=0.01038218 | best_val_mse=0.01025710 | early_stop=02/10 | 0.8s
    epoch 004/100 | train_mse=0.01749415 | val_mse=0.01026015 | best_val_mse=0.01025710 | early_stop=03/10 | 0.8s
    epoch 005/100 | train_mse=0.01736336 | val_mse=0.01014701 | best_val_mse=0.01014701 | early_stop=00/10 | 0.9s
    epoch 006/100 | train_mse=0.01726812 | val_mse=0.01027785 | best_val_mse=0.01014701 | early_stop=01/10 | 0.9s
    epoch 007/100 | train_mse=0.01733226 | val_mse=0.01017055 | best_val_mse=0.01014701 | early_stop=02/10 | 0.8s
    epoch 008/100 | train_mse=0.01726866 | val_mse=0.01014711 | best_val_mse=0.01014701 | early_stop=03/10 | 0.8s
    epoch 009/100 | train_mse=0.01710971 | val_mse=0.01027171 | best_val_mse=0.01014701 | early_stop=04/10 | 0.9s
    epoch 010/100 | train_mse=0.01711652 | val_mse=0.01016671 | best_val_mse=0.01014701 | early_stop=05/10 | 0.8s
    epoch 011/100 | train_mse=0.01707977 | val_mse=0.01022165 | best_val_mse=0.01014701 | early_stop=06/10 | 0.9s
    epoch 012/100 | train_mse=0.01712598 | val_mse=0.01018691 | best_val_mse=0.01014701 | early_stop=07/10 | 0.8s
    epoch 013/100 | train_mse=0.01720894 | val_mse=0.01018667 | best_val_mse=0.01014701 | early_stop=08/10 | 0.8s
    epoch 014/100 | train_mse=0.01704744 | val_mse=0.01020666 | best_val_mse=0.01014701 | early_stop=09/10 | 0.9s
    epoch 015/100 | train_mse=0.01707303 | val_mse=0.01017291 | best_val_mse=0.01014701 | early_stop=10/10 | 0.9s
  refit 02/06 | test_year=2020 | status=saved | n_predictions=5,803
  refit 03/06 | test_year=2021 | status=training | train_n=84,361 | validation_n=22,015 | test_n=4,701
    epoch 001/100 | train_mse=0.01690158 | val_mse=0.01630519 | best_val_mse=0.01630519 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.01614358 | val_mse=0.01671750 | best_val_mse=0.01630519 | early_stop=01/10 | 0.8s
    epoch 003/100 | train_mse=0.01616245 | val_mse=0.01627868 | best_val_mse=0.01627868 | early_stop=00/10 | 0.9s
    epoch 004/100 | train_mse=0.01592315 | val_mse=0.01621491 | best_val_mse=0.01621491 | early_stop=00/10 | 0.9s
    epoch 005/100 | train_mse=0.01587242 | val_mse=0.01620294 | best_val_mse=0.01620294 | early_stop=00/10 | 0.8s
    epoch 006/100 | train_mse=0.01579989 | val_mse=0.01620263 | best_val_mse=0.01620263 | early_stop=00/10 | 0.8s
    epoch 007/100 | train_mse=0.01576087 | val_mse=0.01619845 | best_val_mse=0.01619845 | early_stop=00/10 | 0.8s
    epoch 008/100 | train_mse=0.01577910 | val_mse=0.01621264 | best_val_mse=0.01619845 | early_stop=01/10 | 0.8s
    epoch 009/100 | train_mse=0.01571859 | val_mse=0.01619411 | best_val_mse=0.01619411 | early_stop=00/10 | 0.9s
    epoch 010/100 | train_mse=0.01569227 | val_mse=0.01619504 | best_val_mse=0.01619411 | early_stop=01/10 | 0.8s
    epoch 011/100 | train_mse=0.01560919 | val_mse=0.01621649 | best_val_mse=0.01619411 | early_stop=02/10 | 0.8s
    epoch 012/100 | train_mse=0.01567115 | val_mse=0.01620025 | best_val_mse=0.01619411 | early_stop=03/10 | 0.8s
    epoch 013/100 | train_mse=0.01565642 | val_mse=0.01640714 | best_val_mse=0.01619411 | early_stop=04/10 | 0.8s
    epoch 014/100 | train_mse=0.01557762 | val_mse=0.01622925 | best_val_mse=0.01619411 | early_stop=05/10 | 0.9s
    epoch 015/100 | train_mse=0.01565773 | val_mse=0.01634392 | best_val_mse=0.01619411 | early_stop=06/10 | 0.8s
    epoch 016/100 | train_mse=0.01550379 | val_mse=0.01624280 | best_val_mse=0.01619411 | early_stop=07/10 | 0.9s
    epoch 017/100 | train_mse=0.01544722 | val_mse=0.01638734 | best_val_mse=0.01619411 | early_stop=08/10 | 0.8s
    epoch 018/100 | train_mse=0.01557738 | val_mse=0.01633858 | best_val_mse=0.01619411 | early_stop=09/10 | 0.9s
    epoch 019/100 | train_mse=0.01539162 | val_mse=0.01626684 | best_val_mse=0.01619411 | early_stop=10/10 | 0.8s
  refit 03/06 | test_year=2021 | status=saved | n_predictions=4,701
  refit 04/06 | test_year=2022 | status=training | train_n=83,544 | validation_n=21,180 | test_n=4,916
    epoch 001/100 | train_mse=0.01507748 | val_mse=0.01685460 | best_val_mse=0.01685460 | early_stop=00/10 | 0.8s
    epoch 002/100 | train_mse=0.01454275 | val_mse=0.01717301 | best_val_mse=0.01685460 | early_stop=01/10 | 0.8s
    epoch 003/100 | train_mse=0.01445306 | val_mse=0.01744590 | best_val_mse=0.01685460 | early_stop=02/10 | 0.8s
    epoch 004/100 | train_mse=0.01458691 | val_mse=0.01726363 | best_val_mse=0.01685460 | early_stop=03/10 | 0.8s
    epoch 005/100 | train_mse=0.01432118 | val_mse=0.01679045 | best_val_mse=0.01679045 | early_stop=00/10 | 0.8s
    epoch 006/100 | train_mse=0.01423647 | val_mse=0.01693317 | best_val_mse=0.01679045 | early_stop=01/10 | 0.8s
    epoch 007/100 | train_mse=0.01416153 | val_mse=0.01687293 | best_val_mse=0.01679045 | early_stop=02/10 | 0.8s
    epoch 008/100 | train_mse=0.01418248 | val_mse=0.01678685 | best_val_mse=0.01678685 | early_stop=00/10 | 0.8s
    epoch 009/100 | train_mse=0.01412479 | val_mse=0.01690011 | best_val_mse=0.01678685 | early_stop=01/10 | 0.8s
    epoch 010/100 | train_mse=0.01406337 | val_mse=0.01688162 | best_val_mse=0.01678685 | early_stop=02/10 | 0.9s
    epoch 011/100 | train_mse=0.01409180 | val_mse=0.01685991 | best_val_mse=0.01678685 | early_stop=03/10 | 0.9s
    epoch 012/100 | train_mse=0.01404251 | val_mse=0.01691252 | best_val_mse=0.01678685 | early_stop=04/10 | 0.8s
    epoch 013/100 | train_mse=0.01399804 | val_mse=0.01697426 | best_val_mse=0.01678685 | early_stop=05/10 | 0.8s
    epoch 014/100 | train_mse=0.01399975 | val_mse=0.01687184 | best_val_mse=0.01678685 | early_stop=06/10 | 0.8s
    epoch 015/100 | train_mse=0.01401213 | val_mse=0.01684506 | best_val_mse=0.01678685 | early_stop=07/10 | 0.8s
    epoch 016/100 | train_mse=0.01398686 | val_mse=0.01695827 | best_val_mse=0.01678685 | early_stop=08/10 | 0.8s
    epoch 017/100 | train_mse=0.01393042 | val_mse=0.01710793 | best_val_mse=0.01678685 | early_stop=09/10 | 0.9s
    epoch 018/100 | train_mse=0.01395082 | val_mse=0.01708502 | best_val_mse=0.01678685 | early_stop=10/10 | 0.8s
  refit 04/06 | test_year=2022 | status=saved | n_predictions=4,916
  refit 05/06 | test_year=2023 | status=training | train_n=83,543 | validation_n=20,648 | test_n=5,506
    epoch 001/100 | train_mse=0.01473511 | val_mse=0.01836834 | best_val_mse=0.01836834 | early_stop=00/10 | 0.8s
    epoch 002/100 | train_mse=0.01402714 | val_mse=0.01830276 | best_val_mse=0.01830276 | early_stop=00/10 | 0.8s
    epoch 003/100 | train_mse=0.01393030 | val_mse=0.01827821 | best_val_mse=0.01827821 | early_stop=00/10 | 0.9s
    epoch 004/100 | train_mse=0.01412439 | val_mse=0.01826371 | best_val_mse=0.01826371 | early_stop=00/10 | 0.9s
    epoch 005/100 | train_mse=0.01390303 | val_mse=0.01821336 | best_val_mse=0.01821336 | early_stop=00/10 | 0.9s
    epoch 006/100 | train_mse=0.01385729 | val_mse=0.01830320 | best_val_mse=0.01821336 | early_stop=01/10 | 0.8s
    epoch 007/100 | train_mse=0.01382766 | val_mse=0.01833689 | best_val_mse=0.01821336 | early_stop=02/10 | 0.9s
    epoch 008/100 | train_mse=0.01376672 | val_mse=0.01822833 | best_val_mse=0.01821336 | early_stop=03/10 | 0.8s
    epoch 009/100 | train_mse=0.01369126 | val_mse=0.01821300 | best_val_mse=0.01821300 | early_stop=00/10 | 0.9s
    epoch 010/100 | train_mse=0.01370722 | val_mse=0.01831905 | best_val_mse=0.01821300 | early_stop=01/10 | 0.8s
    epoch 011/100 | train_mse=0.01368509 | val_mse=0.01825466 | best_val_mse=0.01821300 | early_stop=02/10 | 0.8s
    epoch 012/100 | train_mse=0.01367942 | val_mse=0.01822087 | best_val_mse=0.01821300 | early_stop=03/10 | 0.9s
    epoch 013/100 | train_mse=0.01363205 | val_mse=0.01825854 | best_val_mse=0.01821300 | early_stop=04/10 | 0.9s
    epoch 014/100 | train_mse=0.01361194 | val_mse=0.01844780 | best_val_mse=0.01821300 | early_stop=05/10 | 0.9s
    epoch 015/100 | train_mse=0.01368845 | val_mse=0.01823869 | best_val_mse=0.01821300 | early_stop=06/10 | 0.8s
    epoch 016/100 | train_mse=0.01362987 | val_mse=0.01822640 | best_val_mse=0.01821300 | early_stop=07/10 | 0.8s
    epoch 017/100 | train_mse=0.01356215 | val_mse=0.01827258 | best_val_mse=0.01821300 | early_stop=08/10 | 0.9s
    epoch 018/100 | train_mse=0.01356299 | val_mse=0.01829524 | best_val_mse=0.01821300 | early_stop=09/10 | 0.9s
    epoch 019/100 | train_mse=0.01355802 | val_mse=0.01824635 | best_val_mse=0.01821300 | early_stop=10/10 | 0.9s
  refit 05/06 | test_year=2023 | status=saved | n_predictions=5,506
  refit 06/06 | test_year=2024 | status=training | train_n=84,114 | validation_n=20,734 | test_n=5,220
    epoch 001/100 | train_mse=0.01446192 | val_mse=0.02089382 | best_val_mse=0.02089382 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.01424978 | val_mse=0.02014833 | best_val_mse=0.02014833 | early_stop=00/10 | 0.9s
    epoch 003/100 | train_mse=0.01408155 | val_mse=0.02022556 | best_val_mse=0.02014833 | early_stop=01/10 | 0.9s
    epoch 004/100 | train_mse=0.01396426 | val_mse=0.02010290 | best_val_mse=0.02010290 | early_stop=00/10 | 0.9s
    epoch 005/100 | train_mse=0.01397096 | val_mse=0.02013464 | best_val_mse=0.02010290 | early_stop=01/10 | 0.8s
    epoch 006/100 | train_mse=0.01384301 | val_mse=0.02011802 | best_val_mse=0.02010290 | early_stop=02/10 | 0.9s
    epoch 007/100 | train_mse=0.01382800 | val_mse=0.02011689 | best_val_mse=0.02010290 | early_stop=03/10 | 0.8s
    epoch 008/100 | train_mse=0.01388643 | val_mse=0.02035155 | best_val_mse=0.02010290 | early_stop=04/10 | 0.9s
    epoch 009/100 | train_mse=0.01387519 | val_mse=0.02013486 | best_val_mse=0.02010290 | early_stop=05/10 | 0.8s
    epoch 010/100 | train_mse=0.01378637 | val_mse=0.02012776 | best_val_mse=0.02010290 | early_stop=06/10 | 0.8s
    epoch 011/100 | train_mse=0.01376942 | val_mse=0.02025066 | best_val_mse=0.02010290 | early_stop=07/10 | 0.8s
    epoch 012/100 | train_mse=0.01378983 | val_mse=0.02012190 | best_val_mse=0.02010290 | early_stop=08/10 | 0.8s
    epoch 013/100 | train_mse=0.01368787 | val_mse=0.02014328 | best_val_mse=0.02010290 | early_stop=09/10 | 0.8s
    epoch 014/100 | train_mse=0.01363420 | val_mse=0.02024885 | best_val_mse=0.02010290 | early_stop=10/10 | 0.9s
  refit 06/06 | test_year=2024 | status=saved | n_predictions=5,220

=== FRA | HYBRID_LGBM40_DEEPSET40_DYNAMIC ===
Device: cuda

HYBRID_LGBM40_DEEPSET40_DYNAMIC [8977af5939095c8a]
  refit 01/06 | test_year=2019 | status=training | train_n=88,438 | validation_n=21,822 | test_n=5,445

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02011548 | val_mse=0.01045875 | best_val_mse=0.01045875 | early_stop=00/10 | 0.8s
    epoch 002/100 | train_mse=0.01956056 | val_mse=0.01034738 | best_val_mse=0.01034738 | early_stop=00/10 | 0.8s
    epoch 003/100 | train_mse=0.01940035 | val_mse=0.01027417 | best_val_mse=0.01027417 | early_stop=00/10 | 0.9s
    epoch 004/100 | train_mse=0.01933076 | val_mse=0.01044859 | best_val_mse=0.01027417 | early_stop=01/10 | 0.9s
    epoch 005/100 | train_mse=0.01920781 | val_mse=0.01031141 | best_val_mse=0.01027417 | early_stop=02/10 | 0.9s
    epoch 006/100 | train_mse=0.01913498 | val_mse=0.01031868 | best_val_mse=0.01027417 | early_stop=03/10 | 0.9s
    epoch 007/100 | train_mse=0.01915424 | val_mse=0.01046054 | best_val_mse=0.01027417 | early_stop=04/10 | 0.9s
    epoch 008/100 | train_mse=0.01918493 | val_mse=0.01027721 | best_val_mse=0.01027417 | early_stop=05/10 | 0.8s
    epoch 009/100 | train_mse=0.01899293 | val_mse=0.01063839 | best_val_mse=0.01027417 | early_stop=06/10 | 0.8s
    epoch 010/100 | train_mse=0.01909546 | val_mse=0.01031547 | best_val_mse=0.01027417 | early_stop=07/10 | 0.8s
    epoch 011/100 | train_mse=0.01896402 | val_mse=0.01024757 | best_val_mse=0.01024757 | early_stop=00/10 | 0.8s
    epoch 012/100 | train_mse=0.01893653 | val_mse=0.01025506 | best_val_mse=0.01024757 | early_stop=01/10 | 0.8s
    epoch 013/100 | train_mse=0.01891286 | val_mse=0.01019847 | best_val_mse=0.01019847 | early_stop=00/10 | 0.8s
    epoch 014/100 | train_mse=0.01888412 | val_mse=0.01046769 | best_val_mse=0.01019847 | early_stop=01/10 | 0.8s
    epoch 015/100 | train_mse=0.01878952 | val_mse=0.01022508 | best_val_mse=0.01019847 | early_stop=02/10 | 0.8s
    epoch 016/100 | train_mse=0.01877438 | val_mse=0.01065434 | best_val_mse=0.01019847 | early_stop=03/10 | 0.8s
    epoch 017/100 | train_mse=0.01882934 | val_mse=0.01043181 | best_val_mse=0.01019847 | early_stop=04/10 | 0.8s
    epoch 018/100 | train_mse=0.01870620 | val_mse=0.01027087 | best_val_mse=0.01019847 | early_stop=05/10 | 0.8s
    epoch 019/100 | train_mse=0.01862972 | val_mse=0.01032776 | best_val_mse=0.01019847 | early_stop=06/10 | 0.9s
    epoch 020/100 | train_mse=0.01864337 | val_mse=0.01034861 | best_val_mse=0.01019847 | early_stop=07/10 | 0.9s
    epoch 021/100 | train_mse=0.01852052 | val_mse=0.01049911 | best_val_mse=0.01019847 | early_stop=08/10 | 0.9s
    epoch 022/100 | train_mse=0.01839815 | val_mse=0.01047255 | best_val_mse=0.01019847 | early_stop=09/10 | 0.8s
    epoch 023/100 | train_mse=0.01847651 | val_mse=0.01038298 | best_val_mse=0.01019847 | early_stop=10/10 | 0.8s
  refit 01/06 | test_year=2019 | status=saved | n_predictions=5,445
  refit 02/06 | test_year=2020 | status=training | train_n=86,776 | validation_n=21,758 | test_n=5,803

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.01849219 | val_mse=0.01017377 | best_val_mse=0.01017377 | early_stop=00/10 | 0.8s
    epoch 002/100 | train_mse=0.01762678 | val_mse=0.01020734 | best_val_mse=0.01017377 | early_stop=01/10 | 0.8s
    epoch 003/100 | train_mse=0.01756944 | val_mse=0.01032940 | best_val_mse=0.01017377 | early_stop=02/10 | 0.9s
    epoch 004/100 | train_mse=0.01749415 | val_mse=0.01018355 | best_val_mse=0.01017377 | early_stop=03/10 | 0.8s
    epoch 005/100 | train_mse=0.01736336 | val_mse=0.01004642 | best_val_mse=0.01004642 | early_stop=00/10 | 0.8s
    epoch 006/100 | train_mse=0.01726812 | val_mse=0.01014827 | best_val_mse=0.01004642 | early_stop=01/10 | 0.8s
    epoch 007/100 | train_mse=0.01733226 | val_mse=0.01005677 | best_val_mse=0.01004642 | early_stop=02/10 | 0.8s
    epoch 008/100 | train_mse=0.01726866 | val_mse=0.01004085 | best_val_mse=0.01004085 | early_stop=00/10 | 0.8s
    epoch 009/100 | train_mse=0.01710971 | val_mse=0.01020696 | best_val_mse=0.01004085 | early_stop=01/10 | 0.8s
    epoch 010/100 | train_mse=0.01711652 | val_mse=0.01005560 | best_val_mse=0.01004085 | early_stop=02/10 | 0.8s
    epoch 011/100 | train_mse=0.01707977 | val_mse=0.01014674 | best_val_mse=0.01004085 | early_stop=03/10 | 0.8s
    epoch 012/100 | train_mse=0.01712598 | val_mse=0.01009596 | best_val_mse=0.01004085 | early_stop=04/10 | 0.8s
    epoch 013/100 | train_mse=0.01720894 | val_mse=0.01010972 | best_val_mse=0.01004085 | early_stop=05/10 | 0.8s
    epoch 014/100 | train_mse=0.01704744 | val_mse=0.01008801 | best_val_mse=0.01004085 | early_stop=06/10 | 0.8s
    epoch 015/100 | train_mse=0.01707303 | val_mse=0.01006125 | best_val_mse=0.01004085 | early_stop=07/10 | 0.8s
    epoch 016/100 | train_mse=0.01696952 | val_mse=0.01013961 | best_val_mse=0.01004085 | early_stop=08/10 | 0.8s
    epoch 017/100 | train_mse=0.01690619 | val_mse=0.01009412 | best_val_mse=0.01004085 | early_stop=09/10 | 0.8s
    epoch 018/100 | train_mse=0.01686801 | val_mse=0.01007166 | best_val_mse=0.01004085 | early_stop=10/10 | 0.8s
  refit 02/06 | test_year=2020 | status=saved | n_predictions=5,803
  refit 03/06 | test_year=2021 | status=training | train_n=84,361 | validation_n=22,015 | test_n=4,701

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.01690158 | val_mse=0.01060928 | best_val_mse=0.01060928 | early_stop=00/10 | 0.8s
    epoch 002/100 | train_mse=0.01614358 | val_mse=0.01112835 | best_val_mse=0.01060928 | early_stop=01/10 | 0.8s
    epoch 003/100 | train_mse=0.01616245 | val_mse=0.01054558 | best_val_mse=0.01054558 | early_stop=00/10 | 0.8s
    epoch 004/100 | train_mse=0.01592315 | val_mse=0.01041415 | best_val_mse=0.01041415 | early_stop=00/10 | 0.9s
    epoch 005/100 | train_mse=0.01587242 | val_mse=0.01038950 | best_val_mse=0.01038950 | early_stop=00/10 | 1.0s
    epoch 006/100 | train_mse=0.01579989 | val_mse=0.01045408 | best_val_mse=0.01038950 | early_stop=01/10 | 0.9s
    epoch 007/100 | train_mse=0.01576087 | val_mse=0.01042278 | best_val_mse=0.01038950 | early_stop=02/10 | 0.8s
    epoch 008/100 | train_mse=0.01577910 | val_mse=0.01048989 | best_val_mse=0.01038950 | early_stop=03/10 | 0.8s
    epoch 009/100 | train_mse=0.01571859 | val_mse=0.01039425 | best_val_mse=0.01038950 | early_stop=04/10 | 0.8s
    epoch 010/100 | train_mse=0.01569227 | val_mse=0.01039747 | best_val_mse=0.01038950 | early_stop=05/10 | 0.8s
    epoch 011/100 | train_mse=0.01560919 | val_mse=0.01042820 | best_val_mse=0.01038950 | early_stop=06/10 | 0.8s
    epoch 012/100 | train_mse=0.01567115 | val_mse=0.01043283 | best_val_mse=0.01038950 | early_stop=07/10 | 0.8s
    epoch 013/100 | train_mse=0.01565642 | val_mse=0.01079217 | best_val_mse=0.01038950 | early_stop=08/10 | 0.8s
    epoch 014/100 | train_mse=0.01557762 | val_mse=0.01042666 | best_val_mse=0.01038950 | early_stop=09/10 | 0.8s
    epoch 015/100 | train_mse=0.01565773 | val_mse=0.01070460 | best_val_mse=0.01038950 | early_stop=10/10 | 0.8s
  refit 03/06 | test_year=2021 | status=saved | n_predictions=4,701
  refit 04/06 | test_year=2022 | status=training | train_n=83,544 | validation_n=21,180 | test_n=4,916

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.01507748 | val_mse=0.01820459 | best_val_mse=0.01820459 | early_stop=00/10 | 0.8s
    epoch 002/100 | train_mse=0.01454275 | val_mse=0.01855971 | best_val_mse=0.01820459 | early_stop=01/10 | 0.8s
    epoch 003/100 | train_mse=0.01445306 | val_mse=0.01884587 | best_val_mse=0.01820459 | early_stop=02/10 | 0.8s
    epoch 004/100 | train_mse=0.01458691 | val_mse=0.01865813 | best_val_mse=0.01820459 | early_stop=03/10 | 0.8s
    epoch 005/100 | train_mse=0.01432118 | val_mse=0.01814013 | best_val_mse=0.01814013 | early_stop=00/10 | 0.8s
    epoch 006/100 | train_mse=0.01423647 | val_mse=0.01829912 | best_val_mse=0.01814013 | early_stop=01/10 | 0.8s
    epoch 007/100 | train_mse=0.01416153 | val_mse=0.01822958 | best_val_mse=0.01814013 | early_stop=02/10 | 0.8s
    epoch 008/100 | train_mse=0.01418248 | val_mse=0.01813042 | best_val_mse=0.01813042 | early_stop=00/10 | 0.8s
    epoch 009/100 | train_mse=0.01412479 | val_mse=0.01824658 | best_val_mse=0.01813042 | early_stop=01/10 | 0.8s
    epoch 010/100 | train_mse=0.01406337 | val_mse=0.01822883 | best_val_mse=0.01813042 | early_stop=02/10 | 0.8s
    epoch 011/100 | train_mse=0.01409180 | val_mse=0.01820848 | best_val_mse=0.01813042 | early_stop=03/10 | 0.8s
    epoch 012/100 | train_mse=0.01404251 | val_mse=0.01827038 | best_val_mse=0.01813042 | early_stop=04/10 | 0.8s
    epoch 013/100 | train_mse=0.01399804 | val_mse=0.01832693 | best_val_mse=0.01813042 | early_stop=05/10 | 0.8s
    epoch 014/100 | train_mse=0.01399975 | val_mse=0.01822348 | best_val_mse=0.01813042 | early_stop=06/10 | 0.8s
    epoch 015/100 | train_mse=0.01401213 | val_mse=0.01818764 | best_val_mse=0.01813042 | early_stop=07/10 | 0.8s
    epoch 016/100 | train_mse=0.01398686 | val_mse=0.01832416 | best_val_mse=0.01813042 | early_stop=08/10 | 0.8s
    epoch 017/100 | train_mse=0.01393042 | val_mse=0.01846879 | best_val_mse=0.01813042 | early_stop=09/10 | 0.8s
    epoch 018/100 | train_mse=0.01395082 | val_mse=0.01845543 | best_val_mse=0.01813042 | early_stop=10/10 | 0.8s
  refit 04/06 | test_year=2022 | status=saved | n_predictions=4,916
  refit 05/06 | test_year=2023 | status=training | train_n=83,543 | validation_n=20,648 | test_n=5,506

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.01473511 | val_mse=0.01906724 | best_val_mse=0.01906724 | early_stop=00/10 | 0.8s
    epoch 002/100 | train_mse=0.01402714 | val_mse=0.01909678 | best_val_mse=0.01906724 | early_stop=01/10 | 0.8s
    epoch 003/100 | train_mse=0.01393030 | val_mse=0.01896582 | best_val_mse=0.01896582 | early_stop=00/10 | 0.8s
    epoch 004/100 | train_mse=0.01412439 | val_mse=0.01905391 | best_val_mse=0.01896582 | early_stop=01/10 | 0.8s
    epoch 005/100 | train_mse=0.01390303 | val_mse=0.01895643 | best_val_mse=0.01895643 | early_stop=00/10 | 0.8s
    epoch 006/100 | train_mse=0.01385729 | val_mse=0.01911368 | best_val_mse=0.01895643 | early_stop=01/10 | 0.8s
    epoch 007/100 | train_mse=0.01382766 | val_mse=0.01898050 | best_val_mse=0.01895643 | early_stop=02/10 | 0.8s
    epoch 008/100 | train_mse=0.01376672 | val_mse=0.01898555 | best_val_mse=0.01895643 | early_stop=03/10 | 0.8s
    epoch 009/100 | train_mse=0.01369126 | val_mse=0.01895632 | best_val_mse=0.01895632 | early_stop=00/10 | 0.8s
    epoch 010/100 | train_mse=0.01370722 | val_mse=0.01912606 | best_val_mse=0.01895632 | early_stop=01/10 | 0.8s
    epoch 011/100 | train_mse=0.01368509 | val_mse=0.01903938 | best_val_mse=0.01895632 | early_stop=02/10 | 0.8s
    epoch 012/100 | train_mse=0.01367942 | val_mse=0.01896631 | best_val_mse=0.01895632 | early_stop=03/10 | 0.8s
    epoch 013/100 | train_mse=0.01363205 | val_mse=0.01902761 | best_val_mse=0.01895632 | early_stop=04/10 | 0.8s
    epoch 014/100 | train_mse=0.01361194 | val_mse=0.01929279 | best_val_mse=0.01895632 | early_stop=05/10 | 0.8s
    epoch 015/100 | train_mse=0.01368845 | val_mse=0.01900245 | best_val_mse=0.01895632 | early_stop=06/10 | 0.8s
    epoch 016/100 | train_mse=0.01362987 | val_mse=0.01895962 | best_val_mse=0.01895632 | early_stop=07/10 | 0.8s
    epoch 017/100 | train_mse=0.01356215 | val_mse=0.01896603 | best_val_mse=0.01895632 | early_stop=08/10 | 0.8s
    epoch 018/100 | train_mse=0.01356299 | val_mse=0.01899586 | best_val_mse=0.01895632 | early_stop=09/10 | 0.8s
    epoch 019/100 | train_mse=0.01355802 | val_mse=0.01899180 | best_val_mse=0.01895632 | early_stop=10/10 | 0.8s
  refit 05/06 | test_year=2023 | status=saved | n_predictions=5,506
  refit 06/06 | test_year=2024 | status=training | train_n=84,114 | validation_n=20,734 | test_n=5,220

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.01446192 | val_mse=0.02203080 | best_val_mse=0.02203080 | early_stop=00/10 | 0.9s
    epoch 002/100 | train_mse=0.01424978 | val_mse=0.02103599 | best_val_mse=0.02103599 | early_stop=00/10 | 0.9s
    epoch 003/100 | train_mse=0.01408155 | val_mse=0.02103328 | best_val_mse=0.02103328 | early_stop=00/10 | 1.0s
    epoch 004/100 | train_mse=0.01396426 | val_mse=0.02099886 | best_val_mse=0.02099886 | early_stop=00/10 | 1.0s
    epoch 005/100 | train_mse=0.01397096 | val_mse=0.02100580 | best_val_mse=0.02099886 | early_stop=01/10 | 0.8s
    epoch 006/100 | train_mse=0.01384301 | val_mse=0.02100884 | best_val_mse=0.02099886 | early_stop=02/10 | 0.8s
    epoch 007/100 | train_mse=0.01382800 | val_mse=0.02103978 | best_val_mse=0.02099886 | early_stop=03/10 | 0.8s
    epoch 008/100 | train_mse=0.01388643 | val_mse=0.02111095 | best_val_mse=0.02099886 | early_stop=04/10 | 0.8s
    epoch 009/100 | train_mse=0.01387519 | val_mse=0.02099957 | best_val_mse=0.02099886 | early_stop=05/10 | 0.8s
    epoch 010/100 | train_mse=0.01378637 | val_mse=0.02107685 | best_val_mse=0.02099886 | early_stop=06/10 | 0.8s
    epoch 011/100 | train_mse=0.01376942 | val_mse=0.02127325 | best_val_mse=0.02099886 | early_stop=07/10 | 0.9s
    epoch 012/100 | train_mse=0.01378983 | val_mse=0.02103700 | best_val_mse=0.02099886 | early_stop=08/10 | 0.8s
    epoch 013/100 | train_mse=0.01368787 | val_mse=0.02108012 | best_val_mse=0.02099886 | early_stop=09/10 | 0.8s
    epoch 014/100 | train_mse=0.01363420 | val_mse=0.02107897 | best_val_mse=0.02099886 | early_stop=10/10 | 0.8s
  refit 06/06 | test_year=2024 | status=saved | n_predictions=5,220

## 5. Chosen 50/50 model and country tables

The chosen model is constructed from aligned OOS component predictions using the fixed rule $0.5\widehat{r}^{\mathrm{LGBM}}_{i,t+1}+0.5\widehat{r}^{\mathrm{DeepSet}}_{i,t+1}$. The table reports it first, followed by the component benchmarks and the validation-weighted robustness comparator.

In [5]:
from IPython.display import display
from src.developed_markets import country_comparison

country_tables = {}
for country, config in CONFIGS.items():
    table = country_comparison(config)
    country_tables[country] = table
    print(f'\n{COUNTRY_NAMES[country]}')
    display(table)

United Kingdom

,country,country_name,model_id,model_role,pooled_oos_r2,robust_oos_r2,mean_monthly_rank_ic,rank_ic_newey_west_t_stat,annualized_return,annualized_volatility,sharpe,newey_west_t_stat,max_drawdown,hit_rate,n_months
0,GBR,United Kingdom,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,chosen_model,0.000927,0.001469,0.088204,10.061946,0.327338,0.140001,2.338105,4.057702,-0.275165,0.777778,72
1,GBR,United Kingdom,LGBM_40,component_benchmark,0.001189,0.001634,0.075961,9.389031,0.307052,0.128454,2.390353,4.226540,-0.244730,0.805556,72
2,GBR,United Kingdom,DEEPSET_40_DYNAMIC,component_benchmark,-0.003436,-0.003354,0.081027,9.947264,0.306980,0.122102,2.514128,4.931987,-0.193222,0.805556,72
3,GBR,United Kingdom,HYBRID_LGBM40_DEEPSET40_DYNAMIC,robustness_comparator,-0.001394,-0.001281,0.080525,10.424331,0.309142,0.134043,2.306285,4.228197,-0.228245,0.777778,72

Australia

,country,country_name,model_id,model_role,pooled_oos_r2,robust_oos_r2,mean_monthly_rank_ic,rank_ic_newey_west_t_stat,annualized_return,annualized_volatility,sharpe,newey_west_t_stat,max_drawdown,hit_rate,n_months
0,AUS,Australia,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,chosen_model,0.004742,0.005056,0.101720,8.433739,0.481833,0.186741,2.580219,5.926192,-0.202881,0.847222,72
1,AUS,Australia,LGBM_40,component_benchmark,0.005131,0.005777,0.096857,9.417564,0.468209,0.160294,2.920933,8.458087,-0.136183,0.847222,72
2,AUS,Australia,DEEPSET_40_DYNAMIC,component_benchmark,0.001499,0.001000,0.091752,7.620722,0.410833,0.157076,2.615512,6.437820,-0.148201,0.847222,72
3,AUS,Australia,HYBRID_LGBM40_DEEPSET40_DYNAMIC,robustness_comparator,0.004694,0.005394,0.093719,8.844524,0.411207,0.181382,2.267083,5.519029,-0.210532,0.791667,72

Germany

,country,country_name,model_id,model_role,pooled_oos_r2,robust_oos_r2,mean_monthly_rank_ic,rank_ic_newey_west_t_stat,annualized_return,annualized_volatility,sharpe,newey_west_t_stat,max_drawdown,hit_rate,n_months
0,DEU,Germany,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,chosen_model,0.002679,0.003197,0.083174,10.942711,0.353132,0.139654,2.528619,6.134483,-0.108061,0.819444,72
1,DEU,Germany,LGBM_40,component_benchmark,-0.001261,-0.002089,0.076864,10.412527,0.335310,0.133335,2.514788,6.324801,-0.092525,0.875000,72
2,DEU,Germany,DEEPSET_40_DYNAMIC,component_benchmark,0.001363,0.001739,0.075573,9.487785,0.270320,0.114515,2.360560,5.585071,-0.116724,0.805556,72
3,DEU,Germany,HYBRID_LGBM40_DEEPSET40_DYNAMIC,robustness_comparator,-0.001784,-0.002861,0.075932,9.344044,0.339745,0.131679,2.580110,6.942859,-0.078811,0.791667,72

France

,country,country_name,model_id,model_role,pooled_oos_r2,robust_oos_r2,mean_monthly_rank_ic,rank_ic_newey_west_t_stat,annualized_return,annualized_volatility,sharpe,newey_west_t_stat,max_drawdown,hit_rate,n_months
0,FRA,France,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,chosen_model,0.000024,0.001729,0.095568,8.424457,0.381900,0.142266,2.684409,5.867847,-0.142920,0.819444,72
1,FRA,France,LGBM_40,component_benchmark,-0.000021,-0.000287,0.081710,7.701541,-0.366395,1.696447,-0.215978,-0.551040,-4.512655,0.763889,72
2,FRA,France,DEEPSET_40_DYNAMIC,component_benchmark,-0.000021,-0.001645,0.084743,8.344216,0.324078,0.128606,2.519927,4.638597,-0.149724,0.777778,72
3,FRA,France,HYBRID_LGBM40_DEEPSET40_DYNAMIC,robustness_comparator,0.000014,0.001859,0.087774,7.950985,0.349578,0.149628,2.336316,5.249711,-0.185206,0.833333,72

## 6. Portfolio implementability robustness

For every country, implementability tests are applied to the chosen 50/50 model and its two component benchmarks. The 10% tail portfolio is evaluated under full and ex-microcap universes, equal and value weighting, proportional transaction costs, missing-return stress, and observed-return outlier scenarios.

In [6]:
import pandas as pd
from src.portfolio_robustness import run_portfolio_robustness

robustness_tables = []
for country, config in CONFIGS.items():
    table = run_portfolio_robustness(
        config.run_dir, model_ids=(CHOSEN_MODEL_ID, *COMPONENT_BENCHMARK_IDS)
    )
    table.insert(0, 'country_name', COUNTRY_NAMES[country])
    table.insert(0, 'country', country)
    robustness_tables.append(table)
external_robustness = pd.concat(robustness_tables, ignore_index=True)
SUMMARY_DIR.mkdir(parents=True, exist_ok=True)
external_robustness.to_csv(
    SUMMARY_DIR / 'developed_markets_portfolio_robustness.csv', index=False
)
display(external_robustness)

HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50: saved portfolio robustness
LGBM_40: saved portfolio robustness
DEEPSET_40_DYNAMIC: saved portfolio robustness
HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50: saved portfolio robustness
LGBM_40: saved portfolio robustness
DEEPSET_40_DYNAMIC: saved portfolio robustness
HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50: saved portfolio robustness
LGBM_40: saved portfolio robustness
DEEPSET_40_DYNAMIC: saved portfolio robustness
HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50: saved portfolio robustness
LGBM_40: saved portfolio robustness
DEEPSET_40_DYNAMIC: saved portfolio robustness

,country,country_name,universe,weighting,mean_monthly_turnover,annualized_turnover,mean_n_eligible,mean_long_coverage,mean_short_coverage,gross_mean_monthly_return,...,outlier_exclude_abs_gt_10_sharpe,outlier_exclude_abs_gt_10_t_stat,outlier_exclude_abs_gt_10_newey_west_t_stat,outlier_exclude_abs_gt_10_max_drawdown,outlier_exclude_abs_gt_10_hit_rate,outlier_exclude_abs_gt_10_n_months,n_market_abs_gt_10,n_selected_abs_gt_10,model_id,model_signature
0,GBR,United Kingdom,EX_MICRO,EQUAL,1.245499,14.945993,382.347222,0.995576,0.992394,0.009736,...,0.723174,1.771408,1.779641,-0.302879,0.625000,72,0,0,DEEPSET_40_DYNAMIC,11e1aa6b2db4e879
1,GBR,United Kingdom,EX_MICRO,VALUE,1.386975,16.643703,382.347222,0.995576,0.992394,-0.002722,...,-0.166685,-0.408293,-0.369453,-0.456476,0.486111,72,0,0,DEEPSET_40_DYNAMIC,11e1aa6b2db4e879
2,GBR,United Kingdom,FULL,EQUAL,1.165521,13.986246,877.458333,0.993817,0.995377,0.025522,...,2.486943,6.091741,4.867910,-0.197361,0.805556,72,0,0,DEEPSET_40_DYNAMIC,11e1aa6b2db4e879
3,GBR,United Kingdom,FULL,VALUE,1.368770,16.425242,877.458333,0.993817,0.995377,-0.001570,...,-0.081725,-0.200184,-0.154929,-0.634052,0.527778,72,0,0,DEEPSET_40_DYNAMIC,11e1aa6b2db4e879
4,GBR,United Kingdom,EX_MICRO,EQUAL,1.140799,13.689590,382.347222,0.996604,0.993903,0.011987,...,0.841015,2.060058,1.949386,-0.303623,0.625000,72,0,0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,7547db4f6762a503
5,GBR,United Kingdom,EX_MICRO,VALUE,1.273142,15.277705,382.347222,0.996604,0.993903,-0.002093,...,-0.118264,-0.289686,-0.268206,-0.530959,0.486111,72,0,0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,7547db4f6762a503
6,GBR,United Kingdom,FULL,EQUAL,1.026793,12.321510,877.458333,0.993228,0.995270,0.027278,...,2.338105,5.727164,4.057702,-0.275165,0.777778,72,0,0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,7547db4f6762a503
7,GBR,United Kingdom,FULL,VALUE,1.224053,14.688639,877.458333,0.993228,0.995270,0.005420,...,0.223523,0.547517,0.454586,-0.665167,0.583333,72,0,0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,7547db4f6762a503
8,GBR,United Kingdom,EX_MICRO,EQUAL,0.906845,10.882144,382.347222,0.996264,0.993518,0.010087,...,0.764582,1.872836,2.018678,-0.291749,0.638889,72,0,0,LGBM_40,ae0f20ba802df85f
9,GBR,United Kingdom,EX_MICRO,VALUE,1.011646,12.139748,382.347222,0.996264,0.993518,0.002879,...,0.161519,0.395638,0.458049,-0.412452,0.541667,72,0,0,LGBM_40,ae0f20ba802df85f
10,GBR,United Kingdom,FULL,EQUAL,0.859354,10.312245,877.458333,0.994729,0.993665,0.025589,...,2.425126,5.940322,4.323407,-0.234924,0.805556,72,0,0,LGBM_40,ae0f20ba802df85f
11,GBR,United Kingdom,FULL,VALUE,1.001804,12.021645,877.458333,0.994729,0.993665,0.015821,...,0.803970,1.969317,1.729981,-0.455063,0.625000,72,0,0,LGBM_40,ae0f20ba802df85f
12,AUS,Australia,EX_MICRO,EQUAL,1.265976,15.191710,246.972222,0.995300,0.997807,0.013516,...,0.926890,2.270407,2.645164,-0.297457,0.638889,72,0,0,DEEPSET_40_DYNAMIC,e6917ff0b09bbb56
13,AUS,Australia,EX_MICRO,VALUE,1.399313,16.791757,246.972222,0.995300,0.997807,0.006840,...,0.532309,1.303885,1.346673,-0.326390,0.611111,72,0,0,DEEPSET_40_DYNAMIC,e6917ff0b09bbb56
14,AUS,Australia,FULL,EQUAL,1.187577,14.250926,749.500000,0.992338,0.994803,0.034069,...,2.592963,6.351437,6.340414,-0.146108,0.833333,72,0,0,DEEPSET_40_DYNAMIC,e6917ff0b09bbb56
15,AUS,Australia,FULL,VALUE,1.407498,16.889971,749.500000,0.992338,0.994803,0.017717,...,1.020555,2.499839,2.374578,-0.391740,0.666667,72,0,0,DEEPSET_40_DYNAMIC,e6917ff0b09bbb56
16,AUS,Australia,EX_MICRO,EQUAL,1.138034,13.656403,246.972222,0.996400,0.998890,0.013769,...,0.886307,2.171000,2.301163,-0.359555,0.625000,72,0,0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,b569d197c3904525
17,AUS,Australia,EX_MICRO,VALUE,1.320117,15.841407,246.972222,0.996400,0.998890,0.013631,...,0.924408,2.264328,2.823422,-0.270753,0.680556,72,0,0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,b569d197c3904525
18,AUS,Australia,FULL,EQUAL,1.074049,12.888590,749.500000,0.991390,0.993480,0.040153,...,2.580219,6.320220,5.926192,-0.202881,0.847222,72,0,0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,b569d197c3904525
19,AUS,Australia,FULL,VALUE,1.283424,15.401087,749.500000,0.991390,0.993480,0.030162,...,1.391067,3.407404,2.979179,-0.380067,0.722222,72,0,0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,b569d197c3904525
20,AUS,Australia,EX_MICRO,EQUAL,0.965756,11.589068,246.972222,0.998760,0.998334,0.015216,...,1.024310,2.509036,2.017899,-0.336404,0.611111,72,0,0,LGBM_40,26a77b3f5953b7c2
21,AUS,Australia,EX_MICRO,VALUE,1.112107,13.345289,246.972222,0.998760,0.998334,0.017439,...,0.993628,2.433883,2.578538,-0.227232,0.611111,72,0,0,LGBM_40,26a77b3f5953b7c2
22,AUS,Australia,FULL,EQUAL,1.038729,12.464748,749.500000,0.989759,0.994083,0.038759,...,2.899698,7.102780,8.222270,-0.136183,0.833333,72,0,0,LGBM_40,26a77b3f5953b7c2
23,AUS,Australia,FULL,VALUE,1.229965,14.759577,749.500000,0.989759,0.994083,0.032361,...,1.667445,4.084389,3.992477,-0.289915,0.750000,72,0,0,LGBM_40,26a77b3f5953b7c2
24,DEU,Germany,EX_MICRO,EQUAL,1.241956,14.903475,214.680556,0.998146,0.998673,0.009413,...,0.738311,1.808484,1.580469,-0.202809,0.569444,72,0,0,DEEPSET_40_DYNAMIC,5e00a14b3c8919c2
25,DEU,Germany,EX_MICRO,VALUE,1.383708,16.604498,214.680556,0.998146,0.998673,0.012818,...,0.704192,1.724910,1.441011,-0.267128,0.569444,72,0,0,DEEPSET_40_DYNAMIC,5e00a14b3c8919c2
26,DEU,Germany,FULL,EQUAL,1.182256,14.187073,462.166667,0.996735,0.997543,0.022548,...,2.379735,5.829137,5.613222,-0.111758,0.805556,72,0,0,DEEPSET_40_DYNAMIC,5e00a14b3c8919c2
27,DEU,Germany,FULL,VALUE,1.413201,16.958412,462.166667,0.996735,0.997543,0.015901,...,0.722112,1.768805,1.582163,-0.327469,0.555556,72,0,0,DEEPSET_40_DYNAMIC,5e00a14b3c8919c2
28,DEU,Germany,EX_MICRO,EQUAL,1.138592,13.663109,214.680556,0.998146,0.997963,0.010721,...,0.779918,1.910401,1.460672,-0.243390,0.597222,72,0,0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,8eef2a88ee514a83
29,DEU,Germany,EX_MICRO,VALUE,1.321550,15.858603,214.680556,0.998146,0.997963,0.015318,...,0.725092,1.776105,1.452052,-0.354052,0.541667,72,0,0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,8eef2a88ee514a83
30,DEU,Germany,FULL,EQUAL,1.068135,12.817617,462.166667,0.997924,0.996972,0.029428,...,2.528619,6.193825,6.134483,-0.108061,0.819444,72,0,0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,8eef2a88ee514a83
31,DEU,Germany,FULL,VALUE,1.307273,15.687275,462.166667,0.997924,0.996972,0.020936,...,0.824974,2.020766,1.979782,-0.306919,0.583333,72,0,0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,8eef2a88ee514a83
32,DEU,Germany,EX_MICRO,EQUAL,0.930962,11.171539,214.680556,0.997174,0.996746,0.006848,...,0.515024,1.261545,1.135116,-0.176896,0.527778,72,0,0,LGBM_40,61670d27807e6b8b
33,DEU,Germany,EX_MICRO,VALUE,1.047356,12.568276,214.680556,0.997174,0.996746,0.008255,...,0.455582,1.115942,1.546538,-0.205158,0.541667,72,0,0,LGBM_40,61670d27807e6b8b
34,DEU,Germany,FULL,EQUAL,0.899817,10.797800,462.166667,0.996431,0.995284,0.027956,...,2.524808,6.184491,6.471414,-0.092390,0.847222,72,0,0,LGBM_40,61670d27807e6b8b
35,DEU,Germany,FULL,VALUE,1.055851,12.670213,462.166667,0.996431,0.995284,0.012166,...,0.596392,1.460855,1.576511,-0.358255,0.569444,72,0,0,LGBM_40,61670d27807e6b8b
36,FRA,France,EX_MICRO,EQUAL,1.262874,15.154484,191.888889,1.000000,0.993278,0.010374,...,0.876514,2.147012,2.613960,-0.221101,0.583333,72,0,0,DEEPSET_40_DYNAMIC,957deee44ac91bf8
37,FRA,France,EX_MICRO,VALUE,1.490125,17.881495,191.888889,1.000000,0.993278,0.001879,...,0.120016,0.293978,0.296238,-0.520090,0.527778,72,0,0,DEEPSET_40_DYNAMIC,957deee44ac91bf8
38,FRA,France,FULL,EQUAL,1.242194,14.906333,438.763889,0.997144,0.991228,0.026976,...,2.543060,6.229199,4.730603,-0.149125,0.791667,72,1,0,DEEPSET_40_DYNAMIC,957deee44ac91bf8
39,FRA,France,FULL,VALUE,1.510871,18.130455,438.763889,0.997144,0.991228,0.010132,...,0.562326,1.377412,1.298189,-0.382881,0.652778,72,1,0,DEEPSET_40_DYNAMIC,957deee44ac91bf8
40,FRA,France,EX_MICRO,EQUAL,1.162626,13.951512,191.888889,0.998575,0.990386,0.014851,...,1.150962,2.819270,3.437189,-0.212232,0.694444,72,0,0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,af80a744481d1cb3
41,FRA,France,EX_MICRO,VALUE,1.440152,17.281828,191.888889,0.998575,0.990386,0.008313,...,0.330312,0.809096,0.855811,-0.482841,0.555556,72,0,0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,af80a744481d1cb3
42,FRA,France,FULL,EQUAL,1.088853,13.066234,438.763889,0.995566,0.989546,0.031825,...,2.684409,6.575433,5.867847,-0.142920,0.819444,72,1,0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,af80a744481d1cb3
43,FRA,France,FULL,VALUE,1.440767,17.289206,438.763889,0.995566,0.989546,0.025418,...,1.030846,2.525047,2.614928,-0.321201,0.652778,72,1,0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,af80a744481d1cb3
44,FRA,France,EX_MICRO,EQUAL,1.036028,12.432332,191.888889,0.993749,0.990386,0.015811,...,1.525644,3.737049,3.462254,-0.100877,0.694444,72,0,0,LGBM_40,ded9e54eda05e69f
45,FRA,France,EX_MICRO,VALUE,1.345460,16.145526,191.888889,0.993749,0.990386,0.014393,...,0.558272,1.367482,1.362522,-0.286866,0.541667,72,0,0,LGBM_40,ded9e54eda05e69f
46,FRA,France,FULL,EQUAL,0.925690,11.108279,438.763889,0.993117,0.987291,-0.029995,...,2.118705,5.189745,4.443100,-0.224348,0.777778,72,1,1,LGBM_40,ded9e54eda05e69f
47,FRA,France,FULL,VALUE,1.302972,15.635664,438.763889,0.993117,0.987291,-0.001052,...,0.943384,2.310809,2.285313,-0.274824,0.736111,72,1,1,LGBM_40,ded9e54eda05e69f

## 7. Aggregate cross-country comparison

The first table presents all model-country results with an explicit model role. The second reports the chosen 50/50 model's change in Sharpe ratio and annualized return relative to each benchmark or robustness comparator; positive values favour the chosen model.

In [7]:
from src.developed_markets import aggregate_country_comparisons

external_comparison, chosen_model_improvements = aggregate_country_comparisons(
    CONFIGS, SUMMARY_DIR
)
display(external_comparison)
display(chosen_model_improvements)

,country,country_name,model_id,model_role,pooled_oos_r2,robust_oos_r2,mean_monthly_rank_ic,rank_ic_newey_west_t_stat,annualized_return,annualized_volatility,sharpe,newey_west_t_stat,max_drawdown,hit_rate,n_months
0,GBR,United Kingdom,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,chosen_model,0.000927,0.001469,0.088204,10.061946,0.327338,0.140001,2.338105,4.057702,-0.275165,0.777778,72
1,GBR,United Kingdom,LGBM_40,component_benchmark,0.001189,0.001634,0.075961,9.389031,0.307052,0.128454,2.390353,4.226540,-0.244730,0.805556,72
2,GBR,United Kingdom,DEEPSET_40_DYNAMIC,component_benchmark,-0.003436,-0.003354,0.081027,9.947264,0.306980,0.122102,2.514128,4.931987,-0.193222,0.805556,72
3,GBR,United Kingdom,HYBRID_LGBM40_DEEPSET40_DYNAMIC,robustness_comparator,-0.001394,-0.001281,0.080525,10.424331,0.309142,0.134043,2.306285,4.228197,-0.228245,0.777778,72
4,AUS,Australia,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,chosen_model,0.004742,0.005056,0.101720,8.433739,0.481833,0.186741,2.580219,5.926192,-0.202881,0.847222,72
5,AUS,Australia,LGBM_40,component_benchmark,0.005131,0.005777,0.096857,9.417564,0.468209,0.160294,2.920933,8.458087,-0.136183,0.847222,72
6,AUS,Australia,DEEPSET_40_DYNAMIC,component_benchmark,0.001499,0.001000,0.091752,7.620722,0.410833,0.157076,2.615512,6.437820,-0.148201,0.847222,72
7,AUS,Australia,HYBRID_LGBM40_DEEPSET40_DYNAMIC,robustness_comparator,0.004694,0.005394,0.093719,8.844524,0.411207,0.181382,2.267083,5.519029,-0.210532,0.791667,72
8,DEU,Germany,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,chosen_model,0.002679,0.003197,0.083174,10.942711,0.353132,0.139654,2.528619,6.134483,-0.108061,0.819444,72
9,DEU,Germany,LGBM_40,component_benchmark,-0.001261,-0.002089,0.076864,10.412527,0.335310,0.133335,2.514788,6.324801,-0.092525,0.875000,72
10,DEU,Germany,DEEPSET_40_DYNAMIC,component_benchmark,0.001363,0.001739,0.075573,9.487785,0.270320,0.114515,2.360560,5.585071,-0.116724,0.805556,72
11,DEU,Germany,HYBRID_LGBM40_DEEPSET40_DYNAMIC,robustness_comparator,-0.001784,-0.002861,0.075932,9.344044,0.339745,0.131679,2.580110,6.942859,-0.078811,0.791667,72
12,FRA,France,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,chosen_model,0.000024,0.001729,0.095568,8.424457,0.381900,0.142266,2.684409,5.867847,-0.142920,0.819444,72
13,FRA,France,LGBM_40,component_benchmark,-0.000021,-0.000287,0.081710,7.701541,-0.366395,1.696447,-0.215978,-0.551040,-4.512655,0.763889,72
14,FRA,France,DEEPSET_40_DYNAMIC,component_benchmark,-0.000021,-0.001645,0.084743,8.344216,0.324078,0.128606,2.519927,4.638597,-0.149724,0.777778,72
15,FRA,France,HYBRID_LGBM40_DEEPSET40_DYNAMIC,robustness_comparator,0.000014,0.001859,0.087774,7.950985,0.349578,0.149628,2.336316,5.249711,-0.185206,0.833333,72

,country,country_name,chosen_minus_lgbm_40_sharpe,chosen_minus_lgbm_40_annualized_return,chosen_minus_deepset_40_dynamic_sharpe,chosen_minus_deepset_40_dynamic_annualized_return,chosen_minus_hybrid_lgbm40_deepset40_dynamic_sharpe,chosen_minus_hybrid_lgbm40_deepset40_dynamic_annualized_return
0,AUS,Australia,-0.340714,0.013624,-0.035293,0.071000,0.313136,0.070626
1,DEU,Germany,0.013831,0.017821,0.168058,0.082812,-0.051491,0.013386
2,FRA,France,2.900387,0.748295,0.164482,0.057823,0.348093,0.032323
3,GBR,United Kingdom,-0.052249,0.020286,-0.176023,0.020358,0.031820,0.018196

## 8. Completion checks

In [8]:
expected_months = 72
expected_models_per_country = len(REPORT_MODEL_IDS)
if len(external_comparison) != len(COUNTRIES) * expected_models_per_country:
    raise RuntimeError('The aggregate country/model table is incomplete.')
if external_comparison['n_months'].ne(expected_months).any():
    display(external_comparison.loc[external_comparison['n_months'].ne(expected_months)])
    raise RuntimeError('At least one country/model does not cover all 72 OOS months.')
expected_robustness_models = 1 + len(COMPONENT_BENCHMARK_IDS)
if len(external_robustness) != len(COUNTRIES) * expected_robustness_models * 4:
    raise RuntimeError('The aggregate implementability table is incomplete.')
print('External validation complete for:', list(COUNTRIES))
print('Model-country rows:', len(external_comparison))
print('OOS period: 2019-01 through 2024-12')
print('Summary directory:', SUMMARY_DIR)

External validation complete for: ['GBR', 'AUS', 'DEU', 'FRA']
Model-country rows: 16
OOS period: 2019-01 through 2024-12
Summary directory: /content/drive/MyDrive/Colab Notebooks/FDS Project/model_runs/developed_markets/summary