# Models Pipeline

This notebook is the restartable entry point for model estimation, pooled out-of-sample prediction, diagnostic evaluation, portfolio construction, implementability analysis, and paired model tests. Annual refits and derived artifacts are cached by model ID and specification signature.

## Model roster

The model roster includes conventional linear, tree-based, and neural benchmarks; the LightGBM 20/40/60/80/100 characteristic expansion; exact-calendar lagged LightGBM specifications; independent-stock MLP controls; permutation-invariant DeepSets models; and validation-weighted hybrids. `NN2_20` uses hidden widths `[32, 16]`, `NN3_20` uses `[32, 16, 8]`, and `NN4_20` uses `[32, 16, 8, 4]`. These are GKX-style benchmarks rather than exact replications because the information set and sample differ. `MLP_40` is the monthly-panel control without pooled market context. `DEEPSET_40_LAG1` adds exact one-month-lagged characteristics, and `DEEPSET_40_DYNAMIC` additionally includes one-month characteristic velocities.

## Fixed design decisions

- The target is decimal next-month excess return, `ret_exc_lead1m`.
- The universe is USA stocks with a valid stable JKP `id` and size group micro/small/large/mega; nano stocks are excluded.
- Characteristics are ranked within the complete eligible monthly cross-section and mapped to `[-1, 1]` before target availability is inspected. Missing targets are masked from fitting and evaluation calculations but do not change the month-t ranking universe.
- Exact-calendar lags are joined by JKP `id`. Missing prior months receive neutral values plus a zero availability flag.
- The rolling design uses 15 training years, 4 validation years, one temporally held-out test year, and annual refits from 1999 through 2024.
- Validation MSE selects hyperparameters and early stopping. Test outcomes never affect fitting or model selection.
- Primary evaluation is pooled GKX OOS R-squared and the equal-weighted D10-D1 portfolio. Rank IC, calibration, robust R-squared, monotonicity, alternative portfolios, transaction costs, universe sensitivity, and an adverse missing-return stress are supporting diagnostics.
- Constant-forecast months hold cash. Prediction ties receive fractional boundary allocation, so portfolio returns do not depend on identifier ordering.
- Each model/refit has an independent signature and completion marker. Compatible results load without retraining or overwriting.

## 1. Runtime and project setup

This cell selects the Google Drive project when executed in Colab and the local project directory under a standard Windows kernel. It clears cached `src` modules and verifies the resolved import path before configuration or training.

In [1]:
import os
import sys
import importlib
from pathlib import Path

LOCAL_PROJECT_DIR = Path(r"C:\Users\sandh\OneDrive\Documents\Coding\FDS Project")
DRIVE_PROJECT_DIR = Path("/content/drive/MyDrive/Colab Notebooks/FDS Project")

try:
    from google.colab import drive
except ImportError:
    RUNNING_IN_COLAB = False
    PROJECT_DIR = LOCAL_PROJECT_DIR
    RUNTIME = "Local VS Code kernel"
else:
    RUNNING_IN_COLAB = True
    # Reuse an existing Drive mount when available.
    drive.mount("/content/drive", force_remount=False)
    PROJECT_DIR = DRIVE_PROJECT_DIR
    RUNTIME = "Google Colab kernel in VS Code"

if not PROJECT_DIR.is_dir():
    raise FileNotFoundError(
        f"Project folder was not found: {PROJECT_DIR}\n"
        "If this is Colab, confirm that Drive is mounted and that the folder name matches exactly."
    )
if not (PROJECT_DIR / "src").is_dir():
    raise FileNotFoundError(f"The project src folder was not found under: {PROJECT_DIR}")

os.chdir(PROJECT_DIR)
project_path = str(PROJECT_DIR)
# Prioritize the selected project directory during module resolution.
sys.path = [path for path in sys.path if path != project_path]
sys.path.insert(0, project_path)
for module_name in tuple(sys.modules):
    if module_name == "src" or module_name.startswith("src."):
        del sys.modules[module_name]
importlib.invalidate_caches()

# Verify the resolved source package before configuration.
import src
src_file = Path(src.__file__).resolve()
if PROJECT_DIR.resolve() not in src_file.parents:
    raise RuntimeError(f"Imported src from the wrong location: {src_file}")

print("Notebook file: local Models_Pipeline.ipynb")
print("Runtime:", RUNTIME)
print("Project files and outputs:", PROJECT_DIR)
print("Imported src from:", src_file)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Notebook file: local Models_Pipeline.ipynb
Runtime: Google Colab kernel in VS Code
Project files and outputs: /content/drive/MyDrive/Colab Notebooks/FDS Project
Imported src from: /content/drive/MyDrive/Colab Notebooks/FDS Project/src/__init__.py

## 2. Experiment configuration

The configuration fixes the dataset, experiment identifier, selected model roster, random seed, and device policy. A new experiment identifier is required after changing the universe, target, preprocessing, feature definitions, or rolling schedule.

In [2]:
if 'PROJECT_DIR' not in globals():
    raise RuntimeError('Run the Runtime and project setup cell first, or use Run all.')

from src.config import ExperimentConfig, UniverseConfig
from src.models import MODEL_REGISTRY

DATA_PATH = PROJECT_DIR / 'jkp_USA_100chars_1980_2024.parquet'
OUTPUT_DIR = PROJECT_DIR / 'model_runs'
if not DATA_PATH.is_file():
    raise FileNotFoundError(f'Raw data file not found: {DATA_PATH}')

MODEL_ROSTER = (
    'LASSO_20', 'LGBM_20', 'XGBOOST_20', 'NN2_20', 'NN3_20', 'NN4_20',
    'LGBM_40', 'LGBM_60', 'LGBM_80', 'LGBM_100',
    'LGBM_40_LAG1', 'LGBM_40_LAG2',
    'MLP_40', 'DEEPSET_40', 'DEEPSET_40_LAG1', 'DEEPSET_40_DYNAMIC',
    'HYBRID_MLP40_DEEPSET40',
    'HYBRID_LGBM40_DEEPSET40', 'HYBRID_LGBM40_DEEPSET40_DYNAMIC',
)
# Hybrid components use years 1--3 of validation for early stopping;
# the convex combination is estimated on validation year 4.
SELECTED_MODELS = MODEL_ROSTER

CONFIG = ExperimentConfig(
    experiment_id='core20_benchmarks_v1',
    project_dir=PROJECT_DIR,
    data_path=DATA_PATH,
    output_dir=OUTPUT_DIR,
    selected_models=SELECTED_MODELS,
    seed=42,
    use_gpu=True,
    universe=UniverseConfig(security_id_col='id'),
)
CONFIG.validate()

import torch
if CONFIG.use_gpu and not torch.cuda.is_available():
    raise RuntimeError('GPU requested but unavailable. Select a GPU runtime and reconnect before training.')
print('Torch device:', torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU')
print('Selected models:', list(CONFIG.selected_models))
print('Run directory:', CONFIG.run_dir)

Torch device: NVIDIA A100-SXM4-40GB
Selected models: ['LASSO_20', 'LGBM_20', 'XGBOOST_20', 'NN2_20', 'NN3_20', 'NN4_20', 'LGBM_40', 'LGBM_60', 'LGBM_80', 'LGBM_100', 'LGBM_40_LAG1', 'LGBM_40_LAG2', 'MLP_40', 'DEEPSET_40', 'DEEPSET_40_LAG1', 'DEEPSET_40_DYNAMIC', 'HYBRID_MLP40_DEEPSET40', 'HYBRID_LGBM40_DEEPSET40', 'HYBRID_LGBM40_DEEPSET40_DYNAMIC']
Run directory: /content/drive/MyDrive/Colab Notebooks/FDS Project/model_runs/core20_benchmarks_v1

## 3. Preflight checks

This verifies required project files, registry consistency, feature construction, rolling-window timing, evaluation definitions, hybrid validation separation, and tie-safe portfolio construction before model estimation.

In [3]:
import unittest
from src.self_checks import run_framework_self_checks

required_files = (
    DATA_PATH,
    PROJECT_DIR / 'src' / 'config.py',
    PROJECT_DIR / 'src' / 'models.py',
    PROJECT_DIR / 'src' / 'runner.py',
    PROJECT_DIR / 'src' / 'self_checks.py',
    PROJECT_DIR / 'tests' / 'test_pipeline.py',
)
missing_files = [str(path) for path in required_files if not path.is_file()]
if missing_files:
    raise FileNotFoundError(f'Required project files are missing: {missing_files}')
unknown_models = sorted(set(CONFIG.selected_models) - set(MODEL_REGISTRY))
if unknown_models:
    raise ValueError(f'Selected models are not registered: {unknown_models}')

run_framework_self_checks()
suite = unittest.defaultTestLoader.discover(str(PROJECT_DIR / 'tests'))
test_result = unittest.TextTestRunner(verbosity=1).run(suite)
if not test_result.wasSuccessful():
    raise RuntimeError('Pipeline unit tests failed.')
print('Project files: PASS')
print('Selected model registry: PASS')
print('Framework self-checks: PASS')
print('Pipeline unit tests: PASS')

......................
----------------------------------------------------------------------
Ran 22 tests in 3.067s

OK

Project files: PASS
Selected model registry: PASS
Framework self-checks: PASS
Pipeline unit tests: PASS

## 4. Run or resume

This is safe to rerun. Compatible completed refits load, incomplete work resumes or reruns, pooled files rebuild from refit outputs, and metrics and portfolios refresh.

In [4]:
# Process models separately to bound panel memory use.
from dataclasses import replace
import gc
import torch
from src.runner import ExperimentRunner

for model_id in CONFIG.selected_models:
    print(f'\n=== {model_id} ===')
    model_config = replace(CONFIG, selected_models=(model_id,))
    ExperimentRunner(model_config).run()
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

# Construct the cumulative comparison over the full roster.
runner = ExperimentRunner(CONFIG)
comparison = runner._cumulative_comparison()
display(comparison)

=== LASSO_20 ===
Device: cuda
LASSO_20 [bc11f57268346015]: current diagnostics; skipping

=== LGBM_20 ===
Device: cuda
LGBM_20 [2384b144be38bad7]: current diagnostics; skipping

=== XGBOOST_20 ===
Device: cuda
XGBOOST_20 [507f3c420a300c4b]: current diagnostics; skipping

=== NN2_20 ===
Device: cuda
NN2_20 [6130644ff7a7bc93]: current diagnostics; skipping

=== NN3_20 ===
Device: cuda
NN3_20 [739c8c490c1c6d16]: current diagnostics; skipping

=== NN4_20 ===
Device: cuda
NN4_20 [eee1133001253343]: current diagnostics; skipping

=== LGBM_40 ===
Device: cuda
LGBM_40 [9c0540e864a705bf]: current diagnostics; skipping

=== LGBM_60 ===
Device: cuda
LGBM_60 [94e3ec047ddc57fc]: current diagnostics; skipping

=== LGBM_80 ===
Device: cuda
LGBM_80 [80077a60ed146994]: current diagnostics; skipping

=== LGBM_100 ===
Device: cuda
LGBM_100 [56fb90cc59a0ce74]: current diagnostics; skipping

=== LGBM_40_LAG1 ===
Device: cuda
LGBM_40_LAG1 [4aafd74344026b96]: current diagnostics; skipping

=== LGBM_40_LAG2 ===
Device: cuda
LGBM_40_LAG2 [5ea44d3ad39373d9]: current diagnostics; skipping

=== MLP_40 ===
Device: cuda
MLP_40 [e6a25033ee712d15]: current diagnostics; skipping

=== DEEPSET_40 ===
Device: cuda
DEEPSET_40 [4278ae26cf4fdcb7]: current diagnostics; skipping

=== DEEPSET_40_LAG1 ===
Device: cuda
DEEPSET_40_LAG1 [daaa24e9d2d7a5a6]: current diagnostics; skipping

=== DEEPSET_40_DYNAMIC ===
Device: cuda

DEEPSET_40_DYNAMIC [4a51c6755ddf965f]
  refit 01/26 | test_year=1999 | status=loading
  refit 02/26 | test_year=2000 | status=training | train_n=893,802 | validation_n=313,546 | test_n=75,345
    resuming at epoch 56
    epoch 056/100 | train_mse=0.02166661 | val_mse=0.03461101 | best_val_mse=0.03459562 | early_stop=01/10 | 2.7s
    epoch 057/100 | train_mse=0.02184517 | val_mse=0.03460192 | best_val_mse=0.03459562 | early_stop=02/10 | 1.8s
    epoch 058/100 | train_mse=0.02164067 | val_mse=0.03466622 | best_val_mse=0.03459562 | early_stop=03/10 | 1.8s
    epoch 059/100 | train_mse=0.02165233 | val_mse=0.03482661 | best_val_mse=0.03459562 | early_stop=04/10 | 1.7s
    epoch 060/100 | train_mse=0.02161438 | val_mse=0.03464801 | best_val_mse=0.03459562 | early_stop=05/10 | 1.7s
    epoch 061/100 | train_mse=0.02160711 | val_mse=0.03480655 | best_val_mse=0.03459562 | early_stop=06/10 | 1.7s
    epoch 062/100 | train_mse=0.02162779 | val_mse=0.03463641 | best_val_mse=0.03459562 | early_stop=07/10 | 1.8s
    epoch 063/100 | train_mse=0.02160301 | val_mse=0.03459176 | best_val_mse=0.03459176 | early_stop=00/10 | 1.7s
    epoch 064/100 | train_mse=0.02163072 | val_mse=0.03477370 | best_val_mse=0.03459176 | early_stop=01/10 | 1.8s
    epoch 065/100 | train_mse=0.02158063 | val_mse=0.03505518 | best_val_mse=0.03459176 | early_stop=02/10 | 1.8s
    epoch 066/100 | train_mse=0.02162716 | val_mse=0.03477973 | best_val_mse=0.03459176 | early_stop=03/10 | 1.8s
    epoch 067/100 | train_mse=0.02155908 | val_mse=0.03468773 | best_val_mse=0.03459176 | early_stop=04/10 | 1.8s
    epoch 068/100 | train_mse=0.02173201 | val_mse=0.03476909 | best_val_mse=0.03459176 | early_stop=05/10 | 1.7s
    epoch 069/100 | train_mse=0.02155361 | val_mse=0.03475903 | best_val_mse=0.03459176 | early_stop=06/10 | 1.7s
    epoch 070/100 | train_mse=0.02158528 | val_mse=0.03464920 | best_val_mse=0.03459176 | early_stop=07/10 | 1.7s
    epoch 071/100 | train_mse=0.02151562 | val_mse=0.03463403 | best_val_mse=0.03459176 | early_stop=08/10 | 1.7s
    epoch 072/100 | train_mse=0.02149445 | val_mse=0.03459696 | best_val_mse=0.03459176 | early_stop=09/10 | 1.8s
    epoch 073/100 | train_mse=0.02146781 | val_mse=0.03477097 | best_val_mse=0.03459176 | early_stop=10/10 | 1.8s
  refit 02/26 | test_year=2000 | status=saved | n_predictions=75,345
  refit 03/26 | test_year=2001 | status=training | train_n=928,527 | validation_n=309,376 | test_n=69,652
    epoch 001/100 | train_mse=0.02374360 | val_mse=0.04573242 | best_val_mse=0.04573242 | early_stop=00/10 | 1.8s
    epoch 002/100 | train_mse=0.02322346 | val_mse=0.04591293 | best_val_mse=0.04573242 | early_stop=01/10 | 1.7s
    epoch 003/100 | train_mse=0.02325830 | val_mse=0.04565196 | best_val_mse=0.04565196 | early_stop=00/10 | 1.8s
    epoch 004/100 | train_mse=0.02305257 | val_mse=0.04571173 | best_val_mse=0.04565196 | early_stop=01/10 | 1.8s
    epoch 005/100 | train_mse=0.02308809 | val_mse=0.04562631 | best_val_mse=0.04562631 | early_stop=00/10 | 1.8s
    epoch 006/100 | train_mse=0.02302556 | val_mse=0.04563909 | best_val_mse=0.04562631 | early_stop=01/10 | 1.8s
    epoch 007/100 | train_mse=0.02297125 | val_mse=0.04570167 | best_val_mse=0.04562631 | early_stop=02/10 | 1.7s
    epoch 008/100 | train_mse=0.02304687 | val_mse=0.04558535 | best_val_mse=0.04558535 | early_stop=00/10 | 1.8s
    epoch 009/100 | train_mse=0.02298957 | val_mse=0.04573053 | best_val_mse=0.04558535 | early_stop=01/10 | 1.7s
    epoch 010/100 | train_mse=0.02297136 | val_mse=0.04559418 | best_val_mse=0.04558535 | early_stop=02/10 | 1.8s
    epoch 011/100 | train_mse=0.02301156 | val_mse=0.04569545 | best_val_mse=0.04558535 | early_stop=03/10 | 1.8s
    epoch 012/100 | train_mse=0.02295904 | val_mse=0.04555654 | best_val_mse=0.04555654 | early_stop=00/10 | 1.8s
    epoch 013/100 | train_mse=0.02292710 | val_mse=0.04557599 | best_val_mse=0.04555654 | early_stop=01/10 | 1.8s
    epoch 014/100 | train_mse=0.02294640 | val_mse=0.04564839 | best_val_mse=0.04555654 | early_stop=02/10 | 1.7s
    epoch 015/100 | train_mse=0.02296113 | val_mse=0.04556688 | best_val_mse=0.04555654 | early_stop=03/10 | 1.7s
    epoch 016/100 | train_mse=0.02291078 | val_mse=0.04555167 | best_val_mse=0.04555167 | early_stop=00/10 | 1.8s
    epoch 017/100 | train_mse=0.02290418 | val_mse=0.04554641 | best_val_mse=0.04554641 | early_stop=00/10 | 1.8s
    epoch 018/100 | train_mse=0.02288854 | val_mse=0.04555014 | best_val_mse=0.04554641 | early_stop=01/10 | 1.8s
    epoch 019/100 | train_mse=0.02289425 | val_mse=0.04554550 | best_val_mse=0.04554550 | early_stop=00/10 | 1.8s
    epoch 020/100 | train_mse=0.02288168 | val_mse=0.04553323 | best_val_mse=0.04553323 | early_stop=00/10 | 1.7s
    epoch 021/100 | train_mse=0.02293350 | val_mse=0.04554600 | best_val_mse=0.04553323 | early_stop=01/10 | 1.7s
    epoch 022/100 | train_mse=0.02287073 | val_mse=0.04557678 | best_val_mse=0.04553323 | early_stop=02/10 | 1.8s
    epoch 023/100 | train_mse=0.02287027 | val_mse=0.04574518 | best_val_mse=0.04553323 | early_stop=03/10 | 1.7s
    epoch 024/100 | train_mse=0.02291369 | val_mse=0.04553131 | best_val_mse=0.04553131 | early_stop=00/10 | 1.8s
    epoch 025/100 | train_mse=0.02284898 | val_mse=0.04551980 | best_val_mse=0.04551980 | early_stop=00/10 | 1.8s
    epoch 026/100 | train_mse=0.02289309 | val_mse=0.04555896 | best_val_mse=0.04551980 | early_stop=01/10 | 1.8s
    epoch 027/100 | train_mse=0.02285109 | val_mse=0.04555701 | best_val_mse=0.04551980 | early_stop=02/10 | 1.7s
    epoch 028/100 | train_mse=0.02285206 | val_mse=0.04549729 | best_val_mse=0.04549729 | early_stop=00/10 | 1.8s
    epoch 029/100 | train_mse=0.02290525 | val_mse=0.04552180 | best_val_mse=0.04549729 | early_stop=01/10 | 1.8s
    epoch 030/100 | train_mse=0.02285667 | val_mse=0.04550524 | best_val_mse=0.04549729 | early_stop=02/10 | 1.8s
    epoch 031/100 | train_mse=0.02283288 | val_mse=0.04549312 | best_val_mse=0.04549312 | early_stop=00/10 | 1.8s
    epoch 032/100 | train_mse=0.02281775 | val_mse=0.04550022 | best_val_mse=0.04549312 | early_stop=01/10 | 1.7s
    epoch 033/100 | train_mse=0.02279027 | val_mse=0.04550283 | best_val_mse=0.04549312 | early_stop=02/10 | 1.8s
    epoch 034/100 | train_mse=0.02279232 | val_mse=0.04552099 | best_val_mse=0.04549312 | early_stop=03/10 | 1.7s
    epoch 035/100 | train_mse=0.02277223 | val_mse=0.04546233 | best_val_mse=0.04546233 | early_stop=00/10 | 1.8s
    epoch 036/100 | train_mse=0.02276168 | val_mse=0.04570247 | best_val_mse=0.04546233 | early_stop=01/10 | 1.8s
    epoch 037/100 | train_mse=0.02284398 | val_mse=0.04545024 | best_val_mse=0.04545024 | early_stop=00/10 | 1.8s
    epoch 038/100 | train_mse=0.02281036 | val_mse=0.04543462 | best_val_mse=0.04543462 | early_stop=00/10 | 1.8s
    epoch 039/100 | train_mse=0.02275902 | val_mse=0.04543250 | best_val_mse=0.04543250 | early_stop=00/10 | 1.8s
    epoch 040/100 | train_mse=0.02277830 | val_mse=0.04544042 | best_val_mse=0.04543250 | early_stop=01/10 | 1.8s
    epoch 041/100 | train_mse=0.02271698 | val_mse=0.04545921 | best_val_mse=0.04543250 | early_stop=02/10 | 1.8s
    epoch 042/100 | train_mse=0.02273215 | val_mse=0.04545813 | best_val_mse=0.04543250 | early_stop=03/10 | 1.7s
    epoch 043/100 | train_mse=0.02272944 | val_mse=0.04539517 | best_val_mse=0.04539517 | early_stop=00/10 | 1.8s
    epoch 044/100 | train_mse=0.02271465 | val_mse=0.04541311 | best_val_mse=0.04539517 | early_stop=01/10 | 1.8s
    epoch 045/100 | train_mse=0.02269775 | val_mse=0.04539666 | best_val_mse=0.04539517 | early_stop=02/10 | 1.7s
    epoch 046/100 | train_mse=0.02274989 | val_mse=0.04536633 | best_val_mse=0.04536633 | early_stop=00/10 | 1.8s
    epoch 047/100 | train_mse=0.02266349 | val_mse=0.04536347 | best_val_mse=0.04536347 | early_stop=00/10 | 1.8s
    epoch 048/100 | train_mse=0.02269492 | val_mse=0.04528830 | best_val_mse=0.04528830 | early_stop=00/10 | 1.8s
    epoch 049/100 | train_mse=0.02267397 | val_mse=0.04531922 | best_val_mse=0.04528830 | early_stop=01/10 | 1.8s
    epoch 050/100 | train_mse=0.02267076 | val_mse=0.04533896 | best_val_mse=0.04528830 | early_stop=02/10 | 1.8s
    epoch 051/100 | train_mse=0.02260744 | val_mse=0.04527447 | best_val_mse=0.04527447 | early_stop=00/10 | 1.8s
    epoch 052/100 | train_mse=0.02264572 | val_mse=0.04533807 | best_val_mse=0.04527447 | early_stop=01/10 | 1.7s
    epoch 053/100 | train_mse=0.02264437 | val_mse=0.04526905 | best_val_mse=0.04526905 | early_stop=00/10 | 1.7s
    epoch 054/100 | train_mse=0.02262828 | val_mse=0.04537359 | best_val_mse=0.04526905 | early_stop=01/10 | 1.7s
    epoch 055/100 | train_mse=0.02260431 | val_mse=0.04531188 | best_val_mse=0.04526905 | early_stop=02/10 | 1.8s
    epoch 056/100 | train_mse=0.02255324 | val_mse=0.04546157 | best_val_mse=0.04526905 | early_stop=03/10 | 1.7s
    epoch 057/100 | train_mse=0.02254792 | val_mse=0.04521207 | best_val_mse=0.04521207 | early_stop=00/10 | 1.8s
    epoch 058/100 | train_mse=0.02248061 | val_mse=0.04556196 | best_val_mse=0.04521207 | early_stop=01/10 | 1.8s
    epoch 059/100 | train_mse=0.02255550 | val_mse=0.04527332 | best_val_mse=0.04521207 | early_stop=02/10 | 1.8s
    epoch 060/100 | train_mse=0.02252876 | val_mse=0.04526382 | best_val_mse=0.04521207 | early_stop=03/10 | 1.8s
    epoch 061/100 | train_mse=0.02260644 | val_mse=0.04539975 | best_val_mse=0.04521207 | early_stop=04/10 | 1.8s
    epoch 062/100 | train_mse=0.02244093 | val_mse=0.04524326 | best_val_mse=0.04521207 | early_stop=05/10 | 1.7s
    epoch 063/100 | train_mse=0.02248262 | val_mse=0.04531921 | best_val_mse=0.04521207 | early_stop=06/10 | 1.7s
    epoch 064/100 | train_mse=0.02238254 | val_mse=0.04531529 | best_val_mse=0.04521207 | early_stop=07/10 | 1.8s
    epoch 065/100 | train_mse=0.02233444 | val_mse=0.04540890 | best_val_mse=0.04521207 | early_stop=08/10 | 1.8s
    epoch 066/100 | train_mse=0.02247715 | val_mse=0.04533959 | best_val_mse=0.04521207 | early_stop=09/10 | 1.8s
    epoch 067/100 | train_mse=0.02237813 | val_mse=0.04516625 | best_val_mse=0.04516625 | early_stop=00/10 | 1.8s
    epoch 068/100 | train_mse=0.02234949 | val_mse=0.04518784 | best_val_mse=0.04516625 | early_stop=01/10 | 1.7s
    epoch 069/100 | train_mse=0.02231081 | val_mse=0.04517201 | best_val_mse=0.04516625 | early_stop=02/10 | 1.7s
    epoch 070/100 | train_mse=0.02240446 | val_mse=0.04516214 | best_val_mse=0.04516214 | early_stop=00/10 | 1.8s
    epoch 071/100 | train_mse=0.02246748 | val_mse=0.04554007 | best_val_mse=0.04516214 | early_stop=01/10 | 1.8s
    epoch 072/100 | train_mse=0.02223676 | val_mse=0.04523798 | best_val_mse=0.04516214 | early_stop=02/10 | 1.8s
    epoch 073/100 | train_mse=0.02231222 | val_mse=0.04520196 | best_val_mse=0.04516214 | early_stop=03/10 | 1.8s
    epoch 074/100 | train_mse=0.02228348 | val_mse=0.04516785 | best_val_mse=0.04516214 | early_stop=04/10 | 1.8s
    epoch 075/100 | train_mse=0.02246078 | val_mse=0.04532694 | best_val_mse=0.04516214 | early_stop=05/10 | 1.8s
    epoch 076/100 | train_mse=0.02233335 | val_mse=0.04535989 | best_val_mse=0.04516214 | early_stop=06/10 | 1.7s
    epoch 077/100 | train_mse=0.02224818 | val_mse=0.04535087 | best_val_mse=0.04516214 | early_stop=07/10 | 1.7s
    epoch 078/100 | train_mse=0.02227257 | val_mse=0.04520445 | best_val_mse=0.04516214 | early_stop=08/10 | 1.7s
    epoch 079/100 | train_mse=0.02220018 | val_mse=0.04514229 | best_val_mse=0.04514229 | early_stop=00/10 | 1.8s
    epoch 080/100 | train_mse=0.02213428 | val_mse=0.04516273 | best_val_mse=0.04514229 | early_stop=01/10 | 1.8s
    epoch 081/100 | train_mse=0.02231200 | val_mse=0.04537813 | best_val_mse=0.04514229 | early_stop=02/10 | 1.7s
    epoch 082/100 | train_mse=0.02220120 | val_mse=0.04517675 | best_val_mse=0.04514229 | early_stop=03/10 | 1.8s
    epoch 083/100 | train_mse=0.02217735 | val_mse=0.04525044 | best_val_mse=0.04514229 | early_stop=04/10 | 1.7s
    epoch 084/100 | train_mse=0.02222231 | val_mse=0.04516350 | best_val_mse=0.04514229 | early_stop=05/10 | 1.8s
    epoch 085/100 | train_mse=0.02218490 | val_mse=0.04524025 | best_val_mse=0.04514229 | early_stop=06/10 | 1.8s
    epoch 086/100 | train_mse=0.02212988 | val_mse=0.04527369 | best_val_mse=0.04514229 | early_stop=07/10 | 1.8s
    epoch 087/100 | train_mse=0.02224302 | val_mse=0.04531084 | best_val_mse=0.04514229 | early_stop=08/10 | 1.8s
    epoch 088/100 | train_mse=0.02216061 | val_mse=0.04564197 | best_val_mse=0.04514229 | early_stop=09/10 | 1.8s
    epoch 089/100 | train_mse=0.02216747 | val_mse=0.04557903 | best_val_mse=0.04514229 | early_stop=10/10 | 1.7s
  refit 03/26 | test_year=2001 | status=saved | n_predictions=69,652
  refit 04/26 | test_year=2002 | status=training | train_n=965,790 | validation_n=297,051 | test_n=58,995
    epoch 001/100 | train_mse=0.02404291 | val_mse=0.05197161 | best_val_mse=0.05197161 | early_stop=00/10 | 1.8s
    epoch 002/100 | train_mse=0.02359231 | val_mse=0.05188278 | best_val_mse=0.05188278 | early_stop=00/10 | 1.8s
    epoch 003/100 | train_mse=0.02328860 | val_mse=0.05193267 | best_val_mse=0.05188278 | early_stop=01/10 | 1.8s
    epoch 004/100 | train_mse=0.02329326 | val_mse=0.05187826 | best_val_mse=0.05187826 | early_stop=00/10 | 1.8s
    epoch 005/100 | train_mse=0.02324901 | val_mse=0.05186105 | best_val_mse=0.05186105 | early_stop=00/10 | 1.8s
    epoch 006/100 | train_mse=0.02328319 | val_mse=0.05184820 | best_val_mse=0.05184820 | early_stop=00/10 | 1.8s
    epoch 007/100 | train_mse=0.02320628 | val_mse=0.05180557 | best_val_mse=0.05180557 | early_stop=00/10 | 1.8s
    epoch 008/100 | train_mse=0.02320350 | val_mse=0.05198948 | best_val_mse=0.05180557 | early_stop=01/10 | 1.7s
    epoch 009/100 | train_mse=0.02319109 | val_mse=0.05175833 | best_val_mse=0.05175833 | early_stop=00/10 | 1.8s
    epoch 010/100 | train_mse=0.02311463 | val_mse=0.05175541 | best_val_mse=0.05175541 | early_stop=00/10 | 1.8s
    epoch 011/100 | train_mse=0.02316571 | val_mse=0.05175806 | best_val_mse=0.05175541 | early_stop=01/10 | 1.8s
    epoch 012/100 | train_mse=0.02314333 | val_mse=0.05181009 | best_val_mse=0.05175541 | early_stop=02/10 | 1.8s
    epoch 013/100 | train_mse=0.02314639 | val_mse=0.05175684 | best_val_mse=0.05175541 | early_stop=03/10 | 1.8s
    epoch 014/100 | train_mse=0.02310974 | val_mse=0.05175082 | best_val_mse=0.05175082 | early_stop=00/10 | 1.8s
    epoch 015/100 | train_mse=0.02314598 | val_mse=0.05172778 | best_val_mse=0.05172778 | early_stop=00/10 | 1.8s
    epoch 016/100 | train_mse=0.02316751 | val_mse=0.05172360 | best_val_mse=0.05172360 | early_stop=00/10 | 1.8s
    epoch 017/100 | train_mse=0.02311976 | val_mse=0.05170090 | best_val_mse=0.05170090 | early_stop=00/10 | 1.8s
    epoch 018/100 | train_mse=0.02306219 | val_mse=0.05177557 | best_val_mse=0.05170090 | early_stop=01/10 | 1.8s
    epoch 019/100 | train_mse=0.02304767 | val_mse=0.05172602 | best_val_mse=0.05170090 | early_stop=02/10 | 1.8s
    epoch 020/100 | train_mse=0.02307224 | val_mse=0.05167745 | best_val_mse=0.05167745 | early_stop=00/10 | 1.8s
    epoch 021/100 | train_mse=0.02303456 | val_mse=0.05173487 | best_val_mse=0.05167745 | early_stop=01/10 | 1.8s
    epoch 022/100 | train_mse=0.02304087 | val_mse=0.05176800 | best_val_mse=0.05167745 | early_stop=02/10 | 1.8s
    epoch 023/100 | train_mse=0.02304323 | val_mse=0.05168758 | best_val_mse=0.05167745 | early_stop=03/10 | 1.9s
    epoch 024/100 | train_mse=0.02305077 | val_mse=0.05169103 | best_val_mse=0.05167745 | early_stop=04/10 | 1.8s
    epoch 025/100 | train_mse=0.02303530 | val_mse=0.05166144 | best_val_mse=0.05166144 | early_stop=00/10 | 1.8s
    epoch 026/100 | train_mse=0.02305300 | val_mse=0.05175350 | best_val_mse=0.05166144 | early_stop=01/10 | 1.8s
    epoch 027/100 | train_mse=0.02300481 | val_mse=0.05166089 | best_val_mse=0.05166089 | early_stop=00/10 | 1.8s
    epoch 028/100 | train_mse=0.02298952 | val_mse=0.05167479 | best_val_mse=0.05166089 | early_stop=01/10 | 1.8s
    epoch 029/100 | train_mse=0.02301874 | val_mse=0.05165671 | best_val_mse=0.05165671 | early_stop=00/10 | 1.8s
    epoch 030/100 | train_mse=0.02303269 | val_mse=0.05167494 | best_val_mse=0.05165671 | early_stop=01/10 | 1.8s
    epoch 031/100 | train_mse=0.02297085 | val_mse=0.05165799 | best_val_mse=0.05165671 | early_stop=02/10 | 1.8s
    epoch 032/100 | train_mse=0.02298474 | val_mse=0.05165252 | best_val_mse=0.05165252 | early_stop=00/10 | 1.8s
    epoch 033/100 | train_mse=0.02294593 | val_mse=0.05162968 | best_val_mse=0.05162968 | early_stop=00/10 | 1.8s
    epoch 034/100 | train_mse=0.02292920 | val_mse=0.05204757 | best_val_mse=0.05162968 | early_stop=01/10 | 1.8s
    epoch 035/100 | train_mse=0.02303888 | val_mse=0.05171470 | best_val_mse=0.05162968 | early_stop=02/10 | 1.8s
    epoch 036/100 | train_mse=0.02291258 | val_mse=0.05168315 | best_val_mse=0.05162968 | early_stop=03/10 | 1.8s
    epoch 037/100 | train_mse=0.02287849 | val_mse=0.05166661 | best_val_mse=0.05162968 | early_stop=04/10 | 1.8s
    epoch 038/100 | train_mse=0.02291411 | val_mse=0.05158607 | best_val_mse=0.05158607 | early_stop=00/10 | 1.8s
    epoch 039/100 | train_mse=0.02287003 | val_mse=0.05163253 | best_val_mse=0.05158607 | early_stop=01/10 | 1.8s
    epoch 040/100 | train_mse=0.02284996 | val_mse=0.05161891 | best_val_mse=0.05158607 | early_stop=02/10 | 1.8s
    epoch 041/100 | train_mse=0.02283782 | val_mse=0.05178471 | best_val_mse=0.05158607 | early_stop=03/10 | 1.8s
    epoch 042/100 | train_mse=0.02287302 | val_mse=0.05157692 | best_val_mse=0.05157692 | early_stop=00/10 | 1.8s
    epoch 043/100 | train_mse=0.02284667 | val_mse=0.05155034 | best_val_mse=0.05155034 | early_stop=00/10 | 1.8s
    epoch 044/100 | train_mse=0.02276738 | val_mse=0.05159782 | best_val_mse=0.05155034 | early_stop=01/10 | 1.8s
    epoch 045/100 | train_mse=0.02274455 | val_mse=0.05181445 | best_val_mse=0.05155034 | early_stop=02/10 | 1.8s
    epoch 046/100 | train_mse=0.02274784 | val_mse=0.05159703 | best_val_mse=0.05155034 | early_stop=03/10 | 1.8s
    epoch 047/100 | train_mse=0.02282197 | val_mse=0.05155277 | best_val_mse=0.05155034 | early_stop=04/10 | 1.8s
    epoch 048/100 | train_mse=0.02280653 | val_mse=0.05166547 | best_val_mse=0.05155034 | early_stop=05/10 | 1.8s
    epoch 049/100 | train_mse=0.02267890 | val_mse=0.05170178 | best_val_mse=0.05155034 | early_stop=06/10 | 1.8s
    epoch 050/100 | train_mse=0.02267333 | val_mse=0.05156183 | best_val_mse=0.05155034 | early_stop=07/10 | 1.8s
    epoch 051/100 | train_mse=0.02275825 | val_mse=0.05158879 | best_val_mse=0.05155034 | early_stop=08/10 | 1.8s

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02262973 | val_mse=0.02423941 | best_val_mse=0.02423941 | early_stop=00/10 | 1.4s
    epoch 002/100 | train_mse=0.02244136 | val_mse=0.02411871 | best_val_mse=0.02411871 | early_stop=00/10 | 1.4s
    epoch 003/100 | train_mse=0.02237749 | val_mse=0.02403725 | best_val_mse=0.02403725 | early_stop=00/10 | 1.4s
    epoch 004/100 | train_mse=0.02236861 | val_mse=0.02414176 | best_val_mse=0.02403725 | early_stop=01/10 | 1.4s
    epoch 005/100 | train_mse=0.02234328 | val_mse=0.02405427 | best_val_mse=0.02403725 | early_stop=02/10 | 1.4s
    epoch 006/100 | train_mse=0.02229313 | val_mse=0.02393028 | best_val_mse=0.02393028 | early_stop=00/10 | 1.4s
    epoch 007/100 | train_mse=0.02231871 | val_mse=0.02392097 | best_val_mse=0.02392097 | early_stop=00/10 | 1.4s
    epoch 008/100 | train_mse=0.02231310 | val_mse=0.02389111 | best_val_mse=0.02389111 | early_stop=00/10 | 1.4s
    epoch 009/100 | train_mse=0.02230357 | val_mse=0.02403970 | best_val_mse=0.02389111 | early_stop=01/10 | 1.4s
    epoch 010/100 | train_mse=0.02226881 | val_mse=0.02396186 | best_val_mse=0.02389111 | early_stop=02/10 | 1.4s
    epoch 011/100 | train_mse=0.02226077 | val_mse=0.02406483 | best_val_mse=0.02389111 | early_stop=03/10 | 1.4s
    epoch 012/100 | train_mse=0.02228016 | val_mse=0.02398075 | best_val_mse=0.02389111 | early_stop=04/10 | 1.4s
    epoch 013/100 | train_mse=0.02225712 | val_mse=0.02394145 | best_val_mse=0.02389111 | early_stop=05/10 | 1.4s
    epoch 014/100 | train_mse=0.02223725 | val_mse=0.02386799 | best_val_mse=0.02386799 | early_stop=00/10 | 1.4s
    epoch 015/100 | train_mse=0.02224418 | val_mse=0.02420259 | best_val_mse=0.02386799 | early_stop=01/10 | 1.4s
    epoch 016/100 | train_mse=0.02223443 | val_mse=0.02392410 | best_val_mse=0.02386799 | early_stop=02/10 | 1.4s
    epoch 017/100 | train_mse=0.02225142 | val_mse=0.02406298 | best_val_mse=0.02386799 | early_stop=03/10 | 1.5s
    epoch 018/100 | train_mse=0.02222513 | val_mse=0.02389768 | best_val_mse=0.02386799 | early_stop=04/10 | 1.4s
    epoch 019/100 | train_mse=0.02221794 | val_mse=0.02403031 | best_val_mse=0.02386799 | early_stop=05/10 | 1.4s
    epoch 020/100 | train_mse=0.02223201 | val_mse=0.02393161 | best_val_mse=0.02386799 | early_stop=06/10 | 1.4s
    epoch 021/100 | train_mse=0.02220948 | val_mse=0.02400011 | best_val_mse=0.02386799 | early_stop=07/10 | 1.5s
    epoch 022/100 | train_mse=0.02220290 | val_mse=0.02389794 | best_val_mse=0.02386799 | early_stop=08/10 | 1.5s
    epoch 023/100 | train_mse=0.02223560 | val_mse=0.02390005 | best_val_mse=0.02386799 | early_stop=09/10 | 1.4s
    epoch 024/100 | train_mse=0.02224133 | val_mse=0.02402962 | best_val_mse=0.02386799 | early_stop=10/10 | 1.4s
  refit 01/26 | test_year=1999 | status=saved | n_predictions=76,150
  refit 02/26 | test_year=2000 | status=training | train_n=893,802 | validation_n=313,546 | test_n=75,345

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02251642 | val_mse=0.03017240 | best_val_mse=0.03017240 | early_stop=00/10 | 1.4s
    epoch 002/100 | train_mse=0.02238712 | val_mse=0.03014401 | best_val_mse=0.03014401 | early_stop=00/10 | 1.5s
    epoch 003/100 | train_mse=0.02231027 | val_mse=0.03009150 | best_val_mse=0.03009150 | early_stop=00/10 | 1.4s
    epoch 004/100 | train_mse=0.02225045 | val_mse=0.03014038 | best_val_mse=0.03009150 | early_stop=01/10 | 1.5s
    epoch 005/100 | train_mse=0.02230536 | val_mse=0.03011235 | best_val_mse=0.03009150 | early_stop=02/10 | 1.5s
    epoch 006/100 | train_mse=0.02221583 | val_mse=0.03006889 | best_val_mse=0.03006889 | early_stop=00/10 | 1.5s
    epoch 007/100 | train_mse=0.02221761 | val_mse=0.03002922 | best_val_mse=0.03002922 | early_stop=00/10 | 1.4s
    epoch 008/100 | train_mse=0.02219261 | val_mse=0.03004135 | best_val_mse=0.03002922 | early_stop=01/10 | 1.4s
    epoch 009/100 | train_mse=0.02220608 | val_mse=0.03005928 | best_val_mse=0.03002922 | early_stop=02/10 | 1.4s
    epoch 010/100 | train_mse=0.02216223 | val_mse=0.02999554 | best_val_mse=0.02999554 | early_stop=00/10 | 1.5s
    epoch 011/100 | train_mse=0.02215255 | val_mse=0.03001717 | best_val_mse=0.02999554 | early_stop=01/10 | 1.4s
    epoch 012/100 | train_mse=0.02215312 | val_mse=0.03001716 | best_val_mse=0.02999554 | early_stop=02/10 | 1.4s
    epoch 013/100 | train_mse=0.02215366 | val_mse=0.02998976 | best_val_mse=0.02998976 | early_stop=00/10 | 1.5s
    epoch 014/100 | train_mse=0.02215505 | val_mse=0.02999037 | best_val_mse=0.02998976 | early_stop=01/10 | 1.4s
    epoch 015/100 | train_mse=0.02217579 | val_mse=0.02999833 | best_val_mse=0.02998976 | early_stop=02/10 | 1.4s
    epoch 016/100 | train_mse=0.02213215 | val_mse=0.02998531 | best_val_mse=0.02998531 | early_stop=00/10 | 1.4s
    epoch 017/100 | train_mse=0.02214590 | val_mse=0.02998511 | best_val_mse=0.02998511 | early_stop=00/10 | 1.4s
    epoch 018/100 | train_mse=0.02217134 | val_mse=0.02998244 | best_val_mse=0.02998244 | early_stop=00/10 | 1.5s
    epoch 019/100 | train_mse=0.02214049 | val_mse=0.03002956 | best_val_mse=0.02998244 | early_stop=01/10 | 1.4s
    epoch 020/100 | train_mse=0.02213165 | val_mse=0.02998925 | best_val_mse=0.02998244 | early_stop=02/10 | 1.4s
    epoch 021/100 | train_mse=0.02213411 | val_mse=0.02999442 | best_val_mse=0.02998244 | early_stop=03/10 | 1.4s
    epoch 022/100 | train_mse=0.02210609 | val_mse=0.02998666 | best_val_mse=0.02998244 | early_stop=04/10 | 1.4s
    epoch 023/100 | train_mse=0.02212184 | val_mse=0.02998059 | best_val_mse=0.02998059 | early_stop=00/10 | 1.5s
    epoch 024/100 | train_mse=0.02211245 | val_mse=0.03002561 | best_val_mse=0.02998059 | early_stop=01/10 | 1.4s
    epoch 025/100 | train_mse=0.02209870 | val_mse=0.02997279 | best_val_mse=0.02997279 | early_stop=00/10 | 1.4s
    epoch 026/100 | train_mse=0.02210678 | val_mse=0.02998841 | best_val_mse=0.02997279 | early_stop=01/10 | 1.4s
    epoch 027/100 | train_mse=0.02212140 | val_mse=0.03008295 | best_val_mse=0.02997279 | early_stop=02/10 | 1.4s
    epoch 028/100 | train_mse=0.02214395 | val_mse=0.03003534 | best_val_mse=0.02997279 | early_stop=03/10 | 1.4s
    epoch 029/100 | train_mse=0.02210819 | val_mse=0.02997576 | best_val_mse=0.02997279 | early_stop=04/10 | 1.4s
    epoch 030/100 | train_mse=0.02211027 | val_mse=0.02999203 | best_val_mse=0.02997279 | early_stop=05/10 | 1.4s
    epoch 031/100 | train_mse=0.02205340 | val_mse=0.03009480 | best_val_mse=0.02997279 | early_stop=06/10 | 1.4s
    epoch 032/100 | train_mse=0.02213397 | val_mse=0.03001716 | best_val_mse=0.02997279 | early_stop=07/10 | 1.4s
    epoch 033/100 | train_mse=0.02208303 | val_mse=0.02997135 | best_val_mse=0.02997135 | early_stop=00/10 | 1.4s
    epoch 034/100 | train_mse=0.02207479 | val_mse=0.02998314 | best_val_mse=0.02997135 | early_stop=01/10 | 1.4s
    epoch 035/100 | train_mse=0.02208988 | val_mse=0.02997081 | best_val_mse=0.02997081 | early_stop=00/10 | 1.4s
    epoch 036/100 | train_mse=0.02207949 | val_mse=0.02997799 | best_val_mse=0.02997081 | early_stop=01/10 | 1.4s
    epoch 037/100 | train_mse=0.02207585 | val_mse=0.02995699 | best_val_mse=0.02995699 | early_stop=00/10 | 1.4s
    epoch 038/100 | train_mse=0.02209166 | val_mse=0.02995790 | best_val_mse=0.02995699 | early_stop=01/10 | 1.4s
    epoch 039/100 | train_mse=0.02208954 | val_mse=0.02995317 | best_val_mse=0.02995317 | early_stop=00/10 | 1.4s
    epoch 040/100 | train_mse=0.02207404 | val_mse=0.02996861 | best_val_mse=0.02995317 | early_stop=01/10 | 1.4s
    epoch 041/100 | train_mse=0.02205752 | val_mse=0.02996119 | best_val_mse=0.02995317 | early_stop=02/10 | 1.4s
    epoch 042/100 | train_mse=0.02204382 | val_mse=0.02996039 | best_val_mse=0.02995317 | early_stop=03/10 | 1.4s
    epoch 043/100 | train_mse=0.02207156 | val_mse=0.02996289 | best_val_mse=0.02995317 | early_stop=04/10 | 1.4s
    epoch 044/100 | train_mse=0.02210893 | val_mse=0.02994242 | best_val_mse=0.02994242 | early_stop=00/10 | 1.4s
    epoch 045/100 | train_mse=0.02205119 | val_mse=0.03000475 | best_val_mse=0.02994242 | early_stop=01/10 | 1.4s
    epoch 046/100 | train_mse=0.02205718 | val_mse=0.03003218 | best_val_mse=0.02994242 | early_stop=02/10 | 1.4s
    epoch 047/100 | train_mse=0.02205970 | val_mse=0.02995438 | best_val_mse=0.02994242 | early_stop=03/10 | 1.4s
    epoch 048/100 | train_mse=0.02203428 | val_mse=0.02999358 | best_val_mse=0.02994242 | early_stop=04/10 | 1.4s
    epoch 049/100 | train_mse=0.02206200 | val_mse=0.02999388 | best_val_mse=0.02994242 | early_stop=05/10 | 1.4s
    epoch 050/100 | train_mse=0.02204757 | val_mse=0.03000912 | best_val_mse=0.02994242 | early_stop=06/10 | 1.4s
    epoch 051/100 | train_mse=0.02206106 | val_mse=0.02991317 | best_val_mse=0.02991317 | early_stop=00/10 | 1.4s
    epoch 052/100 | train_mse=0.02200639 | val_mse=0.03010497 | best_val_mse=0.02991317 | early_stop=01/10 | 1.4s
    epoch 053/100 | train_mse=0.02206158 | val_mse=0.02990184 | best_val_mse=0.02990184 | early_stop=00/10 | 1.4s
    epoch 054/100 | train_mse=0.02199125 | val_mse=0.02995340 | best_val_mse=0.02990184 | early_stop=01/10 | 1.4s
    epoch 055/100 | train_mse=0.02202283 | val_mse=0.02992195 | best_val_mse=0.02990184 | early_stop=02/10 | 1.4s
    epoch 056/100 | train_mse=0.02196242 | val_mse=0.02987285 | best_val_mse=0.02987285 | early_stop=00/10 | 1.5s
    epoch 057/100 | train_mse=0.02204440 | val_mse=0.02985579 | best_val_mse=0.02985579 | early_stop=00/10 | 1.4s
    epoch 058/100 | train_mse=0.02197095 | val_mse=0.02985239 | best_val_mse=0.02985239 | early_stop=00/10 | 1.4s
    epoch 059/100 | train_mse=0.02197453 | val_mse=0.02990987 | best_val_mse=0.02985239 | early_stop=01/10 | 1.4s
    epoch 060/100 | train_mse=0.02200420 | val_mse=0.02982367 | best_val_mse=0.02982367 | early_stop=00/10 | 1.4s
    epoch 061/100 | train_mse=0.02193189 | val_mse=0.03005967 | best_val_mse=0.02982367 | early_stop=01/10 | 1.4s
    epoch 062/100 | train_mse=0.02196747 | val_mse=0.02978352 | best_val_mse=0.02978352 | early_stop=00/10 | 1.4s
    epoch 063/100 | train_mse=0.02196602 | val_mse=0.02979605 | best_val_mse=0.02978352 | early_stop=01/10 | 1.4s
    epoch 064/100 | train_mse=0.02195162 | val_mse=0.02978464 | best_val_mse=0.02978352 | early_stop=02/10 | 1.4s
    epoch 065/100 | train_mse=0.02195244 | val_mse=0.02975906 | best_val_mse=0.02975906 | early_stop=00/10 | 1.4s
    epoch 066/100 | train_mse=0.02191903 | val_mse=0.02978039 | best_val_mse=0.02975906 | early_stop=01/10 | 1.5s
    epoch 067/100 | train_mse=0.02189961 | val_mse=0.02973463 | best_val_mse=0.02973463 | early_stop=00/10 | 1.4s
    epoch 068/100 | train_mse=0.02203538 | val_mse=0.02980030 | best_val_mse=0.02973463 | early_stop=01/10 | 1.4s
    epoch 069/100 | train_mse=0.02188676 | val_mse=0.02984548 | best_val_mse=0.02973463 | early_stop=02/10 | 1.4s
    epoch 070/100 | train_mse=0.02189646 | val_mse=0.02968890 | best_val_mse=0.02968890 | early_stop=00/10 | 1.5s
    epoch 071/100 | train_mse=0.02188859 | val_mse=0.02970426 | best_val_mse=0.02968890 | early_stop=01/10 | 1.4s
    epoch 072/100 | train_mse=0.02183571 | val_mse=0.02962955 | best_val_mse=0.02962955 | early_stop=00/10 | 1.4s
    epoch 073/100 | train_mse=0.02184127 | val_mse=0.02962616 | best_val_mse=0.02962616 | early_stop=00/10 | 1.4s
    epoch 074/100 | train_mse=0.02183891 | val_mse=0.02959131 | best_val_mse=0.02959131 | early_stop=00/10 | 1.5s
    epoch 075/100 | train_mse=0.02181956 | val_mse=0.02964201 | best_val_mse=0.02959131 | early_stop=01/10 | 1.4s
    epoch 076/100 | train_mse=0.02202953 | val_mse=0.03019409 | best_val_mse=0.02959131 | early_stop=02/10 | 1.4s
    epoch 077/100 | train_mse=0.02178210 | val_mse=0.02972092 | best_val_mse=0.02959131 | early_stop=03/10 | 1.4s
    epoch 078/100 | train_mse=0.02189785 | val_mse=0.02991558 | best_val_mse=0.02959131 | early_stop=04/10 | 1.4s
    epoch 079/100 | train_mse=0.02187935 | val_mse=0.02968573 | best_val_mse=0.02959131 | early_stop=05/10 | 1.4s
    epoch 080/100 | train_mse=0.02178784 | val_mse=0.02956589 | best_val_mse=0.02956589 | early_stop=00/10 | 1.4s
    epoch 081/100 | train_mse=0.02194123 | val_mse=0.02978892 | best_val_mse=0.02956589 | early_stop=01/10 | 1.4s
    epoch 082/100 | train_mse=0.02185845 | val_mse=0.02961879 | best_val_mse=0.02956589 | early_stop=02/10 | 1.4s
    epoch 083/100 | train_mse=0.02176184 | val_mse=0.02955736 | best_val_mse=0.02955736 | early_stop=00/10 | 1.5s
    epoch 084/100 | train_mse=0.02176753 | val_mse=0.02953667 | best_val_mse=0.02953667 | early_stop=00/10 | 1.5s
    epoch 085/100 | train_mse=0.02177164 | val_mse=0.02957522 | best_val_mse=0.02953667 | early_stop=01/10 | 1.4s
    epoch 086/100 | train_mse=0.02179832 | val_mse=0.02956823 | best_val_mse=0.02953667 | early_stop=02/10 | 1.4s
    epoch 087/100 | train_mse=0.02185027 | val_mse=0.02967010 | best_val_mse=0.02953667 | early_stop=03/10 | 1.4s
    epoch 088/100 | train_mse=0.02171876 | val_mse=0.02954922 | best_val_mse=0.02953667 | early_stop=04/10 | 1.4s
    epoch 089/100 | train_mse=0.02171782 | val_mse=0.02954628 | best_val_mse=0.02953667 | early_stop=05/10 | 1.4s
    epoch 090/100 | train_mse=0.02172607 | val_mse=0.02956210 | best_val_mse=0.02953667 | early_stop=06/10 | 1.4s
    epoch 091/100 | train_mse=0.02172848 | val_mse=0.02970790 | best_val_mse=0.02953667 | early_stop=07/10 | 1.5s
    epoch 092/100 | train_mse=0.02168446 | val_mse=0.02999325 | best_val_mse=0.02953667 | early_stop=08/10 | 1.5s
    epoch 093/100 | train_mse=0.02175023 | val_mse=0.02968904 | best_val_mse=0.02953667 | early_stop=09/10 | 1.4s
    epoch 094/100 | train_mse=0.02174272 | val_mse=0.02972158 | best_val_mse=0.02953667 | early_stop=10/10 | 1.4s
  refit 02/26 | test_year=2000 | status=saved | n_predictions=75,345
  refit 03/26 | test_year=2001 | status=training | train_n=928,527 | validation_n=309,376 | test_n=69,652

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02336071 | val_mse=0.03733669 | best_val_mse=0.03733669 | early_stop=00/10 | 1.4s
    epoch 002/100 | train_mse=0.02313194 | val_mse=0.03732110 | best_val_mse=0.03732110 | early_stop=00/10 | 1.4s
    epoch 003/100 | train_mse=0.02315676 | val_mse=0.03727832 | best_val_mse=0.03727832 | early_stop=00/10 | 1.4s
    epoch 004/100 | train_mse=0.02306193 | val_mse=0.03728635 | best_val_mse=0.03727832 | early_stop=01/10 | 1.4s
    epoch 005/100 | train_mse=0.02308013 | val_mse=0.03724790 | best_val_mse=0.03724790 | early_stop=00/10 | 1.4s
    epoch 006/100 | train_mse=0.02304366 | val_mse=0.03727184 | best_val_mse=0.03724790 | early_stop=01/10 | 1.4s
    epoch 007/100 | train_mse=0.02301316 | val_mse=0.03731491 | best_val_mse=0.03724790 | early_stop=02/10 | 1.4s
    epoch 008/100 | train_mse=0.02305074 | val_mse=0.03720123 | best_val_mse=0.03720123 | early_stop=00/10 | 1.5s
    epoch 009/100 | train_mse=0.02302174 | val_mse=0.03721977 | best_val_mse=0.03720123 | early_stop=01/10 | 1.4s
    epoch 010/100 | train_mse=0.02299315 | val_mse=0.03718687 | best_val_mse=0.03718687 | early_stop=00/10 | 1.4s
    epoch 011/100 | train_mse=0.02304976 | val_mse=0.03719596 | best_val_mse=0.03718687 | early_stop=01/10 | 1.4s
    epoch 012/100 | train_mse=0.02297138 | val_mse=0.03717418 | best_val_mse=0.03717418 | early_stop=00/10 | 1.5s
    epoch 013/100 | train_mse=0.02295972 | val_mse=0.03715843 | best_val_mse=0.03715843 | early_stop=00/10 | 1.4s
    epoch 014/100 | train_mse=0.02298900 | val_mse=0.03723591 | best_val_mse=0.03715843 | early_stop=01/10 | 1.4s
    epoch 015/100 | train_mse=0.02299667 | val_mse=0.03717832 | best_val_mse=0.03715843 | early_stop=02/10 | 1.4s
    epoch 016/100 | train_mse=0.02295129 | val_mse=0.03721971 | best_val_mse=0.03715843 | early_stop=03/10 | 1.4s
    epoch 017/100 | train_mse=0.02294065 | val_mse=0.03717205 | best_val_mse=0.03715843 | early_stop=04/10 | 1.4s
    epoch 018/100 | train_mse=0.02293609 | val_mse=0.03716924 | best_val_mse=0.03715843 | early_stop=05/10 | 1.4s
    epoch 019/100 | train_mse=0.02294369 | val_mse=0.03716256 | best_val_mse=0.03715843 | early_stop=06/10 | 1.4s
    epoch 020/100 | train_mse=0.02293484 | val_mse=0.03715106 | best_val_mse=0.03715106 | early_stop=00/10 | 1.5s
    epoch 021/100 | train_mse=0.02295294 | val_mse=0.03715249 | best_val_mse=0.03715106 | early_stop=01/10 | 1.4s
    epoch 022/100 | train_mse=0.02293745 | val_mse=0.03716497 | best_val_mse=0.03715106 | early_stop=02/10 | 1.4s
    epoch 023/100 | train_mse=0.02295783 | val_mse=0.03718458 | best_val_mse=0.03715106 | early_stop=03/10 | 1.4s
    epoch 024/100 | train_mse=0.02295836 | val_mse=0.03720641 | best_val_mse=0.03715106 | early_stop=04/10 | 1.4s
    epoch 025/100 | train_mse=0.02291141 | val_mse=0.03714834 | best_val_mse=0.03714834 | early_stop=00/10 | 1.5s
    epoch 026/100 | train_mse=0.02294228 | val_mse=0.03713392 | best_val_mse=0.03713392 | early_stop=00/10 | 1.4s
    epoch 027/100 | train_mse=0.02291453 | val_mse=0.03724721 | best_val_mse=0.03713392 | early_stop=01/10 | 1.4s
    epoch 028/100 | train_mse=0.02292564 | val_mse=0.03714899 | best_val_mse=0.03713392 | early_stop=02/10 | 1.4s
    epoch 029/100 | train_mse=0.02295355 | val_mse=0.03717878 | best_val_mse=0.03713392 | early_stop=03/10 | 1.4s
    epoch 030/100 | train_mse=0.02292665 | val_mse=0.03718074 | best_val_mse=0.03713392 | early_stop=04/10 | 1.5s
    epoch 031/100 | train_mse=0.02290962 | val_mse=0.03714562 | best_val_mse=0.03713392 | early_stop=05/10 | 1.4s
    epoch 032/100 | train_mse=0.02290216 | val_mse=0.03713335 | best_val_mse=0.03713335 | early_stop=00/10 | 1.5s
    epoch 033/100 | train_mse=0.02289085 | val_mse=0.03716456 | best_val_mse=0.03713335 | early_stop=01/10 | 1.5s
    epoch 034/100 | train_mse=0.02288370 | val_mse=0.03714534 | best_val_mse=0.03713335 | early_stop=02/10 | 1.4s
    epoch 035/100 | train_mse=0.02288175 | val_mse=0.03717233 | best_val_mse=0.03713335 | early_stop=03/10 | 1.5s
    epoch 036/100 | train_mse=0.02292223 | val_mse=0.03714293 | best_val_mse=0.03713335 | early_stop=04/10 | 1.5s
    epoch 037/100 | train_mse=0.02290053 | val_mse=0.03718828 | best_val_mse=0.03713335 | early_stop=05/10 | 1.4s
    epoch 038/100 | train_mse=0.02291112 | val_mse=0.03717052 | best_val_mse=0.03713335 | early_stop=06/10 | 1.4s
    epoch 039/100 | train_mse=0.02287788 | val_mse=0.03713479 | best_val_mse=0.03713335 | early_stop=07/10 | 1.4s
    epoch 040/100 | train_mse=0.02289482 | val_mse=0.03714295 | best_val_mse=0.03713335 | early_stop=08/10 | 1.4s
    epoch 041/100 | train_mse=0.02286399 | val_mse=0.03711369 | best_val_mse=0.03711369 | early_stop=00/10 | 1.5s
    epoch 042/100 | train_mse=0.02287902 | val_mse=0.03710878 | best_val_mse=0.03710878 | early_stop=00/10 | 1.5s
    epoch 043/100 | train_mse=0.02287302 | val_mse=0.03716995 | best_val_mse=0.03710878 | early_stop=01/10 | 1.4s
    epoch 044/100 | train_mse=0.02285857 | val_mse=0.03713499 | best_val_mse=0.03710878 | early_stop=02/10 | 1.4s
    epoch 045/100 | train_mse=0.02289138 | val_mse=0.03717508 | best_val_mse=0.03710878 | early_stop=03/10 | 1.4s
    epoch 046/100 | train_mse=0.02293638 | val_mse=0.03717174 | best_val_mse=0.03710878 | early_stop=04/10 | 1.5s
    epoch 047/100 | train_mse=0.02286528 | val_mse=0.03718602 | best_val_mse=0.03710878 | early_stop=05/10 | 1.5s
    epoch 048/100 | train_mse=0.02289480 | val_mse=0.03710422 | best_val_mse=0.03710422 | early_stop=00/10 | 1.4s
    epoch 049/100 | train_mse=0.02282612 | val_mse=0.03710230 | best_val_mse=0.03710230 | early_stop=00/10 | 1.5s
    epoch 050/100 | train_mse=0.02286667 | val_mse=0.03705305 | best_val_mse=0.03705305 | early_stop=00/10 | 1.5s
    epoch 051/100 | train_mse=0.02283768 | val_mse=0.03708209 | best_val_mse=0.03705305 | early_stop=01/10 | 1.4s
    epoch 052/100 | train_mse=0.02292739 | val_mse=0.03719975 | best_val_mse=0.03705305 | early_stop=02/10 | 1.4s
    epoch 053/100 | train_mse=0.02283291 | val_mse=0.03709167 | best_val_mse=0.03705305 | early_stop=03/10 | 1.4s
    epoch 054/100 | train_mse=0.02285446 | val_mse=0.03708344 | best_val_mse=0.03705305 | early_stop=04/10 | 1.5s
    epoch 055/100 | train_mse=0.02287409 | val_mse=0.03707620 | best_val_mse=0.03705305 | early_stop=05/10 | 1.4s
    epoch 056/100 | train_mse=0.02282224 | val_mse=0.03707003 | best_val_mse=0.03705305 | early_stop=06/10 | 1.5s
    epoch 057/100 | train_mse=0.02282815 | val_mse=0.03706088 | best_val_mse=0.03705305 | early_stop=07/10 | 1.5s
    epoch 058/100 | train_mse=0.02282374 | val_mse=0.03705155 | best_val_mse=0.03705155 | early_stop=00/10 | 1.4s
    epoch 059/100 | train_mse=0.02284195 | val_mse=0.03703128 | best_val_mse=0.03703128 | early_stop=00/10 | 1.5s
    epoch 060/100 | train_mse=0.02282907 | val_mse=0.03700286 | best_val_mse=0.03700286 | early_stop=00/10 | 1.4s
    epoch 061/100 | train_mse=0.02285426 | val_mse=0.03699927 | best_val_mse=0.03699927 | early_stop=00/10 | 1.4s
    epoch 062/100 | train_mse=0.02277229 | val_mse=0.03722972 | best_val_mse=0.03699927 | early_stop=01/10 | 1.4s
    epoch 063/100 | train_mse=0.02286008 | val_mse=0.03700171 | best_val_mse=0.03699927 | early_stop=02/10 | 1.4s
    epoch 064/100 | train_mse=0.02282183 | val_mse=0.03695579 | best_val_mse=0.03695579 | early_stop=00/10 | 1.5s
    epoch 065/100 | train_mse=0.02270300 | val_mse=0.03739491 | best_val_mse=0.03695579 | early_stop=01/10 | 1.4s
    epoch 066/100 | train_mse=0.02288338 | val_mse=0.03699115 | best_val_mse=0.03695579 | early_stop=02/10 | 1.5s
    epoch 067/100 | train_mse=0.02277727 | val_mse=0.03701701 | best_val_mse=0.03695579 | early_stop=03/10 | 1.4s
    epoch 068/100 | train_mse=0.02278015 | val_mse=0.03701994 | best_val_mse=0.03695579 | early_stop=04/10 | 1.4s
    epoch 069/100 | train_mse=0.02275359 | val_mse=0.03696047 | best_val_mse=0.03695579 | early_stop=05/10 | 1.4s
    epoch 070/100 | train_mse=0.02276696 | val_mse=0.03702944 | best_val_mse=0.03695579 | early_stop=06/10 | 1.5s
    epoch 071/100 | train_mse=0.02280070 | val_mse=0.03700573 | best_val_mse=0.03695579 | early_stop=07/10 | 1.4s
    epoch 072/100 | train_mse=0.02267571 | val_mse=0.03716591 | best_val_mse=0.03695579 | early_stop=08/10 | 1.4s
    epoch 073/100 | train_mse=0.02274892 | val_mse=0.03687611 | best_val_mse=0.03687611 | early_stop=00/10 | 1.4s
    epoch 074/100 | train_mse=0.02272378 | val_mse=0.03684166 | best_val_mse=0.03684166 | early_stop=00/10 | 1.4s
    epoch 075/100 | train_mse=0.02280051 | val_mse=0.03688256 | best_val_mse=0.03684166 | early_stop=01/10 | 1.5s
    epoch 076/100 | train_mse=0.02272454 | val_mse=0.03684790 | best_val_mse=0.03684166 | early_stop=02/10 | 1.5s
    epoch 077/100 | train_mse=0.02268975 | val_mse=0.03684597 | best_val_mse=0.03684166 | early_stop=03/10 | 1.4s
    epoch 078/100 | train_mse=0.02275892 | val_mse=0.03688925 | best_val_mse=0.03684166 | early_stop=04/10 | 1.4s
    epoch 079/100 | train_mse=0.02266871 | val_mse=0.03678911 | best_val_mse=0.03678911 | early_stop=00/10 | 1.5s
    epoch 080/100 | train_mse=0.02262583 | val_mse=0.03682726 | best_val_mse=0.03678911 | early_stop=01/10 | 1.4s
    epoch 081/100 | train_mse=0.02269988 | val_mse=0.03682205 | best_val_mse=0.03678911 | early_stop=02/10 | 1.4s
    epoch 082/100 | train_mse=0.02269137 | val_mse=0.03678703 | best_val_mse=0.03678703 | early_stop=00/10 | 1.5s
    epoch 083/100 | train_mse=0.02264215 | val_mse=0.03670671 | best_val_mse=0.03670671 | early_stop=00/10 | 1.4s
    epoch 084/100 | train_mse=0.02266095 | val_mse=0.03673846 | best_val_mse=0.03670671 | early_stop=01/10 | 1.5s
    epoch 085/100 | train_mse=0.02266977 | val_mse=0.03669694 | best_val_mse=0.03669694 | early_stop=00/10 | 1.5s
    epoch 086/100 | train_mse=0.02261024 | val_mse=0.03678901 | best_val_mse=0.03669694 | early_stop=01/10 | 1.4s
    epoch 087/100 | train_mse=0.02271659 | val_mse=0.03671658 | best_val_mse=0.03669694 | early_stop=02/10 | 1.4s
    epoch 088/100 | train_mse=0.02264793 | val_mse=0.03667206 | best_val_mse=0.03667206 | early_stop=00/10 | 1.4s
    epoch 089/100 | train_mse=0.02264567 | val_mse=0.03669370 | best_val_mse=0.03667206 | early_stop=01/10 | 1.4s
    epoch 090/100 | train_mse=0.02267722 | val_mse=0.03674705 | best_val_mse=0.03667206 | early_stop=02/10 | 1.4s
    epoch 091/100 | train_mse=0.02264633 | val_mse=0.03741818 | best_val_mse=0.03667206 | early_stop=03/10 | 1.4s
    epoch 092/100 | train_mse=0.02271842 | val_mse=0.03673218 | best_val_mse=0.03667206 | early_stop=04/10 | 1.5s
    epoch 093/100 | train_mse=0.02261127 | val_mse=0.03670496 | best_val_mse=0.03667206 | early_stop=05/10 | 1.5s
    epoch 094/100 | train_mse=0.02265279 | val_mse=0.03666224 | best_val_mse=0.03666224 | early_stop=00/10 | 1.4s
    epoch 095/100 | train_mse=0.02266213 | val_mse=0.03665979 | best_val_mse=0.03665979 | early_stop=00/10 | 1.4s
    epoch 096/100 | train_mse=0.02255122 | val_mse=0.03670251 | best_val_mse=0.03665979 | early_stop=01/10 | 1.4s
    epoch 097/100 | train_mse=0.02261482 | val_mse=0.03682379 | best_val_mse=0.03665979 | early_stop=02/10 | 1.4s
    epoch 098/100 | train_mse=0.02260903 | val_mse=0.03665586 | best_val_mse=0.03665586 | early_stop=00/10 | 1.5s
    epoch 099/100 | train_mse=0.02256266 | val_mse=0.03676524 | best_val_mse=0.03665586 | early_stop=01/10 | 1.4s
    epoch 100/100 | train_mse=0.02252916 | val_mse=0.03669758 | best_val_mse=0.03665586 | early_stop=02/10 | 1.5s
  refit 03/26 | test_year=2001 | status=saved | n_predictions=69,652
  refit 04/26 | test_year=2002 | status=training | train_n=965,790 | validation_n=297,051 | test_n=58,995

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02351634 | val_mse=0.05369739 | best_val_mse=0.05369739 | early_stop=00/10 | 1.4s
    epoch 002/100 | train_mse=0.02337415 | val_mse=0.05369896 | best_val_mse=0.05369739 | early_stop=01/10 | 1.5s
    epoch 003/100 | train_mse=0.02323872 | val_mse=0.05370816 | best_val_mse=0.05369739 | early_stop=02/10 | 1.5s
    epoch 004/100 | train_mse=0.02327107 | val_mse=0.05364046 | best_val_mse=0.05364046 | early_stop=00/10 | 1.5s
    epoch 005/100 | train_mse=0.02324066 | val_mse=0.05363883 | best_val_mse=0.05363883 | early_stop=00/10 | 1.4s
    epoch 006/100 | train_mse=0.02326132 | val_mse=0.05363038 | best_val_mse=0.05363038 | early_stop=00/10 | 1.5s
    epoch 007/100 | train_mse=0.02319872 | val_mse=0.05359795 | best_val_mse=0.05359795 | early_stop=00/10 | 1.5s
    epoch 008/100 | train_mse=0.02320563 | val_mse=0.05363430 | best_val_mse=0.05359795 | early_stop=01/10 | 1.4s
    epoch 009/100 | train_mse=0.02318954 | val_mse=0.05358481 | best_val_mse=0.05358481 | early_stop=00/10 | 1.5s
    epoch 010/100 | train_mse=0.02314197 | val_mse=0.05357195 | best_val_mse=0.05357195 | early_stop=00/10 | 1.5s
    epoch 011/100 | train_mse=0.02317802 | val_mse=0.05357115 | best_val_mse=0.05357115 | early_stop=00/10 | 1.5s
    epoch 012/100 | train_mse=0.02317244 | val_mse=0.05355991 | best_val_mse=0.05355991 | early_stop=00/10 | 1.5s
    epoch 013/100 | train_mse=0.02316315 | val_mse=0.05355599 | best_val_mse=0.05355599 | early_stop=00/10 | 1.5s
    epoch 014/100 | train_mse=0.02313862 | val_mse=0.05355796 | best_val_mse=0.05355599 | early_stop=01/10 | 1.5s
    epoch 015/100 | train_mse=0.02317123 | val_mse=0.05357835 | best_val_mse=0.05355599 | early_stop=02/10 | 1.5s
    epoch 016/100 | train_mse=0.02319512 | val_mse=0.05358826 | best_val_mse=0.05355599 | early_stop=03/10 | 1.5s
    epoch 017/100 | train_mse=0.02313986 | val_mse=0.05353692 | best_val_mse=0.05353692 | early_stop=00/10 | 1.5s
    epoch 018/100 | train_mse=0.02311192 | val_mse=0.05358453 | best_val_mse=0.05353692 | early_stop=01/10 | 1.4s
    epoch 019/100 | train_mse=0.02309962 | val_mse=0.05356456 | best_val_mse=0.05353692 | early_stop=02/10 | 1.5s
    epoch 020/100 | train_mse=0.02312569 | val_mse=0.05353142 | best_val_mse=0.05353142 | early_stop=00/10 | 1.5s
    epoch 021/100 | train_mse=0.02308923 | val_mse=0.05357025 | best_val_mse=0.05353142 | early_stop=01/10 | 1.5s
    epoch 022/100 | train_mse=0.02310663 | val_mse=0.05354189 | best_val_mse=0.05353142 | early_stop=02/10 | 1.4s
    epoch 023/100 | train_mse=0.02311102 | val_mse=0.05353000 | best_val_mse=0.05353000 | early_stop=00/10 | 1.5s
    epoch 024/100 | train_mse=0.02311261 | val_mse=0.05352692 | best_val_mse=0.05352692 | early_stop=00/10 | 1.5s
    epoch 025/100 | train_mse=0.02309315 | val_mse=0.05349970 | best_val_mse=0.05349970 | early_stop=00/10 | 1.5s
    epoch 026/100 | train_mse=0.02310594 | val_mse=0.05351216 | best_val_mse=0.05349970 | early_stop=01/10 | 1.5s
    epoch 027/100 | train_mse=0.02308475 | val_mse=0.05350539 | best_val_mse=0.05349970 | early_stop=02/10 | 1.5s
    epoch 028/100 | train_mse=0.02308421 | val_mse=0.05352966 | best_val_mse=0.05349970 | early_stop=03/10 | 1.5s
    epoch 029/100 | train_mse=0.02311243 | val_mse=0.05350797 | best_val_mse=0.05349970 | early_stop=04/10 | 1.5s
    epoch 030/100 | train_mse=0.02309856 | val_mse=0.05348617 | best_val_mse=0.05348617 | early_stop=00/10 | 1.5s
    epoch 031/100 | train_mse=0.02307296 | val_mse=0.05347519 | best_val_mse=0.05347519 | early_stop=00/10 | 1.5s
    epoch 032/100 | train_mse=0.02307409 | val_mse=0.05347832 | best_val_mse=0.05347519 | early_stop=01/10 | 1.4s
    epoch 033/100 | train_mse=0.02306384 | val_mse=0.05347176 | best_val_mse=0.05347176 | early_stop=00/10 | 1.5s
    epoch 034/100 | train_mse=0.02308044 | val_mse=0.05350109 | best_val_mse=0.05347176 | early_stop=01/10 | 1.4s
    epoch 035/100 | train_mse=0.02308836 | val_mse=0.05350649 | best_val_mse=0.05347176 | early_stop=02/10 | 1.5s
    epoch 036/100 | train_mse=0.02305875 | val_mse=0.05346954 | best_val_mse=0.05346954 | early_stop=00/10 | 1.5s
    epoch 037/100 | train_mse=0.02303557 | val_mse=0.05354944 | best_val_mse=0.05346954 | early_stop=01/10 | 1.5s
    epoch 038/100 | train_mse=0.02306691 | val_mse=0.05345349 | best_val_mse=0.05345349 | early_stop=00/10 | 1.5s
    epoch 039/100 | train_mse=0.02303315 | val_mse=0.05349348 | best_val_mse=0.05345349 | early_stop=01/10 | 1.5s
    epoch 040/100 | train_mse=0.02306014 | val_mse=0.05344453 | best_val_mse=0.05344453 | early_stop=00/10 | 1.4s
    epoch 041/100 | train_mse=0.02302633 | val_mse=0.05343401 | best_val_mse=0.05343401 | early_stop=00/10 | 1.5s
    epoch 042/100 | train_mse=0.02306598 | val_mse=0.05341589 | best_val_mse=0.05341589 | early_stop=00/10 | 1.5s
    epoch 043/100 | train_mse=0.02302449 | val_mse=0.05337785 | best_val_mse=0.05337785 | early_stop=00/10 | 1.5s
    epoch 044/100 | train_mse=0.02300488 | val_mse=0.05340181 | best_val_mse=0.05337785 | early_stop=01/10 | 1.5s
    epoch 045/100 | train_mse=0.02304829 | val_mse=0.05339700 | best_val_mse=0.05337785 | early_stop=02/10 | 1.5s
    epoch 046/100 | train_mse=0.02302160 | val_mse=0.05340482 | best_val_mse=0.05337785 | early_stop=03/10 | 1.5s
    epoch 047/100 | train_mse=0.02302759 | val_mse=0.05336059 | best_val_mse=0.05336059 | early_stop=00/10 | 1.4s
    epoch 048/100 | train_mse=0.02301018 | val_mse=0.05334653 | best_val_mse=0.05334653 | early_stop=00/10 | 1.5s
    epoch 049/100 | train_mse=0.02297708 | val_mse=0.05329731 | best_val_mse=0.05329731 | early_stop=00/10 | 1.5s
    epoch 050/100 | train_mse=0.02296898 | val_mse=0.05327179 | best_val_mse=0.05327179 | early_stop=00/10 | 1.5s
    epoch 051/100 | train_mse=0.02299407 | val_mse=0.05328370 | best_val_mse=0.05327179 | early_stop=01/10 | 1.5s
    epoch 052/100 | train_mse=0.02292619 | val_mse=0.05336251 | best_val_mse=0.05327179 | early_stop=02/10 | 1.5s
    epoch 053/100 | train_mse=0.02312597 | val_mse=0.05365446 | best_val_mse=0.05327179 | early_stop=03/10 | 1.5s
    epoch 054/100 | train_mse=0.02295857 | val_mse=0.05327465 | best_val_mse=0.05327179 | early_stop=04/10 | 1.5s
    epoch 055/100 | train_mse=0.02302138 | val_mse=0.05329788 | best_val_mse=0.05327179 | early_stop=05/10 | 1.5s
    epoch 056/100 | train_mse=0.02295262 | val_mse=0.05319443 | best_val_mse=0.05319443 | early_stop=00/10 | 1.5s
    epoch 057/100 | train_mse=0.02294015 | val_mse=0.05320760 | best_val_mse=0.05319443 | early_stop=01/10 | 1.5s
    epoch 058/100 | train_mse=0.02292376 | val_mse=0.05323963 | best_val_mse=0.05319443 | early_stop=02/10 | 1.4s
    epoch 059/100 | train_mse=0.02300068 | val_mse=0.05322348 | best_val_mse=0.05319443 | early_stop=03/10 | 1.4s
    epoch 060/100 | train_mse=0.02287095 | val_mse=0.05305836 | best_val_mse=0.05305836 | early_stop=00/10 | 1.4s
    epoch 061/100 | train_mse=0.02293173 | val_mse=0.05319095 | best_val_mse=0.05305836 | early_stop=01/10 | 1.5s
    epoch 062/100 | train_mse=0.02291276 | val_mse=0.05318771 | best_val_mse=0.05305836 | early_stop=02/10 | 1.5s
    epoch 063/100 | train_mse=0.02296539 | val_mse=0.05309145 | best_val_mse=0.05305836 | early_stop=03/10 | 1.4s
    epoch 064/100 | train_mse=0.02284334 | val_mse=0.05295734 | best_val_mse=0.05295734 | early_stop=00/10 | 1.4s
    epoch 065/100 | train_mse=0.02283055 | val_mse=0.05301393 | best_val_mse=0.05295734 | early_stop=01/10 | 1.5s
    epoch 066/100 | train_mse=0.02288243 | val_mse=0.05306487 | best_val_mse=0.05295734 | early_stop=02/10 | 1.4s
    epoch 067/100 | train_mse=0.02287847 | val_mse=0.05294841 | best_val_mse=0.05294841 | early_stop=00/10 | 1.5s
    epoch 068/100 | train_mse=0.02289033 | val_mse=0.05291865 | best_val_mse=0.05291865 | early_stop=00/10 | 1.4s
    epoch 069/100 | train_mse=0.02294407 | val_mse=0.05300817 | best_val_mse=0.05291865 | early_stop=01/10 | 1.5s
    epoch 070/100 | train_mse=0.02277949 | val_mse=0.05305062 | best_val_mse=0.05291865 | early_stop=02/10 | 1.5s
    epoch 071/100 | train_mse=0.02278730 | val_mse=0.05289010 | best_val_mse=0.05289010 | early_stop=00/10 | 1.5s
    epoch 072/100 | train_mse=0.02278305 | val_mse=0.05283067 | best_val_mse=0.05283067 | early_stop=00/10 | 1.5s
    epoch 073/100 | train_mse=0.02279876 | val_mse=0.05293781 | best_val_mse=0.05283067 | early_stop=01/10 | 1.5s
    epoch 074/100 | train_mse=0.02277979 | val_mse=0.05287611 | best_val_mse=0.05283067 | early_stop=02/10 | 1.5s
    epoch 075/100 | train_mse=0.02278723 | val_mse=0.05289144 | best_val_mse=0.05283067 | early_stop=03/10 | 1.5s
    epoch 076/100 | train_mse=0.02275734 | val_mse=0.05277586 | best_val_mse=0.05277586 | early_stop=00/10 | 1.5s
    epoch 077/100 | train_mse=0.02279415 | val_mse=0.05283293 | best_val_mse=0.05277586 | early_stop=01/10 | 1.4s
    epoch 078/100 | train_mse=0.02274182 | val_mse=0.05311471 | best_val_mse=0.05277586 | early_stop=02/10 | 1.4s
    epoch 079/100 | train_mse=0.02276843 | val_mse=0.05284373 | best_val_mse=0.05277586 | early_stop=03/10 | 1.5s
    epoch 080/100 | train_mse=0.02277966 | val_mse=0.05281862 | best_val_mse=0.05277586 | early_stop=04/10 | 1.5s
    epoch 081/100 | train_mse=0.02281034 | val_mse=0.05281454 | best_val_mse=0.05277586 | early_stop=05/10 | 1.4s
    epoch 082/100 | train_mse=0.02276712 | val_mse=0.05286200 | best_val_mse=0.05277586 | early_stop=06/10 | 1.4s
    epoch 083/100 | train_mse=0.02274053 | val_mse=0.05280947 | best_val_mse=0.05277586 | early_stop=07/10 | 1.4s
    epoch 084/100 | train_mse=0.02272980 | val_mse=0.05273517 | best_val_mse=0.05273517 | early_stop=00/10 | 1.5s
    epoch 085/100 | train_mse=0.02268208 | val_mse=0.05276304 | best_val_mse=0.05273517 | early_stop=01/10 | 1.4s
    epoch 086/100 | train_mse=0.02277152 | val_mse=0.05274913 | best_val_mse=0.05273517 | early_stop=02/10 | 1.4s
    epoch 087/100 | train_mse=0.02273037 | val_mse=0.05280405 | best_val_mse=0.05273517 | early_stop=03/10 | 1.5s
    epoch 088/100 | train_mse=0.02275734 | val_mse=0.05312317 | best_val_mse=0.05273517 | early_stop=04/10 | 1.5s
    epoch 089/100 | train_mse=0.02270349 | val_mse=0.05275570 | best_val_mse=0.05273517 | early_stop=05/10 | 1.5s
    epoch 090/100 | train_mse=0.02269843 | val_mse=0.05275616 | best_val_mse=0.05273517 | early_stop=06/10 | 1.5s
    epoch 091/100 | train_mse=0.02272369 | val_mse=0.05278819 | best_val_mse=0.05273517 | early_stop=07/10 | 1.4s
    epoch 092/100 | train_mse=0.02277902 | val_mse=0.05312588 | best_val_mse=0.05273517 | early_stop=08/10 | 1.5s
    epoch 093/100 | train_mse=0.02270986 | val_mse=0.05290895 | best_val_mse=0.05273517 | early_stop=09/10 | 1.4s
    epoch 094/100 | train_mse=0.02270001 | val_mse=0.05277244 | best_val_mse=0.05273517 | early_stop=10/10 | 1.4s
  refit 04/26 | test_year=2002 | status=saved | n_predictions=58,995
  refit 05/26 | test_year=2003 | status=training | train_n=997,898 | validation_n=277,061 | test_n=54,365

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02502065 | val_mse=0.05664113 | best_val_mse=0.05664113 | early_stop=00/10 | 1.5s
    epoch 002/100 | train_mse=0.02485639 | val_mse=0.05659835 | best_val_mse=0.05659835 | early_stop=00/10 | 1.5s
    epoch 003/100 | train_mse=0.02480724 | val_mse=0.05657939 | best_val_mse=0.05657939 | early_stop=00/10 | 1.5s
    epoch 004/100 | train_mse=0.02479757 | val_mse=0.05653568 | best_val_mse=0.05653568 | early_stop=00/10 | 1.5s
    epoch 005/100 | train_mse=0.02474941 | val_mse=0.05651008 | best_val_mse=0.05651008 | early_stop=00/10 | 1.5s
    epoch 006/100 | train_mse=0.02474703 | val_mse=0.05658508 | best_val_mse=0.05651008 | early_stop=01/10 | 1.5s
    epoch 007/100 | train_mse=0.02473479 | val_mse=0.05649516 | best_val_mse=0.05649516 | early_stop=00/10 | 1.5s
    epoch 008/100 | train_mse=0.02472096 | val_mse=0.05644019 | best_val_mse=0.05644019 | early_stop=00/10 | 1.5s
    epoch 009/100 | train_mse=0.02471966 | val_mse=0.05643350 | best_val_mse=0.05643350 | early_stop=00/10 | 1.5s
    epoch 010/100 | train_mse=0.02471723 | val_mse=0.05645091 | best_val_mse=0.05643350 | early_stop=01/10 | 1.5s
    epoch 011/100 | train_mse=0.02467247 | val_mse=0.05644109 | best_val_mse=0.05643350 | early_stop=02/10 | 1.5s
    epoch 012/100 | train_mse=0.02468688 | val_mse=0.05647170 | best_val_mse=0.05643350 | early_stop=03/10 | 1.4s
    epoch 013/100 | train_mse=0.02470203 | val_mse=0.05643266 | best_val_mse=0.05643266 | early_stop=00/10 | 1.5s
    epoch 014/100 | train_mse=0.02469187 | val_mse=0.05647512 | best_val_mse=0.05643266 | early_stop=01/10 | 1.5s
    epoch 015/100 | train_mse=0.02472262 | val_mse=0.05641483 | best_val_mse=0.05641483 | early_stop=00/10 | 1.5s
    epoch 016/100 | train_mse=0.02467188 | val_mse=0.05641063 | best_val_mse=0.05641063 | early_stop=00/10 | 1.5s
    epoch 017/100 | train_mse=0.02465559 | val_mse=0.05640433 | best_val_mse=0.05640433 | early_stop=00/10 | 1.5s
    epoch 018/100 | train_mse=0.02470450 | val_mse=0.05638768 | best_val_mse=0.05638768 | early_stop=00/10 | 1.5s
    epoch 019/100 | train_mse=0.02464734 | val_mse=0.05638777 | best_val_mse=0.05638768 | early_stop=01/10 | 1.5s
    epoch 020/100 | train_mse=0.02460947 | val_mse=0.05637347 | best_val_mse=0.05637347 | early_stop=00/10 | 1.5s
    epoch 021/100 | train_mse=0.02466292 | val_mse=0.05637817 | best_val_mse=0.05637347 | early_stop=01/10 | 1.5s
    epoch 022/100 | train_mse=0.02469446 | val_mse=0.05639079 | best_val_mse=0.05637347 | early_stop=02/10 | 1.5s
    epoch 023/100 | train_mse=0.02462300 | val_mse=0.05635986 | best_val_mse=0.05635986 | early_stop=00/10 | 1.5s
    epoch 024/100 | train_mse=0.02461853 | val_mse=0.05635495 | best_val_mse=0.05635495 | early_stop=00/10 | 1.5s
    epoch 025/100 | train_mse=0.02462976 | val_mse=0.05634461 | best_val_mse=0.05634461 | early_stop=00/10 | 1.5s
    epoch 026/100 | train_mse=0.02462578 | val_mse=0.05639346 | best_val_mse=0.05634461 | early_stop=01/10 | 1.5s
    epoch 027/100 | train_mse=0.02464354 | val_mse=0.05634037 | best_val_mse=0.05634037 | early_stop=00/10 | 1.5s
    epoch 028/100 | train_mse=0.02458637 | val_mse=0.05644174 | best_val_mse=0.05634037 | early_stop=01/10 | 1.5s
    epoch 029/100 | train_mse=0.02469612 | val_mse=0.05635420 | best_val_mse=0.05634037 | early_stop=02/10 | 1.4s
    epoch 030/100 | train_mse=0.02469238 | val_mse=0.05635465 | best_val_mse=0.05634037 | early_stop=03/10 | 1.4s
    epoch 031/100 | train_mse=0.02461127 | val_mse=0.05632637 | best_val_mse=0.05632637 | early_stop=00/10 | 1.4s
    epoch 032/100 | train_mse=0.02461198 | val_mse=0.05633652 | best_val_mse=0.05632637 | early_stop=01/10 | 1.5s
    epoch 033/100 | train_mse=0.02460811 | val_mse=0.05655661 | best_val_mse=0.05632637 | early_stop=02/10 | 1.5s
    epoch 034/100 | train_mse=0.02463737 | val_mse=0.05632295 | best_val_mse=0.05632295 | early_stop=00/10 | 1.6s
    epoch 035/100 | train_mse=0.02463244 | val_mse=0.05633125 | best_val_mse=0.05632295 | early_stop=01/10 | 1.5s
    epoch 036/100 | train_mse=0.02460691 | val_mse=0.05633500 | best_val_mse=0.05632295 | early_stop=02/10 | 1.5s
    epoch 037/100 | train_mse=0.02467053 | val_mse=0.05636627 | best_val_mse=0.05632295 | early_stop=03/10 | 1.5s
    epoch 038/100 | train_mse=0.02459072 | val_mse=0.05632381 | best_val_mse=0.05632295 | early_stop=04/10 | 1.5s
    epoch 039/100 | train_mse=0.02450796 | val_mse=0.05631350 | best_val_mse=0.05631350 | early_stop=00/10 | 1.5s
    epoch 040/100 | train_mse=0.02459080 | val_mse=0.05635919 | best_val_mse=0.05631350 | early_stop=01/10 | 1.5s
    epoch 041/100 | train_mse=0.02465836 | val_mse=0.05630215 | best_val_mse=0.05630215 | early_stop=00/10 | 1.5s
    epoch 042/100 | train_mse=0.02461780 | val_mse=0.05629061 | best_val_mse=0.05629061 | early_stop=00/10 | 1.6s
    epoch 043/100 | train_mse=0.02452974 | val_mse=0.05623310 | best_val_mse=0.05623310 | early_stop=00/10 | 1.6s
    epoch 044/100 | train_mse=0.02452630 | val_mse=0.05624234 | best_val_mse=0.05623310 | early_stop=01/10 | 1.5s
    epoch 045/100 | train_mse=0.02450802 | val_mse=0.05625471 | best_val_mse=0.05623310 | early_stop=02/10 | 1.5s
    epoch 046/100 | train_mse=0.02454263 | val_mse=0.05622058 | best_val_mse=0.05622058 | early_stop=00/10 | 1.6s
    epoch 047/100 | train_mse=0.02449695 | val_mse=0.05618672 | best_val_mse=0.05618672 | early_stop=00/10 | 1.6s
    epoch 048/100 | train_mse=0.02448063 | val_mse=0.05616065 | best_val_mse=0.05616065 | early_stop=00/10 | 1.6s
    epoch 049/100 | train_mse=0.02441031 | val_mse=0.05664803 | best_val_mse=0.05616065 | early_stop=01/10 | 1.5s
    epoch 050/100 | train_mse=0.02454499 | val_mse=0.05650840 | best_val_mse=0.05616065 | early_stop=02/10 | 1.6s
    epoch 051/100 | train_mse=0.02445123 | val_mse=0.05632039 | best_val_mse=0.05616065 | early_stop=03/10 | 1.6s
    epoch 052/100 | train_mse=0.02438298 | val_mse=0.05616842 | best_val_mse=0.05616065 | early_stop=04/10 | 1.6s
    epoch 053/100 | train_mse=0.02444993 | val_mse=0.05617144 | best_val_mse=0.05616065 | early_stop=05/10 | 1.5s
    epoch 054/100 | train_mse=0.02432122 | val_mse=0.05616031 | best_val_mse=0.05616031 | early_stop=00/10 | 1.5s
    epoch 055/100 | train_mse=0.02431686 | val_mse=0.05617525 | best_val_mse=0.05616031 | early_stop=01/10 | 1.5s
    epoch 056/100 | train_mse=0.02433670 | val_mse=0.05616651 | best_val_mse=0.05616031 | early_stop=02/10 | 1.6s
    epoch 057/100 | train_mse=0.02432821 | val_mse=0.05666864 | best_val_mse=0.05616031 | early_stop=03/10 | 1.5s
    epoch 058/100 | train_mse=0.02456008 | val_mse=0.05620863 | best_val_mse=0.05616031 | early_stop=04/10 | 1.6s
    epoch 059/100 | train_mse=0.02435708 | val_mse=0.05613432 | best_val_mse=0.05613432 | early_stop=00/10 | 1.6s
    epoch 060/100 | train_mse=0.02429909 | val_mse=0.05616194 | best_val_mse=0.05613432 | early_stop=01/10 | 1.5s
    epoch 061/100 | train_mse=0.02428891 | val_mse=0.05616101 | best_val_mse=0.05613432 | early_stop=02/10 | 1.5s
    epoch 062/100 | train_mse=0.02431136 | val_mse=0.05616492 | best_val_mse=0.05613432 | early_stop=03/10 | 1.6s
    epoch 063/100 | train_mse=0.02420063 | val_mse=0.05617617 | best_val_mse=0.05613432 | early_stop=04/10 | 1.6s
    epoch 064/100 | train_mse=0.02429656 | val_mse=0.05626020 | best_val_mse=0.05613432 | early_stop=05/10 | 1.5s
    epoch 065/100 | train_mse=0.02436092 | val_mse=0.05630864 | best_val_mse=0.05613432 | early_stop=06/10 | 1.5s
    epoch 066/100 | train_mse=0.02424777 | val_mse=0.05624596 | best_val_mse=0.05613432 | early_stop=07/10 | 1.6s
    epoch 067/100 | train_mse=0.02428821 | val_mse=0.05626026 | best_val_mse=0.05613432 | early_stop=08/10 | 1.7s
    epoch 068/100 | train_mse=0.02426061 | val_mse=0.05630297 | best_val_mse=0.05613432 | early_stop=09/10 | 1.6s
    epoch 069/100 | train_mse=0.02431112 | val_mse=0.05621152 | best_val_mse=0.05613432 | early_stop=10/10 | 1.6s
  refit 05/26 | test_year=2003 | status=saved | n_predictions=54,365
  refit 06/26 | test_year=2004 | status=training | train_n=1,023,477 | validation_n=255,749 | test_n=51,804

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02750861 | val_mse=0.05222805 | best_val_mse=0.05222805 | early_stop=00/10 | 1.6s
    epoch 002/100 | train_mse=0.02722107 | val_mse=0.05211394 | best_val_mse=0.05211394 | early_stop=00/10 | 1.6s
    epoch 003/100 | train_mse=0.02711576 | val_mse=0.05208269 | best_val_mse=0.05208269 | early_stop=00/10 | 1.5s
    epoch 004/100 | train_mse=0.02708977 | val_mse=0.05202076 | best_val_mse=0.05202076 | early_stop=00/10 | 1.5s
    epoch 005/100 | train_mse=0.02710067 | val_mse=0.05222538 | best_val_mse=0.05202076 | early_stop=01/10 | 1.6s
    epoch 006/100 | train_mse=0.02710429 | val_mse=0.05222280 | best_val_mse=0.05202076 | early_stop=02/10 | 1.6s
    epoch 007/100 | train_mse=0.02704581 | val_mse=0.05221643 | best_val_mse=0.05202076 | early_stop=03/10 | 1.6s
    epoch 008/100 | train_mse=0.02703738 | val_mse=0.05207888 | best_val_mse=0.05202076 | early_stop=04/10 | 1.6s
    epoch 009/100 | train_mse=0.02701495 | val_mse=0.05197737 | best_val_mse=0.05197737 | early_stop=00/10 | 1.6s
    epoch 010/100 | train_mse=0.02697588 | val_mse=0.05216611 | best_val_mse=0.05197737 | early_stop=01/10 | 1.5s
    epoch 011/100 | train_mse=0.02696693 | val_mse=0.05181787 | best_val_mse=0.05181787 | early_stop=00/10 | 1.5s
    epoch 012/100 | train_mse=0.02698679 | val_mse=0.05213309 | best_val_mse=0.05181787 | early_stop=01/10 | 1.5s
    epoch 013/100 | train_mse=0.02696781 | val_mse=0.05250255 | best_val_mse=0.05181787 | early_stop=02/10 | 1.5s
    epoch 014/100 | train_mse=0.02700174 | val_mse=0.05214189 | best_val_mse=0.05181787 | early_stop=03/10 | 1.5s
    epoch 015/100 | train_mse=0.02695477 | val_mse=0.05187332 | best_val_mse=0.05181787 | early_stop=04/10 | 1.6s
    epoch 016/100 | train_mse=0.02699862 | val_mse=0.05197215 | best_val_mse=0.05181787 | early_stop=05/10 | 1.6s
    epoch 017/100 | train_mse=0.02692763 | val_mse=0.05233930 | best_val_mse=0.05181787 | early_stop=06/10 | 1.6s
    epoch 018/100 | train_mse=0.02699926 | val_mse=0.05225716 | best_val_mse=0.05181787 | early_stop=07/10 | 1.6s
    epoch 019/100 | train_mse=0.02695525 | val_mse=0.05212320 | best_val_mse=0.05181787 | early_stop=08/10 | 1.6s
    epoch 020/100 | train_mse=0.02696228 | val_mse=0.05255590 | best_val_mse=0.05181787 | early_stop=09/10 | 1.6s
    epoch 021/100 | train_mse=0.02709538 | val_mse=0.05231589 | best_val_mse=0.05181787 | early_stop=10/10 | 1.6s
  refit 06/26 | test_year=2004 | status=saved | n_predictions=51,804
  refit 07/26 | test_year=2005 | status=training | train_n=1,043,741 | validation_n=232,745 | test_n=52,038

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03123863 | val_mse=0.03597362 | best_val_mse=0.03597362 | early_stop=00/10 | 1.6s
    epoch 002/100 | train_mse=0.03100379 | val_mse=0.03598567 | best_val_mse=0.03597362 | early_stop=01/10 | 1.6s
    epoch 003/100 | train_mse=0.03096223 | val_mse=0.03583070 | best_val_mse=0.03583070 | early_stop=00/10 | 1.6s
    epoch 004/100 | train_mse=0.03104768 | val_mse=0.03581758 | best_val_mse=0.03581758 | early_stop=00/10 | 1.5s
    epoch 005/100 | train_mse=0.03090723 | val_mse=0.03586344 | best_val_mse=0.03581758 | early_stop=01/10 | 1.5s
    epoch 006/100 | train_mse=0.03091114 | val_mse=0.03575790 | best_val_mse=0.03575790 | early_stop=00/10 | 1.6s
    epoch 007/100 | train_mse=0.03088264 | val_mse=0.03575017 | best_val_mse=0.03575017 | early_stop=00/10 | 1.5s
    epoch 008/100 | train_mse=0.03089460 | val_mse=0.03572770 | best_val_mse=0.03572770 | early_stop=00/10 | 1.6s
    epoch 009/100 | train_mse=0.03090567 | val_mse=0.03574763 | best_val_mse=0.03572770 | early_stop=01/10 | 1.5s
    epoch 010/100 | train_mse=0.03084834 | val_mse=0.03575509 | best_val_mse=0.03572770 | early_stop=02/10 | 1.6s
    epoch 011/100 | train_mse=0.03087450 | val_mse=0.03570013 | best_val_mse=0.03570013 | early_stop=00/10 | 1.6s
    epoch 012/100 | train_mse=0.03084493 | val_mse=0.03567927 | best_val_mse=0.03567927 | early_stop=00/10 | 1.5s
    epoch 013/100 | train_mse=0.03088661 | val_mse=0.03568209 | best_val_mse=0.03567927 | early_stop=01/10 | 1.5s
    epoch 014/100 | train_mse=0.03083718 | val_mse=0.03570090 | best_val_mse=0.03567927 | early_stop=02/10 | 1.5s
    epoch 015/100 | train_mse=0.03083318 | val_mse=0.03567568 | best_val_mse=0.03567568 | early_stop=00/10 | 1.5s
    epoch 016/100 | train_mse=0.03084121 | val_mse=0.03574650 | best_val_mse=0.03567568 | early_stop=01/10 | 1.5s
    epoch 017/100 | train_mse=0.03079645 | val_mse=0.03565003 | best_val_mse=0.03565003 | early_stop=00/10 | 1.6s
    epoch 018/100 | train_mse=0.03079420 | val_mse=0.03567454 | best_val_mse=0.03565003 | early_stop=01/10 | 1.6s
    epoch 019/100 | train_mse=0.03084027 | val_mse=0.03564849 | best_val_mse=0.03564849 | early_stop=00/10 | 1.6s
    epoch 020/100 | train_mse=0.03084801 | val_mse=0.03571523 | best_val_mse=0.03564849 | early_stop=01/10 | 1.5s
    epoch 021/100 | train_mse=0.03080189 | val_mse=0.03571497 | best_val_mse=0.03564849 | early_stop=02/10 | 1.4s
    epoch 022/100 | train_mse=0.03079489 | val_mse=0.03566228 | best_val_mse=0.03564849 | early_stop=03/10 | 1.4s
    epoch 023/100 | train_mse=0.03077793 | val_mse=0.03561347 | best_val_mse=0.03561347 | early_stop=00/10 | 1.4s
    epoch 024/100 | train_mse=0.03075724 | val_mse=0.03575882 | best_val_mse=0.03561347 | early_stop=01/10 | 1.4s
    epoch 025/100 | train_mse=0.03081427 | val_mse=0.03569670 | best_val_mse=0.03561347 | early_stop=02/10 | 1.4s
    epoch 026/100 | train_mse=0.03078629 | val_mse=0.03565286 | best_val_mse=0.03561347 | early_stop=03/10 | 1.4s
    epoch 027/100 | train_mse=0.03075823 | val_mse=0.03573390 | best_val_mse=0.03561347 | early_stop=04/10 | 1.4s
    epoch 028/100 | train_mse=0.03085171 | val_mse=0.03572468 | best_val_mse=0.03561347 | early_stop=05/10 | 1.4s
    epoch 029/100 | train_mse=0.03077021 | val_mse=0.03561746 | best_val_mse=0.03561347 | early_stop=06/10 | 1.4s
    epoch 030/100 | train_mse=0.03076670 | val_mse=0.03580221 | best_val_mse=0.03561347 | early_stop=07/10 | 1.4s
    epoch 031/100 | train_mse=0.03076576 | val_mse=0.03561235 | best_val_mse=0.03561235 | early_stop=00/10 | 1.4s
    epoch 032/100 | train_mse=0.03077632 | val_mse=0.03564044 | best_val_mse=0.03561235 | early_stop=01/10 | 1.4s
    epoch 033/100 | train_mse=0.03072320 | val_mse=0.03563063 | best_val_mse=0.03561235 | early_stop=02/10 | 1.4s
    epoch 034/100 | train_mse=0.03071363 | val_mse=0.03561652 | best_val_mse=0.03561235 | early_stop=03/10 | 1.4s
    epoch 035/100 | train_mse=0.03071187 | val_mse=0.03562165 | best_val_mse=0.03561235 | early_stop=04/10 | 1.4s
    epoch 036/100 | train_mse=0.03071153 | val_mse=0.03568463 | best_val_mse=0.03561235 | early_stop=05/10 | 1.4s
    epoch 037/100 | train_mse=0.03082490 | val_mse=0.03568021 | best_val_mse=0.03561235 | early_stop=06/10 | 1.4s
    epoch 038/100 | train_mse=0.03075201 | val_mse=0.03562743 | best_val_mse=0.03561235 | early_stop=07/10 | 1.4s
    epoch 039/100 | train_mse=0.03068540 | val_mse=0.03559159 | best_val_mse=0.03559159 | early_stop=00/10 | 1.4s
    epoch 040/100 | train_mse=0.03070760 | val_mse=0.03563211 | best_val_mse=0.03559159 | early_stop=01/10 | 1.4s
    epoch 041/100 | train_mse=0.03073181 | val_mse=0.03563768 | best_val_mse=0.03559159 | early_stop=02/10 | 1.4s
    epoch 042/100 | train_mse=0.03064586 | val_mse=0.03562850 | best_val_mse=0.03559159 | early_stop=03/10 | 1.4s
    epoch 043/100 | train_mse=0.03067990 | val_mse=0.03563843 | best_val_mse=0.03559159 | early_stop=04/10 | 1.4s
    epoch 044/100 | train_mse=0.03071906 | val_mse=0.03577427 | best_val_mse=0.03559159 | early_stop=05/10 | 1.3s
    epoch 045/100 | train_mse=0.03079122 | val_mse=0.03566355 | best_val_mse=0.03559159 | early_stop=06/10 | 1.4s
    epoch 046/100 | train_mse=0.03066092 | val_mse=0.03579051 | best_val_mse=0.03559159 | early_stop=07/10 | 1.4s
    epoch 047/100 | train_mse=0.03063558 | val_mse=0.03568508 | best_val_mse=0.03559159 | early_stop=08/10 | 1.3s
    epoch 048/100 | train_mse=0.03060874 | val_mse=0.03566822 | best_val_mse=0.03559159 | early_stop=09/10 | 1.3s
    epoch 049/100 | train_mse=0.03053820 | val_mse=0.03585447 | best_val_mse=0.03559159 | early_stop=10/10 | 1.4s
  refit 07/26 | test_year=2005 | status=saved | n_predictions=52,038
  refit 08/26 | test_year=2006 | status=training | train_n=1,056,173 | validation_n=215,471 | test_n=52,339

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03286367 | val_mse=0.02508816 | best_val_mse=0.02508816 | early_stop=00/10 | 1.3s
    epoch 002/100 | train_mse=0.03263895 | val_mse=0.02505968 | best_val_mse=0.02505968 | early_stop=00/10 | 1.4s
    epoch 003/100 | train_mse=0.03258328 | val_mse=0.02498712 | best_val_mse=0.02498712 | early_stop=00/10 | 1.4s
    epoch 004/100 | train_mse=0.03255679 | val_mse=0.02505296 | best_val_mse=0.02498712 | early_stop=01/10 | 1.4s
    epoch 005/100 | train_mse=0.03252306 | val_mse=0.02509090 | best_val_mse=0.02498712 | early_stop=02/10 | 1.4s
    epoch 006/100 | train_mse=0.03254086 | val_mse=0.02510225 | best_val_mse=0.02498712 | early_stop=03/10 | 1.4s
    epoch 007/100 | train_mse=0.03252634 | val_mse=0.02493408 | best_val_mse=0.02493408 | early_stop=00/10 | 1.4s
    epoch 008/100 | train_mse=0.03253318 | val_mse=0.02492210 | best_val_mse=0.02492210 | early_stop=00/10 | 1.4s
    epoch 009/100 | train_mse=0.03246502 | val_mse=0.02497589 | best_val_mse=0.02492210 | early_stop=01/10 | 1.3s
    epoch 010/100 | train_mse=0.03249034 | val_mse=0.02493641 | best_val_mse=0.02492210 | early_stop=02/10 | 1.3s
    epoch 011/100 | train_mse=0.03243343 | val_mse=0.02497491 | best_val_mse=0.02492210 | early_stop=03/10 | 1.3s
    epoch 012/100 | train_mse=0.03244822 | val_mse=0.02492803 | best_val_mse=0.02492210 | early_stop=04/10 | 1.4s
    epoch 013/100 | train_mse=0.03244133 | val_mse=0.02507549 | best_val_mse=0.02492210 | early_stop=05/10 | 1.4s
    epoch 014/100 | train_mse=0.03246188 | val_mse=0.02495984 | best_val_mse=0.02492210 | early_stop=06/10 | 1.4s
    epoch 015/100 | train_mse=0.03244208 | val_mse=0.02499256 | best_val_mse=0.02492210 | early_stop=07/10 | 1.4s
    epoch 016/100 | train_mse=0.03249753 | val_mse=0.02503835 | best_val_mse=0.02492210 | early_stop=08/10 | 1.4s
    epoch 017/100 | train_mse=0.03241479 | val_mse=0.02503812 | best_val_mse=0.02492210 | early_stop=09/10 | 1.4s
    epoch 018/100 | train_mse=0.03248068 | val_mse=0.02492090 | best_val_mse=0.02492090 | early_stop=00/10 | 1.4s
    epoch 019/100 | train_mse=0.03243790 | val_mse=0.02505059 | best_val_mse=0.02492090 | early_stop=01/10 | 1.4s
    epoch 020/100 | train_mse=0.03244632 | val_mse=0.02500298 | best_val_mse=0.02492090 | early_stop=02/10 | 1.4s
    epoch 021/100 | train_mse=0.03238142 | val_mse=0.02498046 | best_val_mse=0.02492090 | early_stop=03/10 | 1.4s
    epoch 022/100 | train_mse=0.03240095 | val_mse=0.02493331 | best_val_mse=0.02492090 | early_stop=04/10 | 1.4s
    epoch 023/100 | train_mse=0.03241301 | val_mse=0.02502123 | best_val_mse=0.02492090 | early_stop=05/10 | 1.4s
    epoch 024/100 | train_mse=0.03239849 | val_mse=0.02493841 | best_val_mse=0.02492090 | early_stop=06/10 | 1.4s
    epoch 025/100 | train_mse=0.03241420 | val_mse=0.02499035 | best_val_mse=0.02492090 | early_stop=07/10 | 1.4s
    epoch 026/100 | train_mse=0.03241512 | val_mse=0.02495981 | best_val_mse=0.02492090 | early_stop=08/10 | 1.4s
    epoch 027/100 | train_mse=0.03236252 | val_mse=0.02490935 | best_val_mse=0.02490935 | early_stop=00/10 | 1.4s
    epoch 028/100 | train_mse=0.03233695 | val_mse=0.02509832 | best_val_mse=0.02490935 | early_stop=01/10 | 1.3s
    epoch 029/100 | train_mse=0.03238662 | val_mse=0.02497254 | best_val_mse=0.02490935 | early_stop=02/10 | 1.4s
    epoch 030/100 | train_mse=0.03232202 | val_mse=0.02492288 | best_val_mse=0.02490935 | early_stop=03/10 | 1.4s
    epoch 031/100 | train_mse=0.03234438 | val_mse=0.02501448 | best_val_mse=0.02490935 | early_stop=04/10 | 1.4s
    epoch 032/100 | train_mse=0.03240975 | val_mse=0.02499002 | best_val_mse=0.02490935 | early_stop=05/10 | 1.4s
    epoch 033/100 | train_mse=0.03235051 | val_mse=0.02491610 | best_val_mse=0.02490935 | early_stop=06/10 | 1.4s
    epoch 034/100 | train_mse=0.03231663 | val_mse=0.02487902 | best_val_mse=0.02487902 | early_stop=00/10 | 1.4s
    epoch 035/100 | train_mse=0.03228865 | val_mse=0.02491297 | best_val_mse=0.02487902 | early_stop=01/10 | 1.4s
    epoch 036/100 | train_mse=0.03235212 | val_mse=0.02491220 | best_val_mse=0.02487902 | early_stop=02/10 | 1.4s
    epoch 037/100 | train_mse=0.03230284 | val_mse=0.02494148 | best_val_mse=0.02487902 | early_stop=03/10 | 1.3s
    epoch 038/100 | train_mse=0.03227438 | val_mse=0.02489912 | best_val_mse=0.02487902 | early_stop=04/10 | 1.3s
    epoch 039/100 | train_mse=0.03224600 | val_mse=0.02494785 | best_val_mse=0.02487902 | early_stop=05/10 | 1.3s
    epoch 040/100 | train_mse=0.03235435 | val_mse=0.02505154 | best_val_mse=0.02487902 | early_stop=06/10 | 1.3s
    epoch 041/100 | train_mse=0.03219194 | val_mse=0.02496590 | best_val_mse=0.02487902 | early_stop=07/10 | 1.3s
    epoch 042/100 | train_mse=0.03217947 | val_mse=0.02500115 | best_val_mse=0.02487902 | early_stop=08/10 | 1.4s
    epoch 043/100 | train_mse=0.03222749 | val_mse=0.02496096 | best_val_mse=0.02487902 | early_stop=09/10 | 1.3s
    epoch 044/100 | train_mse=0.03232763 | val_mse=0.02492875 | best_val_mse=0.02487902 | early_stop=10/10 | 1.4s
  refit 08/26 | test_year=2006 | status=saved | n_predictions=52,339
  refit 09/26 | test_year=2007 | status=training | train_n=1,055,556 | validation_n=208,739 | test_n=50,642

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03320330 | val_mse=0.01871500 | best_val_mse=0.01871500 | early_stop=00/10 | 1.4s
    epoch 002/100 | train_mse=0.03298344 | val_mse=0.01863005 | best_val_mse=0.01863005 | early_stop=00/10 | 1.4s
    epoch 003/100 | train_mse=0.03299604 | val_mse=0.01908750 | best_val_mse=0.01863005 | early_stop=01/10 | 1.4s
    epoch 004/100 | train_mse=0.03293659 | val_mse=0.01862744 | best_val_mse=0.01862744 | early_stop=00/10 | 1.4s
    epoch 005/100 | train_mse=0.03288568 | val_mse=0.01841362 | best_val_mse=0.01841362 | early_stop=00/10 | 1.4s
    epoch 006/100 | train_mse=0.03292432 | val_mse=0.01832318 | best_val_mse=0.01832318 | early_stop=00/10 | 1.4s
    epoch 007/100 | train_mse=0.03288490 | val_mse=0.01853587 | best_val_mse=0.01832318 | early_stop=01/10 | 1.3s
    epoch 008/100 | train_mse=0.03288694 | val_mse=0.01844811 | best_val_mse=0.01832318 | early_stop=02/10 | 1.4s
    epoch 009/100 | train_mse=0.03287128 | val_mse=0.01856477 | best_val_mse=0.01832318 | early_stop=03/10 | 1.3s
    epoch 010/100 | train_mse=0.03282778 | val_mse=0.01877694 | best_val_mse=0.01832318 | early_stop=04/10 | 1.3s
    epoch 011/100 | train_mse=0.03283537 | val_mse=0.01832030 | best_val_mse=0.01832030 | early_stop=00/10 | 1.4s
    epoch 012/100 | train_mse=0.03281586 | val_mse=0.01849475 | best_val_mse=0.01832030 | early_stop=01/10 | 1.3s
    epoch 013/100 | train_mse=0.03281695 | val_mse=0.01846842 | best_val_mse=0.01832030 | early_stop=02/10 | 1.3s
    epoch 014/100 | train_mse=0.03281185 | val_mse=0.01865617 | best_val_mse=0.01832030 | early_stop=03/10 | 1.3s
    epoch 015/100 | train_mse=0.03276215 | val_mse=0.01837895 | best_val_mse=0.01832030 | early_stop=04/10 | 1.4s
    epoch 016/100 | train_mse=0.03282748 | val_mse=0.01842209 | best_val_mse=0.01832030 | early_stop=05/10 | 1.3s
    epoch 017/100 | train_mse=0.03282064 | val_mse=0.01831387 | best_val_mse=0.01831387 | early_stop=00/10 | 1.3s
    epoch 018/100 | train_mse=0.03278890 | val_mse=0.01853092 | best_val_mse=0.01831387 | early_stop=01/10 | 1.3s
    epoch 019/100 | train_mse=0.03276613 | val_mse=0.01865311 | best_val_mse=0.01831387 | early_stop=02/10 | 1.3s
    epoch 020/100 | train_mse=0.03287270 | val_mse=0.01847256 | best_val_mse=0.01831387 | early_stop=03/10 | 1.4s
    epoch 021/100 | train_mse=0.03274746 | val_mse=0.01844390 | best_val_mse=0.01831387 | early_stop=04/10 | 1.4s
    epoch 022/100 | train_mse=0.03273883 | val_mse=0.01858824 | best_val_mse=0.01831387 | early_stop=05/10 | 1.4s
    epoch 023/100 | train_mse=0.03272466 | val_mse=0.01842075 | best_val_mse=0.01831387 | early_stop=06/10 | 1.4s
    epoch 024/100 | train_mse=0.03282995 | val_mse=0.01860454 | best_val_mse=0.01831387 | early_stop=07/10 | 1.4s
    epoch 025/100 | train_mse=0.03274458 | val_mse=0.01855428 | best_val_mse=0.01831387 | early_stop=08/10 | 1.4s
    epoch 026/100 | train_mse=0.03277215 | val_mse=0.01861700 | best_val_mse=0.01831387 | early_stop=09/10 | 1.4s
    epoch 027/100 | train_mse=0.03278194 | val_mse=0.01856797 | best_val_mse=0.01831387 | early_stop=10/10 | 1.4s
  refit 09/26 | test_year=2007 | status=saved | n_predictions=50,642
  refit 10/26 | test_year=2008 | status=training | train_n=1,048,198 | validation_n=204,689 | test_n=51,272

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03377530 | val_mse=0.01398597 | best_val_mse=0.01398597 | early_stop=00/10 | 1.4s
    epoch 002/100 | train_mse=0.03355654 | val_mse=0.01397212 | best_val_mse=0.01397212 | early_stop=00/10 | 1.4s
    epoch 003/100 | train_mse=0.03349459 | val_mse=0.01399455 | best_val_mse=0.01397212 | early_stop=01/10 | 1.3s
    epoch 004/100 | train_mse=0.03348160 | val_mse=0.01397456 | best_val_mse=0.01397212 | early_stop=02/10 | 1.3s
    epoch 005/100 | train_mse=0.03347728 | val_mse=0.01397578 | best_val_mse=0.01397212 | early_stop=03/10 | 1.4s
    epoch 006/100 | train_mse=0.03342568 | val_mse=0.01397630 | best_val_mse=0.01397212 | early_stop=04/10 | 1.4s
    epoch 007/100 | train_mse=0.03338672 | val_mse=0.01400668 | best_val_mse=0.01397212 | early_stop=05/10 | 1.4s
    epoch 008/100 | train_mse=0.03339726 | val_mse=0.01400295 | best_val_mse=0.01397212 | early_stop=06/10 | 1.4s
    epoch 009/100 | train_mse=0.03339647 | val_mse=0.01402744 | best_val_mse=0.01397212 | early_stop=07/10 | 1.4s
    epoch 010/100 | train_mse=0.03338137 | val_mse=0.01406180 | best_val_mse=0.01397212 | early_stop=08/10 | 1.4s
    epoch 011/100 | train_mse=0.03346097 | val_mse=0.01394935 | best_val_mse=0.01394935 | early_stop=00/10 | 1.4s
    epoch 012/100 | train_mse=0.03330796 | val_mse=0.01403119 | best_val_mse=0.01394935 | early_stop=01/10 | 1.4s
    epoch 013/100 | train_mse=0.03335562 | val_mse=0.01402015 | best_val_mse=0.01394935 | early_stop=02/10 | 1.4s
    epoch 014/100 | train_mse=0.03340693 | val_mse=0.01401958 | best_val_mse=0.01394935 | early_stop=03/10 | 1.4s
    epoch 015/100 | train_mse=0.03336716 | val_mse=0.01397835 | best_val_mse=0.01394935 | early_stop=04/10 | 1.4s
    epoch 016/100 | train_mse=0.03338081 | val_mse=0.01407292 | best_val_mse=0.01394935 | early_stop=05/10 | 1.4s
    epoch 017/100 | train_mse=0.03340386 | val_mse=0.01396996 | best_val_mse=0.01394935 | early_stop=06/10 | 1.4s
    epoch 018/100 | train_mse=0.03329946 | val_mse=0.01403550 | best_val_mse=0.01394935 | early_stop=07/10 | 1.3s
    epoch 019/100 | train_mse=0.03328085 | val_mse=0.01401227 | best_val_mse=0.01394935 | early_stop=08/10 | 1.4s
    epoch 020/100 | train_mse=0.03328600 | val_mse=0.01404441 | best_val_mse=0.01394935 | early_stop=09/10 | 1.4s
    epoch 021/100 | train_mse=0.03329671 | val_mse=0.01401869 | best_val_mse=0.01394935 | early_stop=10/10 | 1.3s
  refit 10/26 | test_year=2008 | status=saved | n_predictions=51,272
  refit 11/26 | test_year=2009 | status=training | train_n=1,037,605 | validation_n=203,833 | test_n=48,300

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03366339 | val_mse=0.01409427 | best_val_mse=0.01409427 | early_stop=00/10 | 1.3s
    epoch 002/100 | train_mse=0.03343989 | val_mse=0.01399561 | best_val_mse=0.01399561 | early_stop=00/10 | 1.3s
    epoch 003/100 | train_mse=0.03339678 | val_mse=0.01419482 | best_val_mse=0.01399561 | early_stop=01/10 | 1.3s
    epoch 004/100 | train_mse=0.03340552 | val_mse=0.01399036 | best_val_mse=0.01399036 | early_stop=00/10 | 1.3s
    epoch 005/100 | train_mse=0.03332464 | val_mse=0.01401964 | best_val_mse=0.01399036 | early_stop=01/10 | 1.4s
    epoch 006/100 | train_mse=0.03329877 | val_mse=0.01403143 | best_val_mse=0.01399036 | early_stop=02/10 | 1.4s
    epoch 007/100 | train_mse=0.03331862 | val_mse=0.01409587 | best_val_mse=0.01399036 | early_stop=03/10 | 1.4s
    epoch 008/100 | train_mse=0.03329771 | val_mse=0.01412113 | best_val_mse=0.01399036 | early_stop=04/10 | 1.4s
    epoch 009/100 | train_mse=0.03330167 | val_mse=0.01419824 | best_val_mse=0.01399036 | early_stop=05/10 | 1.3s
    epoch 010/100 | train_mse=0.03326141 | val_mse=0.01406278 | best_val_mse=0.01399036 | early_stop=06/10 | 1.3s
    epoch 011/100 | train_mse=0.03326232 | val_mse=0.01404175 | best_val_mse=0.01399036 | early_stop=07/10 | 1.4s
    epoch 012/100 | train_mse=0.03331503 | val_mse=0.01436629 | best_val_mse=0.01399036 | early_stop=08/10 | 1.3s
    epoch 013/100 | train_mse=0.03332892 | val_mse=0.01393943 | best_val_mse=0.01393943 | early_stop=00/10 | 1.3s
    epoch 014/100 | train_mse=0.03326075 | val_mse=0.01401485 | best_val_mse=0.01393943 | early_stop=01/10 | 1.4s
    epoch 015/100 | train_mse=0.03325414 | val_mse=0.01398782 | best_val_mse=0.01393943 | early_stop=02/10 | 1.4s
    epoch 016/100 | train_mse=0.03321203 | val_mse=0.01409621 | best_val_mse=0.01393943 | early_stop=03/10 | 1.3s
    epoch 017/100 | train_mse=0.03319794 | val_mse=0.01402882 | best_val_mse=0.01393943 | early_stop=04/10 | 1.3s
    epoch 018/100 | train_mse=0.03320926 | val_mse=0.01439823 | best_val_mse=0.01393943 | early_stop=05/10 | 1.3s
    epoch 019/100 | train_mse=0.03322503 | val_mse=0.01397482 | best_val_mse=0.01393943 | early_stop=06/10 | 1.3s
    epoch 020/100 | train_mse=0.03323315 | val_mse=0.01400093 | best_val_mse=0.01393943 | early_stop=07/10 | 1.3s
    epoch 021/100 | train_mse=0.03322449 | val_mse=0.01406179 | best_val_mse=0.01393943 | early_stop=08/10 | 1.3s
    epoch 022/100 | train_mse=0.03331350 | val_mse=0.01399375 | best_val_mse=0.01393943 | early_stop=09/10 | 1.3s
    epoch 023/100 | train_mse=0.03322581 | val_mse=0.01399800 | best_val_mse=0.01393943 | early_stop=10/10 | 1.3s
  refit 11/26 | test_year=2009 | status=saved | n_predictions=48,300
  refit 12/26 | test_year=2010 | status=training | train_n=1,023,116 | validation_n=199,878 | test_n=46,429

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03268121 | val_mse=0.02234894 | best_val_mse=0.02234894 | early_stop=00/10 | 1.3s
    epoch 002/100 | train_mse=0.03249240 | val_mse=0.02266987 | best_val_mse=0.02234894 | early_stop=01/10 | 1.3s
    epoch 003/100 | train_mse=0.03239830 | val_mse=0.02270562 | best_val_mse=0.02234894 | early_stop=02/10 | 1.4s
    epoch 004/100 | train_mse=0.03240069 | val_mse=0.02227092 | best_val_mse=0.02227092 | early_stop=00/10 | 1.3s
    epoch 005/100 | train_mse=0.03234702 | val_mse=0.02230818 | best_val_mse=0.02227092 | early_stop=01/10 | 1.4s
    epoch 006/100 | train_mse=0.03234580 | val_mse=0.02265670 | best_val_mse=0.02227092 | early_stop=02/10 | 1.4s
    epoch 007/100 | train_mse=0.03241156 | val_mse=0.02247148 | best_val_mse=0.02227092 | early_stop=03/10 | 1.4s
    epoch 008/100 | train_mse=0.03229263 | val_mse=0.02229365 | best_val_mse=0.02227092 | early_stop=04/10 | 1.3s
    epoch 009/100 | train_mse=0.03231044 | val_mse=0.02253600 | best_val_mse=0.02227092 | early_stop=05/10 | 1.4s
    epoch 010/100 | train_mse=0.03229547 | val_mse=0.02221987 | best_val_mse=0.02221987 | early_stop=00/10 | 1.3s
    epoch 011/100 | train_mse=0.03231155 | val_mse=0.02209665 | best_val_mse=0.02209665 | early_stop=00/10 | 1.4s
    epoch 012/100 | train_mse=0.03232745 | val_mse=0.02187303 | best_val_mse=0.02187303 | early_stop=00/10 | 1.4s
    epoch 013/100 | train_mse=0.03245412 | val_mse=0.02220025 | best_val_mse=0.02187303 | early_stop=01/10 | 1.3s
    epoch 014/100 | train_mse=0.03225530 | val_mse=0.02212904 | best_val_mse=0.02187303 | early_stop=02/10 | 1.4s
    epoch 015/100 | train_mse=0.03230341 | val_mse=0.02250628 | best_val_mse=0.02187303 | early_stop=03/10 | 1.4s
    epoch 016/100 | train_mse=0.03227675 | val_mse=0.02193986 | best_val_mse=0.02187303 | early_stop=04/10 | 1.4s
    epoch 017/100 | train_mse=0.03227864 | val_mse=0.02297673 | best_val_mse=0.02187303 | early_stop=05/10 | 1.3s
    epoch 018/100 | train_mse=0.03233282 | val_mse=0.02301784 | best_val_mse=0.02187303 | early_stop=06/10 | 1.3s
    epoch 019/100 | train_mse=0.03222787 | val_mse=0.02222648 | best_val_mse=0.02187303 | early_stop=07/10 | 1.3s
    epoch 020/100 | train_mse=0.03223968 | val_mse=0.02223017 | best_val_mse=0.02187303 | early_stop=08/10 | 1.3s
    epoch 021/100 | train_mse=0.03223399 | val_mse=0.02247636 | best_val_mse=0.02187303 | early_stop=09/10 | 1.4s
    epoch 022/100 | train_mse=0.03222715 | val_mse=0.02234636 | best_val_mse=0.02187303 | early_stop=10/10 | 1.3s
  refit 12/26 | test_year=2010 | status=saved | n_predictions=46,429
  refit 13/26 | test_year=2011 | status=training | train_n=1,008,847 | validation_n=193,928 | test_n=45,154

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03095956 | val_mse=0.03547055 | best_val_mse=0.03547055 | early_stop=00/10 | 1.4s
    epoch 002/100 | train_mse=0.03074005 | val_mse=0.03540654 | best_val_mse=0.03540654 | early_stop=00/10 | 1.3s
    epoch 003/100 | train_mse=0.03064901 | val_mse=0.03523583 | best_val_mse=0.03523583 | early_stop=00/10 | 1.3s
    epoch 004/100 | train_mse=0.03068354 | val_mse=0.03530470 | best_val_mse=0.03523583 | early_stop=01/10 | 1.3s
    epoch 005/100 | train_mse=0.03060256 | val_mse=0.03525052 | best_val_mse=0.03523583 | early_stop=02/10 | 1.4s
    epoch 006/100 | train_mse=0.03060980 | val_mse=0.03522621 | best_val_mse=0.03522621 | early_stop=00/10 | 1.4s
    epoch 007/100 | train_mse=0.03057504 | val_mse=0.03551302 | best_val_mse=0.03522621 | early_stop=01/10 | 1.3s
    epoch 008/100 | train_mse=0.03066813 | val_mse=0.03542392 | best_val_mse=0.03522621 | early_stop=02/10 | 1.3s
    epoch 009/100 | train_mse=0.03058991 | val_mse=0.03543446 | best_val_mse=0.03522621 | early_stop=03/10 | 1.3s
    epoch 010/100 | train_mse=0.03056960 | val_mse=0.03526523 | best_val_mse=0.03522621 | early_stop=04/10 | 1.3s
    epoch 011/100 | train_mse=0.03058222 | val_mse=0.03524489 | best_val_mse=0.03522621 | early_stop=05/10 | 1.3s
    epoch 012/100 | train_mse=0.03057573 | val_mse=0.03530026 | best_val_mse=0.03522621 | early_stop=06/10 | 1.3s
    epoch 013/100 | train_mse=0.03053884 | val_mse=0.03544936 | best_val_mse=0.03522621 | early_stop=07/10 | 1.3s
    epoch 014/100 | train_mse=0.03054713 | val_mse=0.03525845 | best_val_mse=0.03522621 | early_stop=08/10 | 1.3s
    epoch 015/100 | train_mse=0.03057042 | val_mse=0.03526186 | best_val_mse=0.03522621 | early_stop=09/10 | 1.3s
    epoch 016/100 | train_mse=0.03049082 | val_mse=0.03560721 | best_val_mse=0.03522621 | early_stop=10/10 | 1.4s
  refit 13/26 | test_year=2011 | status=saved | n_predictions=45,154
  refit 14/26 | test_year=2012 | status=training | train_n=992,010 | validation_n=188,512 | test_n=44,459

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03063109 | val_mse=0.03729362 | best_val_mse=0.03729362 | early_stop=00/10 | 1.3s
    epoch 002/100 | train_mse=0.03037413 | val_mse=0.03727607 | best_val_mse=0.03727607 | early_stop=00/10 | 1.3s
    epoch 003/100 | train_mse=0.03031391 | val_mse=0.03726624 | best_val_mse=0.03726624 | early_stop=00/10 | 1.4s
    epoch 004/100 | train_mse=0.03032212 | val_mse=0.03725156 | best_val_mse=0.03725156 | early_stop=00/10 | 1.3s
    epoch 005/100 | train_mse=0.03023554 | val_mse=0.03730969 | best_val_mse=0.03725156 | early_stop=01/10 | 1.3s
    epoch 006/100 | train_mse=0.03026193 | val_mse=0.03722626 | best_val_mse=0.03722626 | early_stop=00/10 | 1.3s
    epoch 007/100 | train_mse=0.03021503 | val_mse=0.03725785 | best_val_mse=0.03722626 | early_stop=01/10 | 1.3s
    epoch 008/100 | train_mse=0.03019487 | val_mse=0.03724211 | best_val_mse=0.03722626 | early_stop=02/10 | 1.3s
    epoch 009/100 | train_mse=0.03018181 | val_mse=0.03724673 | best_val_mse=0.03722626 | early_stop=03/10 | 1.3s
    epoch 010/100 | train_mse=0.03018866 | val_mse=0.03725878 | best_val_mse=0.03722626 | early_stop=04/10 | 1.3s
    epoch 011/100 | train_mse=0.03015860 | val_mse=0.03725157 | best_val_mse=0.03722626 | early_stop=05/10 | 1.3s
    epoch 012/100 | train_mse=0.03016518 | val_mse=0.03725308 | best_val_mse=0.03722626 | early_stop=06/10 | 1.4s
    epoch 013/100 | train_mse=0.03017155 | val_mse=0.03725692 | best_val_mse=0.03722626 | early_stop=07/10 | 1.4s
    epoch 014/100 | train_mse=0.03016091 | val_mse=0.03725668 | best_val_mse=0.03722626 | early_stop=08/10 | 1.3s
    epoch 015/100 | train_mse=0.03016393 | val_mse=0.03726917 | best_val_mse=0.03722626 | early_stop=09/10 | 1.3s
    epoch 016/100 | train_mse=0.03018483 | val_mse=0.03728881 | best_val_mse=0.03722626 | early_stop=10/10 | 1.3s
  refit 14/26 | test_year=2012 | status=saved | n_predictions=44,459
  refit 15/26 | test_year=2013 | status=training | train_n=971,804 | validation_n=181,718 | test_n=44,277

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03149410 | val_mse=0.03052111 | best_val_mse=0.03052111 | early_stop=00/10 | 1.3s
    epoch 002/100 | train_mse=0.03152049 | val_mse=0.03085982 | best_val_mse=0.03052111 | early_stop=01/10 | 1.3s
    epoch 003/100 | train_mse=0.03141855 | val_mse=0.03084664 | best_val_mse=0.03052111 | early_stop=02/10 | 1.3s
    epoch 004/100 | train_mse=0.03136766 | val_mse=0.03079206 | best_val_mse=0.03052111 | early_stop=03/10 | 1.3s
    epoch 005/100 | train_mse=0.03134219 | val_mse=0.03076051 | best_val_mse=0.03052111 | early_stop=04/10 | 1.3s
    epoch 006/100 | train_mse=0.03134654 | val_mse=0.03113044 | best_val_mse=0.03052111 | early_stop=05/10 | 1.3s
    epoch 007/100 | train_mse=0.03135354 | val_mse=0.03080749 | best_val_mse=0.03052111 | early_stop=06/10 | 1.3s
    epoch 008/100 | train_mse=0.03129299 | val_mse=0.03110383 | best_val_mse=0.03052111 | early_stop=07/10 | 1.3s
    epoch 009/100 | train_mse=0.03128112 | val_mse=0.03084412 | best_val_mse=0.03052111 | early_stop=08/10 | 1.3s
    epoch 010/100 | train_mse=0.03134399 | val_mse=0.03064450 | best_val_mse=0.03052111 | early_stop=09/10 | 1.3s
    epoch 011/100 | train_mse=0.03126943 | val_mse=0.03098002 | best_val_mse=0.03052111 | early_stop=10/10 | 1.3s
  refit 15/26 | test_year=2013 | status=saved | n_predictions=44,277
  refit 16/26 | test_year=2014 | status=training | train_n=945,407 | validation_n=177,641 | test_n=45,510

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03390372 | val_mse=0.01799203 | best_val_mse=0.01799203 | early_stop=00/10 | 1.3s
    epoch 002/100 | train_mse=0.03372861 | val_mse=0.01779322 | best_val_mse=0.01779322 | early_stop=00/10 | 1.4s
    epoch 003/100 | train_mse=0.03358197 | val_mse=0.01776822 | best_val_mse=0.01776822 | early_stop=00/10 | 1.3s
    epoch 004/100 | train_mse=0.03357317 | val_mse=0.01787066 | best_val_mse=0.01776822 | early_stop=01/10 | 1.3s
    epoch 005/100 | train_mse=0.03359401 | val_mse=0.01776585 | best_val_mse=0.01776585 | early_stop=00/10 | 1.3s
    epoch 006/100 | train_mse=0.03356409 | val_mse=0.01775643 | best_val_mse=0.01775643 | early_stop=00/10 | 1.3s
    epoch 007/100 | train_mse=0.03353726 | val_mse=0.01776323 | best_val_mse=0.01775643 | early_stop=01/10 | 1.3s
    epoch 008/100 | train_mse=0.03354329 | val_mse=0.01773706 | best_val_mse=0.01773706 | early_stop=00/10 | 1.3s
    epoch 009/100 | train_mse=0.03354647 | val_mse=0.01773766 | best_val_mse=0.01773706 | early_stop=01/10 | 1.3s
    epoch 010/100 | train_mse=0.03352453 | val_mse=0.01780601 | best_val_mse=0.01773706 | early_stop=02/10 | 1.3s
    epoch 011/100 | train_mse=0.03348600 | val_mse=0.01773209 | best_val_mse=0.01773209 | early_stop=00/10 | 1.3s
    epoch 012/100 | train_mse=0.03360047 | val_mse=0.01772150 | best_val_mse=0.01772150 | early_stop=00/10 | 1.3s
    epoch 013/100 | train_mse=0.03349183 | val_mse=0.01773201 | best_val_mse=0.01772150 | early_stop=01/10 | 1.3s
    epoch 014/100 | train_mse=0.03349073 | val_mse=0.01773872 | best_val_mse=0.01772150 | early_stop=02/10 | 1.3s
    epoch 015/100 | train_mse=0.03347694 | val_mse=0.01772728 | best_val_mse=0.01772150 | early_stop=03/10 | 1.3s
    epoch 016/100 | train_mse=0.03359643 | val_mse=0.01776287 | best_val_mse=0.01772150 | early_stop=04/10 | 1.3s
    epoch 017/100 | train_mse=0.03356691 | val_mse=0.01781249 | best_val_mse=0.01772150 | early_stop=05/10 | 1.3s
    epoch 018/100 | train_mse=0.03350587 | val_mse=0.01778362 | best_val_mse=0.01772150 | early_stop=06/10 | 1.3s
    epoch 019/100 | train_mse=0.03346020 | val_mse=0.01773154 | best_val_mse=0.01772150 | early_stop=07/10 | 1.3s
    epoch 020/100 | train_mse=0.03356056 | val_mse=0.01772345 | best_val_mse=0.01772150 | early_stop=08/10 | 1.3s
    epoch 021/100 | train_mse=0.03348649 | val_mse=0.01775151 | best_val_mse=0.01772150 | early_stop=09/10 | 1.3s
    epoch 022/100 | train_mse=0.03341564 | val_mse=0.01782605 | best_val_mse=0.01772150 | early_stop=10/10 | 1.3s
  refit 16/26 | test_year=2014 | status=saved | n_predictions=45,510
  refit 17/26 | test_year=2015 | status=training | train_n=918,021 | validation_n=176,705 | test_n=46,909

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03436965 | val_mse=0.01648136 | best_val_mse=0.01648136 | early_stop=00/10 | 1.3s
    epoch 002/100 | train_mse=0.03407748 | val_mse=0.01630098 | best_val_mse=0.01630098 | early_stop=00/10 | 1.3s
    epoch 003/100 | train_mse=0.03403742 | val_mse=0.01633629 | best_val_mse=0.01630098 | early_stop=01/10 | 1.3s
    epoch 004/100 | train_mse=0.03396100 | val_mse=0.01627898 | best_val_mse=0.01627898 | early_stop=00/10 | 1.3s
    epoch 005/100 | train_mse=0.03398115 | val_mse=0.01624449 | best_val_mse=0.01624449 | early_stop=00/10 | 1.3s
    epoch 006/100 | train_mse=0.03393176 | val_mse=0.01624367 | best_val_mse=0.01624367 | early_stop=00/10 | 1.3s
    epoch 007/100 | train_mse=0.03393646 | val_mse=0.01623671 | best_val_mse=0.01623671 | early_stop=00/10 | 1.3s
    epoch 008/100 | train_mse=0.03391628 | val_mse=0.01628432 | best_val_mse=0.01623671 | early_stop=01/10 | 1.3s
    epoch 009/100 | train_mse=0.03389827 | val_mse=0.01623888 | best_val_mse=0.01623671 | early_stop=02/10 | 1.3s
    epoch 010/100 | train_mse=0.03391533 | val_mse=0.01625897 | best_val_mse=0.01623671 | early_stop=03/10 | 1.3s
    epoch 011/100 | train_mse=0.03394358 | val_mse=0.01623759 | best_val_mse=0.01623671 | early_stop=04/10 | 1.3s
    epoch 012/100 | train_mse=0.03389367 | val_mse=0.01623863 | best_val_mse=0.01623671 | early_stop=05/10 | 1.3s
    epoch 013/100 | train_mse=0.03384687 | val_mse=0.01625474 | best_val_mse=0.01623671 | early_stop=06/10 | 1.3s
    epoch 014/100 | train_mse=0.03385127 | val_mse=0.01631569 | best_val_mse=0.01623671 | early_stop=07/10 | 1.3s
    epoch 015/100 | train_mse=0.03386322 | val_mse=0.01626220 | best_val_mse=0.01623671 | early_stop=08/10 | 1.3s
    epoch 016/100 | train_mse=0.03382571 | val_mse=0.01626606 | best_val_mse=0.01623671 | early_stop=09/10 | 1.3s
    epoch 017/100 | train_mse=0.03386601 | val_mse=0.01626122 | best_val_mse=0.01623671 | early_stop=10/10 | 1.3s
  refit 17/26 | test_year=2015 | status=saved | n_predictions=46,909
  refit 18/26 | test_year=2016 | status=training | train_n=883,923 | validation_n=178,414 | test_n=45,819

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03406973 | val_mse=0.01503385 | best_val_mse=0.01503385 | early_stop=00/10 | 1.3s
    epoch 002/100 | train_mse=0.03377480 | val_mse=0.01491929 | best_val_mse=0.01491929 | early_stop=00/10 | 1.3s
    epoch 003/100 | train_mse=0.03383754 | val_mse=0.01487271 | best_val_mse=0.01487271 | early_stop=00/10 | 1.3s
    epoch 004/100 | train_mse=0.03371182 | val_mse=0.01487364 | best_val_mse=0.01487271 | early_stop=01/10 | 1.2s
    epoch 005/100 | train_mse=0.03369394 | val_mse=0.01487716 | best_val_mse=0.01487271 | early_stop=02/10 | 1.3s
    epoch 006/100 | train_mse=0.03369354 | val_mse=0.01496956 | best_val_mse=0.01487271 | early_stop=03/10 | 1.3s
    epoch 007/100 | train_mse=0.03366151 | val_mse=0.01491102 | best_val_mse=0.01487271 | early_stop=04/10 | 1.3s
    epoch 008/100 | train_mse=0.03364502 | val_mse=0.01495287 | best_val_mse=0.01487271 | early_stop=05/10 | 1.3s
    epoch 009/100 | train_mse=0.03365939 | val_mse=0.01488356 | best_val_mse=0.01487271 | early_stop=06/10 | 1.3s
    epoch 010/100 | train_mse=0.03366941 | val_mse=0.01490059 | best_val_mse=0.01487271 | early_stop=07/10 | 1.2s
    epoch 011/100 | train_mse=0.03367728 | val_mse=0.01486049 | best_val_mse=0.01486049 | early_stop=00/10 | 1.3s
    epoch 012/100 | train_mse=0.03362048 | val_mse=0.01488995 | best_val_mse=0.01486049 | early_stop=01/10 | 1.3s
    epoch 013/100 | train_mse=0.03367711 | val_mse=0.01495049 | best_val_mse=0.01486049 | early_stop=02/10 | 1.3s
    epoch 014/100 | train_mse=0.03360937 | val_mse=0.01486810 | best_val_mse=0.01486049 | early_stop=03/10 | 1.3s
    epoch 015/100 | train_mse=0.03360165 | val_mse=0.01489206 | best_val_mse=0.01486049 | early_stop=04/10 | 1.3s
    epoch 016/100 | train_mse=0.03362973 | val_mse=0.01487566 | best_val_mse=0.01486049 | early_stop=05/10 | 1.3s
    epoch 017/100 | train_mse=0.03361555 | val_mse=0.01491603 | best_val_mse=0.01486049 | early_stop=06/10 | 1.3s
    epoch 018/100 | train_mse=0.03359561 | val_mse=0.01488485 | best_val_mse=0.01486049 | early_stop=07/10 | 1.3s
    epoch 019/100 | train_mse=0.03359969 | val_mse=0.01489845 | best_val_mse=0.01486049 | early_stop=08/10 | 1.3s
    epoch 020/100 | train_mse=0.03357426 | val_mse=0.01490227 | best_val_mse=0.01486049 | early_stop=09/10 | 1.2s
    epoch 021/100 | train_mse=0.03356341 | val_mse=0.01488611 | best_val_mse=0.01486049 | early_stop=10/10 | 1.2s
  refit 18/26 | test_year=2016 | status=saved | n_predictions=45,819
  refit 19/26 | test_year=2017 | status=training | train_n=846,469 | validation_n=179,674 | test_n=44,940

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03403211 | val_mse=0.01642478 | best_val_mse=0.01642478 | early_stop=00/10 | 1.3s
    epoch 002/100 | train_mse=0.03377078 | val_mse=0.01634106 | best_val_mse=0.01634106 | early_stop=00/10 | 1.3s
    epoch 003/100 | train_mse=0.03373433 | val_mse=0.01632003 | best_val_mse=0.01632003 | early_stop=00/10 | 1.3s
    epoch 004/100 | train_mse=0.03376841 | val_mse=0.01639974 | best_val_mse=0.01632003 | early_stop=01/10 | 1.3s
    epoch 005/100 | train_mse=0.03366874 | val_mse=0.01630650 | best_val_mse=0.01630650 | early_stop=00/10 | 1.3s
    epoch 006/100 | train_mse=0.03368005 | val_mse=0.01629681 | best_val_mse=0.01629681 | early_stop=00/10 | 1.3s
    epoch 007/100 | train_mse=0.03364672 | val_mse=0.01634656 | best_val_mse=0.01629681 | early_stop=01/10 | 1.3s
    epoch 008/100 | train_mse=0.03367226 | val_mse=0.01629703 | best_val_mse=0.01629681 | early_stop=02/10 | 1.2s
    epoch 009/100 | train_mse=0.03369879 | val_mse=0.01627399 | best_val_mse=0.01627399 | early_stop=00/10 | 1.3s
    epoch 010/100 | train_mse=0.03366311 | val_mse=0.01633697 | best_val_mse=0.01627399 | early_stop=01/10 | 1.2s
    epoch 011/100 | train_mse=0.03362532 | val_mse=0.01628925 | best_val_mse=0.01627399 | early_stop=02/10 | 1.3s
    epoch 012/100 | train_mse=0.03361616 | val_mse=0.01629827 | best_val_mse=0.01627399 | early_stop=03/10 | 1.3s
    epoch 013/100 | train_mse=0.03364491 | val_mse=0.01631618 | best_val_mse=0.01627399 | early_stop=04/10 | 1.3s
    epoch 014/100 | train_mse=0.03360500 | val_mse=0.01627333 | best_val_mse=0.01627333 | early_stop=00/10 | 1.3s
    epoch 015/100 | train_mse=0.03361954 | val_mse=0.01627492 | best_val_mse=0.01627333 | early_stop=01/10 | 1.3s
    epoch 016/100 | train_mse=0.03360159 | val_mse=0.01627251 | best_val_mse=0.01627251 | early_stop=00/10 | 1.3s
    epoch 017/100 | train_mse=0.03362136 | val_mse=0.01626620 | best_val_mse=0.01626620 | early_stop=00/10 | 1.3s
    epoch 018/100 | train_mse=0.03357552 | val_mse=0.01631873 | best_val_mse=0.01626620 | early_stop=01/10 | 1.2s
    epoch 019/100 | train_mse=0.03364672 | val_mse=0.01628195 | best_val_mse=0.01626620 | early_stop=02/10 | 1.2s
    epoch 020/100 | train_mse=0.03364847 | val_mse=0.01625696 | best_val_mse=0.01625696 | early_stop=00/10 | 1.3s
    epoch 021/100 | train_mse=0.03365069 | val_mse=0.01625702 | best_val_mse=0.01625696 | early_stop=01/10 | 1.3s
    epoch 022/100 | train_mse=0.03359046 | val_mse=0.01626686 | best_val_mse=0.01625696 | early_stop=02/10 | 1.3s
    epoch 023/100 | train_mse=0.03355439 | val_mse=0.01629548 | best_val_mse=0.01625696 | early_stop=03/10 | 1.3s
    epoch 024/100 | train_mse=0.03357685 | val_mse=0.01625421 | best_val_mse=0.01625421 | early_stop=00/10 | 1.3s
    epoch 025/100 | train_mse=0.03355753 | val_mse=0.01625667 | best_val_mse=0.01625421 | early_stop=01/10 | 1.3s
    epoch 026/100 | train_mse=0.03355101 | val_mse=0.01626478 | best_val_mse=0.01625421 | early_stop=02/10 | 1.3s
    epoch 027/100 | train_mse=0.03355942 | val_mse=0.01625288 | best_val_mse=0.01625288 | early_stop=00/10 | 1.3s
    epoch 028/100 | train_mse=0.03355804 | val_mse=0.01626061 | best_val_mse=0.01625288 | early_stop=01/10 | 1.2s
    epoch 029/100 | train_mse=0.03349214 | val_mse=0.01640278 | best_val_mse=0.01625288 | early_stop=02/10 | 1.2s
    epoch 030/100 | train_mse=0.03345823 | val_mse=0.01625768 | best_val_mse=0.01625288 | early_stop=03/10 | 1.3s
    epoch 031/100 | train_mse=0.03366497 | val_mse=0.01627631 | best_val_mse=0.01625288 | early_stop=04/10 | 1.3s
    epoch 032/100 | train_mse=0.03347247 | val_mse=0.01628315 | best_val_mse=0.01625288 | early_stop=05/10 | 1.3s
    epoch 033/100 | train_mse=0.03352776 | val_mse=0.01627433 | best_val_mse=0.01625288 | early_stop=06/10 | 1.3s
    epoch 034/100 | train_mse=0.03345633 | val_mse=0.01628658 | best_val_mse=0.01625288 | early_stop=07/10 | 1.3s
    epoch 035/100 | train_mse=0.03352716 | val_mse=0.01643425 | best_val_mse=0.01625288 | early_stop=08/10 | 1.2s
    epoch 036/100 | train_mse=0.03351463 | val_mse=0.01631470 | best_val_mse=0.01625288 | early_stop=09/10 | 1.2s
    epoch 037/100 | train_mse=0.03348216 | val_mse=0.01626200 | best_val_mse=0.01625288 | early_stop=10/10 | 1.3s
  refit 19/26 | test_year=2017 | status=saved | n_predictions=44,940
  refit 20/26 | test_year=2018 | status=training | train_n=811,524 | validation_n=180,185 | test_n=45,340

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03253351 | val_mse=0.01850335 | best_val_mse=0.01850335 | early_stop=00/10 | 1.3s
    epoch 002/100 | train_mse=0.03225040 | val_mse=0.01843765 | best_val_mse=0.01843765 | early_stop=00/10 | 1.2s
    epoch 003/100 | train_mse=0.03225891 | val_mse=0.01845216 | best_val_mse=0.01843765 | early_stop=01/10 | 1.2s
    epoch 004/100 | train_mse=0.03218002 | val_mse=0.01840127 | best_val_mse=0.01840127 | early_stop=00/10 | 1.2s
    epoch 005/100 | train_mse=0.03217645 | val_mse=0.01839748 | best_val_mse=0.01839748 | early_stop=00/10 | 1.2s
    epoch 006/100 | train_mse=0.03216049 | val_mse=0.01841415 | best_val_mse=0.01839748 | early_stop=01/10 | 1.2s
    epoch 007/100 | train_mse=0.03216419 | val_mse=0.01843603 | best_val_mse=0.01839748 | early_stop=02/10 | 1.2s
    epoch 008/100 | train_mse=0.03215870 | val_mse=0.01841908 | best_val_mse=0.01839748 | early_stop=03/10 | 1.2s
    epoch 009/100 | train_mse=0.03213560 | val_mse=0.01840925 | best_val_mse=0.01839748 | early_stop=04/10 | 1.2s
    epoch 010/100 | train_mse=0.03227777 | val_mse=0.01839710 | best_val_mse=0.01839710 | early_stop=00/10 | 1.2s
    epoch 011/100 | train_mse=0.03215441 | val_mse=0.01846453 | best_val_mse=0.01839710 | early_stop=01/10 | 1.2s
    epoch 012/100 | train_mse=0.03217969 | val_mse=0.01839594 | best_val_mse=0.01839594 | early_stop=00/10 | 1.2s
    epoch 013/100 | train_mse=0.03211638 | val_mse=0.01840191 | best_val_mse=0.01839594 | early_stop=01/10 | 1.2s
    epoch 014/100 | train_mse=0.03213851 | val_mse=0.01839499 | best_val_mse=0.01839499 | early_stop=00/10 | 1.2s
    epoch 015/100 | train_mse=0.03217272 | val_mse=0.01838300 | best_val_mse=0.01838300 | early_stop=00/10 | 1.2s
    epoch 016/100 | train_mse=0.03213169 | val_mse=0.01849394 | best_val_mse=0.01838300 | early_stop=01/10 | 1.2s
    epoch 017/100 | train_mse=0.03214625 | val_mse=0.01841413 | best_val_mse=0.01838300 | early_stop=02/10 | 1.3s
    epoch 018/100 | train_mse=0.03211121 | val_mse=0.01846785 | best_val_mse=0.01838300 | early_stop=03/10 | 1.2s
    epoch 019/100 | train_mse=0.03209176 | val_mse=0.01836834 | best_val_mse=0.01836834 | early_stop=00/10 | 1.2s
    epoch 020/100 | train_mse=0.03206623 | val_mse=0.01842663 | best_val_mse=0.01836834 | early_stop=01/10 | 1.2s
    epoch 021/100 | train_mse=0.03212091 | val_mse=0.01838696 | best_val_mse=0.01836834 | early_stop=02/10 | 1.2s
    epoch 022/100 | train_mse=0.03215147 | val_mse=0.01840349 | best_val_mse=0.01836834 | early_stop=03/10 | 1.2s
    epoch 023/100 | train_mse=0.03209070 | val_mse=0.01847929 | best_val_mse=0.01836834 | early_stop=04/10 | 1.2s
    epoch 024/100 | train_mse=0.03206504 | val_mse=0.01836900 | best_val_mse=0.01836834 | early_stop=05/10 | 1.2s
    epoch 025/100 | train_mse=0.03204991 | val_mse=0.01841025 | best_val_mse=0.01836834 | early_stop=06/10 | 1.2s
    epoch 026/100 | train_mse=0.03212168 | val_mse=0.01849346 | best_val_mse=0.01836834 | early_stop=07/10 | 1.2s
    epoch 027/100 | train_mse=0.03203360 | val_mse=0.01836695 | best_val_mse=0.01836695 | early_stop=00/10 | 1.3s
    epoch 028/100 | train_mse=0.03208522 | val_mse=0.01841411 | best_val_mse=0.01836695 | early_stop=01/10 | 1.3s
    epoch 029/100 | train_mse=0.03206107 | val_mse=0.01840116 | best_val_mse=0.01836695 | early_stop=02/10 | 1.3s
    epoch 030/100 | train_mse=0.03205423 | val_mse=0.01849353 | best_val_mse=0.01836695 | early_stop=03/10 | 1.2s
    epoch 031/100 | train_mse=0.03200733 | val_mse=0.01835531 | best_val_mse=0.01835531 | early_stop=00/10 | 1.2s
    epoch 032/100 | train_mse=0.03201169 | val_mse=0.01842430 | best_val_mse=0.01835531 | early_stop=01/10 | 1.2s
    epoch 033/100 | train_mse=0.03205239 | val_mse=0.01844048 | best_val_mse=0.01835531 | early_stop=02/10 | 1.2s
    epoch 034/100 | train_mse=0.03197527 | val_mse=0.01835995 | best_val_mse=0.01835531 | early_stop=03/10 | 1.2s
    epoch 035/100 | train_mse=0.03206921 | val_mse=0.01857014 | best_val_mse=0.01835531 | early_stop=04/10 | 1.3s
    epoch 036/100 | train_mse=0.03200600 | val_mse=0.01835362 | best_val_mse=0.01835362 | early_stop=00/10 | 1.3s
    epoch 037/100 | train_mse=0.03196486 | val_mse=0.01838919 | best_val_mse=0.01835362 | early_stop=01/10 | 1.3s
    epoch 038/100 | train_mse=0.03194089 | val_mse=0.01841571 | best_val_mse=0.01835362 | early_stop=02/10 | 1.3s
    epoch 039/100 | train_mse=0.03190940 | val_mse=0.01837572 | best_val_mse=0.01835362 | early_stop=03/10 | 1.3s
    epoch 040/100 | train_mse=0.03209453 | val_mse=0.01838275 | best_val_mse=0.01835362 | early_stop=04/10 | 1.3s
    epoch 041/100 | train_mse=0.03191872 | val_mse=0.01841508 | best_val_mse=0.01835362 | early_stop=05/10 | 1.2s
    epoch 042/100 | train_mse=0.03190778 | val_mse=0.01845835 | best_val_mse=0.01835362 | early_stop=06/10 | 1.2s
    epoch 043/100 | train_mse=0.03201951 | val_mse=0.01836370 | best_val_mse=0.01835362 | early_stop=07/10 | 1.3s
    epoch 044/100 | train_mse=0.03188790 | val_mse=0.01841144 | best_val_mse=0.01835362 | early_stop=08/10 | 1.3s
    epoch 045/100 | train_mse=0.03183168 | val_mse=0.01859993 | best_val_mse=0.01835362 | early_stop=09/10 | 1.2s
    epoch 046/100 | train_mse=0.03205130 | val_mse=0.01847486 | best_val_mse=0.01835362 | early_stop=10/10 | 1.2s
  refit 20/26 | test_year=2018 | status=saved | n_predictions=45,340
  refit 21/26 | test_year=2019 | status=training | train_n=781,180 | validation_n=179,655 | test_n=46,350

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02970144 | val_mse=0.01952429 | best_val_mse=0.01952429 | early_stop=00/10 | 1.2s
    epoch 002/100 | train_mse=0.02953463 | val_mse=0.01949999 | best_val_mse=0.01949999 | early_stop=00/10 | 1.2s
    epoch 003/100 | train_mse=0.02945558 | val_mse=0.01945423 | best_val_mse=0.01945423 | early_stop=00/10 | 1.2s
    epoch 004/100 | train_mse=0.02949282 | val_mse=0.01945820 | best_val_mse=0.01945423 | early_stop=01/10 | 1.2s
    epoch 005/100 | train_mse=0.02940925 | val_mse=0.01948545 | best_val_mse=0.01945423 | early_stop=02/10 | 1.2s
    epoch 006/100 | train_mse=0.02938922 | val_mse=0.01944957 | best_val_mse=0.01944957 | early_stop=00/10 | 1.2s
    epoch 007/100 | train_mse=0.02943349 | val_mse=0.01945416 | best_val_mse=0.01944957 | early_stop=01/10 | 1.2s
    epoch 008/100 | train_mse=0.02938231 | val_mse=0.01942683 | best_val_mse=0.01942683 | early_stop=00/10 | 1.3s
    epoch 009/100 | train_mse=0.02938155 | val_mse=0.01952880 | best_val_mse=0.01942683 | early_stop=01/10 | 1.2s
    epoch 010/100 | train_mse=0.02940332 | val_mse=0.01942258 | best_val_mse=0.01942258 | early_stop=00/10 | 1.2s
    epoch 011/100 | train_mse=0.02935217 | val_mse=0.01951342 | best_val_mse=0.01942258 | early_stop=01/10 | 1.2s
    epoch 012/100 | train_mse=0.02937277 | val_mse=0.01942721 | best_val_mse=0.01942258 | early_stop=02/10 | 1.2s
    epoch 013/100 | train_mse=0.02937525 | val_mse=0.01944091 | best_val_mse=0.01942258 | early_stop=03/10 | 1.2s
    epoch 014/100 | train_mse=0.02938965 | val_mse=0.01942771 | best_val_mse=0.01942258 | early_stop=04/10 | 1.2s
    epoch 015/100 | train_mse=0.02933397 | val_mse=0.01942249 | best_val_mse=0.01942249 | early_stop=00/10 | 1.2s
    epoch 016/100 | train_mse=0.02936932 | val_mse=0.01946499 | best_val_mse=0.01942249 | early_stop=01/10 | 1.2s
    epoch 017/100 | train_mse=0.02938666 | val_mse=0.01941861 | best_val_mse=0.01941861 | early_stop=00/10 | 1.3s
    epoch 018/100 | train_mse=0.02931658 | val_mse=0.01944871 | best_val_mse=0.01941861 | early_stop=01/10 | 1.3s
    epoch 019/100 | train_mse=0.02931478 | val_mse=0.01942439 | best_val_mse=0.01941861 | early_stop=02/10 | 1.2s
    epoch 020/100 | train_mse=0.02938335 | val_mse=0.01948383 | best_val_mse=0.01941861 | early_stop=03/10 | 1.2s
    epoch 021/100 | train_mse=0.02929170 | val_mse=0.01941513 | best_val_mse=0.01941513 | early_stop=00/10 | 1.3s
    epoch 022/100 | train_mse=0.02930569 | val_mse=0.01948334 | best_val_mse=0.01941513 | early_stop=01/10 | 1.3s
    epoch 023/100 | train_mse=0.02932357 | val_mse=0.01941674 | best_val_mse=0.01941513 | early_stop=02/10 | 1.2s
    epoch 024/100 | train_mse=0.02936717 | val_mse=0.01943840 | best_val_mse=0.01941513 | early_stop=03/10 | 1.2s
    epoch 025/100 | train_mse=0.02934307 | val_mse=0.01940958 | best_val_mse=0.01940958 | early_stop=00/10 | 1.2s
    epoch 026/100 | train_mse=0.02932225 | val_mse=0.01941560 | best_val_mse=0.01940958 | early_stop=01/10 | 1.2s
    epoch 027/100 | train_mse=0.02934658 | val_mse=0.01941457 | best_val_mse=0.01940958 | early_stop=02/10 | 1.3s
    epoch 028/100 | train_mse=0.02942836 | val_mse=0.01943266 | best_val_mse=0.01940958 | early_stop=03/10 | 1.3s
    epoch 029/100 | train_mse=0.02928724 | val_mse=0.01943673 | best_val_mse=0.01940958 | early_stop=04/10 | 1.3s
    epoch 030/100 | train_mse=0.02926222 | val_mse=0.01943107 | best_val_mse=0.01940958 | early_stop=05/10 | 1.3s
    epoch 031/100 | train_mse=0.02924483 | val_mse=0.01942675 | best_val_mse=0.01940958 | early_stop=06/10 | 1.3s
    epoch 032/100 | train_mse=0.02926656 | val_mse=0.01943448 | best_val_mse=0.01940958 | early_stop=07/10 | 1.3s
    epoch 033/100 | train_mse=0.02923317 | val_mse=0.01942146 | best_val_mse=0.01940958 | early_stop=08/10 | 1.3s
    epoch 034/100 | train_mse=0.02919808 | val_mse=0.01942914 | best_val_mse=0.01940958 | early_stop=09/10 | 1.3s
    epoch 035/100 | train_mse=0.02919332 | val_mse=0.01943788 | best_val_mse=0.01940958 | early_stop=10/10 | 1.2s
  refit 21/26 | test_year=2019 | status=saved | n_predictions=46,350
  refit 22/26 | test_year=2020 | status=training | train_n=752,961 | validation_n=178,743 | test_n=48,260

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02497018 | val_mse=0.02333239 | best_val_mse=0.02333239 | early_stop=00/10 | 1.3s
    epoch 002/100 | train_mse=0.02462374 | val_mse=0.02324016 | best_val_mse=0.02324016 | early_stop=00/10 | 1.3s
    epoch 003/100 | train_mse=0.02461006 | val_mse=0.02325808 | best_val_mse=0.02324016 | early_stop=01/10 | 1.2s
    epoch 004/100 | train_mse=0.02456908 | val_mse=0.02320520 | best_val_mse=0.02320520 | early_stop=00/10 | 1.2s
    epoch 005/100 | train_mse=0.02452159 | val_mse=0.02316013 | best_val_mse=0.02316013 | early_stop=00/10 | 1.2s
    epoch 006/100 | train_mse=0.02449444 | val_mse=0.02313856 | best_val_mse=0.02313856 | early_stop=00/10 | 1.3s
    epoch 007/100 | train_mse=0.02452279 | val_mse=0.02313834 | best_val_mse=0.02313834 | early_stop=00/10 | 1.3s
    epoch 008/100 | train_mse=0.02452232 | val_mse=0.02316759 | best_val_mse=0.02313834 | early_stop=01/10 | 1.3s
    epoch 009/100 | train_mse=0.02445577 | val_mse=0.02326358 | best_val_mse=0.02313834 | early_stop=02/10 | 1.2s
    epoch 010/100 | train_mse=0.02448332 | val_mse=0.02315208 | best_val_mse=0.02313834 | early_stop=03/10 | 1.3s
    epoch 011/100 | train_mse=0.02445996 | val_mse=0.02317253 | best_val_mse=0.02313834 | early_stop=04/10 | 1.2s
    epoch 012/100 | train_mse=0.02445862 | val_mse=0.02317628 | best_val_mse=0.02313834 | early_stop=05/10 | 1.2s
    epoch 013/100 | train_mse=0.02446936 | val_mse=0.02319881 | best_val_mse=0.02313834 | early_stop=06/10 | 1.2s
    epoch 014/100 | train_mse=0.02448346 | val_mse=0.02313718 | best_val_mse=0.02313718 | early_stop=00/10 | 1.2s
    epoch 015/100 | train_mse=0.02448637 | val_mse=0.02317361 | best_val_mse=0.02313718 | early_stop=01/10 | 1.2s
    epoch 016/100 | train_mse=0.02446448 | val_mse=0.02321211 | best_val_mse=0.02313718 | early_stop=02/10 | 1.2s
    epoch 017/100 | train_mse=0.02442633 | val_mse=0.02313525 | best_val_mse=0.02313525 | early_stop=00/10 | 1.3s
    epoch 018/100 | train_mse=0.02443396 | val_mse=0.02317537 | best_val_mse=0.02313525 | early_stop=01/10 | 1.3s
    epoch 019/100 | train_mse=0.02439558 | val_mse=0.02314753 | best_val_mse=0.02313525 | early_stop=02/10 | 1.2s
    epoch 020/100 | train_mse=0.02447336 | val_mse=0.02315002 | best_val_mse=0.02313525 | early_stop=03/10 | 1.3s
    epoch 021/100 | train_mse=0.02445957 | val_mse=0.02332732 | best_val_mse=0.02313525 | early_stop=04/10 | 1.2s
    epoch 022/100 | train_mse=0.02444541 | val_mse=0.02315093 | best_val_mse=0.02313525 | early_stop=05/10 | 1.2s
    epoch 023/100 | train_mse=0.02437508 | val_mse=0.02319836 | best_val_mse=0.02313525 | early_stop=06/10 | 1.2s
    epoch 024/100 | train_mse=0.02444119 | val_mse=0.02316176 | best_val_mse=0.02313525 | early_stop=07/10 | 1.2s
    epoch 025/100 | train_mse=0.02449083 | val_mse=0.02313130 | best_val_mse=0.02313130 | early_stop=00/10 | 1.2s
    epoch 026/100 | train_mse=0.02435656 | val_mse=0.02322152 | best_val_mse=0.02313130 | early_stop=01/10 | 1.3s
    epoch 027/100 | train_mse=0.02435556 | val_mse=0.02317740 | best_val_mse=0.02313130 | early_stop=02/10 | 1.2s
    epoch 028/100 | train_mse=0.02436785 | val_mse=0.02318270 | best_val_mse=0.02313130 | early_stop=03/10 | 1.2s
    epoch 029/100 | train_mse=0.02435071 | val_mse=0.02325121 | best_val_mse=0.02313130 | early_stop=04/10 | 1.2s
    epoch 030/100 | train_mse=0.02434859 | val_mse=0.02316447 | best_val_mse=0.02313130 | early_stop=05/10 | 1.2s
    epoch 031/100 | train_mse=0.02426000 | val_mse=0.02335266 | best_val_mse=0.02313130 | early_stop=06/10 | 1.2s
    epoch 032/100 | train_mse=0.02425421 | val_mse=0.02323622 | best_val_mse=0.02313130 | early_stop=07/10 | 1.2s
    epoch 033/100 | train_mse=0.02422495 | val_mse=0.02332023 | best_val_mse=0.02313130 | early_stop=08/10 | 1.2s
    epoch 034/100 | train_mse=0.02430828 | val_mse=0.02319428 | best_val_mse=0.02313130 | early_stop=09/10 | 1.2s
    epoch 035/100 | train_mse=0.02413795 | val_mse=0.02334907 | best_val_mse=0.02313130 | early_stop=10/10 | 1.2s
  refit 22/26 | test_year=2020 | status=saved | n_predictions=48,260
  refit 23/26 | test_year=2021 | status=training | train_n=729,092 | validation_n=180,735 | test_n=53,601

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02252765 | val_mse=0.02466058 | best_val_mse=0.02466058 | early_stop=00/10 | 1.3s
    epoch 002/100 | train_mse=0.02242236 | val_mse=0.02465522 | best_val_mse=0.02465522 | early_stop=00/10 | 1.2s
    epoch 003/100 | train_mse=0.02237828 | val_mse=0.02459370 | best_val_mse=0.02459370 | early_stop=00/10 | 1.2s
    epoch 004/100 | train_mse=0.02229577 | val_mse=0.02457954 | best_val_mse=0.02457954 | early_stop=00/10 | 1.3s
    epoch 005/100 | train_mse=0.02236046 | val_mse=0.02457361 | best_val_mse=0.02457361 | early_stop=00/10 | 1.2s
    epoch 006/100 | train_mse=0.02230461 | val_mse=0.02457426 | best_val_mse=0.02457361 | early_stop=01/10 | 1.2s
    epoch 007/100 | train_mse=0.02226817 | val_mse=0.02457766 | best_val_mse=0.02457361 | early_stop=02/10 | 1.3s
    epoch 008/100 | train_mse=0.02230321 | val_mse=0.02463956 | best_val_mse=0.02457361 | early_stop=03/10 | 1.2s
    epoch 009/100 | train_mse=0.02226182 | val_mse=0.02457210 | best_val_mse=0.02457210 | early_stop=00/10 | 1.2s
    epoch 010/100 | train_mse=0.02226279 | val_mse=0.02458188 | best_val_mse=0.02457210 | early_stop=01/10 | 1.2s
    epoch 011/100 | train_mse=0.02225275 | val_mse=0.02457656 | best_val_mse=0.02457210 | early_stop=02/10 | 1.2s
    epoch 012/100 | train_mse=0.02228554 | val_mse=0.02457280 | best_val_mse=0.02457210 | early_stop=03/10 | 1.2s
    epoch 013/100 | train_mse=0.02227362 | val_mse=0.02458021 | best_val_mse=0.02457210 | early_stop=04/10 | 1.2s
    epoch 014/100 | train_mse=0.02226606 | val_mse=0.02456652 | best_val_mse=0.02456652 | early_stop=00/10 | 1.2s
    epoch 015/100 | train_mse=0.02229895 | val_mse=0.02464315 | best_val_mse=0.02456652 | early_stop=01/10 | 1.2s
    epoch 016/100 | train_mse=0.02227366 | val_mse=0.02456892 | best_val_mse=0.02456652 | early_stop=02/10 | 1.2s
    epoch 017/100 | train_mse=0.02222960 | val_mse=0.02456068 | best_val_mse=0.02456068 | early_stop=00/10 | 1.3s
    epoch 018/100 | train_mse=0.02225266 | val_mse=0.02457594 | best_val_mse=0.02456068 | early_stop=01/10 | 1.3s
    epoch 019/100 | train_mse=0.02224320 | val_mse=0.02455972 | best_val_mse=0.02455972 | early_stop=00/10 | 1.2s
    epoch 020/100 | train_mse=0.02223304 | val_mse=0.02457413 | best_val_mse=0.02455972 | early_stop=01/10 | 1.2s
    epoch 021/100 | train_mse=0.02228379 | val_mse=0.02456951 | best_val_mse=0.02455972 | early_stop=02/10 | 1.2s
    epoch 022/100 | train_mse=0.02220981 | val_mse=0.02459303 | best_val_mse=0.02455972 | early_stop=03/10 | 1.2s
    epoch 023/100 | train_mse=0.02222345 | val_mse=0.02458680 | best_val_mse=0.02455972 | early_stop=04/10 | 1.2s
    epoch 024/100 | train_mse=0.02221363 | val_mse=0.02459302 | best_val_mse=0.02455972 | early_stop=05/10 | 1.2s
    epoch 025/100 | train_mse=0.02220848 | val_mse=0.02458981 | best_val_mse=0.02455972 | early_stop=06/10 | 1.2s
    epoch 026/100 | train_mse=0.02219382 | val_mse=0.02458495 | best_val_mse=0.02455972 | early_stop=07/10 | 1.2s
    epoch 027/100 | train_mse=0.02219119 | val_mse=0.02460704 | best_val_mse=0.02455972 | early_stop=08/10 | 1.3s
    epoch 028/100 | train_mse=0.02221448 | val_mse=0.02462020 | best_val_mse=0.02455972 | early_stop=09/10 | 1.3s
    epoch 029/100 | train_mse=0.02223650 | val_mse=0.02457446 | best_val_mse=0.02455972 | early_stop=10/10 | 1.2s
  refit 23/26 | test_year=2021 | status=saved | n_predictions=53,601
  refit 24/26 | test_year=2022 | status=training | train_n=714,648 | validation_n=189,194 | test_n=56,253

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02142373 | val_mse=0.04299738 | best_val_mse=0.04299738 | early_stop=00/10 | 1.2s
    epoch 002/100 | train_mse=0.02117377 | val_mse=0.04288314 | best_val_mse=0.04288314 | early_stop=00/10 | 1.2s
    epoch 003/100 | train_mse=0.02122462 | val_mse=0.04288875 | best_val_mse=0.04288314 | early_stop=01/10 | 1.2s
    epoch 004/100 | train_mse=0.02128868 | val_mse=0.04280877 | best_val_mse=0.04280877 | early_stop=00/10 | 1.3s
    epoch 005/100 | train_mse=0.02112333 | val_mse=0.04280778 | best_val_mse=0.04280778 | early_stop=00/10 | 1.2s
    epoch 006/100 | train_mse=0.02110573 | val_mse=0.04279760 | best_val_mse=0.04279760 | early_stop=00/10 | 1.2s
    epoch 007/100 | train_mse=0.02107409 | val_mse=0.04283381 | best_val_mse=0.04279760 | early_stop=01/10 | 1.2s
    epoch 008/100 | train_mse=0.02110852 | val_mse=0.04281901 | best_val_mse=0.04279760 | early_stop=02/10 | 1.2s
    epoch 009/100 | train_mse=0.02107336 | val_mse=0.04282194 | best_val_mse=0.04279760 | early_stop=03/10 | 1.2s
    epoch 010/100 | train_mse=0.02106429 | val_mse=0.04282599 | best_val_mse=0.04279760 | early_stop=04/10 | 1.2s
    epoch 011/100 | train_mse=0.02106373 | val_mse=0.04279087 | best_val_mse=0.04279087 | early_stop=00/10 | 1.2s
    epoch 012/100 | train_mse=0.02108343 | val_mse=0.04282474 | best_val_mse=0.04279087 | early_stop=01/10 | 1.2s
    epoch 013/100 | train_mse=0.02107846 | val_mse=0.04291027 | best_val_mse=0.04279087 | early_stop=02/10 | 1.2s
    epoch 014/100 | train_mse=0.02106743 | val_mse=0.04281793 | best_val_mse=0.04279087 | early_stop=03/10 | 1.2s
    epoch 015/100 | train_mse=0.02105630 | val_mse=0.04286200 | best_val_mse=0.04279087 | early_stop=04/10 | 1.2s
    epoch 016/100 | train_mse=0.02105811 | val_mse=0.04287276 | best_val_mse=0.04279087 | early_stop=05/10 | 1.2s
    epoch 017/100 | train_mse=0.02107801 | val_mse=0.04282636 | best_val_mse=0.04279087 | early_stop=06/10 | 1.2s
    epoch 018/100 | train_mse=0.02103069 | val_mse=0.04282689 | best_val_mse=0.04279087 | early_stop=07/10 | 1.2s
    epoch 019/100 | train_mse=0.02102112 | val_mse=0.04279956 | best_val_mse=0.04279087 | early_stop=08/10 | 1.2s
    epoch 020/100 | train_mse=0.02109043 | val_mse=0.04279928 | best_val_mse=0.04279087 | early_stop=09/10 | 1.2s
    epoch 021/100 | train_mse=0.02108826 | val_mse=0.04277207 | best_val_mse=0.04277207 | early_stop=00/10 | 1.3s
    epoch 022/100 | train_mse=0.02106145 | val_mse=0.04283545 | best_val_mse=0.04277207 | early_stop=01/10 | 1.2s
    epoch 023/100 | train_mse=0.02101947 | val_mse=0.04285537 | best_val_mse=0.04277207 | early_stop=02/10 | 1.2s
    epoch 024/100 | train_mse=0.02104349 | val_mse=0.04280438 | best_val_mse=0.04277207 | early_stop=03/10 | 1.2s
    epoch 025/100 | train_mse=0.02101145 | val_mse=0.04280107 | best_val_mse=0.04277207 | early_stop=04/10 | 1.2s
    epoch 026/100 | train_mse=0.02100763 | val_mse=0.04280830 | best_val_mse=0.04277207 | early_stop=05/10 | 1.2s
    epoch 027/100 | train_mse=0.02101957 | val_mse=0.04303596 | best_val_mse=0.04277207 | early_stop=06/10 | 1.2s
    epoch 028/100 | train_mse=0.02102006 | val_mse=0.04280732 | best_val_mse=0.04277207 | early_stop=07/10 | 1.2s
    epoch 029/100 | train_mse=0.02103179 | val_mse=0.04284411 | best_val_mse=0.04277207 | early_stop=08/10 | 1.2s
    epoch 030/100 | train_mse=0.02101009 | val_mse=0.04282702 | best_val_mse=0.04277207 | early_stop=09/10 | 1.2s
    epoch 031/100 | train_mse=0.02097870 | val_mse=0.04280925 | best_val_mse=0.04277207 | early_stop=10/10 | 1.2s
  refit 24/26 | test_year=2022 | status=saved | n_predictions=56,253
  refit 25/26 | test_year=2023 | status=training | train_n=705,086 | validation_n=200,324 | test_n=53,289

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02172687 | val_mse=0.04127038 | best_val_mse=0.04127038 | early_stop=00/10 | 1.2s
    epoch 002/100 | train_mse=0.02141745 | val_mse=0.04117360 | best_val_mse=0.04117360 | early_stop=00/10 | 1.2s
    epoch 003/100 | train_mse=0.02137992 | val_mse=0.04109429 | best_val_mse=0.04109429 | early_stop=00/10 | 1.2s
    epoch 004/100 | train_mse=0.02140550 | val_mse=0.04125171 | best_val_mse=0.04109429 | early_stop=01/10 | 1.2s
    epoch 005/100 | train_mse=0.02138756 | val_mse=0.04114783 | best_val_mse=0.04109429 | early_stop=02/10 | 1.2s
    epoch 006/100 | train_mse=0.02134193 | val_mse=0.04128418 | best_val_mse=0.04109429 | early_stop=03/10 | 1.2s
    epoch 007/100 | train_mse=0.02134742 | val_mse=0.04106515 | best_val_mse=0.04106515 | early_stop=00/10 | 1.2s
    epoch 008/100 | train_mse=0.02132868 | val_mse=0.04112927 | best_val_mse=0.04106515 | early_stop=01/10 | 1.2s
    epoch 009/100 | train_mse=0.02131356 | val_mse=0.04112838 | best_val_mse=0.04106515 | early_stop=02/10 | 1.2s
    epoch 010/100 | train_mse=0.02131986 | val_mse=0.04112128 | best_val_mse=0.04106515 | early_stop=03/10 | 1.2s
    epoch 011/100 | train_mse=0.02131275 | val_mse=0.04114041 | best_val_mse=0.04106515 | early_stop=04/10 | 1.2s
    epoch 012/100 | train_mse=0.02131455 | val_mse=0.04106726 | best_val_mse=0.04106515 | early_stop=05/10 | 1.2s
    epoch 013/100 | train_mse=0.02133113 | val_mse=0.04125823 | best_val_mse=0.04106515 | early_stop=06/10 | 1.2s
    epoch 014/100 | train_mse=0.02131939 | val_mse=0.04111712 | best_val_mse=0.04106515 | early_stop=07/10 | 1.2s
    epoch 015/100 | train_mse=0.02130023 | val_mse=0.04112868 | best_val_mse=0.04106515 | early_stop=08/10 | 1.2s
    epoch 016/100 | train_mse=0.02128366 | val_mse=0.04111561 | best_val_mse=0.04106515 | early_stop=09/10 | 1.2s
    epoch 017/100 | train_mse=0.02129287 | val_mse=0.04106075 | best_val_mse=0.04106075 | early_stop=00/10 | 1.2s
    epoch 018/100 | train_mse=0.02129802 | val_mse=0.04109227 | best_val_mse=0.04106075 | early_stop=01/10 | 1.2s
    epoch 019/100 | train_mse=0.02130343 | val_mse=0.04111560 | best_val_mse=0.04106075 | early_stop=02/10 | 1.2s
    epoch 020/100 | train_mse=0.02128375 | val_mse=0.04111456 | best_val_mse=0.04106075 | early_stop=03/10 | 1.2s
    epoch 021/100 | train_mse=0.02130609 | val_mse=0.04111979 | best_val_mse=0.04106075 | early_stop=04/10 | 1.2s
    epoch 022/100 | train_mse=0.02126584 | val_mse=0.04104606 | best_val_mse=0.04104606 | early_stop=00/10 | 1.2s
    epoch 023/100 | train_mse=0.02126849 | val_mse=0.04119949 | best_val_mse=0.04104606 | early_stop=01/10 | 1.2s
    epoch 024/100 | train_mse=0.02127170 | val_mse=0.04108115 | best_val_mse=0.04104606 | early_stop=02/10 | 1.2s
    epoch 025/100 | train_mse=0.02128473 | val_mse=0.04116883 | best_val_mse=0.04104606 | early_stop=03/10 | 1.2s
    epoch 026/100 | train_mse=0.02126740 | val_mse=0.04110735 | best_val_mse=0.04104606 | early_stop=04/10 | 1.2s
    epoch 027/100 | train_mse=0.02127859 | val_mse=0.04114205 | best_val_mse=0.04104606 | early_stop=05/10 | 1.2s
    epoch 028/100 | train_mse=0.02125847 | val_mse=0.04115526 | best_val_mse=0.04104606 | early_stop=06/10 | 1.2s
    epoch 029/100 | train_mse=0.02124355 | val_mse=0.04113323 | best_val_mse=0.04104606 | early_stop=07/10 | 1.2s
    epoch 030/100 | train_mse=0.02122591 | val_mse=0.04103441 | best_val_mse=0.04103441 | early_stop=00/10 | 1.2s
    epoch 031/100 | train_mse=0.02128556 | val_mse=0.04115354 | best_val_mse=0.04103441 | early_stop=01/10 | 1.2s
    epoch 032/100 | train_mse=0.02129940 | val_mse=0.04130368 | best_val_mse=0.04103441 | early_stop=02/10 | 1.2s
    epoch 033/100 | train_mse=0.02127565 | val_mse=0.04107169 | best_val_mse=0.04103441 | early_stop=03/10 | 1.2s
    epoch 034/100 | train_mse=0.02126385 | val_mse=0.04108906 | best_val_mse=0.04103441 | early_stop=04/10 | 1.2s
    epoch 035/100 | train_mse=0.02121966 | val_mse=0.04103901 | best_val_mse=0.04103441 | early_stop=05/10 | 1.2s
    epoch 036/100 | train_mse=0.02118776 | val_mse=0.04105909 | best_val_mse=0.04103441 | early_stop=06/10 | 1.2s
    epoch 037/100 | train_mse=0.02119505 | val_mse=0.04108325 | best_val_mse=0.04103441 | early_stop=07/10 | 1.2s
    epoch 038/100 | train_mse=0.02117000 | val_mse=0.04096977 | best_val_mse=0.04096977 | early_stop=00/10 | 1.2s
    epoch 039/100 | train_mse=0.02114129 | val_mse=0.04107870 | best_val_mse=0.04096977 | early_stop=01/10 | 1.2s
    epoch 040/100 | train_mse=0.02122235 | val_mse=0.04098561 | best_val_mse=0.04096977 | early_stop=02/10 | 1.2s
    epoch 041/100 | train_mse=0.02116711 | val_mse=0.04102512 | best_val_mse=0.04096977 | early_stop=03/10 | 1.2s
    epoch 042/100 | train_mse=0.02116788 | val_mse=0.04112941 | best_val_mse=0.04096977 | early_stop=04/10 | 1.2s
    epoch 043/100 | train_mse=0.02118954 | val_mse=0.04127764 | best_val_mse=0.04096977 | early_stop=05/10 | 1.2s
    epoch 044/100 | train_mse=0.02123472 | val_mse=0.04109176 | best_val_mse=0.04096977 | early_stop=06/10 | 1.2s
    epoch 045/100 | train_mse=0.02115754 | val_mse=0.04109750 | best_val_mse=0.04096977 | early_stop=07/10 | 1.2s
    epoch 046/100 | train_mse=0.02103927 | val_mse=0.04095594 | best_val_mse=0.04095594 | early_stop=00/10 | 1.2s
    epoch 047/100 | train_mse=0.02103604 | val_mse=0.04088704 | best_val_mse=0.04088704 | early_stop=00/10 | 1.2s
    epoch 048/100 | train_mse=0.02106815 | val_mse=0.04110849 | best_val_mse=0.04088704 | early_stop=01/10 | 1.2s
    epoch 049/100 | train_mse=0.02112943 | val_mse=0.04094983 | best_val_mse=0.04088704 | early_stop=02/10 | 1.2s
    epoch 050/100 | train_mse=0.02102648 | val_mse=0.04088880 | best_val_mse=0.04088704 | early_stop=03/10 | 1.2s
    epoch 051/100 | train_mse=0.02099618 | val_mse=0.04086667 | best_val_mse=0.04086667 | early_stop=00/10 | 1.2s
    epoch 052/100 | train_mse=0.02099133 | val_mse=0.04086480 | best_val_mse=0.04086480 | early_stop=00/10 | 1.2s
    epoch 053/100 | train_mse=0.02101094 | val_mse=0.04092065 | best_val_mse=0.04086480 | early_stop=01/10 | 1.2s
    epoch 054/100 | train_mse=0.02116287 | val_mse=0.04095824 | best_val_mse=0.04086480 | early_stop=02/10 | 1.2s
    epoch 055/100 | train_mse=0.02100526 | val_mse=0.04086103 | best_val_mse=0.04086103 | early_stop=00/10 | 1.2s
    epoch 056/100 | train_mse=0.02093489 | val_mse=0.04095200 | best_val_mse=0.04086103 | early_stop=01/10 | 1.2s
    epoch 057/100 | train_mse=0.02091983 | val_mse=0.04102983 | best_val_mse=0.04086103 | early_stop=02/10 | 1.2s
    epoch 058/100 | train_mse=0.02093126 | val_mse=0.04088172 | best_val_mse=0.04086103 | early_stop=03/10 | 1.2s
    epoch 059/100 | train_mse=0.02098468 | val_mse=0.04106354 | best_val_mse=0.04086103 | early_stop=04/10 | 1.2s
    epoch 060/100 | train_mse=0.02093013 | val_mse=0.04084669 | best_val_mse=0.04084669 | early_stop=00/10 | 1.2s
    epoch 061/100 | train_mse=0.02096048 | val_mse=0.04088136 | best_val_mse=0.04084669 | early_stop=01/10 | 1.2s
    epoch 062/100 | train_mse=0.02091298 | val_mse=0.04108361 | best_val_mse=0.04084669 | early_stop=02/10 | 1.2s
    epoch 063/100 | train_mse=0.02093388 | val_mse=0.04087254 | best_val_mse=0.04084669 | early_stop=03/10 | 1.2s
    epoch 064/100 | train_mse=0.02088472 | val_mse=0.04084290 | best_val_mse=0.04084290 | early_stop=00/10 | 1.2s
    epoch 065/100 | train_mse=0.02087269 | val_mse=0.04086720 | best_val_mse=0.04084290 | early_stop=01/10 | 1.2s
    epoch 066/100 | train_mse=0.02091325 | val_mse=0.04125564 | best_val_mse=0.04084290 | early_stop=02/10 | 1.2s
    epoch 067/100 | train_mse=0.02088068 | val_mse=0.04092735 | best_val_mse=0.04084290 | early_stop=03/10 | 1.2s
    epoch 068/100 | train_mse=0.02091546 | val_mse=0.04084759 | best_val_mse=0.04084290 | early_stop=04/10 | 1.2s
    epoch 069/100 | train_mse=0.02095525 | val_mse=0.04087999 | best_val_mse=0.04084290 | early_stop=05/10 | 1.2s
    epoch 070/100 | train_mse=0.02106293 | val_mse=0.04091286 | best_val_mse=0.04084290 | early_stop=06/10 | 1.2s
    epoch 071/100 | train_mse=0.02091767 | val_mse=0.04090313 | best_val_mse=0.04084290 | early_stop=07/10 | 1.2s
    epoch 072/100 | train_mse=0.02090462 | val_mse=0.04084501 | best_val_mse=0.04084290 | early_stop=08/10 | 1.2s
    epoch 073/100 | train_mse=0.02078506 | val_mse=0.04088780 | best_val_mse=0.04084290 | early_stop=09/10 | 1.2s
    epoch 074/100 | train_mse=0.02081356 | val_mse=0.04088506 | best_val_mse=0.04084290 | early_stop=10/10 | 1.2s
  refit 25/26 | test_year=2023 | status=saved | n_predictions=53,289
  refit 26/26 | test_year=2024 | status=training | train_n=698,959 | validation_n=207,476 | test_n=49,147

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02241022 | val_mse=0.04520828 | best_val_mse=0.04520828 | early_stop=00/10 | 1.2s
    epoch 002/100 | train_mse=0.02221436 | val_mse=0.04500614 | best_val_mse=0.04500614 | early_stop=00/10 | 1.2s
    epoch 003/100 | train_mse=0.02217327 | val_mse=0.04497184 | best_val_mse=0.04497184 | early_stop=00/10 | 1.2s
    epoch 004/100 | train_mse=0.02210548 | val_mse=0.04494789 | best_val_mse=0.04494789 | early_stop=00/10 | 1.3s
    epoch 005/100 | train_mse=0.02212450 | val_mse=0.04492254 | best_val_mse=0.04492254 | early_stop=00/10 | 1.2s
    epoch 006/100 | train_mse=0.02210557 | val_mse=0.04496008 | best_val_mse=0.04492254 | early_stop=01/10 | 1.2s
    epoch 007/100 | train_mse=0.02207549 | val_mse=0.04493835 | best_val_mse=0.04492254 | early_stop=02/10 | 1.2s
    epoch 008/100 | train_mse=0.02209354 | val_mse=0.04494813 | best_val_mse=0.04492254 | early_stop=03/10 | 1.2s
    epoch 009/100 | train_mse=0.02210437 | val_mse=0.04494384 | best_val_mse=0.04492254 | early_stop=04/10 | 1.2s
    epoch 010/100 | train_mse=0.02206804 | val_mse=0.04494669 | best_val_mse=0.04492254 | early_stop=05/10 | 1.2s
    epoch 011/100 | train_mse=0.02205730 | val_mse=0.04494420 | best_val_mse=0.04492254 | early_stop=06/10 | 1.2s
    epoch 012/100 | train_mse=0.02205878 | val_mse=0.04496406 | best_val_mse=0.04492254 | early_stop=07/10 | 1.2s
    epoch 013/100 | train_mse=0.02205761 | val_mse=0.04489421 | best_val_mse=0.04489421 | early_stop=00/10 | 1.2s
    epoch 014/100 | train_mse=0.02203489 | val_mse=0.04488878 | best_val_mse=0.04488878 | early_stop=00/10 | 1.2s
    epoch 015/100 | train_mse=0.02206559 | val_mse=0.04495698 | best_val_mse=0.04488878 | early_stop=01/10 | 1.2s
    epoch 016/100 | train_mse=0.02204425 | val_mse=0.04488458 | best_val_mse=0.04488458 | early_stop=00/10 | 1.2s
    epoch 017/100 | train_mse=0.02206637 | val_mse=0.04491524 | best_val_mse=0.04488458 | early_stop=01/10 | 1.2s
    epoch 018/100 | train_mse=0.02204647 | val_mse=0.04489593 | best_val_mse=0.04488458 | early_stop=02/10 | 1.2s
    epoch 019/100 | train_mse=0.02204208 | val_mse=0.04493283 | best_val_mse=0.04488458 | early_stop=03/10 | 1.2s
    epoch 020/100 | train_mse=0.02201069 | val_mse=0.04488509 | best_val_mse=0.04488458 | early_stop=04/10 | 1.2s
    epoch 021/100 | train_mse=0.02201333 | val_mse=0.04491912 | best_val_mse=0.04488458 | early_stop=05/10 | 1.2s
    epoch 022/100 | train_mse=0.02207856 | val_mse=0.04512753 | best_val_mse=0.04488458 | early_stop=06/10 | 1.2s
    epoch 023/100 | train_mse=0.02208394 | val_mse=0.04490562 | best_val_mse=0.04488458 | early_stop=07/10 | 1.2s
    epoch 024/100 | train_mse=0.02204652 | val_mse=0.04487959 | best_val_mse=0.04487959 | early_stop=00/10 | 1.2s
    epoch 025/100 | train_mse=0.02204592 | val_mse=0.04490480 | best_val_mse=0.04487959 | early_stop=01/10 | 1.2s
    epoch 026/100 | train_mse=0.02200253 | val_mse=0.04487799 | best_val_mse=0.04487799 | early_stop=00/10 | 1.2s
    epoch 027/100 | train_mse=0.02204861 | val_mse=0.04488334 | best_val_mse=0.04487799 | early_stop=01/10 | 1.2s
    epoch 028/100 | train_mse=0.02200343 | val_mse=0.04495532 | best_val_mse=0.04487799 | early_stop=02/10 | 1.2s
    epoch 029/100 | train_mse=0.02201873 | val_mse=0.04487391 | best_val_mse=0.04487391 | early_stop=00/10 | 1.2s
    epoch 030/100 | train_mse=0.02204565 | val_mse=0.04487941 | best_val_mse=0.04487391 | early_stop=01/10 | 1.2s
    epoch 031/100 | train_mse=0.02200047 | val_mse=0.04490258 | best_val_mse=0.04487391 | early_stop=02/10 | 1.2s
    epoch 032/100 | train_mse=0.02201966 | val_mse=0.04491631 | best_val_mse=0.04487391 | early_stop=03/10 | 1.2s
    epoch 033/100 | train_mse=0.02199377 | val_mse=0.04486710 | best_val_mse=0.04486710 | early_stop=00/10 | 1.2s
    epoch 034/100 | train_mse=0.02196333 | val_mse=0.04491748 | best_val_mse=0.04486710 | early_stop=01/10 | 1.2s
    epoch 035/100 | train_mse=0.02200533 | val_mse=0.04488027 | best_val_mse=0.04486710 | early_stop=02/10 | 1.2s
    epoch 036/100 | train_mse=0.02198114 | val_mse=0.04488909 | best_val_mse=0.04486710 | early_stop=03/10 | 1.2s
    epoch 037/100 | train_mse=0.02194045 | val_mse=0.04483041 | best_val_mse=0.04483041 | early_stop=00/10 | 1.2s
    epoch 038/100 | train_mse=0.02194005 | val_mse=0.04486114 | best_val_mse=0.04483041 | early_stop=01/10 | 1.2s
    epoch 039/100 | train_mse=0.02199121 | val_mse=0.04483373 | best_val_mse=0.04483041 | early_stop=02/10 | 1.2s
    epoch 040/100 | train_mse=0.02197681 | val_mse=0.04482556 | best_val_mse=0.04482556 | early_stop=00/10 | 1.2s
    epoch 041/100 | train_mse=0.02191191 | val_mse=0.04487796 | best_val_mse=0.04482556 | early_stop=01/10 | 1.2s
    epoch 042/100 | train_mse=0.02192888 | val_mse=0.04493101 | best_val_mse=0.04482556 | early_stop=02/10 | 1.2s
    epoch 043/100 | train_mse=0.02186559 | val_mse=0.04477725 | best_val_mse=0.04477725 | early_stop=00/10 | 1.2s
    epoch 044/100 | train_mse=0.02184864 | val_mse=0.04508764 | best_val_mse=0.04477725 | early_stop=01/10 | 1.2s
    epoch 045/100 | train_mse=0.02196321 | val_mse=0.04481906 | best_val_mse=0.04477725 | early_stop=02/10 | 1.2s
    epoch 046/100 | train_mse=0.02190633 | val_mse=0.04496755 | best_val_mse=0.04477725 | early_stop=03/10 | 1.2s
    epoch 047/100 | train_mse=0.02187049 | val_mse=0.04478990 | best_val_mse=0.04477725 | early_stop=04/10 | 1.2s
    epoch 048/100 | train_mse=0.02185771 | val_mse=0.04479556 | best_val_mse=0.04477725 | early_stop=05/10 | 1.2s
    epoch 049/100 | train_mse=0.02180956 | val_mse=0.04470103 | best_val_mse=0.04470103 | early_stop=00/10 | 1.2s
    epoch 050/100 | train_mse=0.02178483 | val_mse=0.04471188 | best_val_mse=0.04470103 | early_stop=01/10 | 1.2s
    epoch 051/100 | train_mse=0.02175093 | val_mse=0.04482828 | best_val_mse=0.04470103 | early_stop=02/10 | 1.2s
    epoch 052/100 | train_mse=0.02169456 | val_mse=0.04473890 | best_val_mse=0.04470103 | early_stop=03/10 | 1.2s
    epoch 053/100 | train_mse=0.02169396 | val_mse=0.04493729 | best_val_mse=0.04470103 | early_stop=04/10 | 1.2s
    epoch 054/100 | train_mse=0.02177330 | val_mse=0.04501022 | best_val_mse=0.04470103 | early_stop=05/10 | 1.2s
    epoch 055/100 | train_mse=0.02188129 | val_mse=0.04473783 | best_val_mse=0.04470103 | early_stop=06/10 | 1.2s
    epoch 056/100 | train_mse=0.02175234 | val_mse=0.04483369 | best_val_mse=0.04470103 | early_stop=07/10 | 1.2s
    epoch 057/100 | train_mse=0.02171141 | val_mse=0.04493964 | best_val_mse=0.04470103 | early_stop=08/10 | 1.2s
    epoch 058/100 | train_mse=0.02174181 | val_mse=0.04479525 | best_val_mse=0.04470103 | early_stop=09/10 | 1.2s
    epoch 059/100 | train_mse=0.02164340 | val_mse=0.04480275 | best_val_mse=0.04470103 | early_stop=10/10 | 1.2s
  refit 26/26 | test_year=2024 | status=saved | n_predictions=49,147

=== HYBRID_LGBM40_DEEPSET40_DYNAMIC ===
Device: cuda

HYBRID_LGBM40_DEEPSET40_DYNAMIC [1c0cc8c096b31146]
  refit 01/26 | test_year=1999 | status=training | train_n=861,850 | validation_n=311,524 | test_n=76,150

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02291688 | val_mse=0.02430610 | best_val_mse=0.02430610 | early_stop=00/10 | 1.6s
    epoch 002/100 | train_mse=0.02256140 | val_mse=0.02422961 | best_val_mse=0.02422961 | early_stop=00/10 | 1.5s
    epoch 003/100 | train_mse=0.02242973 | val_mse=0.02403906 | best_val_mse=0.02403906 | early_stop=00/10 | 1.6s
    epoch 004/100 | train_mse=0.02241511 | val_mse=0.02416898 | best_val_mse=0.02403906 | early_stop=01/10 | 1.6s
    epoch 005/100 | train_mse=0.02234397 | val_mse=0.02404757 | best_val_mse=0.02403906 | early_stop=02/10 | 1.5s
    epoch 006/100 | train_mse=0.02226377 | val_mse=0.02391580 | best_val_mse=0.02391580 | early_stop=00/10 | 1.6s
    epoch 007/100 | train_mse=0.02231033 | val_mse=0.02389644 | best_val_mse=0.02389644 | early_stop=00/10 | 1.6s
    epoch 008/100 | train_mse=0.02227541 | val_mse=0.02395511 | best_val_mse=0.02389644 | early_stop=01/10 | 1.6s
    epoch 009/100 | train_mse=0.02229366 | val_mse=0.02403210 | best_val_mse=0.02389644 | early_stop=02/10 | 1.6s
    epoch 010/100 | train_mse=0.02224826 | val_mse=0.02392859 | best_val_mse=0.02389644 | early_stop=03/10 | 1.5s
    epoch 011/100 | train_mse=0.02222371 | val_mse=0.02404421 | best_val_mse=0.02389644 | early_stop=04/10 | 1.5s
    epoch 012/100 | train_mse=0.02226089 | val_mse=0.02395402 | best_val_mse=0.02389644 | early_stop=05/10 | 1.6s
    epoch 013/100 | train_mse=0.02221653 | val_mse=0.02391262 | best_val_mse=0.02389644 | early_stop=06/10 | 1.5s
    epoch 014/100 | train_mse=0.02218756 | val_mse=0.02385107 | best_val_mse=0.02385107 | early_stop=00/10 | 1.5s
    epoch 015/100 | train_mse=0.02218648 | val_mse=0.02410435 | best_val_mse=0.02385107 | early_stop=01/10 | 1.5s
    epoch 016/100 | train_mse=0.02217935 | val_mse=0.02389038 | best_val_mse=0.02385107 | early_stop=02/10 | 1.6s
    epoch 017/100 | train_mse=0.02220563 | val_mse=0.02398622 | best_val_mse=0.02385107 | early_stop=03/10 | 1.6s
    epoch 018/100 | train_mse=0.02218552 | val_mse=0.02389186 | best_val_mse=0.02385107 | early_stop=04/10 | 1.5s
    epoch 019/100 | train_mse=0.02216397 | val_mse=0.02395614 | best_val_mse=0.02385107 | early_stop=05/10 | 1.5s
    epoch 020/100 | train_mse=0.02218615 | val_mse=0.02388807 | best_val_mse=0.02385107 | early_stop=06/10 | 1.6s
    epoch 021/100 | train_mse=0.02214380 | val_mse=0.02394694 | best_val_mse=0.02385107 | early_stop=07/10 | 1.6s
    epoch 022/100 | train_mse=0.02213693 | val_mse=0.02389029 | best_val_mse=0.02385107 | early_stop=08/10 | 1.5s
    epoch 023/100 | train_mse=0.02218685 | val_mse=0.02385682 | best_val_mse=0.02385107 | early_stop=09/10 | 1.5s
    epoch 024/100 | train_mse=0.02218204 | val_mse=0.02393116 | best_val_mse=0.02385107 | early_stop=10/10 | 1.6s
  refit 01/26 | test_year=1999 | status=saved | n_predictions=76,150
  refit 02/26 | test_year=2000 | status=training | train_n=893,802 | validation_n=313,546 | test_n=75,345

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02277006 | val_mse=0.03031906 | best_val_mse=0.03031906 | early_stop=00/10 | 1.6s
    epoch 002/100 | train_mse=0.02259530 | val_mse=0.03008456 | best_val_mse=0.03008456 | early_stop=00/10 | 1.6s
    epoch 003/100 | train_mse=0.02236797 | val_mse=0.03006080 | best_val_mse=0.03006080 | early_stop=00/10 | 1.6s
    epoch 004/100 | train_mse=0.02224236 | val_mse=0.03019425 | best_val_mse=0.03006080 | early_stop=01/10 | 1.6s
    epoch 005/100 | train_mse=0.02230646 | val_mse=0.03015032 | best_val_mse=0.03006080 | early_stop=02/10 | 1.6s
    epoch 006/100 | train_mse=0.02220653 | val_mse=0.03017847 | best_val_mse=0.03006080 | early_stop=03/10 | 1.5s
    epoch 007/100 | train_mse=0.02219891 | val_mse=0.03001197 | best_val_mse=0.03001197 | early_stop=00/10 | 1.6s
    epoch 008/100 | train_mse=0.02218699 | val_mse=0.03007260 | best_val_mse=0.03001197 | early_stop=01/10 | 1.6s
    epoch 009/100 | train_mse=0.02218974 | val_mse=0.03002952 | best_val_mse=0.03001197 | early_stop=02/10 | 1.6s
    epoch 010/100 | train_mse=0.02212438 | val_mse=0.02998267 | best_val_mse=0.02998267 | early_stop=00/10 | 1.6s
    epoch 011/100 | train_mse=0.02212578 | val_mse=0.03001208 | best_val_mse=0.02998267 | early_stop=01/10 | 1.6s
    epoch 012/100 | train_mse=0.02212204 | val_mse=0.03000578 | best_val_mse=0.02998267 | early_stop=02/10 | 1.6s
    epoch 013/100 | train_mse=0.02213116 | val_mse=0.02999896 | best_val_mse=0.02998267 | early_stop=03/10 | 1.6s
    epoch 014/100 | train_mse=0.02212475 | val_mse=0.02998480 | best_val_mse=0.02998267 | early_stop=04/10 | 1.5s
    epoch 015/100 | train_mse=0.02212540 | val_mse=0.02998222 | best_val_mse=0.02998222 | early_stop=00/10 | 1.6s
    epoch 016/100 | train_mse=0.02207639 | val_mse=0.03000375 | best_val_mse=0.02998222 | early_stop=01/10 | 1.6s
    epoch 017/100 | train_mse=0.02210790 | val_mse=0.03000868 | best_val_mse=0.02998222 | early_stop=02/10 | 1.6s
    epoch 018/100 | train_mse=0.02214977 | val_mse=0.02996063 | best_val_mse=0.02996063 | early_stop=00/10 | 1.6s
    epoch 019/100 | train_mse=0.02210530 | val_mse=0.03005505 | best_val_mse=0.02996063 | early_stop=01/10 | 1.5s
    epoch 020/100 | train_mse=0.02209039 | val_mse=0.02998630 | best_val_mse=0.02996063 | early_stop=02/10 | 1.6s
    epoch 021/100 | train_mse=0.02207897 | val_mse=0.02996572 | best_val_mse=0.02996063 | early_stop=03/10 | 1.6s
    epoch 022/100 | train_mse=0.02205483 | val_mse=0.02996797 | best_val_mse=0.02996063 | early_stop=04/10 | 1.5s
    epoch 023/100 | train_mse=0.02205403 | val_mse=0.02998686 | best_val_mse=0.02996063 | early_stop=05/10 | 1.6s
    epoch 024/100 | train_mse=0.02204610 | val_mse=0.02998467 | best_val_mse=0.02996063 | early_stop=06/10 | 1.6s
    epoch 025/100 | train_mse=0.02202796 | val_mse=0.02994754 | best_val_mse=0.02994754 | early_stop=00/10 | 1.6s
    epoch 026/100 | train_mse=0.02203671 | val_mse=0.03000982 | best_val_mse=0.02994754 | early_stop=01/10 | 1.6s
    epoch 027/100 | train_mse=0.02207005 | val_mse=0.03007809 | best_val_mse=0.02994754 | early_stop=02/10 | 1.5s
    epoch 028/100 | train_mse=0.02206409 | val_mse=0.03005946 | best_val_mse=0.02994754 | early_stop=03/10 | 1.6s
    epoch 029/100 | train_mse=0.02201398 | val_mse=0.02996821 | best_val_mse=0.02994754 | early_stop=04/10 | 1.6s
    epoch 030/100 | train_mse=0.02203981 | val_mse=0.02997225 | best_val_mse=0.02994754 | early_stop=05/10 | 1.5s
    epoch 031/100 | train_mse=0.02196863 | val_mse=0.03013171 | best_val_mse=0.02994754 | early_stop=06/10 | 1.6s
    epoch 032/100 | train_mse=0.02205972 | val_mse=0.02999053 | best_val_mse=0.02994754 | early_stop=07/10 | 1.6s
    epoch 033/100 | train_mse=0.02197828 | val_mse=0.02992463 | best_val_mse=0.02992463 | early_stop=00/10 | 1.6s
    epoch 034/100 | train_mse=0.02198399 | val_mse=0.02990795 | best_val_mse=0.02990795 | early_stop=00/10 | 1.6s
    epoch 035/100 | train_mse=0.02199317 | val_mse=0.02991380 | best_val_mse=0.02990795 | early_stop=01/10 | 1.6s
    epoch 036/100 | train_mse=0.02198792 | val_mse=0.02991880 | best_val_mse=0.02990795 | early_stop=02/10 | 1.6s
    epoch 037/100 | train_mse=0.02195919 | val_mse=0.02988594 | best_val_mse=0.02988594 | early_stop=00/10 | 1.6s
    epoch 038/100 | train_mse=0.02196956 | val_mse=0.02986601 | best_val_mse=0.02986601 | early_stop=00/10 | 1.6s
    epoch 039/100 | train_mse=0.02196654 | val_mse=0.02986097 | best_val_mse=0.02986097 | early_stop=00/10 | 1.6s
    epoch 040/100 | train_mse=0.02191831 | val_mse=0.02990240 | best_val_mse=0.02986097 | early_stop=01/10 | 1.6s
    epoch 041/100 | train_mse=0.02190265 | val_mse=0.02982317 | best_val_mse=0.02982317 | early_stop=00/10 | 1.6s
    epoch 042/100 | train_mse=0.02186889 | val_mse=0.02985039 | best_val_mse=0.02982317 | early_stop=01/10 | 1.5s
    epoch 043/100 | train_mse=0.02191129 | val_mse=0.02976732 | best_val_mse=0.02976732 | early_stop=00/10 | 1.6s
    epoch 044/100 | train_mse=0.02203877 | val_mse=0.02980999 | best_val_mse=0.02976732 | early_stop=01/10 | 1.6s
    epoch 045/100 | train_mse=0.02188475 | val_mse=0.02990855 | best_val_mse=0.02976732 | early_stop=02/10 | 1.6s
    epoch 046/100 | train_mse=0.02189668 | val_mse=0.02991026 | best_val_mse=0.02976732 | early_stop=03/10 | 1.6s
    epoch 047/100 | train_mse=0.02183572 | val_mse=0.02978280 | best_val_mse=0.02976732 | early_stop=04/10 | 1.6s
    epoch 048/100 | train_mse=0.02188139 | val_mse=0.03002557 | best_val_mse=0.02976732 | early_stop=05/10 | 1.6s
    epoch 049/100 | train_mse=0.02188210 | val_mse=0.02980620 | best_val_mse=0.02976732 | early_stop=06/10 | 1.6s
    epoch 050/100 | train_mse=0.02183970 | val_mse=0.02992710 | best_val_mse=0.02976732 | early_stop=07/10 | 1.6s
    epoch 051/100 | train_mse=0.02182647 | val_mse=0.02967411 | best_val_mse=0.02967411 | early_stop=00/10 | 1.6s
    epoch 052/100 | train_mse=0.02173350 | val_mse=0.02983905 | best_val_mse=0.02967411 | early_stop=01/10 | 1.6s
    epoch 053/100 | train_mse=0.02186073 | val_mse=0.02968111 | best_val_mse=0.02967411 | early_stop=02/10 | 1.6s
    epoch 054/100 | train_mse=0.02169381 | val_mse=0.02975429 | best_val_mse=0.02967411 | early_stop=03/10 | 1.6s
    epoch 055/100 | train_mse=0.02173192 | val_mse=0.02967863 | best_val_mse=0.02967411 | early_stop=04/10 | 1.6s
    epoch 056/100 | train_mse=0.02166661 | val_mse=0.02962463 | best_val_mse=0.02962463 | early_stop=00/10 | 1.6s
    epoch 057/100 | train_mse=0.02184517 | val_mse=0.02970340 | best_val_mse=0.02962463 | early_stop=01/10 | 1.6s
    epoch 058/100 | train_mse=0.02164067 | val_mse=0.02963147 | best_val_mse=0.02962463 | early_stop=02/10 | 1.6s
    epoch 059/100 | train_mse=0.02165233 | val_mse=0.02994504 | best_val_mse=0.02962463 | early_stop=03/10 | 1.6s
    epoch 060/100 | train_mse=0.02161438 | val_mse=0.02962525 | best_val_mse=0.02962463 | early_stop=04/10 | 1.6s
    epoch 061/100 | train_mse=0.02160711 | val_mse=0.02975016 | best_val_mse=0.02962463 | early_stop=05/10 | 1.6s
    epoch 062/100 | train_mse=0.02162779 | val_mse=0.02966035 | best_val_mse=0.02962463 | early_stop=06/10 | 1.6s
    epoch 063/100 | train_mse=0.02160301 | val_mse=0.02961067 | best_val_mse=0.02961067 | early_stop=00/10 | 1.7s
    epoch 064/100 | train_mse=0.02163072 | val_mse=0.02970700 | best_val_mse=0.02961067 | early_stop=01/10 | 1.6s
    epoch 065/100 | train_mse=0.02158063 | val_mse=0.03017177 | best_val_mse=0.02961067 | early_stop=02/10 | 1.6s
    epoch 066/100 | train_mse=0.02162716 | val_mse=0.02970354 | best_val_mse=0.02961067 | early_stop=03/10 | 1.6s
    epoch 067/100 | train_mse=0.02155908 | val_mse=0.02966035 | best_val_mse=0.02961067 | early_stop=04/10 | 1.6s
    epoch 068/100 | train_mse=0.02173201 | val_mse=0.02971683 | best_val_mse=0.02961067 | early_stop=05/10 | 1.6s
    epoch 069/100 | train_mse=0.02155361 | val_mse=0.02968570 | best_val_mse=0.02961067 | early_stop=06/10 | 1.6s
    epoch 070/100 | train_mse=0.02158528 | val_mse=0.02963331 | best_val_mse=0.02961067 | early_stop=07/10 | 1.6s
    epoch 071/100 | train_mse=0.02151562 | val_mse=0.02972694 | best_val_mse=0.02961067 | early_stop=08/10 | 1.6s
    epoch 072/100 | train_mse=0.02149445 | val_mse=0.02964293 | best_val_mse=0.02961067 | early_stop=09/10 | 1.6s
    epoch 073/100 | train_mse=0.02146781 | val_mse=0.02987692 | best_val_mse=0.02961067 | early_stop=10/10 | 1.6s
  refit 02/26 | test_year=2000 | status=saved | n_predictions=75,345
  refit 03/26 | test_year=2001 | status=training | train_n=928,527 | validation_n=309,376 | test_n=69,652

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02374360 | val_mse=0.03732481 | best_val_mse=0.03732481 | early_stop=00/10 | 1.6s
    epoch 002/100 | train_mse=0.02322346 | val_mse=0.03744665 | best_val_mse=0.03732481 | early_stop=01/10 | 1.7s
    epoch 003/100 | train_mse=0.02325830 | val_mse=0.03725682 | best_val_mse=0.03725682 | early_stop=00/10 | 1.7s
    epoch 004/100 | train_mse=0.02305257 | val_mse=0.03738163 | best_val_mse=0.03725682 | early_stop=01/10 | 1.6s
    epoch 005/100 | train_mse=0.02308809 | val_mse=0.03723260 | best_val_mse=0.03723260 | early_stop=00/10 | 1.7s
    epoch 006/100 | train_mse=0.02302556 | val_mse=0.03725336 | best_val_mse=0.03723260 | early_stop=01/10 | 1.7s
    epoch 007/100 | train_mse=0.02297125 | val_mse=0.03740023 | best_val_mse=0.03723260 | early_stop=02/10 | 1.6s
    epoch 008/100 | train_mse=0.02304687 | val_mse=0.03721916 | best_val_mse=0.03721916 | early_stop=00/10 | 1.6s
    epoch 009/100 | train_mse=0.02298957 | val_mse=0.03728794 | best_val_mse=0.03721916 | early_stop=01/10 | 1.6s
    epoch 010/100 | train_mse=0.02297136 | val_mse=0.03718784 | best_val_mse=0.03718784 | early_stop=00/10 | 1.7s
    epoch 011/100 | train_mse=0.02301156 | val_mse=0.03723625 | best_val_mse=0.03718784 | early_stop=01/10 | 1.6s
    epoch 012/100 | train_mse=0.02295904 | val_mse=0.03718557 | best_val_mse=0.03718557 | early_stop=00/10 | 1.6s
    epoch 013/100 | train_mse=0.02292710 | val_mse=0.03716697 | best_val_mse=0.03716697 | early_stop=00/10 | 1.7s
    epoch 014/100 | train_mse=0.02294640 | val_mse=0.03735136 | best_val_mse=0.03716697 | early_stop=01/10 | 1.6s
    epoch 015/100 | train_mse=0.02296113 | val_mse=0.03720713 | best_val_mse=0.03716697 | early_stop=02/10 | 1.6s
    epoch 016/100 | train_mse=0.02291078 | val_mse=0.03717218 | best_val_mse=0.03716697 | early_stop=03/10 | 1.6s
    epoch 017/100 | train_mse=0.02290418 | val_mse=0.03717840 | best_val_mse=0.03716697 | early_stop=04/10 | 1.6s
    epoch 018/100 | train_mse=0.02288854 | val_mse=0.03715808 | best_val_mse=0.03715808 | early_stop=00/10 | 1.7s
    epoch 019/100 | train_mse=0.02289425 | val_mse=0.03714106 | best_val_mse=0.03714106 | early_stop=00/10 | 1.6s
    epoch 020/100 | train_mse=0.02288168 | val_mse=0.03714828 | best_val_mse=0.03714106 | early_stop=01/10 | 1.6s
    epoch 021/100 | train_mse=0.02293350 | val_mse=0.03714921 | best_val_mse=0.03714106 | early_stop=02/10 | 1.6s
    epoch 022/100 | train_mse=0.02287073 | val_mse=0.03716113 | best_val_mse=0.03714106 | early_stop=03/10 | 1.6s
    epoch 023/100 | train_mse=0.02287027 | val_mse=0.03727570 | best_val_mse=0.03714106 | early_stop=04/10 | 1.6s
    epoch 024/100 | train_mse=0.02291369 | val_mse=0.03717771 | best_val_mse=0.03714106 | early_stop=05/10 | 1.6s
    epoch 025/100 | train_mse=0.02284898 | val_mse=0.03712768 | best_val_mse=0.03712768 | early_stop=00/10 | 1.7s
    epoch 026/100 | train_mse=0.02289309 | val_mse=0.03713186 | best_val_mse=0.03712768 | early_stop=01/10 | 1.6s
    epoch 027/100 | train_mse=0.02285109 | val_mse=0.03725932 | best_val_mse=0.03712768 | early_stop=02/10 | 1.6s
    epoch 028/100 | train_mse=0.02285206 | val_mse=0.03714020 | best_val_mse=0.03712768 | early_stop=03/10 | 1.6s
    epoch 029/100 | train_mse=0.02290525 | val_mse=0.03719924 | best_val_mse=0.03712768 | early_stop=04/10 | 1.6s
    epoch 030/100 | train_mse=0.02285667 | val_mse=0.03714838 | best_val_mse=0.03712768 | early_stop=05/10 | 1.6s
    epoch 031/100 | train_mse=0.02283288 | val_mse=0.03711851 | best_val_mse=0.03711851 | early_stop=00/10 | 1.6s
    epoch 032/100 | train_mse=0.02281775 | val_mse=0.03708647 | best_val_mse=0.03708647 | early_stop=00/10 | 1.6s
    epoch 033/100 | train_mse=0.02279027 | val_mse=0.03718902 | best_val_mse=0.03708647 | early_stop=01/10 | 1.6s
    epoch 034/100 | train_mse=0.02279232 | val_mse=0.03709685 | best_val_mse=0.03708647 | early_stop=02/10 | 1.6s
    epoch 035/100 | train_mse=0.02277223 | val_mse=0.03710168 | best_val_mse=0.03708647 | early_stop=03/10 | 1.6s
    epoch 036/100 | train_mse=0.02276168 | val_mse=0.03721734 | best_val_mse=0.03708647 | early_stop=04/10 | 1.7s
    epoch 037/100 | train_mse=0.02284398 | val_mse=0.03711411 | best_val_mse=0.03708647 | early_stop=05/10 | 1.6s
    epoch 038/100 | train_mse=0.02281036 | val_mse=0.03706255 | best_val_mse=0.03706255 | early_stop=00/10 | 1.6s
    epoch 039/100 | train_mse=0.02275902 | val_mse=0.03706193 | best_val_mse=0.03706193 | early_stop=00/10 | 1.6s
    epoch 040/100 | train_mse=0.02277830 | val_mse=0.03707472 | best_val_mse=0.03706193 | early_stop=01/10 | 1.6s
    epoch 041/100 | train_mse=0.02271698 | val_mse=0.03703927 | best_val_mse=0.03703927 | early_stop=00/10 | 1.7s
    epoch 042/100 | train_mse=0.02273215 | val_mse=0.03704115 | best_val_mse=0.03703927 | early_stop=01/10 | 1.6s
    epoch 043/100 | train_mse=0.02272944 | val_mse=0.03701807 | best_val_mse=0.03701807 | early_stop=00/10 | 1.7s
    epoch 044/100 | train_mse=0.02271465 | val_mse=0.03708730 | best_val_mse=0.03701807 | early_stop=01/10 | 1.7s
    epoch 045/100 | train_mse=0.02269775 | val_mse=0.03706449 | best_val_mse=0.03701807 | early_stop=02/10 | 1.6s
    epoch 046/100 | train_mse=0.02274989 | val_mse=0.03701295 | best_val_mse=0.03701295 | early_stop=00/10 | 1.6s
    epoch 047/100 | train_mse=0.02266349 | val_mse=0.03701205 | best_val_mse=0.03701205 | early_stop=00/10 | 1.6s
    epoch 048/100 | train_mse=0.02269492 | val_mse=0.03693265 | best_val_mse=0.03693265 | early_stop=00/10 | 1.6s
    epoch 049/100 | train_mse=0.02267397 | val_mse=0.03694542 | best_val_mse=0.03693265 | early_stop=01/10 | 1.6s
    epoch 050/100 | train_mse=0.02267076 | val_mse=0.03690003 | best_val_mse=0.03690003 | early_stop=00/10 | 1.7s
    epoch 051/100 | train_mse=0.02260744 | val_mse=0.03693564 | best_val_mse=0.03690003 | early_stop=01/10 | 1.7s
    epoch 052/100 | train_mse=0.02264572 | val_mse=0.03693889 | best_val_mse=0.03690003 | early_stop=02/10 | 1.6s
    epoch 053/100 | train_mse=0.02264437 | val_mse=0.03691673 | best_val_mse=0.03690003 | early_stop=03/10 | 1.6s
    epoch 054/100 | train_mse=0.02262828 | val_mse=0.03692532 | best_val_mse=0.03690003 | early_stop=04/10 | 1.6s
    epoch 055/100 | train_mse=0.02260431 | val_mse=0.03692358 | best_val_mse=0.03690003 | early_stop=05/10 | 1.6s
    epoch 056/100 | train_mse=0.02255324 | val_mse=0.03704124 | best_val_mse=0.03690003 | early_stop=06/10 | 1.6s
    epoch 057/100 | train_mse=0.02254792 | val_mse=0.03685261 | best_val_mse=0.03685261 | early_stop=00/10 | 1.6s
    epoch 058/100 | train_mse=0.02248061 | val_mse=0.03717253 | best_val_mse=0.03685261 | early_stop=01/10 | 1.7s
    epoch 059/100 | train_mse=0.02255550 | val_mse=0.03692854 | best_val_mse=0.03685261 | early_stop=02/10 | 1.6s
    epoch 060/100 | train_mse=0.02252876 | val_mse=0.03688044 | best_val_mse=0.03685261 | early_stop=03/10 | 1.6s
    epoch 061/100 | train_mse=0.02260644 | val_mse=0.03695872 | best_val_mse=0.03685261 | early_stop=04/10 | 1.6s
    epoch 062/100 | train_mse=0.02244093 | val_mse=0.03686481 | best_val_mse=0.03685261 | early_stop=05/10 | 1.6s
    epoch 063/100 | train_mse=0.02248262 | val_mse=0.03694072 | best_val_mse=0.03685261 | early_stop=06/10 | 1.6s
    epoch 064/100 | train_mse=0.02238254 | val_mse=0.03691513 | best_val_mse=0.03685261 | early_stop=07/10 | 1.6s
    epoch 065/100 | train_mse=0.02233444 | val_mse=0.03704839 | best_val_mse=0.03685261 | early_stop=08/10 | 1.6s
    epoch 066/100 | train_mse=0.02247715 | val_mse=0.03691324 | best_val_mse=0.03685261 | early_stop=09/10 | 1.6s
    epoch 067/100 | train_mse=0.02237813 | val_mse=0.03678323 | best_val_mse=0.03678323 | early_stop=00/10 | 1.6s
    epoch 068/100 | train_mse=0.02234949 | val_mse=0.03682379 | best_val_mse=0.03678323 | early_stop=01/10 | 1.6s
    epoch 069/100 | train_mse=0.02231081 | val_mse=0.03685184 | best_val_mse=0.03678323 | early_stop=02/10 | 1.6s
    epoch 070/100 | train_mse=0.02240446 | val_mse=0.03681927 | best_val_mse=0.03678323 | early_stop=03/10 | 1.6s
    epoch 071/100 | train_mse=0.02246748 | val_mse=0.03723497 | best_val_mse=0.03678323 | early_stop=04/10 | 1.6s
    epoch 072/100 | train_mse=0.02223676 | val_mse=0.03686383 | best_val_mse=0.03678323 | early_stop=05/10 | 1.6s
    epoch 073/100 | train_mse=0.02231222 | val_mse=0.03677670 | best_val_mse=0.03677670 | early_stop=00/10 | 1.6s
    epoch 074/100 | train_mse=0.02228348 | val_mse=0.03678745 | best_val_mse=0.03677670 | early_stop=01/10 | 1.6s
    epoch 075/100 | train_mse=0.02246078 | val_mse=0.03687473 | best_val_mse=0.03677670 | early_stop=02/10 | 1.6s
    epoch 076/100 | train_mse=0.02233335 | val_mse=0.03697795 | best_val_mse=0.03677670 | early_stop=03/10 | 1.6s
    epoch 077/100 | train_mse=0.02224818 | val_mse=0.03703514 | best_val_mse=0.03677670 | early_stop=04/10 | 1.6s
    epoch 078/100 | train_mse=0.02227257 | val_mse=0.03675205 | best_val_mse=0.03675205 | early_stop=00/10 | 1.6s
    epoch 079/100 | train_mse=0.02220018 | val_mse=0.03674970 | best_val_mse=0.03674970 | early_stop=00/10 | 1.6s
    epoch 080/100 | train_mse=0.02213428 | val_mse=0.03674830 | best_val_mse=0.03674830 | early_stop=00/10 | 1.6s
    epoch 081/100 | train_mse=0.02231200 | val_mse=0.03695310 | best_val_mse=0.03674830 | early_stop=01/10 | 1.6s
    epoch 082/100 | train_mse=0.02220120 | val_mse=0.03678750 | best_val_mse=0.03674830 | early_stop=02/10 | 1.6s
    epoch 083/100 | train_mse=0.02217735 | val_mse=0.03684253 | best_val_mse=0.03674830 | early_stop=03/10 | 1.6s
    epoch 084/100 | train_mse=0.02222231 | val_mse=0.03670856 | best_val_mse=0.03670856 | early_stop=00/10 | 1.6s
    epoch 085/100 | train_mse=0.02218490 | val_mse=0.03681537 | best_val_mse=0.03670856 | early_stop=01/10 | 1.6s
    epoch 086/100 | train_mse=0.02212988 | val_mse=0.03690371 | best_val_mse=0.03670856 | early_stop=02/10 | 1.6s
    epoch 087/100 | train_mse=0.02224302 | val_mse=0.03691635 | best_val_mse=0.03670856 | early_stop=03/10 | 1.6s
    epoch 088/100 | train_mse=0.02216061 | val_mse=0.03723847 | best_val_mse=0.03670856 | early_stop=04/10 | 1.6s
    epoch 089/100 | train_mse=0.02216747 | val_mse=0.03715646 | best_val_mse=0.03670856 | early_stop=05/10 | 1.6s
    epoch 090/100 | train_mse=0.02213648 | val_mse=0.03676526 | best_val_mse=0.03670856 | early_stop=06/10 | 1.6s
    epoch 091/100 | train_mse=0.02233499 | val_mse=0.03811190 | best_val_mse=0.03670856 | early_stop=07/10 | 1.6s
    epoch 092/100 | train_mse=0.02225512 | val_mse=0.03677765 | best_val_mse=0.03670856 | early_stop=08/10 | 1.6s
    epoch 093/100 | train_mse=0.02209074 | val_mse=0.03771063 | best_val_mse=0.03670856 | early_stop=09/10 | 1.6s
    epoch 094/100 | train_mse=0.02230007 | val_mse=0.03692861 | best_val_mse=0.03670856 | early_stop=10/10 | 1.6s
  refit 03/26 | test_year=2001 | status=saved | n_predictions=69,652
  refit 04/26 | test_year=2002 | status=training | train_n=965,790 | validation_n=297,051 | test_n=58,995

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02404291 | val_mse=0.05382086 | best_val_mse=0.05382086 | early_stop=00/10 | 1.6s
    epoch 002/100 | train_mse=0.02359231 | val_mse=0.05371659 | best_val_mse=0.05371659 | early_stop=00/10 | 1.6s
    epoch 003/100 | train_mse=0.02328860 | val_mse=0.05372745 | best_val_mse=0.05371659 | early_stop=01/10 | 1.6s
    epoch 004/100 | train_mse=0.02329326 | val_mse=0.05367609 | best_val_mse=0.05367609 | early_stop=00/10 | 1.6s
    epoch 005/100 | train_mse=0.02324901 | val_mse=0.05367845 | best_val_mse=0.05367609 | early_stop=01/10 | 1.6s
    epoch 006/100 | train_mse=0.02328319 | val_mse=0.05366382 | best_val_mse=0.05366382 | early_stop=00/10 | 1.6s
    epoch 007/100 | train_mse=0.02320628 | val_mse=0.05362174 | best_val_mse=0.05362174 | early_stop=00/10 | 1.6s
    epoch 008/100 | train_mse=0.02320350 | val_mse=0.05373969 | best_val_mse=0.05362174 | early_stop=01/10 | 1.6s
    epoch 009/100 | train_mse=0.02319109 | val_mse=0.05362100 | best_val_mse=0.05362100 | early_stop=00/10 | 1.6s
    epoch 010/100 | train_mse=0.02311463 | val_mse=0.05360805 | best_val_mse=0.05360805 | early_stop=00/10 | 1.6s
    epoch 011/100 | train_mse=0.02316571 | val_mse=0.05356792 | best_val_mse=0.05356792 | early_stop=00/10 | 1.6s
    epoch 012/100 | train_mse=0.02314333 | val_mse=0.05361203 | best_val_mse=0.05356792 | early_stop=01/10 | 1.6s
    epoch 013/100 | train_mse=0.02314639 | val_mse=0.05358371 | best_val_mse=0.05356792 | early_stop=02/10 | 1.6s
    epoch 014/100 | train_mse=0.02310974 | val_mse=0.05358173 | best_val_mse=0.05356792 | early_stop=03/10 | 1.6s
    epoch 015/100 | train_mse=0.02314598 | val_mse=0.05357680 | best_val_mse=0.05356792 | early_stop=04/10 | 1.6s
    epoch 016/100 | train_mse=0.02316751 | val_mse=0.05358340 | best_val_mse=0.05356792 | early_stop=05/10 | 1.6s
    epoch 017/100 | train_mse=0.02311976 | val_mse=0.05355935 | best_val_mse=0.05355935 | early_stop=00/10 | 1.6s
    epoch 018/100 | train_mse=0.02306219 | val_mse=0.05359127 | best_val_mse=0.05355935 | early_stop=01/10 | 1.6s
    epoch 019/100 | train_mse=0.02304767 | val_mse=0.05362525 | best_val_mse=0.05355935 | early_stop=02/10 | 1.6s
    epoch 020/100 | train_mse=0.02307224 | val_mse=0.05354294 | best_val_mse=0.05354294 | early_stop=00/10 | 1.6s
    epoch 021/100 | train_mse=0.02303456 | val_mse=0.05359440 | best_val_mse=0.05354294 | early_stop=01/10 | 1.6s
    epoch 022/100 | train_mse=0.02304087 | val_mse=0.05356843 | best_val_mse=0.05354294 | early_stop=02/10 | 1.6s
    epoch 023/100 | train_mse=0.02304323 | val_mse=0.05354332 | best_val_mse=0.05354294 | early_stop=03/10 | 1.6s
    epoch 024/100 | train_mse=0.02305077 | val_mse=0.05353399 | best_val_mse=0.05353399 | early_stop=00/10 | 1.6s
    epoch 025/100 | train_mse=0.02303530 | val_mse=0.05353148 | best_val_mse=0.05353148 | early_stop=00/10 | 1.6s
    epoch 026/100 | train_mse=0.02305300 | val_mse=0.05356945 | best_val_mse=0.05353148 | early_stop=01/10 | 1.6s
    epoch 027/100 | train_mse=0.02300481 | val_mse=0.05353663 | best_val_mse=0.05353148 | early_stop=02/10 | 1.6s
    epoch 028/100 | train_mse=0.02298952 | val_mse=0.05357775 | best_val_mse=0.05353148 | early_stop=03/10 | 1.6s
    epoch 029/100 | train_mse=0.02301874 | val_mse=0.05352852 | best_val_mse=0.05352852 | early_stop=00/10 | 1.6s
    epoch 030/100 | train_mse=0.02303269 | val_mse=0.05355546 | best_val_mse=0.05352852 | early_stop=01/10 | 1.6s
    epoch 031/100 | train_mse=0.02297085 | val_mse=0.05354826 | best_val_mse=0.05352852 | early_stop=02/10 | 1.6s
    epoch 032/100 | train_mse=0.02298474 | val_mse=0.05349036 | best_val_mse=0.05349036 | early_stop=00/10 | 1.7s
    epoch 033/100 | train_mse=0.02294593 | val_mse=0.05349703 | best_val_mse=0.05349036 | early_stop=01/10 | 1.6s
    epoch 034/100 | train_mse=0.02292920 | val_mse=0.05406612 | best_val_mse=0.05349036 | early_stop=02/10 | 1.7s
    epoch 035/100 | train_mse=0.02303888 | val_mse=0.05355217 | best_val_mse=0.05349036 | early_stop=03/10 | 1.7s
    epoch 036/100 | train_mse=0.02291258 | val_mse=0.05349635 | best_val_mse=0.05349036 | early_stop=04/10 | 1.6s
    epoch 037/100 | train_mse=0.02287849 | val_mse=0.05357401 | best_val_mse=0.05349036 | early_stop=05/10 | 1.6s
    epoch 038/100 | train_mse=0.02291411 | val_mse=0.05345951 | best_val_mse=0.05345951 | early_stop=00/10 | 1.6s
    epoch 039/100 | train_mse=0.02287003 | val_mse=0.05352299 | best_val_mse=0.05345951 | early_stop=01/10 | 1.6s
    epoch 040/100 | train_mse=0.02284996 | val_mse=0.05345819 | best_val_mse=0.05345819 | early_stop=00/10 | 1.6s
    epoch 041/100 | train_mse=0.02283782 | val_mse=0.05375191 | best_val_mse=0.05345819 | early_stop=01/10 | 1.6s
    epoch 042/100 | train_mse=0.02287302 | val_mse=0.05341566 | best_val_mse=0.05341566 | early_stop=00/10 | 1.6s
    epoch 043/100 | train_mse=0.02284667 | val_mse=0.05337746 | best_val_mse=0.05337746 | early_stop=00/10 | 1.6s
    epoch 044/100 | train_mse=0.02276738 | val_mse=0.05336061 | best_val_mse=0.05336061 | early_stop=00/10 | 1.6s
    epoch 045/100 | train_mse=0.02274455 | val_mse=0.05344873 | best_val_mse=0.05336061 | early_stop=01/10 | 1.6s
    epoch 046/100 | train_mse=0.02274784 | val_mse=0.05348045 | best_val_mse=0.05336061 | early_stop=02/10 | 1.6s
    epoch 047/100 | train_mse=0.02282197 | val_mse=0.05331298 | best_val_mse=0.05331298 | early_stop=00/10 | 1.6s
    epoch 048/100 | train_mse=0.02280653 | val_mse=0.05338746 | best_val_mse=0.05331298 | early_stop=01/10 | 1.6s
    epoch 049/100 | train_mse=0.02267890 | val_mse=0.05331481 | best_val_mse=0.05331298 | early_stop=02/10 | 1.6s
    epoch 050/100 | train_mse=0.02267333 | val_mse=0.05338749 | best_val_mse=0.05331298 | early_stop=03/10 | 1.6s
    epoch 051/100 | train_mse=0.02275825 | val_mse=0.05331036 | best_val_mse=0.05331036 | early_stop=00/10 | 1.6s
    epoch 052/100 | train_mse=0.02269742 | val_mse=0.05331494 | best_val_mse=0.05331036 | early_stop=01/10 | 1.6s
    epoch 053/100 | train_mse=0.02279894 | val_mse=0.05333654 | best_val_mse=0.05331036 | early_stop=02/10 | 1.6s
    epoch 054/100 | train_mse=0.02257206 | val_mse=0.05402016 | best_val_mse=0.05331036 | early_stop=03/10 | 1.6s
    epoch 055/100 | train_mse=0.02278304 | val_mse=0.05323636 | best_val_mse=0.05323636 | early_stop=00/10 | 1.6s
    epoch 056/100 | train_mse=0.02266341 | val_mse=0.05337483 | best_val_mse=0.05323636 | early_stop=01/10 | 1.6s
    epoch 057/100 | train_mse=0.02265388 | val_mse=0.05357595 | best_val_mse=0.05323636 | early_stop=02/10 | 1.6s
    epoch 058/100 | train_mse=0.02264295 | val_mse=0.05330202 | best_val_mse=0.05323636 | early_stop=03/10 | 1.6s
    epoch 059/100 | train_mse=0.02276465 | val_mse=0.05323130 | best_val_mse=0.05323130 | early_stop=00/10 | 1.6s
    epoch 060/100 | train_mse=0.02257028 | val_mse=0.05318615 | best_val_mse=0.05318615 | early_stop=00/10 | 1.6s
    epoch 061/100 | train_mse=0.02257823 | val_mse=0.05324108 | best_val_mse=0.05318615 | early_stop=01/10 | 1.6s
    epoch 062/100 | train_mse=0.02258746 | val_mse=0.05322289 | best_val_mse=0.05318615 | early_stop=02/10 | 1.6s
    epoch 063/100 | train_mse=0.02260183 | val_mse=0.05319719 | best_val_mse=0.05318615 | early_stop=03/10 | 1.6s
    epoch 064/100 | train_mse=0.02250506 | val_mse=0.05323080 | best_val_mse=0.05318615 | early_stop=04/10 | 1.6s
    epoch 065/100 | train_mse=0.02249149 | val_mse=0.05323742 | best_val_mse=0.05318615 | early_stop=05/10 | 1.6s
    epoch 066/100 | train_mse=0.02252740 | val_mse=0.05319975 | best_val_mse=0.05318615 | early_stop=06/10 | 1.6s
    epoch 067/100 | train_mse=0.02254616 | val_mse=0.05323556 | best_val_mse=0.05318615 | early_stop=07/10 | 1.6s
    epoch 068/100 | train_mse=0.02256711 | val_mse=0.05329372 | best_val_mse=0.05318615 | early_stop=08/10 | 1.6s
    epoch 069/100 | train_mse=0.02270804 | val_mse=0.05324208 | best_val_mse=0.05318615 | early_stop=09/10 | 1.6s
    epoch 070/100 | train_mse=0.02246642 | val_mse=0.05330802 | best_val_mse=0.05318615 | early_stop=10/10 | 1.6s
  refit 04/26 | test_year=2002 | status=saved | n_predictions=58,995
  refit 05/26 | test_year=2003 | status=training | train_n=997,898 | validation_n=277,061 | test_n=54,365

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02534000 | val_mse=0.05661912 | best_val_mse=0.05661912 | early_stop=00/10 | 1.6s
    epoch 002/100 | train_mse=0.02499746 | val_mse=0.05654934 | best_val_mse=0.05654934 | early_stop=00/10 | 1.7s
    epoch 003/100 | train_mse=0.02487184 | val_mse=0.05653359 | best_val_mse=0.05653359 | early_stop=00/10 | 1.6s
    epoch 004/100 | train_mse=0.02480477 | val_mse=0.05658026 | best_val_mse=0.05653359 | early_stop=01/10 | 1.6s
    epoch 005/100 | train_mse=0.02476877 | val_mse=0.05646466 | best_val_mse=0.05646466 | early_stop=00/10 | 1.6s
    epoch 006/100 | train_mse=0.02473615 | val_mse=0.05655807 | best_val_mse=0.05646466 | early_stop=01/10 | 1.6s
    epoch 007/100 | train_mse=0.02470636 | val_mse=0.05642237 | best_val_mse=0.05642237 | early_stop=00/10 | 1.7s
    epoch 008/100 | train_mse=0.02470388 | val_mse=0.05640082 | best_val_mse=0.05640082 | early_stop=00/10 | 1.6s
    epoch 009/100 | train_mse=0.02472446 | val_mse=0.05640684 | best_val_mse=0.05640082 | early_stop=01/10 | 1.6s
    epoch 010/100 | train_mse=0.02470371 | val_mse=0.05639567 | best_val_mse=0.05639567 | early_stop=00/10 | 1.6s
    epoch 011/100 | train_mse=0.02464340 | val_mse=0.05642277 | best_val_mse=0.05639567 | early_stop=01/10 | 1.6s
    epoch 012/100 | train_mse=0.02464689 | val_mse=0.05639352 | best_val_mse=0.05639352 | early_stop=00/10 | 1.6s
    epoch 013/100 | train_mse=0.02465140 | val_mse=0.05637251 | best_val_mse=0.05637251 | early_stop=00/10 | 1.6s
    epoch 014/100 | train_mse=0.02465128 | val_mse=0.05649874 | best_val_mse=0.05637251 | early_stop=01/10 | 1.6s
    epoch 015/100 | train_mse=0.02471491 | val_mse=0.05635530 | best_val_mse=0.05635530 | early_stop=00/10 | 1.6s
    epoch 016/100 | train_mse=0.02464404 | val_mse=0.05638330 | best_val_mse=0.05635530 | early_stop=01/10 | 1.6s
    epoch 017/100 | train_mse=0.02461518 | val_mse=0.05634340 | best_val_mse=0.05634340 | early_stop=00/10 | 1.7s
    epoch 018/100 | train_mse=0.02468933 | val_mse=0.05635385 | best_val_mse=0.05634340 | early_stop=01/10 | 1.6s
    epoch 019/100 | train_mse=0.02460034 | val_mse=0.05630628 | best_val_mse=0.05630628 | early_stop=00/10 | 1.6s
    epoch 020/100 | train_mse=0.02453190 | val_mse=0.05634478 | best_val_mse=0.05630628 | early_stop=01/10 | 1.6s
    epoch 021/100 | train_mse=0.02459785 | val_mse=0.05629903 | best_val_mse=0.05629903 | early_stop=00/10 | 1.6s
    epoch 022/100 | train_mse=0.02464310 | val_mse=0.05630419 | best_val_mse=0.05629903 | early_stop=01/10 | 1.6s
    epoch 023/100 | train_mse=0.02453489 | val_mse=0.05632239 | best_val_mse=0.05629903 | early_stop=02/10 | 1.6s
    epoch 024/100 | train_mse=0.02453727 | val_mse=0.05636962 | best_val_mse=0.05629903 | early_stop=03/10 | 1.6s
    epoch 025/100 | train_mse=0.02454180 | val_mse=0.05626460 | best_val_mse=0.05626460 | early_stop=00/10 | 1.7s
    epoch 026/100 | train_mse=0.02453393 | val_mse=0.05642275 | best_val_mse=0.05626460 | early_stop=01/10 | 1.6s
    epoch 027/100 | train_mse=0.02455602 | val_mse=0.05627344 | best_val_mse=0.05626460 | early_stop=02/10 | 1.6s
    epoch 028/100 | train_mse=0.02444490 | val_mse=0.05643378 | best_val_mse=0.05626460 | early_stop=03/10 | 1.6s
    epoch 029/100 | train_mse=0.02450815 | val_mse=0.05643474 | best_val_mse=0.05626460 | early_stop=04/10 | 1.6s
    epoch 030/100 | train_mse=0.02462268 | val_mse=0.05631024 | best_val_mse=0.05626460 | early_stop=05/10 | 1.6s
    epoch 031/100 | train_mse=0.02450476 | val_mse=0.05626002 | best_val_mse=0.05626002 | early_stop=00/10 | 1.6s
    epoch 032/100 | train_mse=0.02445814 | val_mse=0.05628067 | best_val_mse=0.05626002 | early_stop=01/10 | 1.6s
    epoch 033/100 | train_mse=0.02438660 | val_mse=0.05641359 | best_val_mse=0.05626002 | early_stop=02/10 | 1.6s
    epoch 034/100 | train_mse=0.02448008 | val_mse=0.05617648 | best_val_mse=0.05617648 | early_stop=00/10 | 1.6s
    epoch 035/100 | train_mse=0.02457241 | val_mse=0.05628902 | best_val_mse=0.05617648 | early_stop=01/10 | 1.6s
    epoch 036/100 | train_mse=0.02445246 | val_mse=0.05631466 | best_val_mse=0.05617648 | early_stop=02/10 | 1.6s
    epoch 037/100 | train_mse=0.02457731 | val_mse=0.05641718 | best_val_mse=0.05617648 | early_stop=03/10 | 1.6s
    epoch 038/100 | train_mse=0.02443393 | val_mse=0.05625667 | best_val_mse=0.05617648 | early_stop=04/10 | 1.6s
    epoch 039/100 | train_mse=0.02425617 | val_mse=0.05654460 | best_val_mse=0.05617648 | early_stop=05/10 | 1.6s
    epoch 040/100 | train_mse=0.02438492 | val_mse=0.05618795 | best_val_mse=0.05617648 | early_stop=06/10 | 1.6s
    epoch 041/100 | train_mse=0.02428529 | val_mse=0.05642644 | best_val_mse=0.05617648 | early_stop=07/10 | 1.6s
    epoch 042/100 | train_mse=0.02448066 | val_mse=0.05617278 | best_val_mse=0.05617278 | early_stop=00/10 | 1.6s
    epoch 043/100 | train_mse=0.02426557 | val_mse=0.05618341 | best_val_mse=0.05617278 | early_stop=01/10 | 1.6s
    epoch 044/100 | train_mse=0.02422481 | val_mse=0.05621021 | best_val_mse=0.05617278 | early_stop=02/10 | 1.6s
    epoch 045/100 | train_mse=0.02422619 | val_mse=0.05621229 | best_val_mse=0.05617278 | early_stop=03/10 | 1.6s
    epoch 046/100 | train_mse=0.02427990 | val_mse=0.05645097 | best_val_mse=0.05617278 | early_stop=04/10 | 1.6s
    epoch 047/100 | train_mse=0.02415446 | val_mse=0.05625117 | best_val_mse=0.05617278 | early_stop=05/10 | 1.6s
    epoch 048/100 | train_mse=0.02422718 | val_mse=0.05656826 | best_val_mse=0.05617278 | early_stop=06/10 | 1.6s
    epoch 049/100 | train_mse=0.02417328 | val_mse=0.05647256 | best_val_mse=0.05617278 | early_stop=07/10 | 1.6s
    epoch 050/100 | train_mse=0.02419936 | val_mse=0.05629991 | best_val_mse=0.05617278 | early_stop=08/10 | 1.6s
    epoch 051/100 | train_mse=0.02412062 | val_mse=0.05625519 | best_val_mse=0.05617278 | early_stop=09/10 | 1.6s
    epoch 052/100 | train_mse=0.02408437 | val_mse=0.05631670 | best_val_mse=0.05617278 | early_stop=10/10 | 1.6s
  refit 05/26 | test_year=2003 | status=saved | n_predictions=54,365
  refit 06/26 | test_year=2004 | status=training | train_n=1,023,477 | validation_n=255,749 | test_n=51,804

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02792025 | val_mse=0.05201621 | best_val_mse=0.05201621 | early_stop=00/10 | 1.6s
    epoch 002/100 | train_mse=0.02747756 | val_mse=0.05214563 | best_val_mse=0.05201621 | early_stop=01/10 | 1.7s
    epoch 003/100 | train_mse=0.02716598 | val_mse=0.05196333 | best_val_mse=0.05196333 | early_stop=00/10 | 1.6s
    epoch 004/100 | train_mse=0.02711111 | val_mse=0.05184668 | best_val_mse=0.05184668 | early_stop=00/10 | 1.7s
    epoch 005/100 | train_mse=0.02712739 | val_mse=0.05263740 | best_val_mse=0.05184668 | early_stop=01/10 | 1.7s
    epoch 006/100 | train_mse=0.02715621 | val_mse=0.05227726 | best_val_mse=0.05184668 | early_stop=02/10 | 1.6s
    epoch 007/100 | train_mse=0.02700972 | val_mse=0.05251866 | best_val_mse=0.05184668 | early_stop=03/10 | 1.6s
    epoch 008/100 | train_mse=0.02704158 | val_mse=0.05203756 | best_val_mse=0.05184668 | early_stop=04/10 | 1.6s
    epoch 009/100 | train_mse=0.02698885 | val_mse=0.05185284 | best_val_mse=0.05184668 | early_stop=05/10 | 1.6s
    epoch 010/100 | train_mse=0.02693857 | val_mse=0.05221120 | best_val_mse=0.05184668 | early_stop=06/10 | 1.6s
    epoch 011/100 | train_mse=0.02692627 | val_mse=0.05173529 | best_val_mse=0.05173529 | early_stop=00/10 | 1.6s
    epoch 012/100 | train_mse=0.02694794 | val_mse=0.05200757 | best_val_mse=0.05173529 | early_stop=01/10 | 1.7s
    epoch 013/100 | train_mse=0.02690850 | val_mse=0.05258692 | best_val_mse=0.05173529 | early_stop=02/10 | 1.6s
    epoch 014/100 | train_mse=0.02698796 | val_mse=0.05223566 | best_val_mse=0.05173529 | early_stop=03/10 | 1.6s
    epoch 015/100 | train_mse=0.02691295 | val_mse=0.05180984 | best_val_mse=0.05173529 | early_stop=04/10 | 1.6s
    epoch 016/100 | train_mse=0.02697873 | val_mse=0.05202279 | best_val_mse=0.05173529 | early_stop=05/10 | 1.6s
    epoch 017/100 | train_mse=0.02689703 | val_mse=0.05238838 | best_val_mse=0.05173529 | early_stop=06/10 | 1.6s
    epoch 018/100 | train_mse=0.02695266 | val_mse=0.05242101 | best_val_mse=0.05173529 | early_stop=07/10 | 1.6s
    epoch 019/100 | train_mse=0.02693731 | val_mse=0.05211269 | best_val_mse=0.05173529 | early_stop=08/10 | 1.6s
    epoch 020/100 | train_mse=0.02692260 | val_mse=0.05265423 | best_val_mse=0.05173529 | early_stop=09/10 | 1.6s
    epoch 021/100 | train_mse=0.02706589 | val_mse=0.05260812 | best_val_mse=0.05173529 | early_stop=10/10 | 1.6s
  refit 06/26 | test_year=2004 | status=saved | n_predictions=51,804
  refit 07/26 | test_year=2005 | status=training | train_n=1,043,741 | validation_n=232,745 | test_n=52,038

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03175793 | val_mse=0.03606322 | best_val_mse=0.03606322 | early_stop=00/10 | 1.6s
    epoch 002/100 | train_mse=0.03114164 | val_mse=0.03589634 | best_val_mse=0.03589634 | early_stop=00/10 | 1.6s
    epoch 003/100 | train_mse=0.03108301 | val_mse=0.03587030 | best_val_mse=0.03587030 | early_stop=00/10 | 1.6s
    epoch 004/100 | train_mse=0.03125652 | val_mse=0.03587203 | best_val_mse=0.03587030 | early_stop=01/10 | 1.6s
    epoch 005/100 | train_mse=0.03092398 | val_mse=0.03584279 | best_val_mse=0.03584279 | early_stop=00/10 | 1.7s
    epoch 006/100 | train_mse=0.03093256 | val_mse=0.03574692 | best_val_mse=0.03574692 | early_stop=00/10 | 1.7s
    epoch 007/100 | train_mse=0.03087935 | val_mse=0.03574389 | best_val_mse=0.03574389 | early_stop=00/10 | 1.7s
    epoch 008/100 | train_mse=0.03088327 | val_mse=0.03572479 | best_val_mse=0.03572479 | early_stop=00/10 | 1.6s
    epoch 009/100 | train_mse=0.03091771 | val_mse=0.03573024 | best_val_mse=0.03572479 | early_stop=01/10 | 1.7s
    epoch 010/100 | train_mse=0.03082189 | val_mse=0.03576597 | best_val_mse=0.03572479 | early_stop=02/10 | 1.7s
    epoch 011/100 | train_mse=0.03085456 | val_mse=0.03573931 | best_val_mse=0.03572479 | early_stop=03/10 | 1.6s
    epoch 012/100 | train_mse=0.03081290 | val_mse=0.03574465 | best_val_mse=0.03572479 | early_stop=04/10 | 1.6s
    epoch 013/100 | train_mse=0.03086611 | val_mse=0.03580606 | best_val_mse=0.03572479 | early_stop=05/10 | 1.6s
    epoch 014/100 | train_mse=0.03081477 | val_mse=0.03569235 | best_val_mse=0.03569235 | early_stop=00/10 | 1.6s
    epoch 015/100 | train_mse=0.03081367 | val_mse=0.03566495 | best_val_mse=0.03566495 | early_stop=00/10 | 1.6s
    epoch 016/100 | train_mse=0.03080001 | val_mse=0.03571356 | best_val_mse=0.03566495 | early_stop=01/10 | 1.6s
    epoch 017/100 | train_mse=0.03074498 | val_mse=0.03566889 | best_val_mse=0.03566495 | early_stop=02/10 | 1.6s
    epoch 018/100 | train_mse=0.03074235 | val_mse=0.03569239 | best_val_mse=0.03566495 | early_stop=03/10 | 1.6s
    epoch 019/100 | train_mse=0.03078673 | val_mse=0.03569628 | best_val_mse=0.03566495 | early_stop=04/10 | 1.6s
    epoch 020/100 | train_mse=0.03082679 | val_mse=0.03567503 | best_val_mse=0.03566495 | early_stop=05/10 | 1.6s
    epoch 021/100 | train_mse=0.03076384 | val_mse=0.03574017 | best_val_mse=0.03566495 | early_stop=06/10 | 1.6s
    epoch 022/100 | train_mse=0.03075313 | val_mse=0.03567873 | best_val_mse=0.03566495 | early_stop=07/10 | 1.6s
    epoch 023/100 | train_mse=0.03072865 | val_mse=0.03563613 | best_val_mse=0.03563613 | early_stop=00/10 | 1.6s
    epoch 024/100 | train_mse=0.03068380 | val_mse=0.03577508 | best_val_mse=0.03563613 | early_stop=01/10 | 1.6s
    epoch 025/100 | train_mse=0.03075259 | val_mse=0.03577395 | best_val_mse=0.03563613 | early_stop=02/10 | 1.6s
    epoch 026/100 | train_mse=0.03073787 | val_mse=0.03566003 | best_val_mse=0.03563613 | early_stop=03/10 | 1.6s
    epoch 027/100 | train_mse=0.03068685 | val_mse=0.03585174 | best_val_mse=0.03563613 | early_stop=04/10 | 1.6s
    epoch 028/100 | train_mse=0.03081827 | val_mse=0.03581266 | best_val_mse=0.03563613 | early_stop=05/10 | 1.6s
    epoch 029/100 | train_mse=0.03070215 | val_mse=0.03562821 | best_val_mse=0.03562821 | early_stop=00/10 | 1.7s
    epoch 030/100 | train_mse=0.03067270 | val_mse=0.03578695 | best_val_mse=0.03562821 | early_stop=01/10 | 1.6s
    epoch 031/100 | train_mse=0.03067215 | val_mse=0.03562935 | best_val_mse=0.03562821 | early_stop=02/10 | 1.6s
    epoch 032/100 | train_mse=0.03070370 | val_mse=0.03566779 | best_val_mse=0.03562821 | early_stop=03/10 | 1.6s
    epoch 033/100 | train_mse=0.03061990 | val_mse=0.03564402 | best_val_mse=0.03562821 | early_stop=04/10 | 1.6s
    epoch 034/100 | train_mse=0.03057799 | val_mse=0.03565242 | best_val_mse=0.03562821 | early_stop=05/10 | 1.6s
    epoch 035/100 | train_mse=0.03057596 | val_mse=0.03560576 | best_val_mse=0.03560576 | early_stop=00/10 | 1.7s
    epoch 036/100 | train_mse=0.03056575 | val_mse=0.03577048 | best_val_mse=0.03560576 | early_stop=01/10 | 1.7s
    epoch 037/100 | train_mse=0.03076045 | val_mse=0.03570457 | best_val_mse=0.03560576 | early_stop=02/10 | 1.6s
    epoch 038/100 | train_mse=0.03066411 | val_mse=0.03564603 | best_val_mse=0.03560576 | early_stop=03/10 | 1.6s
    epoch 039/100 | train_mse=0.03056243 | val_mse=0.03558661 | best_val_mse=0.03558661 | early_stop=00/10 | 1.6s
    epoch 040/100 | train_mse=0.03057262 | val_mse=0.03565265 | best_val_mse=0.03558661 | early_stop=01/10 | 1.6s
    epoch 041/100 | train_mse=0.03063158 | val_mse=0.03566702 | best_val_mse=0.03558661 | early_stop=02/10 | 1.6s
    epoch 042/100 | train_mse=0.03046832 | val_mse=0.03577244 | best_val_mse=0.03558661 | early_stop=03/10 | 1.6s
    epoch 043/100 | train_mse=0.03055183 | val_mse=0.03566063 | best_val_mse=0.03558661 | early_stop=04/10 | 1.6s
    epoch 044/100 | train_mse=0.03047747 | val_mse=0.03567367 | best_val_mse=0.03558661 | early_stop=05/10 | 1.7s
    epoch 045/100 | train_mse=0.03073534 | val_mse=0.03566198 | best_val_mse=0.03558661 | early_stop=06/10 | 1.6s
    epoch 046/100 | train_mse=0.03053215 | val_mse=0.03579715 | best_val_mse=0.03558661 | early_stop=07/10 | 1.7s
    epoch 047/100 | train_mse=0.03046025 | val_mse=0.03579252 | best_val_mse=0.03558661 | early_stop=08/10 | 1.6s
    epoch 048/100 | train_mse=0.03038415 | val_mse=0.03572334 | best_val_mse=0.03558661 | early_stop=09/10 | 1.6s
    epoch 049/100 | train_mse=0.03032243 | val_mse=0.03629736 | best_val_mse=0.03558661 | early_stop=10/10 | 1.6s
  refit 07/26 | test_year=2005 | status=saved | n_predictions=52,038
  refit 08/26 | test_year=2006 | status=training | train_n=1,056,173 | validation_n=215,471 | test_n=52,339

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03310773 | val_mse=0.02508883 | best_val_mse=0.02508883 | early_stop=00/10 | 1.6s
    epoch 002/100 | train_mse=0.03278510 | val_mse=0.02509242 | best_val_mse=0.02508883 | early_stop=01/10 | 1.6s
    epoch 003/100 | train_mse=0.03264528 | val_mse=0.02500757 | best_val_mse=0.02500757 | early_stop=00/10 | 1.6s
    epoch 004/100 | train_mse=0.03256931 | val_mse=0.02500074 | best_val_mse=0.02500074 | early_stop=00/10 | 1.6s
    epoch 005/100 | train_mse=0.03253096 | val_mse=0.02519647 | best_val_mse=0.02500074 | early_stop=01/10 | 1.6s
    epoch 006/100 | train_mse=0.03256385 | val_mse=0.02518332 | best_val_mse=0.02500074 | early_stop=02/10 | 1.6s
    epoch 007/100 | train_mse=0.03247903 | val_mse=0.02496288 | best_val_mse=0.02496288 | early_stop=00/10 | 1.6s
    epoch 008/100 | train_mse=0.03250971 | val_mse=0.02494294 | best_val_mse=0.02494294 | early_stop=00/10 | 1.6s
    epoch 009/100 | train_mse=0.03243230 | val_mse=0.02500124 | best_val_mse=0.02494294 | early_stop=01/10 | 1.6s
    epoch 010/100 | train_mse=0.03245706 | val_mse=0.02502221 | best_val_mse=0.02494294 | early_stop=02/10 | 1.6s
    epoch 011/100 | train_mse=0.03239064 | val_mse=0.02499839 | best_val_mse=0.02494294 | early_stop=03/10 | 1.6s
    epoch 012/100 | train_mse=0.03241719 | val_mse=0.02492000 | best_val_mse=0.02492000 | early_stop=00/10 | 1.6s
    epoch 013/100 | train_mse=0.03236762 | val_mse=0.02518423 | best_val_mse=0.02492000 | early_stop=01/10 | 1.6s
    epoch 014/100 | train_mse=0.03246240 | val_mse=0.02499481 | best_val_mse=0.02492000 | early_stop=02/10 | 1.6s
    epoch 015/100 | train_mse=0.03241026 | val_mse=0.02498807 | best_val_mse=0.02492000 | early_stop=03/10 | 1.6s
    epoch 016/100 | train_mse=0.03246277 | val_mse=0.02494324 | best_val_mse=0.02492000 | early_stop=04/10 | 1.6s
    epoch 017/100 | train_mse=0.03235867 | val_mse=0.02510299 | best_val_mse=0.02492000 | early_stop=05/10 | 1.6s
    epoch 018/100 | train_mse=0.03242281 | val_mse=0.02492926 | best_val_mse=0.02492000 | early_stop=06/10 | 1.6s
    epoch 019/100 | train_mse=0.03243018 | val_mse=0.02514404 | best_val_mse=0.02492000 | early_stop=07/10 | 1.6s
    epoch 020/100 | train_mse=0.03240789 | val_mse=0.02502125 | best_val_mse=0.02492000 | early_stop=08/10 | 1.7s
    epoch 021/100 | train_mse=0.03232303 | val_mse=0.02501163 | best_val_mse=0.02492000 | early_stop=09/10 | 1.6s
    epoch 022/100 | train_mse=0.03232969 | val_mse=0.02494599 | best_val_mse=0.02492000 | early_stop=10/10 | 1.6s
  refit 08/26 | test_year=2006 | status=saved | n_predictions=52,339
  refit 09/26 | test_year=2007 | status=training | train_n=1,055,556 | validation_n=208,739 | test_n=50,642

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03369995 | val_mse=0.01908719 | best_val_mse=0.01908719 | early_stop=00/10 | 1.6s
    epoch 002/100 | train_mse=0.03309566 | val_mse=0.01880800 | best_val_mse=0.01880800 | early_stop=00/10 | 1.6s
    epoch 003/100 | train_mse=0.03309414 | val_mse=0.01939297 | best_val_mse=0.01880800 | early_stop=01/10 | 1.6s
    epoch 004/100 | train_mse=0.03296994 | val_mse=0.01892750 | best_val_mse=0.01880800 | early_stop=02/10 | 1.6s
    epoch 005/100 | train_mse=0.03290509 | val_mse=0.01849221 | best_val_mse=0.01849221 | early_stop=00/10 | 1.6s
    epoch 006/100 | train_mse=0.03287831 | val_mse=0.01819576 | best_val_mse=0.01819576 | early_stop=00/10 | 1.7s
    epoch 007/100 | train_mse=0.03292611 | val_mse=0.01873142 | best_val_mse=0.01819576 | early_stop=01/10 | 1.6s
    epoch 008/100 | train_mse=0.03286992 | val_mse=0.01851128 | best_val_mse=0.01819576 | early_stop=02/10 | 1.6s
    epoch 009/100 | train_mse=0.03288368 | val_mse=0.01871785 | best_val_mse=0.01819576 | early_stop=03/10 | 1.6s
    epoch 010/100 | train_mse=0.03279186 | val_mse=0.01909515 | best_val_mse=0.01819576 | early_stop=04/10 | 1.6s
    epoch 011/100 | train_mse=0.03277551 | val_mse=0.01824278 | best_val_mse=0.01819576 | early_stop=05/10 | 1.6s
    epoch 012/100 | train_mse=0.03277198 | val_mse=0.01861172 | best_val_mse=0.01819576 | early_stop=06/10 | 1.6s
    epoch 013/100 | train_mse=0.03277598 | val_mse=0.01836501 | best_val_mse=0.01819576 | early_stop=07/10 | 1.6s
    epoch 014/100 | train_mse=0.03277713 | val_mse=0.01873386 | best_val_mse=0.01819576 | early_stop=08/10 | 1.6s
    epoch 015/100 | train_mse=0.03270196 | val_mse=0.01834946 | best_val_mse=0.01819576 | early_stop=09/10 | 1.6s
    epoch 016/100 | train_mse=0.03280480 | val_mse=0.01841550 | best_val_mse=0.01819576 | early_stop=10/10 | 1.6s
  refit 09/26 | test_year=2007 | status=saved | n_predictions=50,642
  refit 10/26 | test_year=2008 | status=training | train_n=1,048,198 | validation_n=204,689 | test_n=51,272

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03416746 | val_mse=0.01409497 | best_val_mse=0.01409497 | early_stop=00/10 | 1.6s
    epoch 002/100 | train_mse=0.03372876 | val_mse=0.01407446 | best_val_mse=0.01407446 | early_stop=00/10 | 1.6s
    epoch 003/100 | train_mse=0.03352100 | val_mse=0.01409806 | best_val_mse=0.01407446 | early_stop=01/10 | 1.6s
    epoch 004/100 | train_mse=0.03353967 | val_mse=0.01404858 | best_val_mse=0.01404858 | early_stop=00/10 | 1.6s
    epoch 005/100 | train_mse=0.03356919 | val_mse=0.01399956 | best_val_mse=0.01399956 | early_stop=00/10 | 1.6s
    epoch 006/100 | train_mse=0.03340743 | val_mse=0.01407626 | best_val_mse=0.01399956 | early_stop=01/10 | 1.6s
    epoch 007/100 | train_mse=0.03340597 | val_mse=0.01398082 | best_val_mse=0.01398082 | early_stop=00/10 | 1.6s
    epoch 008/100 | train_mse=0.03339069 | val_mse=0.01409833 | best_val_mse=0.01398082 | early_stop=01/10 | 1.6s
    epoch 009/100 | train_mse=0.03342281 | val_mse=0.01399871 | best_val_mse=0.01398082 | early_stop=02/10 | 1.6s
    epoch 010/100 | train_mse=0.03333593 | val_mse=0.01416389 | best_val_mse=0.01398082 | early_stop=03/10 | 1.6s
    epoch 011/100 | train_mse=0.03346468 | val_mse=0.01393109 | best_val_mse=0.01393109 | early_stop=00/10 | 1.6s
    epoch 012/100 | train_mse=0.03329701 | val_mse=0.01400150 | best_val_mse=0.01393109 | early_stop=01/10 | 1.6s
    epoch 013/100 | train_mse=0.03330564 | val_mse=0.01401124 | best_val_mse=0.01393109 | early_stop=02/10 | 1.6s
    epoch 014/100 | train_mse=0.03339020 | val_mse=0.01410513 | best_val_mse=0.01393109 | early_stop=03/10 | 1.6s
    epoch 015/100 | train_mse=0.03335492 | val_mse=0.01400963 | best_val_mse=0.01393109 | early_stop=04/10 | 1.6s
    epoch 016/100 | train_mse=0.03338094 | val_mse=0.01419858 | best_val_mse=0.01393109 | early_stop=05/10 | 1.7s
    epoch 017/100 | train_mse=0.03341033 | val_mse=0.01397694 | best_val_mse=0.01393109 | early_stop=06/10 | 1.6s
    epoch 018/100 | train_mse=0.03324836 | val_mse=0.01403271 | best_val_mse=0.01393109 | early_stop=07/10 | 1.6s
    epoch 019/100 | train_mse=0.03320986 | val_mse=0.01399236 | best_val_mse=0.01393109 | early_stop=08/10 | 1.6s
    epoch 020/100 | train_mse=0.03322246 | val_mse=0.01405692 | best_val_mse=0.01393109 | early_stop=09/10 | 1.6s
    epoch 021/100 | train_mse=0.03325186 | val_mse=0.01405604 | best_val_mse=0.01393109 | early_stop=10/10 | 1.6s
  refit 10/26 | test_year=2008 | status=saved | n_predictions=51,272
  refit 11/26 | test_year=2009 | status=training | train_n=1,037,605 | validation_n=203,833 | test_n=48,300

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03413114 | val_mse=0.01412158 | best_val_mse=0.01412158 | early_stop=00/10 | 1.6s
    epoch 002/100 | train_mse=0.03356715 | val_mse=0.01411019 | best_val_mse=0.01411019 | early_stop=00/10 | 1.6s
    epoch 003/100 | train_mse=0.03346374 | val_mse=0.01442590 | best_val_mse=0.01411019 | early_stop=01/10 | 1.6s
    epoch 004/100 | train_mse=0.03351604 | val_mse=0.01403838 | best_val_mse=0.01403838 | early_stop=00/10 | 1.6s
    epoch 005/100 | train_mse=0.03333930 | val_mse=0.01405735 | best_val_mse=0.01403838 | early_stop=01/10 | 1.6s
    epoch 006/100 | train_mse=0.03328671 | val_mse=0.01403594 | best_val_mse=0.01403594 | early_stop=00/10 | 1.6s
    epoch 007/100 | train_mse=0.03332240 | val_mse=0.01407755 | best_val_mse=0.01403594 | early_stop=01/10 | 1.6s
    epoch 008/100 | train_mse=0.03328184 | val_mse=0.01414685 | best_val_mse=0.01403594 | early_stop=02/10 | 1.6s
    epoch 009/100 | train_mse=0.03329187 | val_mse=0.01423287 | best_val_mse=0.01403594 | early_stop=03/10 | 1.6s
    epoch 010/100 | train_mse=0.03322501 | val_mse=0.01408508 | best_val_mse=0.01403594 | early_stop=04/10 | 1.6s
    epoch 011/100 | train_mse=0.03323652 | val_mse=0.01402632 | best_val_mse=0.01402632 | early_stop=00/10 | 1.6s
    epoch 012/100 | train_mse=0.03323429 | val_mse=0.01470740 | best_val_mse=0.01402632 | early_stop=01/10 | 1.6s
    epoch 013/100 | train_mse=0.03334236 | val_mse=0.01396120 | best_val_mse=0.01396120 | early_stop=00/10 | 1.6s
    epoch 014/100 | train_mse=0.03322523 | val_mse=0.01404771 | best_val_mse=0.01396120 | early_stop=01/10 | 1.6s
    epoch 015/100 | train_mse=0.03322944 | val_mse=0.01399741 | best_val_mse=0.01396120 | early_stop=02/10 | 1.6s
    epoch 016/100 | train_mse=0.03315348 | val_mse=0.01410211 | best_val_mse=0.01396120 | early_stop=03/10 | 1.6s
    epoch 017/100 | train_mse=0.03313252 | val_mse=0.01403413 | best_val_mse=0.01396120 | early_stop=04/10 | 1.6s
    epoch 018/100 | train_mse=0.03313061 | val_mse=0.01443737 | best_val_mse=0.01396120 | early_stop=05/10 | 1.6s
    epoch 019/100 | train_mse=0.03315296 | val_mse=0.01401814 | best_val_mse=0.01396120 | early_stop=06/10 | 1.6s
    epoch 020/100 | train_mse=0.03316114 | val_mse=0.01401550 | best_val_mse=0.01396120 | early_stop=07/10 | 1.6s
    epoch 021/100 | train_mse=0.03319462 | val_mse=0.01407811 | best_val_mse=0.01396120 | early_stop=08/10 | 1.6s
    epoch 022/100 | train_mse=0.03326076 | val_mse=0.01407842 | best_val_mse=0.01396120 | early_stop=09/10 | 1.6s
    epoch 023/100 | train_mse=0.03321196 | val_mse=0.01401735 | best_val_mse=0.01396120 | early_stop=10/10 | 1.6s
  refit 11/26 | test_year=2009 | status=saved | n_predictions=48,300
  refit 12/26 | test_year=2010 | status=training | train_n=1,023,116 | validation_n=199,878 | test_n=46,429

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03313777 | val_mse=0.02273816 | best_val_mse=0.02273816 | early_stop=00/10 | 1.6s
    epoch 002/100 | train_mse=0.03263423 | val_mse=0.02281171 | best_val_mse=0.02273816 | early_stop=01/10 | 1.6s
    epoch 003/100 | train_mse=0.03242465 | val_mse=0.02308303 | best_val_mse=0.02273816 | early_stop=02/10 | 1.6s
    epoch 004/100 | train_mse=0.03241500 | val_mse=0.02267241 | best_val_mse=0.02267241 | early_stop=00/10 | 1.7s
    epoch 005/100 | train_mse=0.03235971 | val_mse=0.02235425 | best_val_mse=0.02235425 | early_stop=00/10 | 1.6s
    epoch 006/100 | train_mse=0.03233822 | val_mse=0.02305178 | best_val_mse=0.02235425 | early_stop=01/10 | 1.6s
    epoch 007/100 | train_mse=0.03242938 | val_mse=0.02286635 | best_val_mse=0.02235425 | early_stop=02/10 | 1.6s
    epoch 008/100 | train_mse=0.03229432 | val_mse=0.02229142 | best_val_mse=0.02229142 | early_stop=00/10 | 1.6s
    epoch 009/100 | train_mse=0.03228767 | val_mse=0.02290915 | best_val_mse=0.02229142 | early_stop=01/10 | 1.6s
    epoch 010/100 | train_mse=0.03228443 | val_mse=0.02222563 | best_val_mse=0.02222563 | early_stop=00/10 | 1.6s
    epoch 011/100 | train_mse=0.03229048 | val_mse=0.02218262 | best_val_mse=0.02218262 | early_stop=00/10 | 1.6s
    epoch 012/100 | train_mse=0.03225250 | val_mse=0.02173511 | best_val_mse=0.02173511 | early_stop=00/10 | 1.6s
    epoch 013/100 | train_mse=0.03250376 | val_mse=0.02208599 | best_val_mse=0.02173511 | early_stop=01/10 | 1.6s
    epoch 014/100 | train_mse=0.03226567 | val_mse=0.02205930 | best_val_mse=0.02173511 | early_stop=02/10 | 1.6s
    epoch 015/100 | train_mse=0.03228744 | val_mse=0.02258939 | best_val_mse=0.02173511 | early_stop=03/10 | 1.6s
    epoch 016/100 | train_mse=0.03222361 | val_mse=0.02194638 | best_val_mse=0.02173511 | early_stop=04/10 | 1.6s
    epoch 017/100 | train_mse=0.03222274 | val_mse=0.02333051 | best_val_mse=0.02173511 | early_stop=05/10 | 1.6s
    epoch 018/100 | train_mse=0.03234823 | val_mse=0.02314515 | best_val_mse=0.02173511 | early_stop=06/10 | 1.6s
    epoch 019/100 | train_mse=0.03217172 | val_mse=0.02218708 | best_val_mse=0.02173511 | early_stop=07/10 | 1.6s
    epoch 020/100 | train_mse=0.03219824 | val_mse=0.02223358 | best_val_mse=0.02173511 | early_stop=08/10 | 1.6s
    epoch 021/100 | train_mse=0.03217451 | val_mse=0.02247750 | best_val_mse=0.02173511 | early_stop=09/10 | 1.6s
    epoch 022/100 | train_mse=0.03217155 | val_mse=0.02238049 | best_val_mse=0.02173511 | early_stop=10/10 | 1.6s
  refit 12/26 | test_year=2010 | status=saved | n_predictions=46,429
  refit 13/26 | test_year=2011 | status=training | train_n=1,008,847 | validation_n=193,928 | test_n=45,154

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03117322 | val_mse=0.03559702 | best_val_mse=0.03559702 | early_stop=00/10 | 1.6s
    epoch 002/100 | train_mse=0.03078489 | val_mse=0.03574358 | best_val_mse=0.03559702 | early_stop=01/10 | 1.6s
    epoch 003/100 | train_mse=0.03070503 | val_mse=0.03532740 | best_val_mse=0.03532740 | early_stop=00/10 | 1.7s
    epoch 004/100 | train_mse=0.03074930 | val_mse=0.03535064 | best_val_mse=0.03532740 | early_stop=01/10 | 1.6s
    epoch 005/100 | train_mse=0.03060576 | val_mse=0.03531764 | best_val_mse=0.03531764 | early_stop=00/10 | 1.6s
    epoch 006/100 | train_mse=0.03062241 | val_mse=0.03530667 | best_val_mse=0.03530667 | early_stop=00/10 | 1.6s
    epoch 007/100 | train_mse=0.03054777 | val_mse=0.03566785 | best_val_mse=0.03530667 | early_stop=01/10 | 1.6s
    epoch 008/100 | train_mse=0.03064700 | val_mse=0.03578553 | best_val_mse=0.03530667 | early_stop=02/10 | 1.6s
    epoch 009/100 | train_mse=0.03068148 | val_mse=0.03545057 | best_val_mse=0.03530667 | early_stop=03/10 | 1.6s
    epoch 010/100 | train_mse=0.03054620 | val_mse=0.03528802 | best_val_mse=0.03528802 | early_stop=00/10 | 1.6s
    epoch 011/100 | train_mse=0.03058798 | val_mse=0.03527004 | best_val_mse=0.03527004 | early_stop=00/10 | 1.6s
    epoch 012/100 | train_mse=0.03057875 | val_mse=0.03530115 | best_val_mse=0.03527004 | early_stop=01/10 | 1.6s
    epoch 013/100 | train_mse=0.03051295 | val_mse=0.03550557 | best_val_mse=0.03527004 | early_stop=02/10 | 1.6s
    epoch 014/100 | train_mse=0.03048996 | val_mse=0.03529651 | best_val_mse=0.03527004 | early_stop=03/10 | 1.5s
    epoch 015/100 | train_mse=0.03057503 | val_mse=0.03529830 | best_val_mse=0.03527004 | early_stop=04/10 | 1.6s
    epoch 016/100 | train_mse=0.03042006 | val_mse=0.03566317 | best_val_mse=0.03527004 | early_stop=05/10 | 1.6s
    epoch 017/100 | train_mse=0.03044810 | val_mse=0.03542640 | best_val_mse=0.03527004 | early_stop=06/10 | 1.6s
    epoch 018/100 | train_mse=0.03046596 | val_mse=0.03539901 | best_val_mse=0.03527004 | early_stop=07/10 | 1.6s
    epoch 019/100 | train_mse=0.03054709 | val_mse=0.03539611 | best_val_mse=0.03527004 | early_stop=08/10 | 1.6s
    epoch 020/100 | train_mse=0.03049649 | val_mse=0.03534610 | best_val_mse=0.03527004 | early_stop=09/10 | 1.6s
    epoch 021/100 | train_mse=0.03057927 | val_mse=0.03542493 | best_val_mse=0.03527004 | early_stop=10/10 | 1.6s
  refit 13/26 | test_year=2011 | status=saved | n_predictions=45,154
  refit 14/26 | test_year=2012 | status=training | train_n=992,010 | validation_n=188,512 | test_n=44,459

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03115501 | val_mse=0.03755141 | best_val_mse=0.03755141 | early_stop=00/10 | 1.6s
    epoch 002/100 | train_mse=0.03058284 | val_mse=0.03740573 | best_val_mse=0.03740573 | early_stop=00/10 | 1.6s
    epoch 003/100 | train_mse=0.03036948 | val_mse=0.03737568 | best_val_mse=0.03737568 | early_stop=00/10 | 1.6s
    epoch 004/100 | train_mse=0.03041224 | val_mse=0.03733142 | best_val_mse=0.03733142 | early_stop=00/10 | 1.6s
    epoch 005/100 | train_mse=0.03027025 | val_mse=0.03747494 | best_val_mse=0.03733142 | early_stop=01/10 | 1.6s
    epoch 006/100 | train_mse=0.03027230 | val_mse=0.03732563 | best_val_mse=0.03732563 | early_stop=00/10 | 1.6s
    epoch 007/100 | train_mse=0.03021816 | val_mse=0.03734258 | best_val_mse=0.03732563 | early_stop=01/10 | 1.6s
    epoch 008/100 | train_mse=0.03019437 | val_mse=0.03732904 | best_val_mse=0.03732563 | early_stop=02/10 | 1.6s
    epoch 009/100 | train_mse=0.03016627 | val_mse=0.03730825 | best_val_mse=0.03730825 | early_stop=00/10 | 1.6s
    epoch 010/100 | train_mse=0.03017855 | val_mse=0.03734244 | best_val_mse=0.03730825 | early_stop=01/10 | 1.6s
    epoch 011/100 | train_mse=0.03013031 | val_mse=0.03729909 | best_val_mse=0.03729909 | early_stop=00/10 | 1.6s
    epoch 012/100 | train_mse=0.03012664 | val_mse=0.03730397 | best_val_mse=0.03729909 | early_stop=01/10 | 1.6s
    epoch 013/100 | train_mse=0.03014798 | val_mse=0.03730625 | best_val_mse=0.03729909 | early_stop=02/10 | 1.6s
    epoch 014/100 | train_mse=0.03012731 | val_mse=0.03729951 | best_val_mse=0.03729909 | early_stop=03/10 | 1.6s
    epoch 015/100 | train_mse=0.03011713 | val_mse=0.03733773 | best_val_mse=0.03729909 | early_stop=04/10 | 1.5s
    epoch 016/100 | train_mse=0.03016550 | val_mse=0.03730455 | best_val_mse=0.03729909 | early_stop=05/10 | 1.6s
    epoch 017/100 | train_mse=0.03011117 | val_mse=0.03740244 | best_val_mse=0.03729909 | early_stop=06/10 | 1.6s
    epoch 018/100 | train_mse=0.03010899 | val_mse=0.03727922 | best_val_mse=0.03727922 | early_stop=00/10 | 1.6s
    epoch 019/100 | train_mse=0.03009779 | val_mse=0.03728649 | best_val_mse=0.03727922 | early_stop=01/10 | 1.6s
    epoch 020/100 | train_mse=0.03013199 | val_mse=0.03738416 | best_val_mse=0.03727922 | early_stop=02/10 | 1.6s
    epoch 021/100 | train_mse=0.03010466 | val_mse=0.03730511 | best_val_mse=0.03727922 | early_stop=03/10 | 1.6s
    epoch 022/100 | train_mse=0.03009600 | val_mse=0.03728756 | best_val_mse=0.03727922 | early_stop=04/10 | 1.6s
    epoch 023/100 | train_mse=0.03010365 | val_mse=0.03726448 | best_val_mse=0.03726448 | early_stop=00/10 | 1.6s
    epoch 024/100 | train_mse=0.03002984 | val_mse=0.03738554 | best_val_mse=0.03726448 | early_stop=01/10 | 1.6s
    epoch 025/100 | train_mse=0.03008170 | val_mse=0.03734951 | best_val_mse=0.03726448 | early_stop=02/10 | 1.6s
    epoch 026/100 | train_mse=0.03018111 | val_mse=0.03730937 | best_val_mse=0.03726448 | early_stop=03/10 | 1.6s
    epoch 027/100 | train_mse=0.03003710 | val_mse=0.03734710 | best_val_mse=0.03726448 | early_stop=04/10 | 1.6s
    epoch 028/100 | train_mse=0.03005025 | val_mse=0.03729704 | best_val_mse=0.03726448 | early_stop=05/10 | 1.6s
    epoch 029/100 | train_mse=0.03000952 | val_mse=0.03728020 | best_val_mse=0.03726448 | early_stop=06/10 | 1.5s
    epoch 030/100 | train_mse=0.02997563 | val_mse=0.03731007 | best_val_mse=0.03726448 | early_stop=07/10 | 1.5s
    epoch 031/100 | train_mse=0.02997164 | val_mse=0.03733513 | best_val_mse=0.03726448 | early_stop=08/10 | 1.6s
    epoch 032/100 | train_mse=0.03002824 | val_mse=0.03729287 | best_val_mse=0.03726448 | early_stop=09/10 | 1.6s
    epoch 033/100 | train_mse=0.02998404 | val_mse=0.03726004 | best_val_mse=0.03726004 | early_stop=00/10 | 1.6s
    epoch 034/100 | train_mse=0.03011861 | val_mse=0.03727747 | best_val_mse=0.03726004 | early_stop=01/10 | 1.6s
    epoch 035/100 | train_mse=0.02994228 | val_mse=0.03734273 | best_val_mse=0.03726004 | early_stop=02/10 | 1.5s
    epoch 036/100 | train_mse=0.02992257 | val_mse=0.03731053 | best_val_mse=0.03726004 | early_stop=03/10 | 1.6s
    epoch 037/100 | train_mse=0.03000126 | val_mse=0.03737735 | best_val_mse=0.03726004 | early_stop=04/10 | 1.5s
    epoch 038/100 | train_mse=0.02989428 | val_mse=0.03722979 | best_val_mse=0.03722979 | early_stop=00/10 | 1.6s
    epoch 039/100 | train_mse=0.03001641 | val_mse=0.03724857 | best_val_mse=0.03722979 | early_stop=01/10 | 1.5s
    epoch 040/100 | train_mse=0.02994359 | val_mse=0.03724500 | best_val_mse=0.03722979 | early_stop=02/10 | 1.5s
    epoch 041/100 | train_mse=0.02985650 | val_mse=0.03717263 | best_val_mse=0.03717263 | early_stop=00/10 | 1.6s
    epoch 042/100 | train_mse=0.02986796 | val_mse=0.03712426 | best_val_mse=0.03712426 | early_stop=00/10 | 1.6s
    epoch 043/100 | train_mse=0.02987038 | val_mse=0.03712580 | best_val_mse=0.03712426 | early_stop=01/10 | 1.5s
    epoch 044/100 | train_mse=0.02977336 | val_mse=0.03728680 | best_val_mse=0.03712426 | early_stop=02/10 | 1.5s
    epoch 045/100 | train_mse=0.02965172 | val_mse=0.03719306 | best_val_mse=0.03712426 | early_stop=03/10 | 1.5s
    epoch 046/100 | train_mse=0.02981876 | val_mse=0.03710514 | best_val_mse=0.03710514 | early_stop=00/10 | 1.6s
    epoch 047/100 | train_mse=0.02979720 | val_mse=0.03723075 | best_val_mse=0.03710514 | early_stop=01/10 | 1.6s
    epoch 048/100 | train_mse=0.03007175 | val_mse=0.03708397 | best_val_mse=0.03708397 | early_stop=00/10 | 1.6s
    epoch 049/100 | train_mse=0.02988622 | val_mse=0.03714191 | best_val_mse=0.03708397 | early_stop=01/10 | 1.6s
    epoch 050/100 | train_mse=0.02965283 | val_mse=0.03711069 | best_val_mse=0.03708397 | early_stop=02/10 | 1.5s
    epoch 051/100 | train_mse=0.02961147 | val_mse=0.03700700 | best_val_mse=0.03700700 | early_stop=00/10 | 1.6s
    epoch 052/100 | train_mse=0.02954474 | val_mse=0.03706043 | best_val_mse=0.03700700 | early_stop=01/10 | 1.5s
    epoch 053/100 | train_mse=0.02973793 | val_mse=0.03698500 | best_val_mse=0.03698500 | early_stop=00/10 | 1.5s
    epoch 054/100 | train_mse=0.02952533 | val_mse=0.03767615 | best_val_mse=0.03698500 | early_stop=01/10 | 1.6s
    epoch 055/100 | train_mse=0.03003428 | val_mse=0.03728081 | best_val_mse=0.03698500 | early_stop=02/10 | 1.6s
    epoch 056/100 | train_mse=0.02958029 | val_mse=0.03708267 | best_val_mse=0.03698500 | early_stop=03/10 | 1.6s
    epoch 057/100 | train_mse=0.02961180 | val_mse=0.03700478 | best_val_mse=0.03698500 | early_stop=04/10 | 1.5s
    epoch 058/100 | train_mse=0.02948505 | val_mse=0.03693047 | best_val_mse=0.03693047 | early_stop=00/10 | 1.6s
    epoch 059/100 | train_mse=0.02961070 | val_mse=0.03703266 | best_val_mse=0.03693047 | early_stop=01/10 | 1.5s
    epoch 060/100 | train_mse=0.02942359 | val_mse=0.03699209 | best_val_mse=0.03693047 | early_stop=02/10 | 1.5s
    epoch 061/100 | train_mse=0.02940095 | val_mse=0.03692905 | best_val_mse=0.03692905 | early_stop=00/10 | 1.6s
    epoch 062/100 | train_mse=0.02939249 | val_mse=0.03709509 | best_val_mse=0.03692905 | early_stop=01/10 | 1.5s
    epoch 063/100 | train_mse=0.02954144 | val_mse=0.03699813 | best_val_mse=0.03692905 | early_stop=02/10 | 1.6s
    epoch 064/100 | train_mse=0.02931417 | val_mse=0.03693406 | best_val_mse=0.03692905 | early_stop=03/10 | 1.6s
    epoch 065/100 | train_mse=0.02932790 | val_mse=0.03693857 | best_val_mse=0.03692905 | early_stop=04/10 | 1.5s
    epoch 066/100 | train_mse=0.02931988 | val_mse=0.03695962 | best_val_mse=0.03692905 | early_stop=05/10 | 1.5s
    epoch 067/100 | train_mse=0.02930127 | val_mse=0.03707645 | best_val_mse=0.03692905 | early_stop=06/10 | 1.6s
    epoch 068/100 | train_mse=0.02958521 | val_mse=0.03712011 | best_val_mse=0.03692905 | early_stop=07/10 | 1.6s
    epoch 069/100 | train_mse=0.02931542 | val_mse=0.03741171 | best_val_mse=0.03692905 | early_stop=08/10 | 1.6s
    epoch 070/100 | train_mse=0.02952621 | val_mse=0.03711749 | best_val_mse=0.03692905 | early_stop=09/10 | 1.5s
    epoch 071/100 | train_mse=0.02947830 | val_mse=0.03701247 | best_val_mse=0.03692905 | early_stop=10/10 | 1.6s
  refit 14/26 | test_year=2012 | status=saved | n_predictions=44,459
  refit 15/26 | test_year=2013 | status=training | train_n=971,804 | validation_n=181,718 | test_n=44,277

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03218838 | val_mse=0.03064166 | best_val_mse=0.03064166 | early_stop=00/10 | 1.5s
    epoch 002/100 | train_mse=0.03169193 | val_mse=0.03098031 | best_val_mse=0.03064166 | early_stop=01/10 | 1.5s
    epoch 003/100 | train_mse=0.03153599 | val_mse=0.03068150 | best_val_mse=0.03064166 | early_stop=02/10 | 1.5s
    epoch 004/100 | train_mse=0.03143593 | val_mse=0.03103585 | best_val_mse=0.03064166 | early_stop=03/10 | 1.5s
    epoch 005/100 | train_mse=0.03136312 | val_mse=0.03065908 | best_val_mse=0.03064166 | early_stop=04/10 | 1.5s
    epoch 006/100 | train_mse=0.03135977 | val_mse=0.03120736 | best_val_mse=0.03064166 | early_stop=05/10 | 1.5s
    epoch 007/100 | train_mse=0.03142000 | val_mse=0.03079434 | best_val_mse=0.03064166 | early_stop=06/10 | 1.5s
    epoch 008/100 | train_mse=0.03129816 | val_mse=0.03120303 | best_val_mse=0.03064166 | early_stop=07/10 | 1.5s
    epoch 009/100 | train_mse=0.03124994 | val_mse=0.03097721 | best_val_mse=0.03064166 | early_stop=08/10 | 1.5s
    epoch 010/100 | train_mse=0.03133610 | val_mse=0.03063059 | best_val_mse=0.03063059 | early_stop=00/10 | 1.5s
    epoch 011/100 | train_mse=0.03123702 | val_mse=0.03088566 | best_val_mse=0.03063059 | early_stop=01/10 | 1.5s
    epoch 012/100 | train_mse=0.03121497 | val_mse=0.03116343 | best_val_mse=0.03063059 | early_stop=02/10 | 1.6s
    epoch 013/100 | train_mse=0.03123562 | val_mse=0.03113292 | best_val_mse=0.03063059 | early_stop=03/10 | 1.5s
    epoch 014/100 | train_mse=0.03129172 | val_mse=0.03098526 | best_val_mse=0.03063059 | early_stop=04/10 | 1.5s
    epoch 015/100 | train_mse=0.03134392 | val_mse=0.03193183 | best_val_mse=0.03063059 | early_stop=05/10 | 1.5s
    epoch 016/100 | train_mse=0.03122099 | val_mse=0.03065451 | best_val_mse=0.03063059 | early_stop=06/10 | 1.5s
    epoch 017/100 | train_mse=0.03132939 | val_mse=0.03078702 | best_val_mse=0.03063059 | early_stop=07/10 | 1.5s
    epoch 018/100 | train_mse=0.03119112 | val_mse=0.03100071 | best_val_mse=0.03063059 | early_stop=08/10 | 1.5s
    epoch 019/100 | train_mse=0.03116746 | val_mse=0.03115578 | best_val_mse=0.03063059 | early_stop=09/10 | 1.5s
    epoch 020/100 | train_mse=0.03122058 | val_mse=0.03088511 | best_val_mse=0.03063059 | early_stop=10/10 | 1.6s
  refit 15/26 | test_year=2013 | status=saved | n_predictions=44,277
  refit 16/26 | test_year=2014 | status=training | train_n=945,407 | validation_n=177,641 | test_n=45,510

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03452487 | val_mse=0.01828872 | best_val_mse=0.01828872 | early_stop=00/10 | 1.5s
    epoch 002/100 | train_mse=0.03403314 | val_mse=0.01779992 | best_val_mse=0.01779992 | early_stop=00/10 | 1.5s
    epoch 003/100 | train_mse=0.03364955 | val_mse=0.01782444 | best_val_mse=0.01779992 | early_stop=01/10 | 1.5s
    epoch 004/100 | train_mse=0.03363664 | val_mse=0.01802403 | best_val_mse=0.01779992 | early_stop=02/10 | 1.5s
    epoch 005/100 | train_mse=0.03361169 | val_mse=0.01782452 | best_val_mse=0.01779992 | early_stop=03/10 | 1.5s
    epoch 006/100 | train_mse=0.03356685 | val_mse=0.01778244 | best_val_mse=0.01778244 | early_stop=00/10 | 1.5s
    epoch 007/100 | train_mse=0.03353858 | val_mse=0.01784047 | best_val_mse=0.01778244 | early_stop=01/10 | 1.5s
    epoch 008/100 | train_mse=0.03354544 | val_mse=0.01777445 | best_val_mse=0.01777445 | early_stop=00/10 | 1.5s
    epoch 009/100 | train_mse=0.03353077 | val_mse=0.01779756 | best_val_mse=0.01777445 | early_stop=01/10 | 1.5s
    epoch 010/100 | train_mse=0.03350562 | val_mse=0.01783551 | best_val_mse=0.01777445 | early_stop=02/10 | 1.5s
    epoch 011/100 | train_mse=0.03346201 | val_mse=0.01778297 | best_val_mse=0.01777445 | early_stop=03/10 | 1.5s
    epoch 012/100 | train_mse=0.03356347 | val_mse=0.01782645 | best_val_mse=0.01777445 | early_stop=04/10 | 1.6s
    epoch 013/100 | train_mse=0.03349149 | val_mse=0.01779202 | best_val_mse=0.01777445 | early_stop=05/10 | 1.5s
    epoch 014/100 | train_mse=0.03344239 | val_mse=0.01778692 | best_val_mse=0.01777445 | early_stop=06/10 | 1.5s
    epoch 015/100 | train_mse=0.03340351 | val_mse=0.01780172 | best_val_mse=0.01777445 | early_stop=07/10 | 1.5s
    epoch 016/100 | train_mse=0.03356918 | val_mse=0.01776176 | best_val_mse=0.01776176 | early_stop=00/10 | 1.5s
    epoch 017/100 | train_mse=0.03357353 | val_mse=0.01788537 | best_val_mse=0.01776176 | early_stop=01/10 | 1.5s
    epoch 018/100 | train_mse=0.03347867 | val_mse=0.01792790 | best_val_mse=0.01776176 | early_stop=02/10 | 1.5s
    epoch 019/100 | train_mse=0.03336724 | val_mse=0.01780212 | best_val_mse=0.01776176 | early_stop=03/10 | 1.5s
    epoch 020/100 | train_mse=0.03354384 | val_mse=0.01779209 | best_val_mse=0.01776176 | early_stop=04/10 | 1.5s
    epoch 021/100 | train_mse=0.03344155 | val_mse=0.01785297 | best_val_mse=0.01776176 | early_stop=05/10 | 1.5s
    epoch 022/100 | train_mse=0.03332429 | val_mse=0.01799677 | best_val_mse=0.01776176 | early_stop=06/10 | 1.5s
    epoch 023/100 | train_mse=0.03341232 | val_mse=0.01779569 | best_val_mse=0.01776176 | early_stop=07/10 | 1.5s
    epoch 024/100 | train_mse=0.03335584 | val_mse=0.01778945 | best_val_mse=0.01776176 | early_stop=08/10 | 1.5s
    epoch 025/100 | train_mse=0.03332003 | val_mse=0.01803727 | best_val_mse=0.01776176 | early_stop=09/10 | 1.5s
    epoch 026/100 | train_mse=0.03332582 | val_mse=0.01781441 | best_val_mse=0.01776176 | early_stop=10/10 | 1.5s
  refit 16/26 | test_year=2014 | status=saved | n_predictions=45,510
  refit 17/26 | test_year=2015 | status=training | train_n=918,021 | validation_n=176,705 | test_n=46,909

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03474758 | val_mse=0.01703475 | best_val_mse=0.01703475 | early_stop=00/10 | 1.5s
    epoch 002/100 | train_mse=0.03436028 | val_mse=0.01631585 | best_val_mse=0.01631585 | early_stop=00/10 | 1.5s
    epoch 003/100 | train_mse=0.03411750 | val_mse=0.01631016 | best_val_mse=0.01631016 | early_stop=00/10 | 1.5s
    epoch 004/100 | train_mse=0.03403181 | val_mse=0.01633300 | best_val_mse=0.01631016 | early_stop=01/10 | 1.5s
    epoch 005/100 | train_mse=0.03400053 | val_mse=0.01628003 | best_val_mse=0.01628003 | early_stop=00/10 | 1.5s
    epoch 006/100 | train_mse=0.03399069 | val_mse=0.01624436 | best_val_mse=0.01624436 | early_stop=00/10 | 1.5s
    epoch 007/100 | train_mse=0.03390955 | val_mse=0.01626625 | best_val_mse=0.01624436 | early_stop=01/10 | 1.5s
    epoch 008/100 | train_mse=0.03392641 | val_mse=0.01632401 | best_val_mse=0.01624436 | early_stop=02/10 | 1.5s
    epoch 009/100 | train_mse=0.03387389 | val_mse=0.01625284 | best_val_mse=0.01624436 | early_stop=03/10 | 1.5s
    epoch 010/100 | train_mse=0.03392996 | val_mse=0.01626818 | best_val_mse=0.01624436 | early_stop=04/10 | 1.5s
    epoch 011/100 | train_mse=0.03394213 | val_mse=0.01624604 | best_val_mse=0.01624436 | early_stop=05/10 | 1.5s
    epoch 012/100 | train_mse=0.03386187 | val_mse=0.01624307 | best_val_mse=0.01624307 | early_stop=00/10 | 1.5s
    epoch 013/100 | train_mse=0.03379073 | val_mse=0.01625157 | best_val_mse=0.01624307 | early_stop=01/10 | 1.5s
    epoch 014/100 | train_mse=0.03378702 | val_mse=0.01637685 | best_val_mse=0.01624307 | early_stop=02/10 | 1.5s
    epoch 015/100 | train_mse=0.03383434 | val_mse=0.01630664 | best_val_mse=0.01624307 | early_stop=03/10 | 1.5s
    epoch 016/100 | train_mse=0.03376912 | val_mse=0.01630921 | best_val_mse=0.01624307 | early_stop=04/10 | 1.5s
    epoch 017/100 | train_mse=0.03383883 | val_mse=0.01627331 | best_val_mse=0.01624307 | early_stop=05/10 | 1.5s
    epoch 018/100 | train_mse=0.03380673 | val_mse=0.01640534 | best_val_mse=0.01624307 | early_stop=06/10 | 1.5s
    epoch 019/100 | train_mse=0.03380410 | val_mse=0.01629901 | best_val_mse=0.01624307 | early_stop=07/10 | 1.5s
    epoch 020/100 | train_mse=0.03383389 | val_mse=0.01624716 | best_val_mse=0.01624307 | early_stop=08/10 | 1.5s
    epoch 021/100 | train_mse=0.03372701 | val_mse=0.01641233 | best_val_mse=0.01624307 | early_stop=09/10 | 1.5s
    epoch 022/100 | train_mse=0.03381342 | val_mse=0.01624749 | best_val_mse=0.01624307 | early_stop=10/10 | 1.5s
  refit 17/26 | test_year=2015 | status=saved | n_predictions=46,909
  refit 18/26 | test_year=2016 | status=training | train_n=883,923 | validation_n=178,414 | test_n=45,819

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03438091 | val_mse=0.01500055 | best_val_mse=0.01500055 | early_stop=00/10 | 1.5s
    epoch 002/100 | train_mse=0.03396333 | val_mse=0.01494914 | best_val_mse=0.01494914 | early_stop=00/10 | 1.5s
    epoch 003/100 | train_mse=0.03399598 | val_mse=0.01490501 | best_val_mse=0.01490501 | early_stop=00/10 | 1.5s
    epoch 004/100 | train_mse=0.03379454 | val_mse=0.01488298 | best_val_mse=0.01488298 | early_stop=00/10 | 1.5s
    epoch 005/100 | train_mse=0.03373760 | val_mse=0.01488722 | best_val_mse=0.01488298 | early_stop=01/10 | 1.5s
    epoch 006/100 | train_mse=0.03369903 | val_mse=0.01502565 | best_val_mse=0.01488298 | early_stop=02/10 | 1.5s
    epoch 007/100 | train_mse=0.03365504 | val_mse=0.01499675 | best_val_mse=0.01488298 | early_stop=03/10 | 1.5s
    epoch 008/100 | train_mse=0.03363847 | val_mse=0.01500063 | best_val_mse=0.01488298 | early_stop=04/10 | 1.5s
    epoch 009/100 | train_mse=0.03364383 | val_mse=0.01489382 | best_val_mse=0.01488298 | early_stop=05/10 | 1.5s
    epoch 010/100 | train_mse=0.03367323 | val_mse=0.01488190 | best_val_mse=0.01488190 | early_stop=00/10 | 1.5s
    epoch 011/100 | train_mse=0.03367241 | val_mse=0.01487345 | best_val_mse=0.01487345 | early_stop=00/10 | 1.5s
    epoch 012/100 | train_mse=0.03353986 | val_mse=0.01484888 | best_val_mse=0.01484888 | early_stop=00/10 | 1.5s
    epoch 013/100 | train_mse=0.03368718 | val_mse=0.01498521 | best_val_mse=0.01484888 | early_stop=01/10 | 1.5s
    epoch 014/100 | train_mse=0.03360571 | val_mse=0.01488604 | best_val_mse=0.01484888 | early_stop=02/10 | 1.5s
    epoch 015/100 | train_mse=0.03355451 | val_mse=0.01487194 | best_val_mse=0.01484888 | early_stop=03/10 | 1.5s
    epoch 016/100 | train_mse=0.03358335 | val_mse=0.01492513 | best_val_mse=0.01484888 | early_stop=04/10 | 1.5s
    epoch 017/100 | train_mse=0.03354974 | val_mse=0.01487331 | best_val_mse=0.01484888 | early_stop=05/10 | 1.5s
    epoch 018/100 | train_mse=0.03357892 | val_mse=0.01492058 | best_val_mse=0.01484888 | early_stop=06/10 | 1.5s
    epoch 019/100 | train_mse=0.03353132 | val_mse=0.01492357 | best_val_mse=0.01484888 | early_stop=07/10 | 1.5s
    epoch 020/100 | train_mse=0.03349304 | val_mse=0.01500921 | best_val_mse=0.01484888 | early_stop=08/10 | 1.5s
    epoch 021/100 | train_mse=0.03349656 | val_mse=0.01488780 | best_val_mse=0.01484888 | early_stop=09/10 | 1.5s
    epoch 022/100 | train_mse=0.03349948 | val_mse=0.01488128 | best_val_mse=0.01484888 | early_stop=10/10 | 1.5s
  refit 18/26 | test_year=2016 | status=saved | n_predictions=45,819
  refit 19/26 | test_year=2017 | status=training | train_n=846,469 | validation_n=179,674 | test_n=44,940

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03431711 | val_mse=0.01653847 | best_val_mse=0.01653847 | early_stop=00/10 | 1.5s
    epoch 002/100 | train_mse=0.03391033 | val_mse=0.01637488 | best_val_mse=0.01637488 | early_stop=00/10 | 1.5s
    epoch 003/100 | train_mse=0.03386865 | val_mse=0.01634290 | best_val_mse=0.01634290 | early_stop=00/10 | 1.5s
    epoch 004/100 | train_mse=0.03389823 | val_mse=0.01649397 | best_val_mse=0.01634290 | early_stop=01/10 | 1.5s
    epoch 005/100 | train_mse=0.03368354 | val_mse=0.01633296 | best_val_mse=0.01633296 | early_stop=00/10 | 1.5s
    epoch 006/100 | train_mse=0.03369958 | val_mse=0.01629837 | best_val_mse=0.01629837 | early_stop=00/10 | 1.5s
    epoch 007/100 | train_mse=0.03362016 | val_mse=0.01643417 | best_val_mse=0.01629837 | early_stop=01/10 | 1.4s
    epoch 008/100 | train_mse=0.03364099 | val_mse=0.01632938 | best_val_mse=0.01629837 | early_stop=02/10 | 1.5s
    epoch 009/100 | train_mse=0.03368143 | val_mse=0.01631646 | best_val_mse=0.01629837 | early_stop=03/10 | 1.5s
    epoch 010/100 | train_mse=0.03363025 | val_mse=0.01644718 | best_val_mse=0.01629837 | early_stop=04/10 | 1.5s
    epoch 011/100 | train_mse=0.03361776 | val_mse=0.01631147 | best_val_mse=0.01629837 | early_stop=05/10 | 1.5s
    epoch 012/100 | train_mse=0.03356661 | val_mse=0.01635141 | best_val_mse=0.01629837 | early_stop=06/10 | 1.4s
    epoch 013/100 | train_mse=0.03363742 | val_mse=0.01635294 | best_val_mse=0.01629837 | early_stop=07/10 | 1.4s
    epoch 014/100 | train_mse=0.03354519 | val_mse=0.01631186 | best_val_mse=0.01629837 | early_stop=08/10 | 1.4s
    epoch 015/100 | train_mse=0.03356892 | val_mse=0.01632309 | best_val_mse=0.01629837 | early_stop=09/10 | 1.5s
    epoch 016/100 | train_mse=0.03353461 | val_mse=0.01631821 | best_val_mse=0.01629837 | early_stop=10/10 | 1.5s
  refit 19/26 | test_year=2017 | status=saved | n_predictions=44,940
  refit 20/26 | test_year=2018 | status=training | train_n=811,524 | validation_n=180,185 | test_n=45,340

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03289465 | val_mse=0.01854427 | best_val_mse=0.01854427 | early_stop=00/10 | 1.4s
    epoch 002/100 | train_mse=0.03236635 | val_mse=0.01861389 | best_val_mse=0.01854427 | early_stop=01/10 | 1.4s
    epoch 003/100 | train_mse=0.03241962 | val_mse=0.01853080 | best_val_mse=0.01853080 | early_stop=00/10 | 1.4s
    epoch 004/100 | train_mse=0.03221004 | val_mse=0.01843306 | best_val_mse=0.01843306 | early_stop=00/10 | 1.4s
    epoch 005/100 | train_mse=0.03218356 | val_mse=0.01841220 | best_val_mse=0.01841220 | early_stop=00/10 | 1.4s
    epoch 006/100 | train_mse=0.03216994 | val_mse=0.01844999 | best_val_mse=0.01841220 | early_stop=01/10 | 1.5s
    epoch 007/100 | train_mse=0.03215594 | val_mse=0.01844837 | best_val_mse=0.01841220 | early_stop=02/10 | 1.5s
    epoch 008/100 | train_mse=0.03216325 | val_mse=0.01847421 | best_val_mse=0.01841220 | early_stop=03/10 | 1.4s
    epoch 009/100 | train_mse=0.03213249 | val_mse=0.01844670 | best_val_mse=0.01841220 | early_stop=04/10 | 1.4s
    epoch 010/100 | train_mse=0.03231032 | val_mse=0.01839890 | best_val_mse=0.01839890 | early_stop=00/10 | 1.5s
    epoch 011/100 | train_mse=0.03212658 | val_mse=0.01852961 | best_val_mse=0.01839890 | early_stop=01/10 | 1.5s
    epoch 012/100 | train_mse=0.03216158 | val_mse=0.01844881 | best_val_mse=0.01839890 | early_stop=02/10 | 1.5s
    epoch 013/100 | train_mse=0.03206817 | val_mse=0.01841791 | best_val_mse=0.01839890 | early_stop=03/10 | 1.4s
    epoch 014/100 | train_mse=0.03204531 | val_mse=0.01851267 | best_val_mse=0.01839890 | early_stop=04/10 | 1.5s
    epoch 015/100 | train_mse=0.03216608 | val_mse=0.01843467 | best_val_mse=0.01839890 | early_stop=05/10 | 1.5s
    epoch 016/100 | train_mse=0.03208793 | val_mse=0.01858056 | best_val_mse=0.01839890 | early_stop=06/10 | 1.4s
    epoch 017/100 | train_mse=0.03212694 | val_mse=0.01849226 | best_val_mse=0.01839890 | early_stop=07/10 | 1.4s
    epoch 018/100 | train_mse=0.03207559 | val_mse=0.01856419 | best_val_mse=0.01839890 | early_stop=08/10 | 1.5s
    epoch 019/100 | train_mse=0.03202096 | val_mse=0.01841491 | best_val_mse=0.01839890 | early_stop=09/10 | 1.4s
    epoch 020/100 | train_mse=0.03198343 | val_mse=0.01852002 | best_val_mse=0.01839890 | early_stop=10/10 | 1.4s
  refit 20/26 | test_year=2018 | status=saved | n_predictions=45,340
  refit 21/26 | test_year=2019 | status=training | train_n=781,180 | validation_n=179,655 | test_n=46,350

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.03016651 | val_mse=0.01972433 | best_val_mse=0.01972433 | early_stop=00/10 | 1.5s
    epoch 002/100 | train_mse=0.02972379 | val_mse=0.01951243 | best_val_mse=0.01951243 | early_stop=00/10 | 1.5s
    epoch 003/100 | train_mse=0.02960198 | val_mse=0.01945179 | best_val_mse=0.01945179 | early_stop=00/10 | 1.5s
    epoch 004/100 | train_mse=0.02962498 | val_mse=0.01949896 | best_val_mse=0.01945179 | early_stop=01/10 | 1.5s
    epoch 005/100 | train_mse=0.02944666 | val_mse=0.01951334 | best_val_mse=0.01945179 | early_stop=02/10 | 1.5s
    epoch 006/100 | train_mse=0.02940873 | val_mse=0.01949286 | best_val_mse=0.01945179 | early_stop=03/10 | 1.5s
    epoch 007/100 | train_mse=0.02944218 | val_mse=0.01945416 | best_val_mse=0.01945179 | early_stop=04/10 | 1.5s
    epoch 008/100 | train_mse=0.02941149 | val_mse=0.01942193 | best_val_mse=0.01942193 | early_stop=00/10 | 1.5s
    epoch 009/100 | train_mse=0.02937882 | val_mse=0.01966314 | best_val_mse=0.01942193 | early_stop=01/10 | 1.5s
    epoch 010/100 | train_mse=0.02939555 | val_mse=0.01942816 | best_val_mse=0.01942193 | early_stop=02/10 | 1.5s
    epoch 011/100 | train_mse=0.02932966 | val_mse=0.01959527 | best_val_mse=0.01942193 | early_stop=03/10 | 1.5s
    epoch 012/100 | train_mse=0.02936551 | val_mse=0.01942252 | best_val_mse=0.01942193 | early_stop=04/10 | 1.5s
    epoch 013/100 | train_mse=0.02936095 | val_mse=0.01942991 | best_val_mse=0.01942193 | early_stop=05/10 | 1.5s
    epoch 014/100 | train_mse=0.02936113 | val_mse=0.01944950 | best_val_mse=0.01942193 | early_stop=06/10 | 1.5s
    epoch 015/100 | train_mse=0.02928246 | val_mse=0.01941094 | best_val_mse=0.01941094 | early_stop=00/10 | 1.5s
    epoch 016/100 | train_mse=0.02934246 | val_mse=0.01960889 | best_val_mse=0.01941094 | early_stop=01/10 | 1.5s
    epoch 017/100 | train_mse=0.02934725 | val_mse=0.01943247 | best_val_mse=0.01941094 | early_stop=02/10 | 1.5s
    epoch 018/100 | train_mse=0.02925757 | val_mse=0.01942229 | best_val_mse=0.01941094 | early_stop=03/10 | 1.5s
    epoch 019/100 | train_mse=0.02925980 | val_mse=0.01943913 | best_val_mse=0.01941094 | early_stop=04/10 | 1.5s
    epoch 020/100 | train_mse=0.02936833 | val_mse=0.01953108 | best_val_mse=0.01941094 | early_stop=05/10 | 1.5s
    epoch 021/100 | train_mse=0.02922828 | val_mse=0.01942742 | best_val_mse=0.01941094 | early_stop=06/10 | 1.5s
    epoch 022/100 | train_mse=0.02922912 | val_mse=0.01961670 | best_val_mse=0.01941094 | early_stop=07/10 | 1.5s
    epoch 023/100 | train_mse=0.02926636 | val_mse=0.01941333 | best_val_mse=0.01941094 | early_stop=08/10 | 1.4s
    epoch 024/100 | train_mse=0.02924888 | val_mse=0.01948913 | best_val_mse=0.01941094 | early_stop=09/10 | 1.4s
    epoch 025/100 | train_mse=0.02931038 | val_mse=0.01941830 | best_val_mse=0.01941094 | early_stop=10/10 | 1.4s
  refit 21/26 | test_year=2019 | status=saved | n_predictions=46,350
  refit 22/26 | test_year=2020 | status=training | train_n=752,961 | validation_n=178,743 | test_n=48,260

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02542213 | val_mse=0.02345193 | best_val_mse=0.02345193 | early_stop=00/10 | 1.4s
    epoch 002/100 | train_mse=0.02481099 | val_mse=0.02334084 | best_val_mse=0.02334084 | early_stop=00/10 | 1.4s
    epoch 003/100 | train_mse=0.02470571 | val_mse=0.02356299 | best_val_mse=0.02334084 | early_stop=01/10 | 1.4s
    epoch 004/100 | train_mse=0.02469961 | val_mse=0.02327405 | best_val_mse=0.02327405 | early_stop=00/10 | 1.4s
    epoch 005/100 | train_mse=0.02455133 | val_mse=0.02314218 | best_val_mse=0.02314218 | early_stop=00/10 | 1.4s
    epoch 006/100 | train_mse=0.02450117 | val_mse=0.02313342 | best_val_mse=0.02313342 | early_stop=00/10 | 1.4s
    epoch 007/100 | train_mse=0.02455179 | val_mse=0.02313495 | best_val_mse=0.02313342 | early_stop=01/10 | 1.4s
    epoch 008/100 | train_mse=0.02456012 | val_mse=0.02316424 | best_val_mse=0.02313342 | early_stop=02/10 | 1.4s
    epoch 009/100 | train_mse=0.02442423 | val_mse=0.02334665 | best_val_mse=0.02313342 | early_stop=03/10 | 1.4s
    epoch 010/100 | train_mse=0.02447823 | val_mse=0.02314477 | best_val_mse=0.02313342 | early_stop=04/10 | 1.4s
    epoch 011/100 | train_mse=0.02444710 | val_mse=0.02316571 | best_val_mse=0.02313342 | early_stop=05/10 | 1.4s
    epoch 012/100 | train_mse=0.02444483 | val_mse=0.02319621 | best_val_mse=0.02313342 | early_stop=06/10 | 1.4s
    epoch 013/100 | train_mse=0.02444377 | val_mse=0.02318990 | best_val_mse=0.02313342 | early_stop=07/10 | 1.4s
    epoch 014/100 | train_mse=0.02448962 | val_mse=0.02315086 | best_val_mse=0.02313342 | early_stop=08/10 | 1.4s
    epoch 015/100 | train_mse=0.02446272 | val_mse=0.02318995 | best_val_mse=0.02313342 | early_stop=09/10 | 1.4s
    epoch 016/100 | train_mse=0.02442115 | val_mse=0.02317821 | best_val_mse=0.02313342 | early_stop=10/10 | 1.4s
  refit 22/26 | test_year=2020 | status=saved | n_predictions=48,260
  refit 23/26 | test_year=2021 | status=training | train_n=729,092 | validation_n=180,735 | test_n=53,601

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02304135 | val_mse=0.02474179 | best_val_mse=0.02474179 | early_stop=00/10 | 1.4s
    epoch 002/100 | train_mse=0.02258287 | val_mse=0.02512734 | best_val_mse=0.02474179 | early_stop=01/10 | 1.4s
    epoch 003/100 | train_mse=0.02256133 | val_mse=0.02469933 | best_val_mse=0.02469933 | early_stop=00/10 | 1.4s
    epoch 004/100 | train_mse=0.02231879 | val_mse=0.02462692 | best_val_mse=0.02462692 | early_stop=00/10 | 1.4s
    epoch 005/100 | train_mse=0.02242678 | val_mse=0.02460243 | best_val_mse=0.02460243 | early_stop=00/10 | 1.4s
    epoch 006/100 | train_mse=0.02234553 | val_mse=0.02459026 | best_val_mse=0.02459026 | early_stop=00/10 | 1.4s
    epoch 007/100 | train_mse=0.02226677 | val_mse=0.02459540 | best_val_mse=0.02459026 | early_stop=01/10 | 1.4s
    epoch 008/100 | train_mse=0.02232892 | val_mse=0.02469063 | best_val_mse=0.02459026 | early_stop=02/10 | 1.4s
    epoch 009/100 | train_mse=0.02227022 | val_mse=0.02459039 | best_val_mse=0.02459026 | early_stop=03/10 | 1.4s
    epoch 010/100 | train_mse=0.02226604 | val_mse=0.02459582 | best_val_mse=0.02459026 | early_stop=04/10 | 1.4s
    epoch 011/100 | train_mse=0.02223632 | val_mse=0.02460690 | best_val_mse=0.02459026 | early_stop=05/10 | 1.4s
    epoch 012/100 | train_mse=0.02227863 | val_mse=0.02460233 | best_val_mse=0.02459026 | early_stop=06/10 | 1.4s
    epoch 013/100 | train_mse=0.02225679 | val_mse=0.02463008 | best_val_mse=0.02459026 | early_stop=07/10 | 1.4s
    epoch 014/100 | train_mse=0.02224468 | val_mse=0.02458122 | best_val_mse=0.02458122 | early_stop=00/10 | 1.4s
    epoch 015/100 | train_mse=0.02228111 | val_mse=0.02466322 | best_val_mse=0.02458122 | early_stop=01/10 | 1.4s
    epoch 016/100 | train_mse=0.02220924 | val_mse=0.02463265 | best_val_mse=0.02458122 | early_stop=02/10 | 1.4s
    epoch 017/100 | train_mse=0.02216925 | val_mse=0.02462841 | best_val_mse=0.02458122 | early_stop=03/10 | 1.4s
    epoch 018/100 | train_mse=0.02223413 | val_mse=0.02458833 | best_val_mse=0.02458122 | early_stop=04/10 | 1.4s
    epoch 019/100 | train_mse=0.02217433 | val_mse=0.02465976 | best_val_mse=0.02458122 | early_stop=05/10 | 1.4s
    epoch 020/100 | train_mse=0.02221396 | val_mse=0.02460308 | best_val_mse=0.02458122 | early_stop=06/10 | 1.4s
    epoch 021/100 | train_mse=0.02227524 | val_mse=0.02462709 | best_val_mse=0.02458122 | early_stop=07/10 | 1.4s
    epoch 022/100 | train_mse=0.02216326 | val_mse=0.02468281 | best_val_mse=0.02458122 | early_stop=08/10 | 1.4s
    epoch 023/100 | train_mse=0.02217880 | val_mse=0.02462844 | best_val_mse=0.02458122 | early_stop=09/10 | 1.4s
    epoch 024/100 | train_mse=0.02215181 | val_mse=0.02465608 | best_val_mse=0.02458122 | early_stop=10/10 | 1.4s
  refit 23/26 | test_year=2021 | status=saved | n_predictions=53,601
  refit 24/26 | test_year=2022 | status=training | train_n=714,648 | validation_n=189,194 | test_n=56,253

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02187643 | val_mse=0.04309168 | best_val_mse=0.04309168 | early_stop=00/10 | 1.4s
    epoch 002/100 | train_mse=0.02132577 | val_mse=0.04297610 | best_val_mse=0.04297610 | early_stop=00/10 | 1.4s
    epoch 003/100 | train_mse=0.02128014 | val_mse=0.04315745 | best_val_mse=0.04297610 | early_stop=01/10 | 1.4s
    epoch 004/100 | train_mse=0.02143522 | val_mse=0.04281589 | best_val_mse=0.04281589 | early_stop=00/10 | 1.4s
    epoch 005/100 | train_mse=0.02119281 | val_mse=0.04276206 | best_val_mse=0.04276206 | early_stop=00/10 | 1.4s
    epoch 006/100 | train_mse=0.02113618 | val_mse=0.04276914 | best_val_mse=0.04276206 | early_stop=01/10 | 1.4s
    epoch 007/100 | train_mse=0.02107618 | val_mse=0.04284960 | best_val_mse=0.04276206 | early_stop=02/10 | 1.4s
    epoch 008/100 | train_mse=0.02112394 | val_mse=0.04281221 | best_val_mse=0.04276206 | early_stop=03/10 | 1.3s
    epoch 009/100 | train_mse=0.02105871 | val_mse=0.04280081 | best_val_mse=0.04276206 | early_stop=04/10 | 1.3s
    epoch 010/100 | train_mse=0.02103698 | val_mse=0.04287307 | best_val_mse=0.04276206 | early_stop=05/10 | 1.3s
    epoch 011/100 | train_mse=0.02103687 | val_mse=0.04279073 | best_val_mse=0.04276206 | early_stop=06/10 | 1.4s
    epoch 012/100 | train_mse=0.02107329 | val_mse=0.04284746 | best_val_mse=0.04276206 | early_stop=07/10 | 1.4s
    epoch 013/100 | train_mse=0.02103414 | val_mse=0.04313169 | best_val_mse=0.04276206 | early_stop=08/10 | 1.4s
    epoch 014/100 | train_mse=0.02104650 | val_mse=0.04286751 | best_val_mse=0.04276206 | early_stop=09/10 | 1.4s
    epoch 015/100 | train_mse=0.02102349 | val_mse=0.04290584 | best_val_mse=0.04276206 | early_stop=10/10 | 1.4s
  refit 24/26 | test_year=2022 | status=saved | n_predictions=56,253
  refit 25/26 | test_year=2023 | status=training | train_n=705,086 | validation_n=200,324 | test_n=53,289

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02228257 | val_mse=0.04120696 | best_val_mse=0.04120696 | early_stop=00/10 | 1.4s
    epoch 002/100 | train_mse=0.02161886 | val_mse=0.04122010 | best_val_mse=0.04120696 | early_stop=01/10 | 1.4s
    epoch 003/100 | train_mse=0.02144859 | val_mse=0.04114263 | best_val_mse=0.04114263 | early_stop=00/10 | 1.4s
    epoch 004/100 | train_mse=0.02150765 | val_mse=0.04136835 | best_val_mse=0.04114263 | early_stop=01/10 | 1.4s
    epoch 005/100 | train_mse=0.02149612 | val_mse=0.04113540 | best_val_mse=0.04113540 | early_stop=00/10 | 1.4s
    epoch 006/100 | train_mse=0.02135022 | val_mse=0.04136683 | best_val_mse=0.04113540 | early_stop=01/10 | 1.4s
    epoch 007/100 | train_mse=0.02134366 | val_mse=0.04110024 | best_val_mse=0.04110024 | early_stop=00/10 | 1.4s
    epoch 008/100 | train_mse=0.02133109 | val_mse=0.04116163 | best_val_mse=0.04110024 | early_stop=01/10 | 1.4s
    epoch 009/100 | train_mse=0.02130336 | val_mse=0.04114325 | best_val_mse=0.04110024 | early_stop=02/10 | 1.4s
    epoch 010/100 | train_mse=0.02130519 | val_mse=0.04117258 | best_val_mse=0.04110024 | early_stop=03/10 | 1.4s
    epoch 011/100 | train_mse=0.02130770 | val_mse=0.04116853 | best_val_mse=0.04110024 | early_stop=04/10 | 1.4s
    epoch 012/100 | train_mse=0.02129618 | val_mse=0.04110080 | best_val_mse=0.04110024 | early_stop=05/10 | 1.4s
    epoch 013/100 | train_mse=0.02130776 | val_mse=0.04128755 | best_val_mse=0.04110024 | early_stop=06/10 | 1.4s
    epoch 014/100 | train_mse=0.02124745 | val_mse=0.04123075 | best_val_mse=0.04110024 | early_stop=07/10 | 1.4s
    epoch 015/100 | train_mse=0.02127340 | val_mse=0.04115375 | best_val_mse=0.04110024 | early_stop=08/10 | 1.4s
    epoch 016/100 | train_mse=0.02122127 | val_mse=0.04118679 | best_val_mse=0.04110024 | early_stop=09/10 | 1.4s
    epoch 017/100 | train_mse=0.02124846 | val_mse=0.04109030 | best_val_mse=0.04109030 | early_stop=00/10 | 1.4s
    epoch 018/100 | train_mse=0.02124777 | val_mse=0.04112966 | best_val_mse=0.04109030 | early_stop=01/10 | 1.4s
    epoch 019/100 | train_mse=0.02127354 | val_mse=0.04115906 | best_val_mse=0.04109030 | early_stop=02/10 | 1.3s
    epoch 020/100 | train_mse=0.02120939 | val_mse=0.04114476 | best_val_mse=0.04109030 | early_stop=03/10 | 1.4s
    epoch 021/100 | train_mse=0.02124117 | val_mse=0.04113175 | best_val_mse=0.04109030 | early_stop=04/10 | 1.4s
    epoch 022/100 | train_mse=0.02121066 | val_mse=0.04112723 | best_val_mse=0.04109030 | early_stop=05/10 | 1.4s
    epoch 023/100 | train_mse=0.02117715 | val_mse=0.04123980 | best_val_mse=0.04109030 | early_stop=06/10 | 1.4s
    epoch 024/100 | train_mse=0.02118049 | val_mse=0.04118559 | best_val_mse=0.04109030 | early_stop=07/10 | 1.4s
    epoch 025/100 | train_mse=0.02119696 | val_mse=0.04146931 | best_val_mse=0.04109030 | early_stop=08/10 | 1.4s
    epoch 026/100 | train_mse=0.02117999 | val_mse=0.04119952 | best_val_mse=0.04109030 | early_stop=09/10 | 1.4s
    epoch 027/100 | train_mse=0.02115951 | val_mse=0.04120510 | best_val_mse=0.04109030 | early_stop=10/10 | 1.3s
  refit 25/26 | test_year=2023 | status=saved | n_predictions=53,289
  refit 26/26 | test_year=2024 | status=training | train_n=698,959 | validation_n=207,476 | test_n=49,147

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

    epoch 001/100 | train_mse=0.02268921 | val_mse=0.04520349 | best_val_mse=0.04520349 | early_stop=00/10 | 1.4s
    epoch 002/100 | train_mse=0.02238969 | val_mse=0.04516050 | best_val_mse=0.04516050 | early_stop=00/10 | 1.4s
    epoch 003/100 | train_mse=0.02234955 | val_mse=0.04500828 | best_val_mse=0.04500828 | early_stop=00/10 | 1.4s
    epoch 004/100 | train_mse=0.02217075 | val_mse=0.04496568 | best_val_mse=0.04496568 | early_stop=00/10 | 1.4s
    epoch 005/100 | train_mse=0.02216924 | val_mse=0.04500365 | best_val_mse=0.04496568 | early_stop=01/10 | 1.4s
    epoch 006/100 | train_mse=0.02213612 | val_mse=0.04496039 | best_val_mse=0.04496039 | early_stop=00/10 | 1.4s
    epoch 007/100 | train_mse=0.02207522 | val_mse=0.04497667 | best_val_mse=0.04496039 | early_stop=01/10 | 1.4s
    epoch 008/100 | train_mse=0.02205943 | val_mse=0.04515593 | best_val_mse=0.04496039 | early_stop=02/10 | 1.4s
    epoch 009/100 | train_mse=0.02211640 | val_mse=0.04497149 | best_val_mse=0.04496039 | early_stop=03/10 | 1.4s
    epoch 010/100 | train_mse=0.02203875 | val_mse=0.04496927 | best_val_mse=0.04496039 | early_stop=04/10 | 1.4s
    epoch 011/100 | train_mse=0.02203281 | val_mse=0.04498076 | best_val_mse=0.04496039 | early_stop=05/10 | 1.4s
    epoch 012/100 | train_mse=0.02202397 | val_mse=0.04504691 | best_val_mse=0.04496039 | early_stop=06/10 | 1.4s
    epoch 013/100 | train_mse=0.02201303 | val_mse=0.04494894 | best_val_mse=0.04494894 | early_stop=00/10 | 1.4s
    epoch 014/100 | train_mse=0.02198604 | val_mse=0.04495257 | best_val_mse=0.04494894 | early_stop=01/10 | 1.4s
    epoch 015/100 | train_mse=0.02201966 | val_mse=0.04499525 | best_val_mse=0.04494894 | early_stop=02/10 | 1.4s
    epoch 016/100 | train_mse=0.02197527 | val_mse=0.04493829 | best_val_mse=0.04493829 | early_stop=00/10 | 1.4s
    epoch 017/100 | train_mse=0.02203494 | val_mse=0.04495893 | best_val_mse=0.04493829 | early_stop=01/10 | 1.4s
    epoch 018/100 | train_mse=0.02198261 | val_mse=0.04494358 | best_val_mse=0.04493829 | early_stop=02/10 | 1.4s
    epoch 019/100 | train_mse=0.02198890 | val_mse=0.04497476 | best_val_mse=0.04493829 | early_stop=03/10 | 1.4s
    epoch 020/100 | train_mse=0.02195337 | val_mse=0.04496070 | best_val_mse=0.04493829 | early_stop=04/10 | 1.4s
    epoch 021/100 | train_mse=0.02192544 | val_mse=0.04496087 | best_val_mse=0.04493829 | early_stop=05/10 | 1.4s
    epoch 022/100 | train_mse=0.02198762 | val_mse=0.04527964 | best_val_mse=0.04493829 | early_stop=06/10 | 1.4s
    epoch 023/100 | train_mse=0.02201274 | val_mse=0.04499173 | best_val_mse=0.04493829 | early_stop=07/10 | 1.4s
    epoch 024/100 | train_mse=0.02197929 | val_mse=0.04495502 | best_val_mse=0.04493829 | early_stop=08/10 | 1.4s
    epoch 025/100 | train_mse=0.02197926 | val_mse=0.04496688 | best_val_mse=0.04493829 | early_stop=09/10 | 1.4s
    epoch 026/100 | train_mse=0.02188694 | val_mse=0.04494059 | best_val_mse=0.04493829 | early_stop=10/10 | 1.4s
  refit 26/26 | test_year=2024 | status=saved | n_predictions=49,147

,model_id,model_signature,pooled_oos_r2,n_predictions,diagnostics_version,robust_oos_r2,mean_monthly_rank_ic,stock_count_weighted_mean_rank_ic,rank_ic_std,rank_ic_information_ratio,...,tail_5pct_mean_short_coverage,mean_monthly_return,annualized_return,annualized_volatility,sharpe,t_stat,newey_west_t_stat,max_drawdown,hit_rate,n_months
8,LGBM_20,2384b144be38bad7,0.003086,1356639,post_model_v6_fractional_ties,0.003808,0.060782,0.065054,0.098706,2.133144,...,0.983126,0.023449,0.281386,0.190347,1.478275,7.537755,5.577166,-0.373339,0.695513,312
18,XGBOOST_20,507f3c420a300c4b,0.002922,1356639,post_model_v6_fractional_ties,0.003854,0.062256,0.066416,0.098213,2.195861,...,0.984952,0.023188,0.278261,0.197928,1.405871,7.168563,5.435424,-0.432644,0.708333,312
9,LGBM_40,9c0540e864a705bf,0.002835,1356639,post_model_v6_fractional_ties,0.003282,0.053859,0.058450,0.089344,2.088255,...,0.978927,0.024516,0.294188,0.176287,1.668800,8.509243,5.742294,-0.318891,0.746795,312
12,LGBM_60,94e3ec047ddc57fc,0.002619,1356639,post_model_v6_fractional_ties,0.002808,0.034065,0.038211,0.110666,1.066310,...,0.976185,0.019709,0.236512,0.185318,1.276250,6.507623,4.146292,-0.361825,0.641026,312
11,LGBM_40_LAG2,5ea44d3ad39373d9,0.002538,1356639,post_model_v6_fractional_ties,0.002916,0.056310,0.061383,0.095859,2.034899,...,0.982039,0.025517,0.306208,0.184819,1.656799,8.448048,5.819175,-0.367963,0.730769,312
10,LGBM_40_LAG1,4aafd74344026b96,0.002302,1356639,post_model_v6_fractional_ties,0.002672,0.055924,0.060804,0.094822,2.043043,...,0.979866,0.025624,0.307483,0.182669,1.683278,8.583070,5.917585,-0.330912,0.753205,312
14,MLP_40,e6a25033ee712d15,0.002287,1356639,post_model_v6_fractional_ties,0.002552,0.060230,0.064485,0.089489,2.331493,...,0.990752,0.025333,0.304001,0.177616,1.711557,8.727261,5.805627,-0.289474,0.721154,312
16,NN3_20,739c8c490c1c6d16,0.001806,1356639,post_model_v6_fractional_ties,0.002120,0.051122,0.054852,0.090022,1.967208,...,0.985011,0.019546,0.234549,0.180191,1.301669,6.637238,4.855011,-0.413451,0.692308,312
6,LASSO_20,bc11f57268346015,0.001746,1356639,post_model_v6_fractional_ties,0.002109,0.071919,0.076510,0.133655,1.864029,...,0.987852,0.014327,0.171923,0.240600,0.714560,3.643554,2.969408,-0.567106,0.467949,312
5,HYBRID_MLP40_DEEPSET40,e76569f5ea5b351a,0.001529,1356639,post_model_v6_fractional_ties,0.001416,0.057928,0.061570,0.083942,2.390546,...,0.992155,0.024872,0.298459,0.170882,1.746579,8.905839,5.839902,-0.354444,0.733974,312
3,HYBRID_LGBM40_DEEPSET40,993ba37b5aa04e71,0.001487,1356639,post_model_v6_fractional_ties,0.001416,0.055509,0.059133,0.085144,2.258404,...,0.978281,0.025577,0.306929,0.166189,1.846868,9.417218,6.350380,-0.318594,0.753205,312
4,HYBRID_LGBM40_DEEPSET40_DYNAMIC,1c0cc8c096b31146,0.001325,1356639,post_model_v6_fractional_ties,0.001338,0.057151,0.061133,0.084803,2.334582,...,0.977722,0.026067,0.312803,0.170194,1.837917,9.371576,5.672754,-0.299941,0.769231,312
7,LGBM_100,56fb90cc59a0ce74,0.000887,1356639,post_model_v6_fractional_ties,0.000459,0.027856,0.031953,0.100949,0.955883,...,0.989350,0.014791,0.177496,0.181166,0.979739,4.995710,3.160333,-0.335618,0.634615,312
13,LGBM_80,80077a60ed146994,0.000763,1356639,post_model_v6_fractional_ties,0.000328,0.033160,0.037410,0.107805,1.065528,...,0.981085,0.017261,0.207132,0.186276,1.111968,5.669946,3.813405,-0.311793,0.637821,312
15,NN2_20,6130644ff7a7bc93,0.000372,1356639,post_model_v6_fractional_ties,0.000306,0.045747,0.048868,0.078438,2.020356,...,0.993852,0.017153,0.205838,0.177501,1.159647,5.913063,4.581541,-0.477759,0.669872,312
0,DEEPSET_40,4278ae26cf4fdcb7,0.000371,1356639,post_model_v6_fractional_ties,-0.000050,0.057759,0.061314,0.081708,2.448762,...,0.990836,0.024202,0.290423,0.164595,1.764464,8.997036,6.140677,-0.372863,0.724359,312
17,NN4_20,eee1133001253343,-0.000839,1356639,post_model_v6_fractional_ties,-0.001544,0.039566,0.042808,0.087253,1.570859,...,0.988585,0.009241,0.110896,0.194979,0.568762,2.900129,2.389890,-0.490236,0.631410,312
2,DEEPSET_40_LAG1,daaa24e9d2d7a5a6,-0.001073,1356639,post_model_v6_fractional_ties,-0.001867,0.058043,0.061046,0.077662,2.589023,...,0.985910,0.024427,0.293127,0.167634,1.748609,8.916192,6.505526,-0.350012,0.737179,312
1,DEEPSET_40_DYNAMIC,4a51c6755ddf965f,-0.001240,1356639,post_model_v6_fractional_ties,-0.002081,0.057633,0.061071,0.073511,2.715839,...,0.987655,0.026086,0.313032,0.162574,1.925476,9.818042,6.274631,-0.327161,0.753205,312

## 5. HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50

After `LGBM_40` and `DEEPSET_40_DYNAMIC` are complete, this forms a transparent US comparator by averaging their independently trained, observation-aligned OOS predictions. It performs no additional fitting and does not use test outcomes to choose weights.

In [5]:
import pandas as pd
from src.developed_markets import build_fifty_fifty_comparator

us_fifty_fifty = build_fifty_fifty_comparator(CONFIG)
display(pd.DataFrame([us_fifty_fifty]))

,model_id,model_signature,comparator_version,pooled_oos_r2,robust_oos_r2,mean_monthly_rank_ic,stock_count_weighted_mean_rank_ic,rank_ic_std,rank_ic_information_ratio,rank_ic_t_stat,...,rank_ic_autocorr_lag12,mean_monthly_return,annualized_return,annualized_volatility,sharpe,t_stat,newey_west_t_stat,max_drawdown,hit_rate,n_months
0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,d14e8c2a63ec5c8e,standalone_oos_prediction_average_v1,0.003475,0.00403,0.060747,0.065044,0.077398,2.718839,13.863413,...,-0.041883,0.028445,0.34134,0.168209,2.029261,10.347244,6.382897,-0.35137,0.766026,312

## 6. Reload saved comparison

In [6]:
import pandas as pd

comparison_path = CONFIG.run_dir / 'model_comparison.csv'
if comparison_path.exists():
    display(pd.read_csv(comparison_path))
else:
    print('No completed model comparison exists yet.')

,model_id,model_signature,pooled_oos_r2,n_predictions,diagnostics_version,robust_oos_r2,mean_monthly_rank_ic,stock_count_weighted_mean_rank_ic,rank_ic_std,rank_ic_information_ratio,...,tail_5pct_mean_short_coverage,mean_monthly_return,annualized_return,annualized_volatility,sharpe,t_stat,newey_west_t_stat,max_drawdown,hit_rate,n_months
0,LGBM_20,2384b144be38bad7,0.003086,1356639,post_model_v6_fractional_ties,0.003808,0.060782,0.065054,0.098706,2.133144,...,0.983126,0.023449,0.281386,0.190347,1.478275,7.537755,5.577166,-0.373339,0.695513,312
1,XGBOOST_20,507f3c420a300c4b,0.002922,1356639,post_model_v6_fractional_ties,0.003854,0.062256,0.066416,0.098213,2.195861,...,0.984952,0.023188,0.278261,0.197928,1.405871,7.168563,5.435424,-0.432644,0.708333,312
2,LGBM_40,9c0540e864a705bf,0.002835,1356639,post_model_v6_fractional_ties,0.003282,0.053859,0.058450,0.089344,2.088255,...,0.978927,0.024516,0.294188,0.176287,1.668800,8.509243,5.742294,-0.318891,0.746795,312
3,LGBM_60,94e3ec047ddc57fc,0.002619,1356639,post_model_v6_fractional_ties,0.002808,0.034065,0.038211,0.110666,1.066310,...,0.976185,0.019709,0.236512,0.185318,1.276250,6.507623,4.146292,-0.361825,0.641026,312
4,LGBM_40_LAG2,5ea44d3ad39373d9,0.002538,1356639,post_model_v6_fractional_ties,0.002916,0.056310,0.061383,0.095859,2.034899,...,0.982039,0.025517,0.306208,0.184819,1.656799,8.448048,5.819175,-0.367963,0.730769,312
5,LGBM_40_LAG1,4aafd74344026b96,0.002302,1356639,post_model_v6_fractional_ties,0.002672,0.055924,0.060804,0.094822,2.043043,...,0.979866,0.025624,0.307483,0.182669,1.683278,8.583070,5.917585,-0.330912,0.753205,312
6,MLP_40,e6a25033ee712d15,0.002287,1356639,post_model_v6_fractional_ties,0.002552,0.060230,0.064485,0.089489,2.331493,...,0.990752,0.025333,0.304001,0.177616,1.711557,8.727261,5.805627,-0.289474,0.721154,312
7,NN3_20,739c8c490c1c6d16,0.001806,1356639,post_model_v6_fractional_ties,0.002120,0.051122,0.054852,0.090022,1.967208,...,0.985011,0.019546,0.234549,0.180191,1.301669,6.637238,4.855011,-0.413451,0.692308,312
8,LASSO_20,bc11f57268346015,0.001746,1356639,post_model_v6_fractional_ties,0.002109,0.071919,0.076510,0.133655,1.864029,...,0.987852,0.014327,0.171923,0.240600,0.714560,3.643554,2.969408,-0.567106,0.467949,312
9,HYBRID_MLP40_DEEPSET40,e76569f5ea5b351a,0.001529,1356639,post_model_v6_fractional_ties,0.001416,0.057928,0.061570,0.083942,2.390546,...,0.992155,0.024872,0.298459,0.170882,1.746579,8.905839,5.839902,-0.354444,0.733974,312
10,HYBRID_LGBM40_DEEPSET40,993ba37b5aa04e71,0.001487,1356639,post_model_v6_fractional_ties,0.001416,0.055509,0.059133,0.085144,2.258404,...,0.978281,0.025577,0.306929,0.166189,1.846868,9.417218,6.350380,-0.318594,0.753205,312
11,HYBRID_LGBM40_DEEPSET40_DYNAMIC,1c0cc8c096b31146,0.001325,1356639,post_model_v6_fractional_ties,0.001338,0.057151,0.061133,0.084803,2.334582,...,0.977722,0.026067,0.312803,0.170194,1.837917,9.371576,5.672754,-0.299941,0.769231,312
12,LGBM_100,56fb90cc59a0ce74,0.000887,1356639,post_model_v6_fractional_ties,0.000459,0.027856,0.031953,0.100949,0.955883,...,0.989350,0.014791,0.177496,0.181166,0.979739,4.995710,3.160333,-0.335618,0.634615,312
13,LGBM_80,80077a60ed146994,0.000763,1356639,post_model_v6_fractional_ties,0.000328,0.033160,0.037410,0.107805,1.065528,...,0.981085,0.017261,0.207132,0.186276,1.111968,5.669946,3.813405,-0.311793,0.637821,312
14,NN2_20,6130644ff7a7bc93,0.000372,1356639,post_model_v6_fractional_ties,0.000306,0.045747,0.048868,0.078438,2.020356,...,0.993852,0.017153,0.205838,0.177501,1.159647,5.913063,4.581541,-0.477759,0.669872,312
15,DEEPSET_40,4278ae26cf4fdcb7,0.000371,1356639,post_model_v6_fractional_ties,-0.000050,0.057759,0.061314,0.081708,2.448762,...,0.990836,0.024202,0.290423,0.164595,1.764464,8.997036,6.140677,-0.372863,0.724359,312
16,NN4_20,eee1133001253343,-0.000839,1356639,post_model_v6_fractional_ties,-0.001544,0.039566,0.042808,0.087253,1.570859,...,0.988585,0.009241,0.110896,0.194979,0.568762,2.900129,2.389890,-0.490236,0.631410,312
17,DEEPSET_40_LAG1,daaa24e9d2d7a5a6,-0.001073,1356639,post_model_v6_fractional_ties,-0.001867,0.058043,0.061046,0.077662,2.589023,...,0.985910,0.024427,0.293127,0.167634,1.748609,8.916192,6.505526,-0.350012,0.737179,312
18,DEEPSET_40_DYNAMIC,4a51c6755ddf965f,-0.001240,1356639,post_model_v6_fractional_ties,-0.002081,0.057633,0.061071,0.073511,2.715839,...,0.987655,0.026086,0.313032,0.162574,1.925476,9.818042,6.274631,-0.327161,0.753205,312

## 7. Portfolio implementability robustness

This cached diagnostic reads each pooled prediction file once and never loads model weights. It evaluates the 10% tail portfolio under full/ex-microcap universes, equal/value weighting, fixed proportional transaction-cost scenarios, and the adverse missing-return stress.

In [ ]:
from src.portfolio_robustness import run_portfolio_robustness

ROBUSTNESS_MODEL_IDS = (
    'LGBM_40',
    'DEEPSET_40_DYNAMIC',
    'HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50',
)

portfolio_robustness = run_portfolio_robustness(
    CONFIG.run_dir,
    model_ids=ROBUSTNESS_MODEL_IDS,
)
display(portfolio_robustness)

LGBM_40: current robustness; skipping
DEEPSET_40_DYNAMIC: saved portfolio robustness
HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50: saved portfolio robustness

,universe,weighting,mean_monthly_turnover,annualized_turnover,mean_n_eligible,mean_long_coverage,mean_short_coverage,gross_mean_monthly_return,gross_annualized_return,gross_annualized_volatility,...,outlier_exclude_abs_gt_10_sharpe,outlier_exclude_abs_gt_10_t_stat,outlier_exclude_abs_gt_10_newey_west_t_stat,outlier_exclude_abs_gt_10_max_drawdown,outlier_exclude_abs_gt_10_hit_rate,outlier_exclude_abs_gt_10_n_months,n_market_abs_gt_10,n_selected_abs_gt_10,model_id,model_signature
4,EX_MICRO,EQUAL,1.183841,14.206098,2284.227564,0.991476,0.994021,0.014417,0.173007,0.180433,...,0.958842,4.889154,3.892569,-0.391687,0.657051,312,1,0,DEEPSET_40_DYNAMIC,4a51c6755ddf965f
5,EX_MICRO,VALUE,1.396020,16.752235,2284.227564,0.991476,0.994021,0.010148,0.121775,0.201062,...,0.605659,3.088265,3.023649,-0.408595,0.592949,312,1,0,DEEPSET_40_DYNAMIC,4a51c6755ddf965f
6,FULL,EQUAL,1.151408,13.816897,4348.201923,0.989532,0.984097,0.026060,0.312722,0.162586,...,1.957261,9.980112,6.373144,-0.328509,0.756410,312,9,2,DEEPSET_40_DYNAMIC,4a51c6755ddf965f
7,FULL,VALUE,1.412021,16.944257,4348.201923,0.989532,0.984097,0.016507,0.198087,0.223291,...,0.891912,4.547878,4.068427,-0.476804,0.628205,312,9,2,DEEPSET_40_DYNAMIC,4a51c6755ddf965f
8,EX_MICRO,EQUAL,1.056904,12.682847,2284.227564,0.991203,0.993288,0.015652,0.187819,0.197509,...,0.950940,4.848862,3.647439,-0.383989,0.647436,312,1,0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,d14e8c2a63ec5c8e
9,EX_MICRO,VALUE,1.274706,15.296473,2284.227564,0.991203,0.993288,0.012634,0.151609,0.208851,...,0.725918,3.701472,3.164281,-0.487074,0.612179,312,1,0,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,d14e8c2a63ec5c8e
10,FULL,EQUAL,1.031025,12.372303,4348.201923,0.989031,0.979709,0.028445,0.341340,0.168209,...,2.041172,10.407976,6.410485,-0.351370,0.769231,312,9,1,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,d14e8c2a63ec5c8e
11,FULL,VALUE,1.285147,15.421766,4348.201923,0.989031,0.979709,0.017480,0.209758,0.224105,...,0.938501,4.785432,3.721010,-0.542289,0.634615,312,9,1,HYBRID_LGBM40_DEEPSET40_DYNAMIC_50_50,d14e8c2a63ec5c8e
0,EX_MICRO,EQUAL,0.896191,10.754294,2284.227564,0.991412,0.992692,0.012011,0.144137,0.221326,...,0.667078,3.401441,2.681841,-0.421071,0.592949,312,1,1,LGBM_40,9c0540e864a705bf
1,EX_MICRO,VALUE,1.038877,12.466526,2284.227564,0.991412,0.992692,0.012698,0.152372,0.234687,...,0.653900,3.334247,2.811860,-0.512802,0.570513,312,1,1,LGBM_40,9c0540e864a705bf
2,FULL,EQUAL,0.927494,11.129927,4348.201923,0.989137,0.973575,0.024502,0.294029,0.176336,...,1.657484,8.451541,5.694220,-0.319062,0.743590,312,9,1,LGBM_40,9c0540e864a705bf
3,FULL,VALUE,1.072341,12.868087,4348.201923,0.989137,0.973575,0.016233,0.194802,0.247700,...,0.786256,4.009136,3.372140,-0.590954,0.612179,312,9,1,LGBM_40,9c0540e864a705bf

## 8. Paired model tests

Declared model pairs are evaluated on matched out-of-sample months using differences in monthly MSE, rank IC, 10% tail returns, and Sharpe ratios. Newey--West inference, test-year clustering, year-block bootstrap intervals, Holm adjustment, and a one-standard-error interpretation are reported. Missing artifacts cause the comparison to fail rather than silently omit a planned pair.

In [ ]:
from src.model_comparison import run_paired_model_comparisons

paired_comparison = run_paired_model_comparisons(CONFIG.run_dir, seed=CONFIG.seed)
display(paired_comparison)

,model_a,model_b,difference_definition,mean_monthly_mse_difference,mse_difference_nw_t_stat,mse_difference_p_value,mean_monthly_return_difference,return_difference_nw_t_stat,return_difference_p_value,mean_rank_ic_difference,...,sharpe_difference,sharpe_difference_bootstrap_standard_error,sharpe_difference_exceeds_one_standard_error,sharpe_difference_block_bootstrap_ci_low,sharpe_difference_block_bootstrap_ci_high,simpler_model_within_sharpe_interval,n_paired_months,mse_difference_holm_p_value,return_difference_holm_p_value,rank_ic_difference_holm_p_value
0,NN4_20,NN2_20,model_a_minus_model_b,0.000038,1.407567,0.159259,-0.007963,-3.794501,0.000148,-0.006181,...,-0.594612,0.149661,False,-0.929084,-0.342423,False,312,1.000000,0.002367,1.000000
1,NN4_20,NN3_20,model_a_minus_model_b,0.000085,2.623588,0.008701,-0.010344,-4.050927,0.000051,-0.011555,...,-0.735253,0.172717,False,-1.107387,-0.430349,False,312,0.147915,0.000867,1.000000
2,LGBM_40,LGBM_20,model_a_minus_model_b,0.000012,0.443049,0.657731,0.001076,0.701790,0.482810,-0.006923,...,0.190848,0.131719,True,-0.044976,0.471354,True,312,1.000000,1.000000,0.941792
3,LGBM_40,LGBM_40_LAG1,model_a_minus_model_b,-0.000016,-1.075069,0.282344,-0.001115,-1.113947,0.265302,-0.002065,...,-0.015827,0.080330,False,-0.181889,0.133001,True,312,1.000000,1.000000,1.000000
4,LGBM_40,LGBM_40_LAG2,model_a_minus_model_b,-0.000006,-0.404244,0.686033,-0.000993,-0.897316,0.369550,-0.002451,...,0.011664,0.091675,False,-0.169182,0.190178,True,312,1.000000,1.000000,1.000000
5,LGBM_40_LAG1,LGBM_40_LAG2,model_a_minus_model_b,0.000010,1.271530,0.203540,0.000121,0.212501,0.831716,-0.000386,...,0.027491,0.053888,False,-0.090386,0.120851,True,312,1.000000,1.000000,1.000000
6,MLP_40,DEEPSET_40,model_a_minus_model_b,-0.000055,-0.849090,0.395831,0.001143,0.709348,0.478108,0.002471,...,-0.052084,0.120751,False,-0.304396,0.168938,True,312,1.000000,1.000000,1.000000
7,HYBRID_MLP40_DEEPSET40,MLP_40,model_a_minus_model_b,0.000023,0.406830,0.684133,-0.000472,-0.330058,0.741356,-0.002302,...,0.033953,0.147114,False,-0.215661,0.361016,True,312,1.000000,1.000000,1.000000
8,HYBRID_MLP40_DEEPSET40,DEEPSET_40,model_a_minus_model_b,-0.000032,-0.733758,0.463096,0.000671,0.400552,0.688750,0.000169,...,-0.018131,0.130335,False,-0.282185,0.228717,True,312,1.000000,1.000000,1.000000
9,DEEPSET_40,DEEPSET_40_LAG1,model_a_minus_model_b,-0.000045,-1.328941,0.183868,-0.000237,-0.128876,0.897456,-0.000284,...,0.013791,0.206229,False,-0.375326,0.433075,True,312,1.000000,1.000000,1.000000
10,DEEPSET_40,DEEPSET_40_DYNAMIC,model_a_minus_model_b,-0.000059,-1.109985,0.267006,-0.001881,-0.766169,0.443576,0.000127,...,-0.160414,0.224566,False,-0.610563,0.269720,True,312,1.000000,1.000000,1.000000
11,DEEPSET_40_LAG1,DEEPSET_40_DYNAMIC,model_a_minus_model_b,-0.000014,-0.316976,0.751262,-0.001643,-0.924436,0.355259,0.000411,...,-0.174205,0.096992,False,-0.396698,-0.016497,False,312,1.000000,1.000000,1.000000
12,HYBRID_LGBM40_DEEPSET40_DYNAMIC,LGBM_40,model_a_minus_model_b,0.000053,1.045593,0.295749,0.001559,1.359067,0.174125,0.003293,...,0.171018,0.107685,True,-0.013866,0.408251,True,312,1.000000,1.000000,1.000000
13,HYBRID_LGBM40_DEEPSET40_DYNAMIC,LGBM_20,model_a_minus_model_b,0.000064,1.307613,0.191004,0.002635,1.469301,0.141751,-0.003630,...,0.361866,0.144453,True,0.102592,0.668838,False,312,1.000000,1.000000,1.000000
14,HYBRID_LGBM40_DEEPSET40_DYNAMIC,DEEPSET_40_DYNAMIC,model_a_minus_model_b,-0.000081,-1.214890,0.224408,0.000002,0.000660,0.999474,-0.000481,...,-0.084965,0.215285,False,-0.583219,0.260681,True,312,1.000000,1.000000,1.000000
15,HYBRID_LGBM40_DEEPSET40_DYNAMIC,HYBRID_LGBM40_DEEPSET40,model_a_minus_model_b,0.000012,0.308006,0.758078,0.000483,0.378624,0.704967,0.001642,...,-0.008460,0.115951,False,-0.264399,0.190121,True,312,1.000000,1.000000,1.000000
16,HYBRID_LGBM40_DEEPSET40_DYNAMIC,HYBRID_MLP40_DEEPSET40,model_a_minus_model_b,0.000009,0.176339,0.860028,0.001211,0.756837,0.449147,-0.000776,...,0.093580,0.137927,False,-0.177826,0.362838,True,312,1.000000,1.000000,1.000000

## 9. Final completion checks and frozen outputs

In [ ]:
# Read current artifacts without invoking model training.
from src.runner import ExperimentRunner
runner = ExperimentRunner(CONFIG)
final_comparison = runner._cumulative_comparison()
expected_models = set(CONFIG.selected_models)
completed_models = set(final_comparison.loc[
    final_comparison['diagnostics_version'].eq(runner.DIAGNOSTICS_VERSION), 'model_id'
])
missing_current = sorted(expected_models - completed_models)
if missing_current:
    raise RuntimeError(f'Models missing current diagnostics: {missing_current}')
expected_oos_months = 12 * (
    CONFIG.universe.end_year - CONFIG.universe.start_year
    - CONFIG.windows.train_years - CONFIG.windows.validation_years + 1
)
selected_comparison = final_comparison.set_index('model_id').loc[list(expected_models)]
if selected_comparison['n_months'].ne(expected_oos_months).any():
    raise RuntimeError('At least one model does not cover the complete OOS portfolio calendar.')
if (selected_comparison['n_signal_months'] + selected_comparison['n_no_signal_months']).ne(expected_oos_months).any():
    raise RuntimeError('At least one model has an incomplete signal-availability accounting.')
required_columns = [
    'robust_oos_r2', 'mean_monthly_rank_ic', 'n_no_signal_months',
    'mean_monthly_calibration_slope', 'tail_5pct_sharpe',
    'tail_10pct_sharpe', 'tail_20pct_sharpe', 'rank_weighted_sharpe',
    'tail_10pct_missing_return_stress_annualized_return',
]
missing_values = final_comparison.set_index('model_id').loc[list(expected_models), required_columns].isna()
if missing_values.any().any():
    print('Legitimate undefined diagnostics require review:')
    display(missing_values[missing_values.any(axis=1)])
else:
    print('All selected models have current complete diagnostics.')
expected_robustness_rows = 4 * len(ROBUSTNESS_MODEL_IDS)
if len(portfolio_robustness) != expected_robustness_rows:
    raise RuntimeError(
        f'Expected {expected_robustness_rows} robustness rows, got {len(portfolio_robustness)}.'
    )
from src.model_comparison import DEFAULT_MODEL_PAIRS
if len(paired_comparison) != len(DEFAULT_MODEL_PAIRS):
    raise RuntimeError('Paired model comparison is incomplete.')
print('Portfolio robustness and paired model comparisons are complete.')

All selected models have current complete diagnostics.
Portfolio robustness and paired model comparisons are complete.